.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.40.2 */

.align 2
nonmatching D_80010000

dlabel D_80010000
    /* 800 80010000 */ .asciz "OVER FLOW\n"
    /* 4F56455220464C4F570A0000 */
.align 2
enddlabel D_80010000

.align 2
nonmatching D_8001000C

dlabel D_8001000C
    /* 80C 8001000C */ .asciz "eff_init:%08x size:%08x\n"
    /* 6566665F696E69743A253038782073697A653A253038780A00000000 */
.align 2
enddlabel D_8001000C

.align 2
nonmatching D_80010028

dlabel D_80010028
    /* 828 80010028 */ .asciz "LIMIT:%08x\n"
    /* 4C494D49543A253038780A00 */
.align 2
enddlabel D_80010028

.align 2
nonmatching D_80010034

dlabel D_80010034
    /* 834 80010034 */ .asciz "common prim over flow\n"
    /* 636F6D6D6F6E207072696D206F76657220666C6F770A0000 */
.align 2
.align 2
    /* 84C 8001004C */ .asciz "Fri Aug  7 22:26:32 1998\n"
    /* 467269204175672020372032323A32363A333220313939380A000000 */
.align 2
enddlabel D_80010034

