"""Explicit build configuration — the single source of truth for how a C file
becomes a byte-identical object.

This DATA mirrors the Makefile exactly as of the commit recorded in the oracle
manifest. The Makefile is retained only until `engine build` is proven at full
byte-parity (Phase 0, task 4); after that this module is canonical.

Keep this as plain data. The pipeline assembly lives in pipeline.py so that the
"what" (config) and the "how" (command construction) stay separable — which is
also what lets the Phase 1 cheat-invisible sandbox swap cheat stages without
touching any of these values.
"""

# -- Ground truth -----------------------------------------------------------
ORACLE_SHA1 = "62efab4f73f992798c43e8c730aa43baa10bb4fa"
TARGET_EXE = "disc/SLUS_006.63"

# -- Toolchain --------------------------------------------------------------
CC1 = "tools/gcc-2.7.2/build/cc1"
CPP = "mipsel-linux-gnu-cpp"
AS = "mipsel-linux-gnu-as"
LD = "mipsel-linux-gnu-ld"
OBJCOPY = "mipsel-linux-gnu-objcopy"
OBJDUMP = "mipsel-linux-gnu-objdump"
NM = "mipsel-linux-gnu-nm"

# PS-EXE layout: the raw binary loads at LOAD_ADDR; build/bb2.exe prepends a
# HEADER_SIZE-byte PS-X EXE header. So vram V lives at file offset
# HEADER_SIZE + (V - LOAD_ADDR) in build/bb2.exe.
LOAD_ADDR = 0x80010000
HEADER_SIZE = 0x800

# Python pipeline stages (invoked exactly as the Makefile invokes them)
MASPSX = "python3 tools/maspsx/maspsx.py"
PROLOGUE_FIX = "python3 tools/prologue_fix.py"
MULTU_PAD = "python3 tools/multu_pad.py --funcs multu_pad_funcs.txt"
# NOTE: the regfix / regfix_stage2 / asmfix rule stages were REMOVED 2026-08-30
# after the rules-to-zero campaign (2026-08-25) reached 0 rules project-wide.
# The sandbox's cheat neutralization now covers source-level cheat-asm and the
# tracked prologue_fix config only.

# -- Flags ------------------------------------------------------------------
CC_FLAGS = "-O2 -G0 -funsigned-char -quiet -mcpu=3000 -mips1 -mno-abicalls -fno-builtin -w -mel -msoft-float"
CC_FLAGS_GP = "-O2 -G8 -funsigned-char -quiet -mcpu=3000 -mips1 -mno-abicalls -fno-builtin -w -mel -msoft-float"
AS_FLAGS = "-Iinclude -march=r3000 -mtune=r3000 -no-pad-sections -O1 -G0"
CPP_FLAGS = "-Iinclude -undef -Wall -lang-c -fno-builtin"
CPP_DEFS = (
    "-Dmips -D__GNUC__=2 -D__OPTIMIZE__ -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx "
    "-D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D_LANGUAGE_C -DLANGUAGE_C"
)
LD_FLAGS = "-nostdlib --no-check-sections"
MASPSX_FLAGS = (
    "--expand-div --aspsx-version=2.34 --expand-lb "
    "--expand-lb-funcs=expand_lb_funcs.txt --multu-funcs=multu_funcs.txt "
    "--expand-dest-funcs=expand_dest_funcs.txt "
    "--prefill-label-funcs=maspsx_prefill_label_funcs.txt "
    "--comm-syms=maspsx_comm_syms.txt --use-comm-section"
)
# MUST mirror Makefile MASPSX_FLAGS_GP verbatim (the 2026-08-05 text1a landing
# brought it to full parity with MASPSX_FLAGS — 7 options — and dropped the
# old --dont-force-G0/-G8 maspsx args). Divergence here made the engine's
# driver emit a 44-byte-short text1a.o whenever it recompiled text1a,
# false-MISMATCHing the oracle (caught 2026-08-06, text1b extraction landing).
MASPSX_FLAGS_GP = (
    "--expand-div --aspsx-version=2.34 --expand-lb "
    "--expand-lb-funcs=expand_lb_funcs.txt --multu-funcs=multu_funcs.txt "
    "--expand-dest-funcs=expand_dest_funcs.txt "
    "--prefill-label-funcs=maspsx_prefill_label_funcs.txt "
    "--comm-syms=maspsx_comm_syms.txt --use-comm-section"
)

# -- Per-file opt-ins (C file stem, no path/extension) ----------------------
# Mirrors the Makefile GP_FILES / EXPAND_LB_FILES /
# NO_SR_FILES lists. Byte-parity (task 4) is the proof
# these are correct; do not edit without re-running `engine parity`.
GP_FILES = {"main/309CC", "main/31548", "main/31CFC", "main/31D3C", "main/24F08", "main/26730", "main/26940", "main/5ED34", "main/368E4"}
EXPAND_LB_FILES = {"main/175A4", "main/17AFC", "main/24BF0", "main/24F08", "main/25788"}
EXPAND_LH_FILES = set()
# Mirrors the Makefile PSYQ_LIBRARY_FILES (owner ruling Q69): Sony library code, maspsx without -G8;
# every other file gets -G8. Generated by tools/psyq_library_files.py (--check verifies).
PSYQ_LIBRARY_FILES = {"main/psxsdk/libcomb/comb", "main/psxsdk/libgpu/sys", "main/psxsdk/libgpu/prim", "main/psxsdk/libetc/intr", "main/psxsdk/libspu/spu", "main/psxsdk/libcd/bios", "main/psxsdk/libc2/prnt", "main/psxsdk/libc2/sprintf", "main/psxsdk/libapi/c67", "main/psxsdk/libapi/c112", "main/psxsdk/libapi/c159", "main/psxsdk/libapi/a08", "main/psxsdk/libapi/a09", "main/psxsdk/libapi/a11", "main/psxsdk/libapi/a12", "main/psxsdk/libapi/a36", "main/psxsdk/libapi/a37", "main/psxsdk/libapi/a39", "main/psxsdk/libapi/a50", "main/psxsdk/libapi/a52", "main/psxsdk/libapi/a53", "main/psxsdk/libapi/a54", "main/psxsdk/libapi/a65", "main/psxsdk/libapi/a66", "main/psxsdk/libapi/a67", "main/psxsdk/libapi/a91", "main/psxsdk/libapi/counter", "main/psxsdk/libapi/pad", "main/psxsdk/libapi/a18", "main/psxsdk/libapi/a19", "main/psxsdk/libapi/a20", "main/psxsdk/libapi/a21", "main/psxsdk/libapi/l02", "main/psxsdk/libapi/l03", "main/psxsdk/libapi/patch", "main/psxsdk/libapi/c68", "main/psxsdk/libapi/sendpad", "main/psxsdk/libapi/chclrpad", "main/psxsdk/libc2/memcpy", "main/psxsdk/libc2/rand", "main/psxsdk/libc2/strcpy", "main/psxsdk/libc2/strlen", "main/psxsdk/libc2/printf", "main/psxsdk/libapi/a71", "main/psxsdk/libapi/a72", "main/psxsdk/libc2/ctype", "main/psxsdk/libc2/memchr", "main/psxsdk/libc2/putchar", "main/psxsdk/libc2/memmove", "main/psxsdk/libcard/c171", "main/psxsdk/libcard/c172", "main/psxsdk/libcard/card", "main/psxsdk/libcard/a78", "main/psxsdk/libcard/a80", "main/psxsdk/libcard/init", "main/psxsdk/libcard/a74", "main/psxsdk/libcard/a75", "main/psxsdk/libcard/a76", "main/psxsdk/libcard/end", "main/psxsdk/libgpu/ext", "main/psxsdk/libapi/c73", "main/psxsdk/libgte/geo_00", "main/psxsdk/libgte/geo_01", "main/psxsdk/libgte/msc00", "main/psxsdk/libgte/msc01", "main/psxsdk/libgte/msc06", "main/psxsdk/libgte/msc09", "main/psxsdk/libgte/mtx_000", "main/psxsdk/libgte/mtx_003", "main/psxsdk/libgte/mtx_004", "main/psxsdk/libgte/mtx_005", "main/psxsdk/libgte/mtx_00a", "main/psxsdk/libgte/mtx_01", "main/psxsdk/libgte/mtx_03", "main/psxsdk/libgte/mtx_04", "main/psxsdk/libgte/mtx_05", "main/psxsdk/libgte/mtx_08", "main/psxsdk/libgte/mtx_09", "main/psxsdk/libgte/mtx_11", "main/psxsdk/libgte/mtx_12", "main/psxsdk/libgte/reg04", "main/psxsdk/libgte/reg09", "main/psxsdk/libgte/reg10", "main/psxsdk/libgte/reg11", "main/psxsdk/libgte/reg12", "main/psxsdk/libgte/reg13", "main/psxsdk/libgte/smp_00", "main/psxsdk/libgte/smp_02", "main/psxsdk/libgte/smp_03", "main/psxsdk/libgte/smp_04", "main/psxsdk/libgte/cmb_00", "main/psxsdk/libgte/fgo_01", "main/psxsdk/libgte/fgo_03", "main/psxsdk/libgte/fgo_04", "main/psxsdk/libgte/fgo_05", "main/psxsdk/libgte/fgo_06", "main/psxsdk/libgte/ratan", "main/psxsdk/libgte/patchgte", "main/psxsdk/libcd/event", "main/psxsdk/libapi/a07", "main/psxsdk/libcd/sys", "main/psxsdk/libc2/puts", "main/psxsdk/libcd/cdread", "main/psxsdk/libetc/vsync", "main/psxsdk/libapi/l10", "main/psxsdk/libapi/c114", "main/psxsdk/libapi/a23", "main/psxsdk/libapi/a24", "main/psxsdk/libapi/a25", "main/psxsdk/libc2/setjmp", "main/psxsdk/libetc/intr_vb", "main/psxsdk/libetc/intr_dma", "main/psxsdk/libetc/vmode", "main/psxsdk/libsn/73E98", "main/psxsdk/libapi/c57", "main/psxsdk/libsn/7407C", "main/psxsdk/libsnd/ssend", "main/psxsdk/libsnd/ssinit_c", "main/psxsdk/libsnd/ssinit", "main/psxsdk/libsnd/ssquit", "main/psxsdk/libsnd/scssattr", "main/psxsdk/libsnd/scsmvol", "main/psxsdk/libsnd/ssstart", "main/psxsdk/libsnd/sscall", "main/psxsdk/libsnd/cres", "main/psxsdk/libsnd/pause", "main/psxsdk/libsnd/play", "main/psxsdk/libsnd/midiread", "main/psxsdk/libsnd/miditime", "main/psxsdk/libsnd/next", "main/psxsdk/libsnd/replay", "main/psxsdk/libsnd/stop", "main/psxsdk/libsnd/scssvol", "main/psxsdk/libsnd/sstick", "main/psxsdk/libsnd/tempo", "main/psxsdk/libsnd/760D0", "main/psxsdk/libsnd/ut_gvba", "main/psxsdk/libsnd/ut_keyv", "main/psxsdk/libsnd/ut_rdep", "main/psxsdk/libsnd/ut_rev", "main/psxsdk/libsnd/ut_roff", "main/psxsdk/libsnd/ut_ron", "main/psxsdk/libsnd/ut_vvol", "main/psxsdk/libsnd/vm_doff", "main/psxsdk/libsnd/vm_f", "main/psxsdk/libsnd/vm_n2p", "main/psxsdk/libsnd/vm_no1", "main/psxsdk/libsnd/vm_vsu", "main/psxsdk/libsnd/vs_auto", "main/psxsdk/libsnd/vs_mono", "main/psxsdk/libsnd/vs_srv", "main/psxsdk/libsnd/vs_vab", "main/psxsdk/libsnd/vs_vfb", "main/psxsdk/libsnd/vs_vh", "main/psxsdk/libsnd/vs_vtb", "main/psxsdk/libsnd/vs_vtc", "main/psxsdk/libspu/s_i", "main/psxsdk/libspu/s_ini", "main/psxsdk/libspu/s_dcb", "main/psxsdk/libspu/s_q", "main/psxsdk/libapi/a13", "main/psxsdk/libspu/s_m_init", "main/psxsdk/libspu/s_m_m", "main/psxsdk/libspu/s_m_int", "main/psxsdk/libspu/s_m_f", "main/psxsdk/libspu/s_snv", "main/psxsdk/libspu/7A248", "main/psxsdk/libspu/s_snc", "main/psxsdk/libspu/s_sr", "main/psxsdk/libspu/s_m_util", "main/psxsdk/libspu/s_srmp", "main/psxsdk/libspu/s_sra", "main/psxsdk/libspu/s_srv", "main/psxsdk/libspu/s_crwa", "main/psxsdk/libapi/a10", "main/psxsdk/libspu/s_sk", "main/psxsdk/libspu/s_gks", "main/psxsdk/libspu/s_r", "main/psxsdk/libspu/s_w", "main/psxsdk/libspu/s_stsa", "main/psxsdk/libspu/s_stm", "main/psxsdk/libspu/s_itc", "main/psxsdk/libspu/s_it", "main/psxsdk/libspu/s_sca", "main/psxsdk/libspu/sr_gaks", "main/psxsdk/libspu/7BC88", "main/psxsdk/libspu/s_n2p", "main/psxsdk/libspu/s_gvv", "main/psxsdk/libspu/s_gvex"}
# Object-relative rodata alignment (owner ruling 2026-09-30,
# .claude/rules/rodata-object-alignment.md): every C object's .rodata section
# alignment is set to 4 after `as`, mirroring the Makefile's RODATA_OBJ_ALIGN.
# One rule for all objects; the per-file .align sed is retired.
RODATA_OBJ_ALIGN = "--set-section-alignment .rodata=4"
NO_SR_FILES = set()

# Mirrors the Makefile LINKED_ASM_FUNCS list: per-function objects assembled
# straight from asm/funcs/<name>.s and linked by bb2.ld. Explicit opt-in, never
# a wildcard over asm/funcs/ (which holds all 1437 split functions).
LINKED_ASM_FUNCS = []

# -- Linker -----------------------------------------------------------------
LD_SCRIPT = "bb2.ld"
LD_SYM_FILES = ["undefined_funcs_auto.txt", "undefined_syms_auto.txt", "named_syms.txt"]
