"""(a4′)(4) member table for the CdState span func_80036140 accesses (0x80101E62..0x80101EA7): per
member, every func_80036140 instruction that accesses it (address + opcode, incl. `la` forms and the
0(reg) loads/stores through that register), and for members func_80036140 never touches, every other
function's original accesses (asm/funcs) — the Q13 forced-in evidence.
usage: python3 tmp/func_80036140/memtable.py > memory/grind/func_80036140/landing/member_table.md"""
import re, glob
from pathlib import Path

MEMBERS = [  # (offset in CdState, address, width, C member, type, splat symbol in the shipped asm)
    (0x0A, 0x80101E62, 2, 'rec.unk02', 's16', 'D_80101E62'),
    (0x0C, 0x80101E64, 2, 'rec.unk04', 's16', 'D_80101E64'),
    (0x0E, 0x80101E66, 2, 'rec.unk06', 's16', 'D_80101E66'),
    (0x10, 0x80101E68, 2, 'rec.unk08', 's16', 'D_80101E68'),
    (0x12, 0x80101E6A, 2, 'rec.unk0A', 's16', 'D_80101E6A'),
    (0x14, 0x80101E6C, 8, 'rec.pair', 'CamPair', 'g_cd_loc'),
    (0x1C, 0x80101E74, 4, 'rec.unk14', 's32', 'D_80101E74'),
    (0x20, 0x80101E78, 4, 'rec.unk18', 's32', 'D_80101E78'),
    (0x24, 0x80101E7C, 4, 'rec.unk1C', 's32', 'D_80101E7C'),
    (0x28, 0x80101E80, 4, 'rec.sectors_remaining', 's32', 'g_cdread_sectors_remaining'),
    (0x2C, 0x80101E84, 4, 'rec.dest_buffer', 's32', 'g_cdread_dest_buffer'),
    (0x30, 0x80101E88, 4, 'rec.unk28', 's32', 'D_80101E88'),
    (0x34, 0x80101E8C, 4, 'rec.unk2C', 's32', 'D_80101E8C'),
    (0x38, 0x80101E90, 1, 'rec.unk30', 'u8', 'D_80101E90'),
    (0x3C, 0x80101E94, 4, 'rec.unk34', 's32', 'D_80101E94'),
    (0x40, 0x80101E98, 2, 'rec.unk38', 's16', 'D_80101E98'),
    (0x42, 0x80101E9A, 2, 'rec.unk3A', 's16', 'D_80101E9A'),
    (0x44, 0x80101E9C, 2, 'rec.unk3C', 's16', 'D_80101E9C'),
    (0x46, 0x80101E9E, 2, 'rec.unk3E', 'u16', 'D_80101E9E'),
    (0x48, 0x80101EA0, 4, 'rec.expected_pos', 's32', 'g_cdread_expected_pos'),
    (0x4C, 0x80101EA4, 4, 'rec.unk44', 's32', 'D_80101EA4'),
]
INSN = re.compile(r'/\*\s*[0-9A-F]+\s+([0-9A-F]{8})\s+[0-9A-F]{8}\s*\*/\s+(\w+)\s+(.*)$')


def accesses(path, sym):
    lines = [l.rstrip() for l in open(path)]
    out = []
    for i, l in enumerate(lines):
        m = INSN.search(l)
        if not m or not re.search(r'\b' + re.escape(sym) + r'\b', m.group(3)):
            continue
        addr, op, ops = m.groups()
        out.append(f'{addr} {op} {ops.strip()}')
        if op == 'addiu':            # `la reg,sym`: follow 0(reg) uses of that register
            reg = ops.split(',')[0].strip()
            for l2 in lines[i + 1:i + 40]:
                m2 = INSN.search(l2)
                if not m2:
                    continue
                if re.search(r'0x0\(' + re.escape(reg) + r'\)', m2.group(3)):
                    out.append(f'  {m2.group(1)} {m2.group(2)} {m2.group(3).strip()}')
                if re.match(r'\s*' + re.escape(reg) + r',', m2.group(3)) and m2.group(2) not in ('sw', 'sh', 'sb'):
                    break
    return out


print('# (a4′)(4) member table — CdState D_80101E58 over the span func_80036140 accesses')
print('# (0x80101E62..0x80101EA7); shipped symbol names as in asm/funcs. Generated by landing/tools/memtable.py.\n')
own_span = []
for off, addr, w, name, ty, sym in MEMBERS:
    acc = accesses('asm/funcs/func_80036140.s', sym)
    print(f'## +0x{off:02X} 0x{addr:08X} width {w} `{ty} {name}` (shipped {sym})')
    if acc:
        print('func_80036140:')
        for a in acc:
            print('    ' + a)
    else:
        print('NOT accessed by func_80036140. Other functions\' original accesses:')
        for f in sorted(glob.glob('asm/funcs/*.s')):
            fn = Path(f).stem
            if fn == 'func_80036140':
                continue
            for a in accesses(f, sym):
                print(f'    {fn}: {a}')
    print()
