"""Classify every banked func_800187F4 body: lz declaration, FAKE / !FAKE annotations other than the lz one.
Writes memory/grind/func_800187F4/r11/fake_scan.md. Run from repo root (WSL python)."""
import re, pathlib, collections

L = pathlib.Path("memory/grind/func_800187F4")
rows = []
for p in sorted(L.rglob("*.c")):
    s = p.read_bytes().decode("utf-8", "replace")
    if "func_800187F4" not in s and "@gte" not in s:
        continue
    lz = re.findall(r"\bs32\s+lz\[(\d+)\]", s)
    scal = bool(re.search(r"\bs32\s+lz0\b", s))
    # FAKE annotations: locate each and decide whether it is the lz one (next declaration is lz)
    other = []
    for m in re.finditer(r"(!?FAKE)\b[:\s]", s):
        tail = s[m.end():]
        close = tail.find("*/")
        after = tail[close + 2:] if close >= 0 else tail
        nxt = after.lstrip().split("\n", 1)[0]
        if re.match(r"s32\s+lz(\[|0\b)", nxt):
            continue
        line = s[: m.start()].count("\n") + 1
        other.append(f"{m.group(1)}@{line}")
    lzfake = bool(re.search(r"/\*(?:(?!\*/).)*?FAKE(?:(?!\*/).)*\*/\s*s32\s+lz(\[|0\b)", s, re.S))
    rows.append((str(p.relative_to(L)), ",".join(lz) or ("scalars" if scal else "-"), "yes" if lzfake else "no", len(other), " ".join(other[:6])))

out = ["# fake_scan — every banked .c body: lz declaration and FAKE annotations other than lz's",
       "", "Generated by tmp/f187/fakescan.py (copy: r11/tools/fakescan.py). `lz FAKE` = the lz declaration carries a",
       "FAKE comment. `other` = count of FAKE / !FAKE annotations not on the lz declaration.", "",
       "| body | lz | lz FAKE | other | where |", "|---|---|---|---|---|"]
for r in rows:
    out.append("| " + " | ".join(str(x) for x in r) + " |")
cnt = collections.Counter((r[0].split("/")[0] if "/" in r[0] else ".", r[1], r[3] > 0) for r in rows)
out += ["", "Summary (top dir, lz size, has other FAKE): count"]
for k, v in sorted(cnt.items()):
    out.append(f"- {k}: {v}")
(L / "r11/fake_scan.md").write_bytes(("\n".join(out) + "\n").encode("utf-8"))
print("\n".join(out[-len(cnt) - 1:]))
print("bodies:", len(rows))
