"""Build memory/grind/func_800187F4/r11/manifest.md from the uniform sweep (tmp/f187/sweep.log, fast4.sh = the
real per-file recipe) over every banked body, plus the result files of bodies banked only as generator +
result (v2 / v3 reviewers, delta ablation, dead-store sweeps). Every body that reaches 0 must carry an
explicit reason from ZERO_REASONS; the script fails otherwise. Run from repo root (WSL python)."""
import re, sys, pathlib, collections

L = pathlib.Path("memory/grind/func_800187F4")
import shutil
EXCLUDE = {"tmp:rv8_cand_head.c", "tmp:rv8_code6cac_index.c", "tmp:rv8_staged_body.c"}  # reviewer scratch copies, not probes
tags = {}
for l in open("tmp/f187/sweep_tags.tsv"):
    if not l.strip():
        continue
    t, rel = l.rstrip("\n").split("\t")
    if rel in EXCLUDE:
        continue
    if rel.startswith("tmp:"):
        name = rel[4:]
        rel = ("r11/banked/" if name in ("w1.c", "w2.c") else "r11/reviewer_probes/") + name
        shutil.copy("tmp/func_800187F4/" + name, L / rel)
    tags[t] = rel
for f in ["tmp/func_800187F4/fast4.sh", "tmp/f187/manifest.py", "tmp/f187/zero_reasons.py", "tmp/f187/sweep_prep.py",
          "tmp/f187/sweep_run.sh", "tmp/f187/mkfast4.py", "tmp/func_800187F4/rv8_mk.py"]:
    shutil.copy(f, L / "r11/tools" / pathlib.Path(f).name)
shutil.copy("tmp/f187/sweep.log", L / "r11/banked/sweep.log")
shutil.copy("tmp/f187/sweep_tags.tsv", L / "r11/banked/sweep_tags.tsv")
res, frame, fail = {}, {}, {}
joined = None
mode = "plain"
for l in open("tmp/f187/sweep.log"):
    if l.startswith("JOINED:"):
        mode = "joined"; continue
    m = re.match(r"(mf_\d+)\s+diff=(\d+) tgt=(\d+) ours=(\d+)", l)
    if m:
        if mode == "joined":
            joined = (int(m.group(2)), int(m.group(4)))
        else:
            res[m.group(1)] = (int(m.group(2)), int(m.group(4)))
        continue
    m = re.match(r"(mf_\d+) (BUILD FAIL|CC1 ERR)", l)
    if m:
        fail[m.group(1)] = m.group(2); continue
    m = re.match(r"FRAME (mf_\d+) addiu sp,sp,-(\d+)", l)
    if m:
        frame[m.group(1)] = int(m.group(2))

sys.path.insert(0, "tmp/f187")
from zero_reasons import ZERO_REASONS, RESULT_ZERO_REASONS  # noqa: E402

rows, zeros, missing = [], [], []
for tag, rel in tags.items():
    if tag in fail or tag not in res:
        rows.append((rel, "build fail" if tag in fail else "no result", "", ""))
        missing.append(rel)
        continue
    d, n = res[tag]
    fr = f"0x{frame[tag]:X}" if tag in frame else "?"
    rows.append((rel, str(d), str(n), fr))
    if d == 0:
        zeros.append(rel)

# result-file sets (bodies banked as generator + result only)
RESULT_FILES = [
    ("rejected/v2_review/res_a.txt", "v2 reviewer (c6 chassis)"), ("rejected/v2_review/res_b.txt", "v2 reviewer (c6 chassis)"),
    ("rejected/v2_review/res_c.txt", "v2 reviewer (c6 chassis)"), ("rejected/v2_review/res_d.txt", "v2 reviewer (c6 chassis)"),
    ("rejected/v2_review/res_e.txt", "v2 reviewer (c6 chassis)"), ("rejected/v2_review/res_f.txt", "v2 reviewer (c6 chassis)"),
    ("rejected/v2_review/res_g.txt", "v2 reviewer (c6 chassis)"),
    ("rejected/v3_review/combo_res.txt", "v3 reviewer (c7)"), ("rejected/v3_review/loop_res.txt", "v3 reviewer (c7)"),
    ("rejected/v3_review/order_res.txt", "v3 reviewer (c7)"), ("rejected/v3_review/init_res.txt", "v3 reviewer (c7)"),
    ("rejected/v3_review/init2_res.txt", "v3 reviewer (c7)"),
    ("r11/abl_d.log", "author, delta ablation on w2"), ("r11/ds.log", "author, c6 dead-store sweep"),
    ("r11/ds2.log", "author, c6 self-assign / chain-extender sweep"),
]
rsum, rzeros = [], []
for f, who in RESULT_FILES:
    p = L / f
    ent = []
    for l in open(p, encoding="utf-8", errors="replace"):
        m = re.match(r"(\S+)\s+diff=(\d+)", l)
        if m:
            ent.append((m.group(1), int(m.group(2))))
    z = [t for t, d in ent if d == 0]
    nz = [d for t, d in ent if d]
    rsum.append((f, who, len(ent), len(z), min(nz) if nz else "-"))
    for t in z:
        rzeros.append((f, t))

bad = [z for z in zeros if z not in ZERO_REASONS]
rbad = [(f, t) for f, t in rzeros if not any(re.fullmatch(pat, t) and f == ff for ff, pat, _ in RESULT_ZERO_REASONS)]
if bad or rbad:
    print("UNEXPLAINED ZEROS:", bad, rbad[:20], len(rbad))
    sys.exit(1)

out = ["# func_800187F4 — manifest of every measured body (generated)", "",
       "Generated by r11/tools/manifest.py from one uniform sweep (r11/tools/fast4.sh = the real per-file recipe,",
       "fast3.sh with the prototype matched to the body's `arg0` type; log r11/banked/sweep.log) over every banked",
       "`.c` body in this ledger, plus the result files of the sets banked as generator + results only. \"lines\" =",
       "differing objdump lines vs the target (662); \"insns\" = objdump instruction lines of our build.", "",
       "## Bodies that reach 0 (every one, with its reason)", "",
       "| body | reason |", "|---|---|"]
for z in zeros:
    out.append(f"| {z} | {ZERO_REASONS[z]} |")
for f, t in rzeros:
    reason = next(r for ff, pat, r in RESULT_ZERO_REASONS if ff == f and re.fullmatch(pat, t))
    out.append(f"| {f}: {t} | {reason} |")
out += ["", "Every other measured body misses (lines > 0).", "",
        "## Result-file sets (bodies banked as generator + results)", "",
        "| file | set | bodies | reaching 0 | best nonzero |", "|---|---|---|---|---|"]
for r in rsum:
    out.append("| " + " | ".join(str(x) for x in r) + " |")
out += ["", "## Every banked body (sweep)", "", "| body | lines | insns | frame |", "|---|---|---|---|"]
for r in rows:
    out.append("| " + " | ".join(r) + " |")
if joined:
    out += ["", f"r11/banked/pc_joined.c under GENMODE=--joined (each macro one __asm__): {joined[0]} lines, {joined[1]} insns."]
if missing:
    out += ["", "Bodies that did not build under the current harness: " + ", ".join(missing)]
(L / "r11/manifest.md").write_bytes(("\n".join(out) + "\n").encode("utf-8"))
print("bodies", len(rows), "zeros", len(zeros), "result-file zeros", len(rzeros), "missing", missing, "joined", joined)
