.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching func_801D919C, 0x30

glabel func_801D919C
    /* 119C 801D919C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 11A0 801D91A0 1000A4A3 */  sb         $a0, 0x10($sp)
    /* 11A4 801D91A4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 11A8 801D91A8 1800BFAF */  sw         $ra, 0x18($sp)
    /* 11AC 801D91AC 1100A5A3 */  sb         $a1, 0x11($sp)
    /* 11B0 801D91B0 1200A6A3 */  sb         $a2, 0x12($sp)
    /* 11B4 801D91B4 497D070C */  jal        CdMix
    /* 11B8 801D91B8 1300A7A3 */   sb        $a3, 0x13($sp)
    /* 11BC 801D91BC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 11C0 801D91C0 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 11C4 801D91C4 0800E003 */  jr         $ra
    /* 11C8 801D91C8 00000000 */   nop
endlabel func_801D919C

nonmatching func_801D91CC, 0x548

glabel func_801D91CC
    /* 11CC 801D91CC B8FEBD27 */  addiu      $sp, $sp, -0x148
    /* 11D0 801D91D0 3401B3AF */  sw         $s3, 0x134($sp)
    /* 11D4 801D91D4 2198A000 */  addu       $s3, $a1, $zero
    /* 11D8 801D91D8 4401BFAF */  sw         $ra, 0x144($sp)
    /* 11DC 801D91DC 4001B6AF */  sw         $s6, 0x140($sp)
    /* 11E0 801D91E0 3C01B5AF */  sw         $s5, 0x13C($sp)
    /* 11E4 801D91E4 3801B4AF */  sw         $s4, 0x138($sp)
    /* 11E8 801D91E8 3001B2AF */  sw         $s2, 0x130($sp)
    /* 11EC 801D91EC 2C01B1AF */  sw         $s1, 0x12C($sp)
    /* 11F0 801D91F0 1F68070C */  jal        func_801DA07C
    /* 11F4 801D91F4 2801B0AF */   sw        $s0, 0x128($sp)
    /* 11F8 801D91F8 118C070C */  jal        ResetCallback
    /* 11FC 801D91FC 21B00000 */   addu      $s6, $zero, $zero
    /* 1200 801D9200 A87B070C */  jal        CdInit
    /* 1204 801D9204 00000000 */   nop
    /* 1208 801D9208 168A070C */  jal        PadInit
    /* 120C 801D920C 21200000 */   addu      $a0, $zero, $zero
    /* 1210 801D9210 666F070C */  jal        ResetGraph
    /* 1214 801D9214 21200000 */   addu      $a0, $zero, $zero
    /* 1218 801D9218 0C70070C */  jal        SetGraphDebug
    /* 121C 801D921C 21200000 */   addu      $a0, $zero, $zero
    /* 1220 801D9220 948B070C */  jal        VSync
    /* 1224 801D9224 21200000 */   addu      $a0, $zero, $zero
    /* 1228 801D9228 6F70070C */  jal        SetDispMask
    /* 122C 801D922C 21200000 */   addu      $a0, $zero, $zero
    /* 1230 801D9230 FF000424 */  addiu      $a0, $zero, 0xFF
    /* 1234 801D9234 21280000 */  addu       $a1, $zero, $zero
    /* 1238 801D9238 FF000624 */  addiu      $a2, $zero, 0xFF
    /* 123C 801D923C 6764070C */  jal        func_801D919C
    /* 1240 801D9240 21380000 */   addu      $a3, $zero, $zero
    /* 1244 801D9244 02000424 */  addiu      $a0, $zero, 0x2
    /* 1248 801D9248 1000658E */  lw         $a1, 0x10($s3)
    /* 124C 801D924C 5F7C070C */  jal        CdControl
    /* 1250 801D9250 21300000 */   addu      $a2, $zero, $zero
    /* 1254 801D9254 4C000424 */  addiu      $a0, $zero, 0x4C
    /* 1258 801D9258 80000624 */  addiu      $a2, $zero, 0x80
    /* 125C 801D925C 0C00658E */  lw         $a1, 0xC($s3)
    /* 1260 801D9260 7C85070C */  jal        CdRead
    /* 1264 801D9264 F800B227 */   addiu     $s2, $sp, 0xF8
    /* 1268 801D9268 01000424 */  addiu      $a0, $zero, 0x1
  .L801D926C:
    /* 126C 801D926C BD85070C */  jal        CdReadSync
    /* 1270 801D9270 21280000 */   addu      $a1, $zero, $zero
    /* 1274 801D9274 05004018 */  blez       $v0, .L801D928C
    /* 1278 801D9278 21880000 */   addu      $s1, $zero, $zero
    /* 127C 801D927C 948B070C */  jal        VSync
    /* 1280 801D9280 21200000 */   addu      $a0, $zero, $zero
    /* 1284 801D9284 9B640708 */  j          .L801D926C
    /* 1288 801D9288 01000424 */   addiu     $a0, $zero, 0x1
  .L801D928C:
    /* 128C 801D928C 1F80043C */  lui        $a0, %hi(D_801F65DC)
    /* 1290 801D9290 DC658424 */  addiu      $a0, $a0, %lo(D_801F65DC)
    /* 1294 801D9294 0C00658E */  lw         $a1, 0xC($s3)
    /* 1298 801D9298 21A00000 */  addu       $s4, $zero, $zero
    /* 129C 801D929C 4771070C */  jal        LoadImage
    /* 12A0 801D92A0 1400A524 */   addiu     $a1, $a1, 0x14
    /* 12A4 801D92A4 9670070C */  jal        DrawSync
    /* 12A8 801D92A8 21200000 */   addu      $a0, $zero, $zero
    /* 12AC 801D92AC 1800A427 */  addiu      $a0, $sp, 0x18
    /* 12B0 801D92B0 21280000 */  addu       $a1, $zero, $zero
    /* 12B4 801D92B4 21300000 */  addu       $a2, $zero, $zero
    /* 12B8 801D92B8 40010724 */  addiu      $a3, $zero, 0x140
    /* 12BC 801D92BC F0001024 */  addiu      $s0, $zero, 0xF0
    /* 12C0 801D92C0 9A6D070C */  jal        SetDefDispEnv
    /* 12C4 801D92C4 1000B0AF */   sw        $s0, 0x10($sp)
    /* 12C8 801D92C8 2C00A427 */  addiu      $a0, $sp, 0x2C
    /* 12CC 801D92CC 21280000 */  addu       $a1, $zero, $zero
    /* 12D0 801D92D0 F0000624 */  addiu      $a2, $zero, 0xF0
    /* 12D4 801D92D4 40010724 */  addiu      $a3, $zero, 0x140
    /* 12D8 801D92D8 9A6D070C */  jal        SetDefDispEnv
    /* 12DC 801D92DC 1000B0AF */   sw        $s0, 0x10($sp)
    /* 12E0 801D92E0 1800A427 */  addiu      $a0, $sp, 0x18
    /* 12E4 801D92E4 01000224 */  addiu      $v0, $zero, 0x1
    /* 12E8 801D92E8 3D00A2A3 */  sb         $v0, 0x3D($sp)
    /* 12EC 801D92EC C972070C */  jal        PutDispEnv
    /* 12F0 801D92F0 2900A2A3 */   sb        $v0, 0x29($sp)
    /* 12F4 801D92F4 1F80043C */  lui        $a0, %hi(D_801F65D4)
    /* 12F8 801D92F8 D4658424 */  addiu      $a0, $a0, %lo(D_801F65D4)
    /* 12FC 801D92FC 21280000 */  addu       $a1, $zero, $zero
    /* 1300 801D9300 21300000 */  addu       $a2, $zero, $zero
    /* 1304 801D9304 FB70070C */  jal        ClearImage
    /* 1308 801D9308 21380000 */   addu      $a3, $zero, $zero
    /* 130C 801D930C 9670070C */  jal        DrawSync
    /* 1310 801D9310 21200000 */   addu      $a0, $zero, $zero
    /* 1314 801D9314 6F70070C */  jal        SetDispMask
    /* 1318 801D9318 01000424 */   addiu     $a0, $zero, 0x1
    /* 131C 801D931C 948B070C */  jal        VSync
    /* 1320 801D9320 04000424 */   addiu     $a0, $zero, 0x4
    /* 1324 801D9324 1400628E */  lw         $v0, 0x14($s3)
    /* 1328 801D9328 21A80000 */  addu       $s5, $zero, $zero
    /* 132C 801D932C 1000A2AF */  sw         $v0, 0x10($sp)
    /* 1330 801D9330 0000648E */  lw         $a0, 0x0($s3)
    /* 1334 801D9334 0400658E */  lw         $a1, 0x4($s3)
    /* 1338 801D9338 0800668E */  lw         $a2, 0x8($s3)
    /* 133C 801D933C 0C00678E */  lw         $a3, 0xC($s3)
    /* 1340 801D9340 3766070C */  jal        func_801D98DC
    /* 1344 801D9344 21980000 */   addu      $s3, $zero, $zero
    /* 1348 801D9348 0367070C */  jal        func_801D9C0C
    /* 134C 801D934C 00000000 */   nop
  .L801D9350:
    /* 1350 801D9350 0200A012 */  beqz       $s5, .L801D935C
    /* 1354 801D9354 0100312E */   sltiu     $s1, $s1, 0x1
    /* 1358 801D9358 21880000 */  addu       $s1, $zero, $zero
  .L801D935C:
    /* 135C 801D935C 21808002 */  addu       $s0, $s4, $zero
    /* 1360 801D9360 2A8A070C */  jal        PadRead
    /* 1364 801D9364 21200000 */   addu      $a0, $zero, $zero
    /* 1368 801D9368 21A04000 */  addu       $s4, $v0, $zero
    /* 136C 801D936C 27101000 */  nor        $v0, $zero, $s0
    /* 1370 801D9370 24108202 */  and        $v0, $s4, $v0
    /* 1374 801D9374 40004230 */  andi       $v0, $v0, 0x40
    /* 1378 801D9378 03004010 */  beqz       $v0, .L801D9388
    /* 137C 801D937C 00000000 */   nop
  .L801D9380:
    /* 1380 801D9380 0D650708 */  j          .L801D9434
    /* 1384 801D9384 01001624 */   addiu     $s6, $zero, 0x1
  .L801D9388:
    /* 1388 801D9388 1000A016 */  bnez       $s5, .L801D93CC
    /* 138C 801D938C 00000000 */   nop
    /* 1390 801D9390 0000828F */  lw         $v0, %gp_rel(D_801F65D0)($gp)
    /* 1394 801D9394 00000000 */  nop
    /* 1398 801D9398 0C004010 */  beqz       $v0, .L801D93CC
    /* 139C 801D939C 1800A427 */   addiu     $a0, $sp, 0x18
    /* 13A0 801D93A0 01001524 */  addiu      $s5, $zero, 0x1
    /* 13A4 801D93A4 E0010524 */  addiu      $a1, $zero, 0x1E0
    /* 13A8 801D93A8 21300000 */  addu       $a2, $zero, $zero
    /* 13AC 801D93AC 40010724 */  addiu      $a3, $zero, 0x140
    /* 13B0 801D93B0 F0000224 */  addiu      $v0, $zero, 0xF0
    /* 13B4 801D93B4 9A6D070C */  jal        SetDefDispEnv
    /* 13B8 801D93B8 1000A2AF */   sw        $v0, 0x10($sp)
    /* 13BC 801D93BC 1800A427 */  addiu      $a0, $sp, 0x18
    /* 13C0 801D93C0 C972070C */  jal        PutDispEnv
    /* 13C4 801D93C4 2900A0A3 */   sb        $zero, 0x29($sp)
    /* 13C8 801D93C8 21880000 */  addu       $s1, $zero, $zero
  .L801D93CC:
    /* 13CC 801D93CC E667070C */  jal        func_801D9F98
    /* 13D0 801D93D0 21202002 */   addu      $a0, $s1, $zero
    /* 13D4 801D93D4 0B004014 */  bnez       $v0, .L801D9404
    /* 13D8 801D93D8 00000000 */   nop
    /* 13DC 801D93DC 1C68070C */  jal        func_801DA070
    /* 13E0 801D93E0 00000000 */   nop
    /* 13E4 801D93E4 E6FF4010 */  beqz       $v0, .L801D9380
    /* 13E8 801D93E8 21200000 */   addu      $a0, $zero, $zero
    /* 13EC 801D93EC 21280000 */  addu       $a1, $zero, $zero
    /* 13F0 801D93F0 21300000 */  addu       $a2, $zero, $zero
    /* 13F4 801D93F4 6764070C */  jal        func_801D919C
    /* 13F8 801D93F8 21380000 */   addu      $a3, $zero, $zero
    /* 13FC 801D93FC 0D650708 */  j          .L801D9434
    /* 1400 801D9400 58021324 */   addiu     $s3, $zero, 0x258
  .L801D9404:
    /* 1404 801D9404 9670070C */  jal        DrawSync
    /* 1408 801D9408 21200000 */   addu      $a0, $zero, $zero
    /* 140C 801D940C 948B070C */  jal        VSync
    /* 1410 801D9410 21200000 */   addu      $a0, $zero, $zero
    /* 1414 801D9414 80201100 */  sll        $a0, $s1, 2
    /* 1418 801D9418 21209100 */  addu       $a0, $a0, $s1
    /* 141C 801D941C 80200400 */  sll        $a0, $a0, 2
    /* 1420 801D9420 1800A227 */  addiu      $v0, $sp, 0x18
    /* 1424 801D9424 C972070C */  jal        PutDispEnv
    /* 1428 801D9428 21204400 */   addu      $a0, $v0, $a0
    /* 142C 801D942C D4640708 */  j          .L801D9350
    /* 1430 801D9430 00000000 */   nop
  .L801D9434:
    /* 1434 801D9434 9A00C016 */  bnez       $s6, .L801D96A0
    /* 1438 801D9438 00000000 */   nop
    /* 143C 801D943C FFFF7326 */  addiu      $s3, $s3, -0x1
    /* 1440 801D9440 10006012 */  beqz       $s3, .L801D9484
    /* 1444 801D9444 21808002 */   addu      $s0, $s4, $zero
  .L801D9448:
    /* 1448 801D9448 2A8A070C */  jal        PadRead
    /* 144C 801D944C 21200000 */   addu      $a0, $zero, $zero
    /* 1450 801D9450 21A04000 */  addu       $s4, $v0, $zero
    /* 1454 801D9454 27101000 */  nor        $v0, $zero, $s0
    /* 1458 801D9458 24108202 */  and        $v0, $s4, $v0
    /* 145C 801D945C 40004230 */  andi       $v0, $v0, 0x40
    /* 1460 801D9460 03004010 */  beqz       $v0, .L801D9470
    /* 1464 801D9464 00000000 */   nop
    /* 1468 801D9468 21650708 */  j          .L801D9484
    /* 146C 801D946C 01001624 */   addiu     $s6, $zero, 0x1
  .L801D9470:
    /* 1470 801D9470 948B070C */  jal        VSync
    /* 1474 801D9474 21200000 */   addu      $a0, $zero, $zero
    /* 1478 801D9478 FFFF7326 */  addiu      $s3, $s3, -0x1
    /* 147C 801D947C F2FF6016 */  bnez       $s3, .L801D9448
    /* 1480 801D9480 21808002 */   addu      $s0, $s4, $zero
  .L801D9484:
    /* 1484 801D9484 8600C016 */  bnez       $s6, .L801D96A0
    /* 1488 801D9488 21280000 */   addu      $a1, $zero, $zero
    /* 148C 801D948C 1800A427 */  addiu      $a0, $sp, 0x18
    /* 1490 801D9490 21300000 */  addu       $a2, $zero, $zero
    /* 1494 801D9494 40010724 */  addiu      $a3, $zero, 0x140
    /* 1498 801D9498 F0001024 */  addiu      $s0, $zero, 0xF0
    /* 149C 801D949C 9A6D070C */  jal        SetDefDispEnv
    /* 14A0 801D94A0 1000B0AF */   sw        $s0, 0x10($sp)
    /* 14A4 801D94A4 2C00A427 */  addiu      $a0, $sp, 0x2C
    /* 14A8 801D94A8 21280000 */  addu       $a1, $zero, $zero
    /* 14AC 801D94AC F0000624 */  addiu      $a2, $zero, 0xF0
    /* 14B0 801D94B0 40010724 */  addiu      $a3, $zero, 0x140
    /* 14B4 801D94B4 9A6D070C */  jal        SetDefDispEnv
    /* 14B8 801D94B8 1000B0AF */   sw        $s0, 0x10($sp)
    /* 14BC 801D94BC 4000B127 */  addiu      $s1, $sp, 0x40
    /* 14C0 801D94C0 21202002 */  addu       $a0, $s1, $zero
    /* 14C4 801D94C4 21280000 */  addu       $a1, $zero, $zero
    /* 14C8 801D94C8 21300000 */  addu       $a2, $zero, $zero
    /* 14CC 801D94CC 40010724 */  addiu      $a3, $zero, 0x140
    /* 14D0 801D94D0 3D00A0A3 */  sb         $zero, 0x3D($sp)
    /* 14D4 801D94D4 2900A0A3 */  sb         $zero, 0x29($sp)
    /* 14D8 801D94D8 6C6D070C */  jal        SetDefDrawEnv
    /* 14DC 801D94DC 1000B0AF */   sw        $s0, 0x10($sp)
    /* 14E0 801D94E0 9C00A427 */  addiu      $a0, $sp, 0x9C
    /* 14E4 801D94E4 21280000 */  addu       $a1, $zero, $zero
    /* 14E8 801D94E8 F0000624 */  addiu      $a2, $zero, 0xF0
    /* 14EC 801D94EC 40010724 */  addiu      $a3, $zero, 0x140
    /* 14F0 801D94F0 6C6D070C */  jal        SetDefDrawEnv
    /* 14F4 801D94F4 1000B0AF */   sw        $s0, 0x10($sp)
    /* 14F8 801D94F8 40001524 */  addiu      $s5, $zero, 0x40
    /* 14FC 801D94FC 21980000 */  addu       $s3, $zero, $zero
    /* 1500 801D9500 2001B427 */  addiu      $s4, $sp, 0x120
    /* 1504 801D9504 40011624 */  addiu      $s6, $zero, 0x140
    /* 1508 801D9508 B400A0A3 */  sb         $zero, 0xB4($sp)
    /* 150C 801D950C 5800A0A3 */  sb         $zero, 0x58($sp)
    /* 1510 801D9510 01007032 */  andi       $s0, $s3, 0x1
  .L801D9514:
    /* 1514 801D9514 40201000 */  sll        $a0, $s0, 1
    /* 1518 801D9518 21209000 */  addu       $a0, $a0, $s0
    /* 151C 801D951C C0200400 */  sll        $a0, $a0, 3
    /* 1520 801D9520 23209000 */  subu       $a0, $a0, $s0
    /* 1524 801D9524 80200400 */  sll        $a0, $a0, 2
    /* 1528 801D9528 3372070C */  jal        PutDrawEnv
    /* 152C 801D952C 21202402 */   addu      $a0, $s1, $a0
    /* 1530 801D9530 1F80043C */  lui        $a0, %hi(D_801F65DC)
    /* 1534 801D9534 DC658424 */  addiu      $a0, $a0, %lo(D_801F65DC)
    /* 1538 801D9538 21280000 */  addu       $a1, $zero, $zero
    /* 153C 801D953C 00311000 */  sll        $a2, $s0, 4
    /* 1540 801D9540 2330D000 */  subu       $a2, $a2, $s0
    /* 1544 801D9544 7971070C */  jal        MoveImage
    /* 1548 801D9548 00310600 */   sll       $a2, $a2, 4
    /* 154C 801D954C 21208002 */  addu       $a0, $s4, $zero
    /* 1550 801D9550 21280000 */  addu       $a1, $zero, $zero
    /* 1554 801D9554 01000624 */  addiu      $a2, $zero, 0x1
    /* 1558 801D9558 AA6E070C */  jal        SetDrawTPage
    /* 155C 801D955C 40000724 */   addiu     $a3, $zero, 0x40
    /* 1560 801D9560 FE71070C */  jal        DrawPrim
    /* 1564 801D9564 21208002 */   addu      $a0, $s4, $zero
    /* 1568 801D9568 536E070C */  jal        SetPolyG4
    /* 156C 801D956C 21204002 */   addu      $a0, $s2, $zero
    /* 1570 801D9570 21204002 */  addu       $a0, $s2, $zero
    /* 1574 801D9574 216E070C */  jal        SetSemiTrans
    /* 1578 801D9578 01000524 */   addiu     $a1, $zero, 0x1
    /* 157C 801D957C 00121300 */  sll        $v0, $s3, 8
    /* 1580 801D9580 1A005500 */  div        $zero, $v0, $s5
    /* 1584 801D9584 0200A016 */  bnez       $s5, .L801D9590
    /* 1588 801D9588 00000000 */   nop
    /* 158C 801D958C 0D000700 */  break      7
  .L801D9590:
    /* 1590 801D9590 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 1594 801D9594 0400A116 */  bne        $s5, $at, .L801D95A8
    /* 1598 801D9598 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 159C 801D959C 02004114 */  bne        $v0, $at, .L801D95A8
    /* 15A0 801D95A0 00000000 */   nop
    /* 15A4 801D95A4 0D000600 */  break      6
  .L801D95A8:
    /* 15A8 801D95A8 12280000 */  mflo       $a1
    /* 15AC 801D95AC F0000224 */  addiu      $v0, $zero, 0xF0
    /* 15B0 801D95B0 080040A6 */  sh         $zero, 0x8($s2)
    /* 15B4 801D95B4 0A0040A6 */  sh         $zero, 0xA($s2)
    /* 15B8 801D95B8 100056A6 */  sh         $s6, 0x10($s2)
    /* 15BC 801D95BC 120040A6 */  sh         $zero, 0x12($s2)
    /* 15C0 801D95C0 180040A6 */  sh         $zero, 0x18($s2)
    /* 15C4 801D95C4 1A0042A6 */  sh         $v0, 0x1A($s2)
    /* 15C8 801D95C8 200056A6 */  sh         $s6, 0x20($s2)
    /* 15CC 801D95CC 220042A6 */  sh         $v0, 0x22($s2)
    /* 15D0 801D95D0 2118A000 */  addu       $v1, $a1, $zero
    /* 15D4 801D95D4 0300A104 */  bgez       $a1, .L801D95E4
    /* 15D8 801D95D8 2130A000 */   addu      $a2, $a1, $zero
    /* 15DC 801D95DC 7D650708 */  j          .L801D95F4
    /* 15E0 801D95E0 21300000 */   addu      $a2, $zero, $zero
  .L801D95E4:
    /* 15E4 801D95E4 0001A228 */  slti       $v0, $a1, 0x100
    /* 15E8 801D95E8 02004014 */  bnez       $v0, .L801D95F4
    /* 15EC 801D95EC 00000000 */   nop
    /* 15F0 801D95F0 FF000624 */  addiu      $a2, $zero, 0xFF
  .L801D95F4:
    /* 15F4 801D95F4 03006104 */  bgez       $v1, .L801D9604
    /* 15F8 801D95F8 00016228 */   slti      $v0, $v1, 0x100
    /* 15FC 801D95FC 84650708 */  j          .L801D9610
    /* 1600 801D9600 21180000 */   addu      $v1, $zero, $zero
  .L801D9604:
    /* 1604 801D9604 02004014 */  bnez       $v0, .L801D9610
    /* 1608 801D9608 00000000 */   nop
    /* 160C 801D960C FF000324 */  addiu      $v1, $zero, 0xFF
  .L801D9610:
    /* 1610 801D9610 0300A104 */  bgez       $a1, .L801D9620
    /* 1614 801D9614 0001A228 */   slti      $v0, $a1, 0x100
    /* 1618 801D9618 8B650708 */  j          .L801D962C
    /* 161C 801D961C 21280000 */   addu      $a1, $zero, $zero
  .L801D9620:
    /* 1620 801D9620 02004014 */  bnez       $v0, .L801D962C
    /* 1624 801D9624 00000000 */   nop
    /* 1628 801D9628 FF000524 */  addiu      $a1, $zero, 0xFF
  .L801D962C:
    /* 162C 801D962C 21204002 */  addu       $a0, $s2, $zero
    /* 1630 801D9630 040046A2 */  sb         $a2, 0x4($s2)
    /* 1634 801D9634 050046A2 */  sb         $a2, 0x5($s2)
    /* 1638 801D9638 060046A2 */  sb         $a2, 0x6($s2)
    /* 163C 801D963C 0C0043A2 */  sb         $v1, 0xC($s2)
    /* 1640 801D9640 0D0043A2 */  sb         $v1, 0xD($s2)
    /* 1644 801D9644 0E0043A2 */  sb         $v1, 0xE($s2)
    /* 1648 801D9648 140043A2 */  sb         $v1, 0x14($s2)
    /* 164C 801D964C 150043A2 */  sb         $v1, 0x15($s2)
    /* 1650 801D9650 160043A2 */  sb         $v1, 0x16($s2)
    /* 1654 801D9654 1C0045A2 */  sb         $a1, 0x1C($s2)
    /* 1658 801D9658 1D0045A2 */  sb         $a1, 0x1D($s2)
    /* 165C 801D965C FE71070C */  jal        DrawPrim
    /* 1660 801D9660 1E0045A2 */   sb        $a1, 0x1E($s2)
    /* 1664 801D9664 9670070C */  jal        DrawSync
    /* 1668 801D9668 21200000 */   addu      $a0, $zero, $zero
    /* 166C 801D966C 948B070C */  jal        VSync
    /* 1670 801D9670 21200000 */   addu      $a0, $zero, $zero
    /* 1674 801D9674 01006232 */  andi       $v0, $s3, 0x1
    /* 1678 801D9678 80200200 */  sll        $a0, $v0, 2
    /* 167C 801D967C 21208200 */  addu       $a0, $a0, $v0
    /* 1680 801D9680 80200400 */  sll        $a0, $a0, 2
    /* 1684 801D9684 1800A227 */  addiu      $v0, $sp, 0x18
    /* 1688 801D9688 C972070C */  jal        PutDispEnv
    /* 168C 801D968C 21204400 */   addu      $a0, $v0, $a0
    /* 1690 801D9690 01007326 */  addiu      $s3, $s3, 0x1
    /* 1694 801D9694 2A107502 */  slt        $v0, $s3, $s5
    /* 1698 801D9698 9EFF4014 */  bnez       $v0, .L801D9514
    /* 169C 801D969C 01007032 */   andi      $s0, $s3, 0x1
  .L801D96A0:
    /* 16A0 801D96A0 948B070C */  jal        VSync
    /* 16A4 801D96A4 21200000 */   addu      $a0, $zero, $zero
    /* 16A8 801D96A8 6F70070C */  jal        SetDispMask
    /* 16AC 801D96AC 21200000 */   addu      $a0, $zero, $zero
    /* 16B0 801D96B0 1F80043C */  lui        $a0, %hi(D_801F65D4)
    /* 16B4 801D96B4 D4658424 */  addiu      $a0, $a0, %lo(D_801F65D4)
    /* 16B8 801D96B8 21280000 */  addu       $a1, $zero, $zero
    /* 16BC 801D96BC 21300000 */  addu       $a2, $zero, $zero
    /* 16C0 801D96C0 FB70070C */  jal        ClearImage
    /* 16C4 801D96C4 21380000 */   addu      $a3, $zero, $zero
    /* 16C8 801D96C8 9670070C */  jal        DrawSync
    /* 16CC 801D96CC 21200000 */   addu      $a0, $zero, $zero
    /* 16D0 801D96D0 348A070C */  jal        PadStop
    /* 16D4 801D96D4 00000000 */   nop
    /* 16D8 801D96D8 666F070C */  jal        ResetGraph
    /* 16DC 801D96DC 03000424 */   addiu     $a0, $zero, 0x3
    /* 16E0 801D96E0 4E8C070C */  jal        StopCallback
    /* 16E4 801D96E4 00000000 */   nop
    /* 16E8 801D96E8 4401BF8F */  lw         $ra, 0x144($sp)
    /* 16EC 801D96EC 4001B68F */  lw         $s6, 0x140($sp)
    /* 16F0 801D96F0 3C01B58F */  lw         $s5, 0x13C($sp)
    /* 16F4 801D96F4 3801B48F */  lw         $s4, 0x138($sp)
    /* 16F8 801D96F8 3401B38F */  lw         $s3, 0x134($sp)
    /* 16FC 801D96FC 3001B28F */  lw         $s2, 0x130($sp)
    /* 1700 801D9700 2C01B18F */  lw         $s1, 0x12C($sp)
    /* 1704 801D9704 2801B08F */  lw         $s0, 0x128($sp)
    /* 1708 801D9708 4801BD27 */  addiu      $sp, $sp, 0x148
    /* 170C 801D970C 0800E003 */  jr         $ra
    /* 1710 801D9710 00000000 */   nop
endlabel func_801D91CC

nonmatching func_801D9714, 0x8

glabel func_801D9714
    /* 1714 801D9714 1F80023C */  lui        $v0, %hi(D_801F67E8)
    /* 1718 801D9718 E867428C */  lw         $v0, %lo(D_801F67E8)($v0)
endlabel func_801D9714

nonmatching func_801D971C, 0x1C0

glabel func_801D971C
    /* 171C 801D971C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1720 801D9720 05004010 */  beqz       $v0, .L801D9738
    /* 1724 801D9724 1000BFAF */   sw        $ra, 0x10($sp)
    /* 1728 801D9728 3E87070C */  jal        StCdInterrupt
    /* 172C 801D972C 00000000 */   nop
    /* 1730 801D9730 1F80013C */  lui        $at, %hi(D_801F67E8)
    /* 1734 801D9734 E86720AC */  sw         $zero, %lo(D_801F67E8)($at)
  .L801D9738:
    /* 1738 801D9738 1400848F */  lw         $a0, %gp_rel(D_801F65E4)($gp)
    /* 173C 801D973C 00000000 */  nop
    /* 1740 801D9740 05008290 */  lbu        $v0, 0x5($a0)
    /* 1744 801D9744 00000000 */  nop
    /* 1748 801D9748 1A004010 */  beqz       $v0, .L801D97B4
    /* 174C 801D974C 00000000 */   nop
    /* 1750 801D9750 04008290 */  lbu        $v0, 0x4($a0)
    /* 1754 801D9754 20008384 */  lh         $v1, 0x20($a0)
    /* 1758 801D9758 C0100200 */  sll        $v0, $v0, 3
    /* 175C 801D975C 21108200 */  addu       $v0, $a0, $v0
    /* 1760 801D9760 10004284 */  lh         $v0, 0x10($v0)
    /* 1764 801D9764 00000000 */  nop
    /* 1768 801D9768 1A004300 */  div        $zero, $v0, $v1
    /* 176C 801D976C 02006014 */  bnez       $v1, .L801D9778
    /* 1770 801D9770 00000000 */   nop
    /* 1774 801D9774 0D000700 */  break      7
  .L801D9778:
    /* 1778 801D9778 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 177C 801D977C 04006114 */  bne        $v1, $at, .L801D9790
    /* 1780 801D9780 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 1784 801D9784 02004114 */  bne        $v0, $at, .L801D9790
    /* 1788 801D9788 00000000 */   nop
    /* 178C 801D978C 0D000600 */  break      6
  .L801D9790:
    /* 1790 801D9790 10180000 */  mfhi       $v1
    /* 1794 801D9794 00000000 */  nop
    /* 1798 801D9798 06006010 */  beqz       $v1, .L801D97B4
    /* 179C 801D979C 00000000 */   nop
    /* 17A0 801D97A0 1C008294 */  lhu        $v0, 0x1C($a0)
    /* 17A4 801D97A4 050080A0 */  sb         $zero, 0x5($a0)
    /* 17A8 801D97A8 21104300 */  addu       $v0, $v0, $v1
    /* 17AC 801D97AC F4650708 */  j          .L801D97D0
    /* 17B0 801D97B0 1C0082A4 */   sh        $v0, 0x1C($a0)
  .L801D97B4:
    /* 17B4 801D97B4 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 17B8 801D97B8 00000000 */  nop
    /* 17BC 801D97BC 1C004394 */  lhu        $v1, 0x1C($v0)
    /* 17C0 801D97C0 20004494 */  lhu        $a0, 0x20($v0)
    /* 17C4 801D97C4 00000000 */  nop
    /* 17C8 801D97C8 21186400 */  addu       $v1, $v1, $a0
    /* 17CC 801D97CC 1C0043A4 */  sh         $v1, 0x1C($v0)
  .L801D97D0:
    /* 17D0 801D97D0 1400848F */  lw         $a0, %gp_rel(D_801F65E4)($gp)
    /* 17D4 801D97D4 00000000 */  nop
    /* 17D8 801D97D8 04008290 */  lbu        $v0, 0x4($a0)
    /* 17DC 801D97DC 00000000 */  nop
    /* 17E0 801D97E0 C0100200 */  sll        $v0, $v0, 3
    /* 17E4 801D97E4 21108200 */  addu       $v0, $a0, $v0
    /* 17E8 801D97E8 0C004384 */  lh         $v1, 0xC($v0)
    /* 17EC 801D97EC 10004284 */  lh         $v0, 0x10($v0)
    /* 17F0 801D97F0 1C008584 */  lh         $a1, 0x1C($a0)
    /* 17F4 801D97F4 21186200 */  addu       $v1, $v1, $v0
    /* 17F8 801D97F8 2A18A300 */  slt        $v1, $a1, $v1
    /* 17FC 801D97FC 1A006010 */  beqz       $v1, .L801D9868
    /* 1800 801D9800 01000324 */   addiu     $v1, $zero, 0x1
    /* 1804 801D9804 22008284 */  lh         $v0, 0x22($a0)
    /* 1808 801D9808 00000000 */  nop
    /* 180C 801D980C 1800A200 */  mult       $a1, $v0
    /* 1810 801D9810 12380000 */  mflo       $a3
    /* 1814 801D9814 20008584 */  lh         $a1, 0x20($a0)
    /* 1818 801D9818 03008390 */  lbu        $v1, 0x3($a0)
    /* 181C 801D981C 1800A200 */  mult       $a1, $v0
    /* 1820 801D9820 5800848F */  lw         $a0, %gp_rel(D_801F6628)($gp)
    /* 1824 801D9824 C0100300 */  sll        $v0, $v1, 3
    /* 1828 801D9828 23104300 */  subu       $v0, $v0, $v1
    /* 182C 801D982C 40110200 */  sll        $v0, $v0, 5
    /* 1830 801D9830 21104300 */  addu       $v0, $v0, $v1
    /* 1834 801D9834 80120200 */  sll        $v0, $v0, 10
    /* 1838 801D9838 0500033C */  lui        $v1, (0x50000 >> 16)
    /* 183C 801D983C 21104300 */  addu       $v0, $v0, $v1
    /* 1840 801D9840 21208200 */  addu       $a0, $a0, $v0
    /* 1844 801D9844 40180700 */  sll        $v1, $a3, 1
    /* 1848 801D9848 21208300 */  addu       $a0, $a0, $v1
    /* 184C 801D984C 12280000 */  mflo       $a1
    /* 1850 801D9850 C2170500 */  srl        $v0, $a1, 31
    /* 1854 801D9854 2128A200 */  addu       $a1, $a1, $v0
    /* 1858 801D9858 B96A070C */  jal        DecDCTout
    /* 185C 801D985C 43280500 */   sra       $a1, $a1, 1
    /* 1860 801D9860 33660708 */  j          .L801D98CC
    /* 1864 801D9864 00000000 */   nop
  .L801D9868:
    /* 1868 801D9868 000083A0 */  sb         $v1, 0x0($a0)
    /* 186C 801D986C 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1870 801D9870 00000000 */  nop
    /* 1874 801D9874 050043A0 */  sb         $v1, 0x5($v0)
    /* 1878 801D9878 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 187C 801D987C 00000000 */  nop
    /* 1880 801D9880 04006290 */  lbu        $v0, 0x4($v1)
    /* 1884 801D9884 00000000 */  nop
    /* 1888 801D9888 0100422C */  sltiu      $v0, $v0, 0x1
    /* 188C 801D988C 040062A0 */  sb         $v0, 0x4($v1)
    /* 1890 801D9890 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1894 801D9894 00000000 */  nop
    /* 1898 801D9898 04006290 */  lbu        $v0, 0x4($v1)
    /* 189C 801D989C 00000000 */  nop
    /* 18A0 801D98A0 C0100200 */  sll        $v0, $v0, 3
    /* 18A4 801D98A4 21106200 */  addu       $v0, $v1, $v0
    /* 18A8 801D98A8 0C004494 */  lhu        $a0, 0xC($v0)
    /* 18AC 801D98AC 04006290 */  lbu        $v0, 0x4($v1)
    /* 18B0 801D98B0 00000000 */  nop
    /* 18B4 801D98B4 C0100200 */  sll        $v0, $v0, 3
    /* 18B8 801D98B8 21106200 */  addu       $v0, $v1, $v0
    /* 18BC 801D98BC 1C0064A4 */  sh         $a0, 0x1C($v1)
    /* 18C0 801D98C0 0E004294 */  lhu        $v0, 0xE($v0)
    /* 18C4 801D98C4 00000000 */  nop
    /* 18C8 801D98C8 1E0062A4 */  sh         $v0, 0x1E($v1)
  .L801D98CC:
    /* 18CC 801D98CC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 18D0 801D98D0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 18D4 801D98D4 0800E003 */  jr         $ra
    /* 18D8 801D98D8 00000000 */   nop
endlabel func_801D971C

nonmatching func_801D98DC, 0x88

glabel func_801D98DC
    /* 18DC 801D98DC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 18E0 801D98E0 2800A28F */  lw         $v0, 0x28($sp)
    /* 18E4 801D98E4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 18E8 801D98E8 1F800A3C */  lui        $t2, %hi(D_801F6828)
    /* 18EC 801D98EC 28684A25 */  addiu      $t2, $t2, %lo(D_801F6828)
    /* 18F0 801D98F0 0000838C */  lw         $v1, 0x0($a0)
    /* 18F4 801D98F4 0400888C */  lw         $t0, 0x4($a0)
    /* 18F8 801D98F8 0800898C */  lw         $t1, 0x8($a0)
    /* 18FC 801D98FC 000043AD */  sw         $v1, 0x0($t2)
    /* 1900 801D9900 040048AD */  sw         $t0, 0x4($t2)
    /* 1904 801D9904 080049AD */  sw         $t1, 0x8($t2)
    /* 1908 801D9908 0C00838C */  lw         $v1, 0xC($a0)
    /* 190C 801D990C 1000888C */  lw         $t0, 0x10($a0)
    /* 1910 801D9910 1400898C */  lw         $t1, 0x14($a0)
    /* 1914 801D9914 0C0043AD */  sw         $v1, 0xC($t2)
    /* 1918 801D9918 100048AD */  sw         $t0, 0x10($t2)
    /* 191C 801D991C 140049AD */  sw         $t1, 0x14($t2)
    /* 1920 801D9920 1E80043C */  lui        $a0, %hi(D_801D8800)
    /* 1924 801D9924 00888424 */  addiu      $a0, $a0, %lo(D_801D8800)
    /* 1928 801D9928 540085AF */  sw         $a1, %gp_rel(D_801F6624)($gp)
    /* 192C 801D992C 480086AF */  sw         $a2, %gp_rel(D_801F6618)($gp)
    /* 1930 801D9930 580087AF */  sw         $a3, %gp_rel(D_801F6628)($gp)
    /* 1934 801D9934 4C0082AF */  sw         $v0, %gp_rel(D_801F661C)($gp)
    /* 1938 801D9938 2568070C */  jal        printf
    /* 193C 801D993C 0100053C */   lui       $a1, (0x10000 >> 16)
    /* 1940 801D9940 1E80043C */  lui        $a0, %hi(D_801D881C)
    /* 1944 801D9944 1C888424 */  addiu      $a0, $a0, %lo(D_801D881C)
    /* 1948 801D9948 0C00053C */  lui        $a1, (0xC0800 >> 16)
    /* 194C 801D994C 2568070C */  jal        printf
    /* 1950 801D9950 0008A534 */   ori       $a1, $a1, (0xC0800 & 0xFFFF)
    /* 1954 801D9954 1000BF8F */  lw         $ra, 0x10($sp)
    /* 1958 801D9958 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 195C 801D995C 0800E003 */  jr         $ra
    /* 1960 801D9960 00000000 */   nop
endlabel func_801D98DC

nonmatching func_801D9964, 0x80

glabel func_801D9964
    /* 1964 801D9964 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1968 801D9968 00000000 */  nop
    /* 196C 801D996C 020040A0 */  sb         $zero, 0x2($v0)
    /* 1970 801D9970 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1974 801D9974 00000000 */  nop
    /* 1978 801D9978 030040A0 */  sb         $zero, 0x3($v0)
    /* 197C 801D997C 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1980 801D9980 00000000 */  nop
    /* 1984 801D9984 040040A0 */  sb         $zero, 0x4($v0)
    /* 1988 801D9988 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 198C 801D998C 0C0040A4 */  sh         $zero, 0xC($v0)
    /* 1990 801D9990 0E0040A4 */  sh         $zero, 0xE($v0)
    /* 1994 801D9994 140040A4 */  sh         $zero, 0x14($v0)
    /* 1998 801D9998 160040A4 */  sh         $zero, 0x16($v0)
    /* 199C 801D999C 01000224 */  addiu      $v0, $zero, 0x1
    /* 19A0 801D99A0 010062A0 */  sb         $v0, 0x1($v1)
    /* 19A4 801D99A4 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 19A8 801D99A8 00000000 */  nop
    /* 19AC 801D99AC 01006290 */  lbu        $v0, 0x1($v1)
    /* 19B0 801D99B0 10000424 */  addiu      $a0, $zero, 0x10
    /* 19B4 801D99B4 1C0060A4 */  sh         $zero, 0x1C($v1)
    /* 19B8 801D99B8 02004010 */  beqz       $v0, .L801D99C4
    /* 19BC 801D99BC 1E0060A4 */   sh        $zero, 0x1E($v1)
    /* 19C0 801D99C0 18000424 */  addiu      $a0, $zero, 0x18
  .L801D99C4:
    /* 19C4 801D99C4 000060A0 */  sb         $zero, 0x0($v1)
    /* 19C8 801D99C8 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 19CC 801D99CC 200064A4 */  sh         $a0, 0x20($v1)
    /* 19D0 801D99D0 40010324 */  addiu      $v1, $zero, 0x140
    /* 19D4 801D99D4 080043A4 */  sh         $v1, 0x8($v0)
    /* 19D8 801D99D8 F0000324 */  addiu      $v1, $zero, 0xF0
    /* 19DC 801D99DC 0800E003 */  jr         $ra
    /* 19E0 801D99E0 0A0043A4 */   sh        $v1, 0xA($v0)
endlabel func_801D9964

nonmatching func_801D99E4, 0x88

glabel func_801D99E4
    /* 19E4 801D99E4 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 19E8 801D99E8 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 19EC 801D99EC 21888000 */  addu       $s1, $a0, $zero
    /* 19F0 801D99F0 1800B0AF */  sw         $s0, 0x18($sp)
    /* 19F4 801D99F4 2180A000 */  addu       $s0, $a1, $zero
    /* 19F8 801D99F8 2000BFAF */  sw         $ra, 0x20($sp)
    /* 19FC 801D99FC 3F6A070C */  jal        DecDCTReset
    /* 1A00 801D9A00 21200000 */   addu      $a0, $zero, $zero
    /* 1A04 801D9A04 E86A070C */  jal        DecDCToutCallback
    /* 1A08 801D9A08 21200002 */   addu      $a0, $s0, $zero
    /* 1A0C 801D9A0C 4800848F */  lw         $a0, %gp_rel(D_801F6618)($gp)
    /* 1A10 801D9A10 9C7B070C */  jal        StSetRing
    /* 1A14 801D9A14 20000524 */   addiu     $a1, $zero, 0x20
    /* 1A18 801D9A18 01000524 */  addiu      $a1, $zero, 0x1
    /* 1A1C 801D9A1C 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1A20 801D9A20 FFFF0624 */  addiu      $a2, $zero, -0x1
    /* 1A24 801D9A24 01004490 */  lbu        $a0, 0x1($v0)
    /* 1A28 801D9A28 21380000 */  addu       $a3, $zero, $zero
    /* 1A2C 801D9A2C A686070C */  jal        StSetStream
    /* 1A30 801D9A30 1000A0AF */   sw        $zero, 0x10($sp)
    /* 1A34 801D9A34 02000424 */  addiu      $a0, $zero, 0x2
    /* 1A38 801D9A38 21282002 */  addu       $a1, $s1, $zero
    /* 1A3C 801D9A3C F87C070C */  jal        CdControlB
    /* 1A40 801D9A40 21300000 */   addu      $a2, $zero, $zero
    /* 1A44 801D9A44 03004010 */  beqz       $v0, .L801D9A54
    /* 1A48 801D9A48 21100000 */   addu      $v0, $zero, $zero
    /* 1A4C 801D9A4C FC85070C */  jal        CdRead2
    /* 1A50 801D9A50 C0010424 */   addiu     $a0, $zero, 0x1C0
  .L801D9A54:
    /* 1A54 801D9A54 2000BF8F */  lw         $ra, 0x20($sp)
    /* 1A58 801D9A58 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 1A5C 801D9A5C 1800B08F */  lw         $s0, 0x18($sp)
    /* 1A60 801D9A60 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 1A64 801D9A64 0800E003 */  jr         $ra
    /* 1A68 801D9A68 00000000 */   nop
endlabel func_801D99E4

nonmatching func_801D9A6C, 0x108

glabel func_801D9A6C
    /* 1A6C 801D9A6C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1A70 801D9A70 1800B0AF */  sw         $s0, 0x18($sp)
    /* 1A74 801D9A74 0010103C */  lui        $s0, %hi(D_FFFFFFF)
    /* 1A78 801D9A78 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 1A7C 801D9A7C 1000A427 */  addiu      $a0, $sp, 0x10
  .L801D9A80:
    /* 1A80 801D9A80 0587070C */  jal        StGetNext
    /* 1A84 801D9A84 1400A527 */   addiu     $a1, $sp, 0x14
    /* 1A88 801D9A88 05004010 */  beqz       $v0, .L801D9AA0
    /* 1A8C 801D9A8C FFFF1026 */   addiu     $s0, $s0, %lo(D_FFFFFFF)
    /* 1A90 801D9A90 FBFF0016 */  bnez       $s0, .L801D9A80
    /* 1A94 801D9A94 1000A427 */   addiu     $a0, $sp, 0x10
    /* 1A98 801D9A98 D8660708 */  j          .L801D9B60
    /* 1A9C 801D9A9C 21100000 */   addu      $v0, $zero, $zero
  .L801D9AA0:
    /* 1AA0 801D9AA0 1400A28F */  lw         $v0, 0x14($sp)
    /* 1AA4 801D9AA4 00000000 */  nop
    /* 1AA8 801D9AA8 0800438C */  lw         $v1, 0x8($v0)
    /* 1AAC 801D9AAC 5400828F */  lw         $v0, %gp_rel(D_801F6624)($gp)
    /* 1AB0 801D9AB0 00000000 */  nop
    /* 1AB4 801D9AB4 2B106200 */  sltu       $v0, $v1, $v0
    /* 1AB8 801D9AB8 04004014 */  bnez       $v0, .L801D9ACC
    /* 1ABC 801D9ABC 00000000 */   nop
    /* 1AC0 801D9AC0 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1AC4 801D9AC4 BA660708 */  j          .L801D9AE8
    /* 1AC8 801D9AC8 060040A0 */   sb        $zero, 0x6($v0)
  .L801D9ACC:
    /* 1ACC 801D9ACC 4C00828F */  lw         $v0, %gp_rel(D_801F661C)($gp)
    /* 1AD0 801D9AD0 00000000 */  nop
    /* 1AD4 801D9AD4 2B106200 */  sltu       $v0, $v1, $v0
    /* 1AD8 801D9AD8 03004014 */  bnez       $v0, .L801D9AE8
    /* 1ADC 801D9ADC 01000224 */   addiu     $v0, $zero, 0x1
    /* 1AE0 801D9AE0 1F80013C */  lui        $at, %hi(D_801F65D0)
    /* 1AE4 801D9AE4 D06522AC */  sw         $v0, %lo(D_801F65D0)($at)
  .L801D9AE8:
    /* 1AE8 801D9AE8 1400A48F */  lw         $a0, 0x14($sp)
    /* 1AEC 801D9AEC 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1AF0 801D9AF0 10008294 */  lhu        $v0, 0x10($a0)
    /* 1AF4 801D9AF4 00000000 */  nop
    /* 1AF8 801D9AF8 080062A4 */  sh         $v0, 0x8($v1)
    /* 1AFC 801D9AFC 12008294 */  lhu        $v0, 0x12($a0)
    /* 1B00 801D9B00 21286000 */  addu       $a1, $v1, $zero
    /* 1B04 801D9B04 0A0062A4 */  sh         $v0, 0xA($v1)
    /* 1B08 801D9B08 0100A290 */  lbu        $v0, 0x1($a1)
    /* 1B0C 801D9B0C 00000000 */  nop
    /* 1B10 801D9B10 09004010 */  beqz       $v0, .L801D9B38
    /* 1B14 801D9B14 2130A000 */   addu      $a2, $a1, $zero
    /* 1B18 801D9B18 0800A284 */  lh         $v0, 0x8($a1)
    /* 1B1C 801D9B1C 00000000 */  nop
    /* 1B20 801D9B20 40180200 */  sll        $v1, $v0, 1
    /* 1B24 801D9B24 21186200 */  addu       $v1, $v1, $v0
    /* 1B28 801D9B28 C2170300 */  srl        $v0, $v1, 31
    /* 1B2C 801D9B2C 21186200 */  addu       $v1, $v1, $v0
    /* 1B30 801D9B30 CF660708 */  j          .L801D9B3C
    /* 1B34 801D9B34 42200300 */   srl       $a0, $v1, 1
  .L801D9B38:
    /* 1B38 801D9B38 0800A494 */  lhu        $a0, 0x8($a1)
  .L801D9B3C:
    /* 1B3C 801D9B3C 1000A28F */  lw         $v0, 0x10($sp)
    /* 1B40 801D9B40 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1B44 801D9B44 1800C4A4 */  sh         $a0, 0x18($a2)
    /* 1B48 801D9B48 1000A4A4 */  sh         $a0, 0x10($a1)
    /* 1B4C 801D9B4C 0A006494 */  lhu        $a0, 0xA($v1)
    /* 1B50 801D9B50 0A006594 */  lhu        $a1, 0xA($v1)
    /* 1B54 801D9B54 1A0064A4 */  sh         $a0, 0x1A($v1)
    /* 1B58 801D9B58 120064A4 */  sh         $a0, 0x12($v1)
    /* 1B5C 801D9B5C 220065A4 */  sh         $a1, 0x22($v1)
  .L801D9B60:
    /* 1B60 801D9B60 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 1B64 801D9B64 1800B08F */  lw         $s0, 0x18($sp)
    /* 1B68 801D9B68 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 1B6C 801D9B6C 0800E003 */  jr         $ra
    /* 1B70 801D9B70 00000000 */   nop
endlabel func_801D9A6C

nonmatching func_801D9B74, 0x98

glabel func_801D9B74
    /* 1B74 801D9B74 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1B78 801D9B78 1400BFAF */  sw         $ra, 0x14($sp)
    /* 1B7C 801D9B7C 9B66070C */  jal        func_801D9A6C
    /* 1B80 801D9B80 1000B0AF */   sw        $s0, 0x10($sp)
    /* 1B84 801D9B84 21804000 */  addu       $s0, $v0, $zero
    /* 1B88 801D9B88 09000016 */  bnez       $s0, .L801D9BB0
    /* 1B8C 801D9B8C 21200002 */   addu      $a0, $s0, $zero
    /* 1B90 801D9B90 1E80043C */  lui        $a0, %hi(D_801D8838)
    /* 1B94 801D9B94 38888424 */  addiu      $a0, $a0, %lo(D_801D8838)
    /* 1B98 801D9B98 2568070C */  jal        printf
    /* 1B9C 801D9B9C 00000000 */   nop
    /* 1BA0 801D9BA0 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1BA4 801D9BA4 02000224 */  addiu      $v0, $zero, 0x2
    /* 1BA8 801D9BA8 FE660708 */  j          .L801D9BF8
    /* 1BAC 801D9BAC 060062A0 */   sb        $v0, 0x6($v1)
  .L801D9BB0:
    /* 1BB0 801D9BB0 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1BB4 801D9BB4 00000000 */  nop
    /* 1BB8 801D9BB8 02006290 */  lbu        $v0, 0x2($v1)
    /* 1BBC 801D9BBC 00000000 */  nop
    /* 1BC0 801D9BC0 0100422C */  sltiu      $v0, $v0, 0x1
    /* 1BC4 801D9BC4 020062A0 */  sb         $v0, 0x2($v1)
    /* 1BC8 801D9BC8 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1BCC 801D9BCC 00000000 */  nop
    /* 1BD0 801D9BD0 02004290 */  lbu        $v0, 0x2($v0)
    /* 1BD4 801D9BD4 00000000 */  nop
    /* 1BD8 801D9BD8 80280200 */  sll        $a1, $v0, 2
    /* 1BDC 801D9BDC 2128A200 */  addu       $a1, $a1, $v0
    /* 1BE0 801D9BE0 5800828F */  lw         $v0, %gp_rel(D_801F6628)($gp)
    /* 1BE4 801D9BE4 C02B0500 */  sll        $a1, $a1, 15
    /* 1BE8 801D9BE8 246C070C */  jal        DecDCTvlc
    /* 1BEC 801D9BEC 21284500 */   addu      $a1, $v0, $a1
    /* 1BF0 801D9BF0 C886070C */  jal        StFreeRing
    /* 1BF4 801D9BF4 21200002 */   addu      $a0, $s0, $zero
  .L801D9BF8:
    /* 1BF8 801D9BF8 1400BF8F */  lw         $ra, 0x14($sp)
    /* 1BFC 801D9BFC 1000B08F */  lw         $s0, 0x10($sp)
    /* 1C00 801D9C00 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1C04 801D9C04 0800E003 */  jr         $ra
    /* 1C08 801D9C08 00000000 */   nop
endlabel func_801D9B74

nonmatching func_801D9C0C, 0x120

glabel func_801D9C0C
    /* 1C0C 801D9C0C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1C10 801D9C10 FF3F0424 */  addiu      $a0, $zero, 0x3FFF
    /* 1C14 801D9C14 4800838F */  lw         $v1, %gp_rel(D_801F6618)($gp)
    /* 1C18 801D9C18 FCFF0234 */  ori        $v0, $zero, 0xFFFC
    /* 1C1C 801D9C1C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 1C20 801D9C20 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1C24 801D9C24 21186200 */  addu       $v1, $v1, $v0
  .L801D9C28:
    /* 1C28 801D9C28 000060AC */  sw         $zero, 0x0($v1)
    /* 1C2C 801D9C2C FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 1C30 801D9C30 FDFF8104 */  bgez       $a0, .L801D9C28
    /* 1C34 801D9C34 FCFF6324 */   addiu     $v1, $v1, -0x4
    /* 1C38 801D9C38 21400000 */  addu       $t0, $zero, $zero
    /* 1C3C 801D9C3C FF9F0934 */  ori        $t1, $zero, 0x9FFF
    /* 1C40 801D9C40 5800868F */  lw         $a2, %gp_rel(D_801F6628)($gp)
    /* 1C44 801D9C44 05000A3C */  lui        $t2, (0x50000 >> 16)
    /* 1C48 801D9C48 2138C000 */  addu       $a3, $a2, $zero
    /* 1C4C 801D9C4C 21200000 */  addu       $a0, $zero, $zero
  .L801D9C50:
    /* 1C50 801D9C50 2118E000 */  addu       $v1, $a3, $zero
  .L801D9C54:
    /* 1C54 801D9C54 000060AC */  sw         $zero, 0x0($v1)
    /* 1C58 801D9C58 01008424 */  addiu      $a0, $a0, 0x1
    /* 1C5C 801D9C5C 2A102401 */  slt        $v0, $t1, $a0
    /* 1C60 801D9C60 FCFF4010 */  beqz       $v0, .L801D9C54
    /* 1C64 801D9C64 04006324 */   addiu     $v1, $v1, 0x4
    /* 1C68 801D9C68 21200000 */  addu       $a0, $zero, $zero
    /* 1C6C 801D9C6C 0100053C */  lui        $a1, (0x1C1FF >> 16)
    /* 1C70 801D9C70 FFC1A534 */  ori        $a1, $a1, (0x1C1FF & 0xFFFF)
    /* 1C74 801D9C74 2118CA00 */  addu       $v1, $a2, $t2
  .L801D9C78:
    /* 1C78 801D9C78 000060A4 */  sh         $zero, (0x50000 & 0xFFFF)($v1)
    /* 1C7C 801D9C7C 01008424 */  addiu      $a0, $a0, 0x1
    /* 1C80 801D9C80 2A10A400 */  slt        $v0, $a1, $a0
    /* 1C84 801D9C84 FCFF4010 */  beqz       $v0, .L801D9C78
    /* 1C88 801D9C88 02006324 */   addiu     $v1, $v1, %lo(D_50002)
    /* 1C8C 801D9C8C 0300023C */  lui        $v0, (0x38400 >> 16)
    /* 1C90 801D9C90 00844234 */  ori        $v0, $v0, (0x38400 & 0xFFFF)
    /* 1C94 801D9C94 2130C200 */  addu       $a2, $a2, $v0
    /* 1C98 801D9C98 0200023C */  lui        $v0, (0x28000 >> 16)
    /* 1C9C 801D9C9C 00804234 */  ori        $v0, $v0, (0x28000 & 0xFFFF)
    /* 1CA0 801D9CA0 2138E200 */  addu       $a3, $a3, $v0
    /* 1CA4 801D9CA4 01000825 */  addiu      $t0, $t0, 0x1
    /* 1CA8 801D9CA8 02000229 */  slti       $v0, $t0, 0x2
    /* 1CAC 801D9CAC E8FF4014 */  bnez       $v0, .L801D9C50
    /* 1CB0 801D9CB0 21200000 */   addu      $a0, $zero, $zero
    /* 1CB4 801D9CB4 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1CB8 801D9CB8 01001024 */  addiu      $s0, $zero, 0x1
    /* 1CBC 801D9CBC 5966070C */  jal        func_801D9964
    /* 1CC0 801D9CC0 050050A0 */   sb        $s0, 0x5($v0)
    /* 1CC4 801D9CC4 1F80043C */  lui        $a0, %hi(D_801F6828)
    /* 1CC8 801D9CC8 28688424 */  addiu      $a0, $a0, %lo(D_801F6828)
    /* 1CCC 801D9CCC 1E80053C */  lui        $a1, %hi(func_801D9714)
    /* 1CD0 801D9CD0 1497A524 */  addiu      $a1, $a1, %lo(func_801D9714)
    /* 1CD4 801D9CD4 7966070C */  jal        func_801D99E4
    /* 1CD8 801D9CD8 00000000 */   nop
    /* 1CDC 801D9CDC 07004010 */  beqz       $v0, .L801D9CFC
    /* 1CE0 801D9CE0 00000000 */   nop
    /* 1CE4 801D9CE4 DD66070C */  jal        func_801D9B74
    /* 1CE8 801D9CE8 00000000 */   nop
    /* 1CEC 801D9CEC 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1CF0 801D9CF0 01000224 */  addiu      $v0, $zero, 0x1
    /* 1CF4 801D9CF4 46670708 */  j          .L801D9D18
    /* 1CF8 801D9CF8 060070A0 */   sb        $s0, 0x6($v1)
  .L801D9CFC:
    /* 1CFC 801D9CFC E86A070C */  jal        DecDCToutCallback
    /* 1D00 801D9D00 21200000 */   addu      $a0, $zero, $zero
    /* 1D04 801D9D04 4186070C */  jal        StUnSetRing
    /* 1D08 801D9D08 00000000 */   nop
    /* 1D0C 801D9D0C 2986070C */  jal        StClearRing
    /* 1D10 801D9D10 00000000 */   nop
    /* 1D14 801D9D14 21100000 */  addu       $v0, $zero, $zero
  .L801D9D18:
    /* 1D18 801D9D18 1400BF8F */  lw         $ra, 0x14($sp)
    /* 1D1C 801D9D1C 1000B08F */  lw         $s0, 0x10($sp)
    /* 1D20 801D9D20 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1D24 801D9D24 0800E003 */  jr         $ra
    /* 1D28 801D9D28 00000000 */   nop
endlabel func_801D9C0C

nonmatching func_801D9D2C, 0x98

glabel func_801D9D2C
    /* 1D2C 801D9D2C 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1D30 801D9D30 00000000 */  nop
    /* 1D34 801D9D34 00006290 */  lbu        $v0, 0x0($v1)
    /* 1D38 801D9D38 00000000 */  nop
    /* 1D3C 801D9D3C 1E004014 */  bnez       $v0, .L801D9DB8
    /* 1D40 801D9D40 0010053C */   lui       $a1, %hi(D_FFFFFFF)
    /* 1D44 801D9D44 FFFFA524 */  addiu      $a1, $a1, %lo(D_FFFFFFF)
  .L801D9D48:
    /* 1D48 801D9D48 1400A014 */  bnez       $a1, .L801D9D9C
    /* 1D4C 801D9D4C 00000000 */   nop
    /* 1D50 801D9D50 04006290 */  lbu        $v0, 0x4($v1)
    /* 1D54 801D9D54 00000000 */  nop
    /* 1D58 801D9D58 0100422C */  sltiu      $v0, $v0, 0x1
    /* 1D5C 801D9D5C 040062A0 */  sb         $v0, 0x4($v1)
    /* 1D60 801D9D60 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1D64 801D9D64 00000000 */  nop
    /* 1D68 801D9D68 04006290 */  lbu        $v0, 0x4($v1)
    /* 1D6C 801D9D6C 00000000 */  nop
    /* 1D70 801D9D70 C0100200 */  sll        $v0, $v0, 3
    /* 1D74 801D9D74 21106200 */  addu       $v0, $v1, $v0
    /* 1D78 801D9D78 0C004494 */  lhu        $a0, 0xC($v0)
    /* 1D7C 801D9D7C 04006290 */  lbu        $v0, 0x4($v1)
    /* 1D80 801D9D80 00000000 */  nop
    /* 1D84 801D9D84 C0100200 */  sll        $v0, $v0, 3
    /* 1D88 801D9D88 21106200 */  addu       $v0, $v1, $v0
    /* 1D8C 801D9D8C 1C0064A4 */  sh         $a0, 0x1C($v1)
    /* 1D90 801D9D90 0E004294 */  lhu        $v0, 0xE($v0)
    /* 1D94 801D9D94 00000000 */  nop
    /* 1D98 801D9D98 1E0062A4 */  sh         $v0, 0x1E($v1)
  .L801D9D9C:
    /* 1D9C 801D9D9C 1400838F */  lw         $v1, %gp_rel(D_801F65E4)($gp)
    /* 1DA0 801D9DA0 00000000 */  nop
    /* 1DA4 801D9DA4 00006290 */  lbu        $v0, 0x0($v1)
    /* 1DA8 801D9DA8 00000000 */  nop
    /* 1DAC 801D9DAC E6FF4010 */  beqz       $v0, .L801D9D48
    /* 1DB0 801D9DB0 FFFFA524 */   addiu     $a1, $a1, -0x1
    /* 1DB4 801D9DB4 0100A524 */  addiu      $a1, $a1, 0x1
  .L801D9DB8:
    /* 1DB8 801D9DB8 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1DBC 801D9DBC 0800E003 */  jr         $ra
    /* 1DC0 801D9DC0 000040A0 */   sb        $zero, 0x0($v0)
endlabel func_801D9D2C

nonmatching func_801D9DC4, 0xAC

glabel func_801D9DC4
    /* 1DC4 801D9DC4 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 1DC8 801D9DC8 21308000 */  addu       $a2, $a0, $zero
    /* 1DCC 801D9DCC 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1DD0 801D9DD0 5800838F */  lw         $v1, %gp_rel(D_801F6628)($gp)
    /* 1DD4 801D9DD4 0500043C */  lui        $a0, (0x50000 >> 16)
    /* 1DD8 801D9DD8 2400BFAF */  sw         $ra, 0x24($sp)
    /* 1DDC 801D9DDC 2000B2AF */  sw         $s2, 0x20($sp)
    /* 1DE0 801D9DE0 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 1DE4 801D9DE4 1800B0AF */  sw         $s0, 0x18($sp)
    /* 1DE8 801D9DE8 03004290 */  lbu        $v0, 0x3($v0)
    /* 1DEC 801D9DEC 00000000 */  nop
    /* 1DF0 801D9DF0 04004014 */  bnez       $v0, .L801D9E04
    /* 1DF4 801D9DF4 21286400 */   addu      $a1, $v1, $a0
    /* 1DF8 801D9DF8 0300023C */  lui        $v0, (0x38400 >> 16)
    /* 1DFC 801D9DFC 00844234 */  ori        $v0, $v0, (0x38400 & 0xFFFF)
    /* 1E00 801D9E00 2128A200 */  addu       $a1, $a1, $v0
  .L801D9E04:
    /* 1E04 801D9E04 18000224 */  addiu      $v0, $zero, 0x18
    /* 1E08 801D9E08 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 1E0C 801D9E0C F0000224 */  addiu      $v0, $zero, 0xF0
    /* 1E10 801D9E10 0300C010 */  beqz       $a2, .L801D9E20
    /* 1E14 801D9E14 1600A2A7 */   sh        $v0, 0x16($sp)
    /* 1E18 801D9E18 89670708 */  j          .L801D9E24
    /* 1E1C 801D9E1C 1200A2A7 */   sh        $v0, 0x12($sp)
  .L801D9E20:
    /* 1E20 801D9E20 1200A0A7 */  sh         $zero, 0x12($sp)
  .L801D9E24:
    /* 1E24 801D9E24 21900000 */  addu       $s2, $zero, $zero
    /* 1E28 801D9E28 21880000 */  addu       $s1, $zero, $zero
    /* 1E2C 801D9E2C 2180A000 */  addu       $s0, $a1, $zero
  .L801D9E30:
    /* 1E30 801D9E30 1000B2A7 */  sh         $s2, 0x10($sp)
    /* 1E34 801D9E34 1000A427 */  addiu      $a0, $sp, 0x10
    /* 1E38 801D9E38 4771070C */  jal        LoadImage
    /* 1E3C 801D9E3C 21280002 */   addu      $a1, $s0, $zero
    /* 1E40 801D9E40 01003126 */  addiu      $s1, $s1, 0x1
    /* 1E44 801D9E44 002D1026 */  addiu      $s0, $s0, 0x2D00
    /* 1E48 801D9E48 1400222A */  slti       $v0, $s1, 0x14
    /* 1E4C 801D9E4C F8FF4014 */  bnez       $v0, .L801D9E30
    /* 1E50 801D9E50 18005226 */   addiu     $s2, $s2, 0x18
    /* 1E54 801D9E54 2400BF8F */  lw         $ra, 0x24($sp)
    /* 1E58 801D9E58 2000B28F */  lw         $s2, 0x20($sp)
    /* 1E5C 801D9E5C 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 1E60 801D9E60 1800B08F */  lw         $s0, 0x18($sp)
    /* 1E64 801D9E64 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 1E68 801D9E68 0800E003 */  jr         $ra
    /* 1E6C 801D9E6C 00000000 */   nop
endlabel func_801D9DC4

nonmatching func_801D9E70, 0x128

glabel func_801D9E70
    /* 1E70 801D9E70 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 1E74 801D9E74 2000B0AF */  sw         $s0, 0x20($sp)
    /* 1E78 801D9E78 21808000 */  addu       $s0, $a0, $zero
    /* 1E7C 801D9E7C 01000424 */  addiu      $a0, $zero, 0x1
    /* 1E80 801D9E80 2400BFAF */  sw         $ra, 0x24($sp)
    /* 1E84 801D9E84 437C070C */  jal        CdSync
    /* 1E88 801D9E88 1000A527 */   addiu     $a1, $sp, 0x10
    /* 1E8C 801D9E8C 05000324 */  addiu      $v1, $zero, 0x5
    /* 1E90 801D9E90 0A004314 */  bne        $v0, $v1, .L801D9EBC
    /* 1E94 801D9E94 02000524 */   addiu     $a1, $zero, 0x2
    /* 1E98 801D9E98 1E80043C */  lui        $a0, %hi(D_801D884C)
    /* 1E9C 801D9E9C 4C888424 */  addiu      $a0, $a0, %lo(D_801D884C)
    /* 1EA0 801D9EA0 2568070C */  jal        printf
    /* 1EA4 801D9EA4 00000000 */   nop
    /* 1EA8 801D9EA8 21100000 */  addu       $v0, $zero, $zero
    /* 1EAC 801D9EAC 1400848F */  lw         $a0, %gp_rel(D_801F65E4)($gp)
    /* 1EB0 801D9EB0 02000324 */  addiu      $v1, $zero, 0x2
    /* 1EB4 801D9EB4 E1670708 */  j          .L801D9F84
    /* 1EB8 801D9EB8 060083A0 */   sb        $v1, 0x6($a0)
  .L801D9EBC:
    /* 1EBC 801D9EBC 1400848F */  lw         $a0, %gp_rel(D_801F65E4)($gp)
    /* 1EC0 801D9EC0 00000000 */  nop
    /* 1EC4 801D9EC4 02008390 */  lbu        $v1, 0x2($a0)
    /* 1EC8 801D9EC8 01008490 */  lbu        $a0, 0x1($a0)
    /* 1ECC 801D9ECC 80100300 */  sll        $v0, $v1, 2
    /* 1ED0 801D9ED0 21104300 */  addu       $v0, $v0, $v1
    /* 1ED4 801D9ED4 5800838F */  lw         $v1, %gp_rel(D_801F6628)($gp)
    /* 1ED8 801D9ED8 C0130200 */  sll        $v0, $v0, 15
    /* 1EDC 801D9EDC 02008010 */  beqz       $a0, .L801D9EE8
    /* 1EE0 801D9EE0 21186200 */   addu      $v1, $v1, $v0
    /* 1EE4 801D9EE4 03000524 */  addiu      $a1, $zero, 0x3
  .L801D9EE8:
    /* 1EE8 801D9EE8 9A6A070C */  jal        DecDCTin
    /* 1EEC 801D9EEC 21206000 */   addu      $a0, $v1, $zero
    /* 1EF0 801D9EF0 1400848F */  lw         $a0, %gp_rel(D_801F65E4)($gp)
    /* 1EF4 801D9EF4 00000000 */  nop
    /* 1EF8 801D9EF8 22008584 */  lh         $a1, 0x22($a0)
    /* 1EFC 801D9EFC 03008390 */  lbu        $v1, 0x3($a0)
    /* 1F00 801D9F00 20008484 */  lh         $a0, 0x20($a0)
    /* 1F04 801D9F04 FFFFA624 */  addiu      $a2, $a1, -0x1
    /* 1F08 801D9F08 C0100300 */  sll        $v0, $v1, 3
    /* 1F0C 801D9F0C 23104300 */  subu       $v0, $v0, $v1
    /* 1F10 801D9F10 40110200 */  sll        $v0, $v0, 5
    /* 1F14 801D9F14 21104300 */  addu       $v0, $v0, $v1
    /* 1F18 801D9F18 80120200 */  sll        $v0, $v0, 10
    /* 1F1C 801D9F1C 0500033C */  lui        $v1, (0x50000 >> 16)
    /* 1F20 801D9F20 21104300 */  addu       $v0, $v0, $v1
    /* 1F24 801D9F24 5800838F */  lw         $v1, %gp_rel(D_801F6628)($gp)
    /* 1F28 801D9F28 00210400 */  sll        $a0, $a0, 4
    /* 1F2C 801D9F2C 0200C104 */  bgez       $a2, .L801D9F38
    /* 1F30 801D9F30 21186200 */   addu      $v1, $v1, $v0
    /* 1F34 801D9F34 0E00A624 */  addiu      $a2, $a1, 0xE
  .L801D9F38:
    /* 1F38 801D9F38 03110600 */  sra        $v0, $a2, 4
    /* 1F3C 801D9F3C 01004224 */  addiu      $v0, $v0, 0x1
    /* 1F40 801D9F40 18008200 */  mult       $a0, $v0
    /* 1F44 801D9F44 21206000 */  addu       $a0, $v1, $zero
    /* 1F48 801D9F48 12380000 */  mflo       $a3
    /* 1F4C 801D9F4C B96A070C */  jal        DecDCTout
    /* 1F50 801D9F50 43280700 */   sra       $a1, $a3, 1
    /* 1F54 801D9F54 7167070C */  jal        func_801D9DC4
    /* 1F58 801D9F58 21200002 */   addu      $a0, $s0, $zero
    /* 1F5C 801D9F5C DD66070C */  jal        func_801D9B74
    /* 1F60 801D9F60 00000000 */   nop
    /* 1F64 801D9F64 4B67070C */  jal        func_801D9D2C
    /* 1F68 801D9F68 00000000 */   nop
    /* 1F6C 801D9F6C 1400848F */  lw         $a0, %gp_rel(D_801F65E4)($gp)
    /* 1F70 801D9F70 00000000 */  nop
    /* 1F74 801D9F74 03008390 */  lbu        $v1, 0x3($a0)
    /* 1F78 801D9F78 01000224 */  addiu      $v0, $zero, 0x1
    /* 1F7C 801D9F7C 0100632C */  sltiu      $v1, $v1, 0x1
    /* 1F80 801D9F80 030083A0 */  sb         $v1, 0x3($a0)
  .L801D9F84:
    /* 1F84 801D9F84 2400BF8F */  lw         $ra, 0x24($sp)
    /* 1F88 801D9F88 2000B08F */  lw         $s0, 0x20($sp)
    /* 1F8C 801D9F8C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 1F90 801D9F90 0800E003 */  jr         $ra
    /* 1F94 801D9F94 00000000 */   nop
endlabel func_801D9E70

nonmatching func_801D9F98, 0xD8

glabel func_801D9F98
    /* 1F98 801D9F98 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1F9C 801D9F9C 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 1FA0 801D9FA0 9C67070C */  jal        func_801D9E70
    /* 1FA4 801D9FA4 1800B0AF */   sw        $s0, 0x18($sp)
    /* 1FA8 801D9FA8 07004010 */  beqz       $v0, .L801D9FC8
    /* 1FAC 801D9FAC 00000000 */   nop
    /* 1FB0 801D9FB0 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1FB4 801D9FB4 00000000 */  nop
    /* 1FB8 801D9FB8 06004390 */  lbu        $v1, 0x6($v0)
    /* 1FBC 801D9FBC 01000224 */  addiu      $v0, $zero, 0x1
    /* 1FC0 801D9FC0 26006210 */  beq        $v1, $v0, .L801DA05C
    /* 1FC4 801D9FC4 00000000 */   nop
  .L801D9FC8:
    /* 1FC8 801D9FC8 E86A070C */  jal        DecDCToutCallback
    /* 1FCC 801D9FCC 21200000 */   addu      $a0, $zero, $zero
    /* 1FD0 801D9FD0 4186070C */  jal        StUnSetRing
    /* 1FD4 801D9FD4 00000000 */   nop
    /* 1FD8 801D9FD8 2986070C */  jal        StClearRing
    /* 1FDC 801D9FDC 00000000 */   nop
    /* 1FE0 801D9FE0 09000424 */  addiu      $a0, $zero, 0x9
    /* 1FE4 801D9FE4 AD7C070C */  jal        CdControlF
    /* 1FE8 801D9FE8 21280000 */   addu      $a1, $zero, $zero
    /* 1FEC 801D9FEC 1400828F */  lw         $v0, %gp_rel(D_801F65E4)($gp)
    /* 1FF0 801D9FF0 00000000 */  nop
    /* 1FF4 801D9FF4 06004390 */  lbu        $v1, 0x6($v0)
    /* 1FF8 801D9FF8 02000224 */  addiu      $v0, $zero, 0x2
    /* 1FFC 801D9FFC 15006214 */  bne        $v1, $v0, .L801DA054
    /* 2000 801DA000 01000224 */   addiu     $v0, $zero, 0x1
    /* 2004 801DA004 21200000 */  addu       $a0, $zero, $zero
    /* 2008 801DA008 21280000 */  addu       $a1, $zero, $zero
    /* 200C 801DA00C 21300000 */  addu       $a2, $zero, $zero
    /* 2010 801DA010 6764070C */  jal        func_801D919C
    /* 2014 801DA014 21380000 */   addu      $a3, $zero, $zero
    /* 2018 801DA018 05001024 */  addiu      $s0, $zero, 0x5
    /* 201C 801DA01C 01000424 */  addiu      $a0, $zero, 0x1
  .L801DA020:
    /* 2020 801DA020 4B7C070C */  jal        CdReady
    /* 2024 801DA024 1000A527 */   addiu     $a1, $sp, 0x10
    /* 2028 801DA028 07005014 */  bne        $v0, $s0, .L801DA048
    /* 202C 801DA02C 07000424 */   addiu     $a0, $zero, 0x7
    /* 2030 801DA030 AD7C070C */  jal        CdControlF
    /* 2034 801DA034 21280000 */   addu      $a1, $zero, $zero
    /* 2038 801DA038 948B070C */  jal        VSync
    /* 203C 801DA03C 04000424 */   addiu     $a0, $zero, 0x4
    /* 2040 801DA040 08680708 */  j          .L801DA020
    /* 2044 801DA044 01000424 */   addiu     $a0, $zero, 0x1
  .L801DA048:
    /* 2048 801DA048 500080AF */  sw         $zero, %gp_rel(D_801F6620)($gp)
    /* 204C 801DA04C 17680708 */  j          .L801DA05C
    /* 2050 801DA050 21100000 */   addu      $v0, $zero, $zero
  .L801DA054:
    /* 2054 801DA054 500082AF */  sw         $v0, %gp_rel(D_801F6620)($gp)
    /* 2058 801DA058 21100000 */  addu       $v0, $zero, $zero
  .L801DA05C:
    /* 205C 801DA05C 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 2060 801DA060 1800B08F */  lw         $s0, 0x18($sp)
    /* 2064 801DA064 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2068 801DA068 0800E003 */  jr         $ra
    /* 206C 801DA06C 00000000 */   nop
endlabel func_801D9F98

nonmatching func_801DA070, 0xC

glabel func_801DA070
    /* 2070 801DA070 5000828F */  lw         $v0, %gp_rel(D_801F6620)($gp)
    /* 2074 801DA074 0800E003 */  jr         $ra
    /* 2078 801DA078 00000000 */   nop
endlabel func_801DA070

nonmatching func_801DA07C, 0x8

glabel func_801DA07C
    /* 207C 801DA07C 0800E003 */  jr         $ra
    /* 2080 801DA080 00000000 */   nop
endlabel func_801DA07C

nonmatching func_801DA084, 0x10

glabel func_801DA084
    /* 2084 801DA084 1F801C3C */  lui        $gp, %hi(_gp)
    /* 2088 801DA088 D0659C27 */  addiu      $gp, $gp, %lo(_gp)
    /* 208C 801DA08C 73640708 */  j          func_801D91CC
    /* 2090 801DA090 00000000 */   nop
endlabel func_801DA084
