.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching SysEnqIntRP, 0xC

glabel SysEnqIntRP
    /* AC70 801E2C70 C0000A24 */  addiu      $t2, $zero, 0xC0
    /* AC74 801E2C74 08004001 */  jr         $t2
    /* AC78 801E2C78 02000924 */   addiu     $t1, $zero, 0x2
endlabel SysEnqIntRP
    /* AC7C 801E2C7C 00000000 */  nop
