.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching DeliverEvent, 0xC

glabel DeliverEvent
    /* 6FB0 801DEFB0 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 6FB4 801DEFB4 08004001 */  jr         $t2
    /* 6FB8 801DEFB8 07000924 */   addiu     $t1, $zero, 0x7
endlabel DeliverEvent
    /* 6FBC 801DEFBC 00000000 */  nop
