.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching SysDeqIntRP, 0xC

glabel SysDeqIntRP
    /* AC80 801E2C80 C0000A24 */  addiu      $t2, $zero, 0xC0
    /* AC84 801E2C84 08004001 */  jr         $t2
    /* AC88 801E2C88 03000924 */   addiu     $t1, $zero, 0x3
endlabel SysDeqIntRP
    /* AC8C 801E2C8C 00000000 */  nop
