.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching GPU_cw, 0xC

glabel GPU_cw
    /* 6E2C 801DEE2C A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 6E30 801DEE30 08004001 */  jr         $t2
    /* 6E34 801DEE34 49000924 */   addiu     $t1, $zero, 0x49
endlabel GPU_cw
    /* 6E38 801DEE38 00000000 */  nop
