.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching FlushCache, 0xC

glabel FlushCache
    /* AD20 801E2D20 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* AD24 801E2D24 08004001 */  jr         $t2
    /* AD28 801E2D28 44000924 */   addiu     $t1, $zero, 0x44
endlabel FlushCache
    /* AD2C 801E2D2C 00000000 */  nop
