.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching _SendPAD, 0x28

glabel _SendPAD
    /* AD30 801E2D30 1F80093C */  lui        $t1, %hi(D_801F65FC)
    /* AD34 801E2D34 FC65298D */  lw         $t1, %lo(D_801F65FC)($t1)
    /* AD38 801E2D38 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* AD3C 801E2D3C 1400BFAF */  sw         $ra, 0x14($sp)
    /* AD40 801E2D40 09F82001 */  jalr       $t1
    /* AD44 801E2D44 00000000 */   nop
    /* AD48 801E2D48 1400BF8F */  lw         $ra, 0x14($sp)
    /* AD4C 801E2D4C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* AD50 801E2D50 0800E003 */  jr         $ra
    /* AD54 801E2D54 00000000 */   nop
endlabel _SendPAD

/* Handwritten function */
nonmatching _send_pad, 0x7C

glabel _send_pad
    /* AD58 801E2D58 1F80013C */  lui        $at, %hi(D_801F65F8)
    /* AD5C 801E2D5C F8653FAC */  sw         $ra, %lo(D_801F65F8)($at)
    /* AD60 801E2D60 6286070C */  jal        EnterCriticalSection
    /* AD64 801E2D64 00000000 */   nop
    /* AD68 801E2D68 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* AD6C 801E2D6C 09F84001 */  jalr       $t2
    /* AD70 801E2D70 57000924 */   addiu     $t1, $zero, 0x57
    /* AD74 801E2D74 6C01428C */  lw         $v0, 0x16C($v0)
    /* AD78 801E2D78 1E800A3C */  lui        $t2, %hi(func_801E2DD4)
    /* AD7C 801E2D7C 1E80093C */  lui        $t1, %hi(D_801E2DE4)
    /* AD80 801E2D80 1F80013C */  lui        $at, %hi(D_801F65FC)
    /* AD84 801E2D84 A0074320 */  addi       $v1, $v0, 0x7A0 /* handwritten instruction */
    /* AD88 801E2D88 D42D4A25 */  addiu      $t2, $t2, %lo(func_801E2DD4)
    /* AD8C 801E2D8C E42D2925 */  addiu      $t1, $t1, %lo(D_801E2DE4)
    /* AD90 801E2D90 FC6523AC */  sw         $v1, %lo(D_801F65FC)($at)
  .L801E2D94:
    /* AD94 801E2D94 0000438D */  lw         $v1, 0x0($t2)
    /* AD98 801E2D98 04004A25 */  addiu      $t2, $t2, 0x4
    /* AD9C 801E2D9C D80343AC */  sw         $v1, 0x3D8($v0)
    /* ADA0 801E2DA0 04004224 */  addiu      $v0, $v0, 0x4
    /* ADA4 801E2DA4 FBFF4915 */  bne        $t2, $t1, .L801E2D94
    /* ADA8 801E2DA8 DC0443AC */   sw        $v1, 0x4DC($v0)
    /* ADAC 801E2DAC 488B070C */  jal        FlushCache
    /* ADB0 801E2DB0 00000000 */   nop
    /* ADB4 801E2DB4 6686070C */  jal        ExitCriticalSection
    /* ADB8 801E2DB8 00000000 */   nop
    /* ADBC 801E2DBC 1F801F3C */  lui        $ra, %hi(D_801F65F8)
    /* ADC0 801E2DC0 F865FF8F */  lw         $ra, %lo(D_801F65F8)($ra)
    /* ADC4 801E2DC4 1F80023C */  lui        $v0, %hi(D_801F65FC)
    /* ADC8 801E2DC8 FC65428C */  lw         $v0, %lo(D_801F65FC)($v0)
    /* ADCC 801E2DCC 0800E003 */  jr         $ra
    /* ADD0 801E2DD0 00000000 */   nop
endlabel _send_pad

nonmatching func_801E2DD4, 0x4

glabel func_801E2DD4
    /* ADD4 801E2DD4 24105500 */  and        $v0, $v0, $s5
endlabel func_801E2DD4
    /* ADD8 801E2DD8 00000000 */  nop
    /* ADDC 801E2DDC 00000000 */  nop
    /* ADE0 801E2DE0 00000000 */  nop
  alabel D_801E2DE4
    /* ADE4 801E2DE4 00000000 */  nop
    /* ADE8 801E2DE8 00000000 */  nop
    /* ADEC 801E2DEC 00000000 */  nop
