.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching ResetEntryInt, 0xC

glabel ResetEntryInt
    /* B784 801E3784 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* B788 801E3788 08004001 */  jr         $t2
    /* B78C 801E378C 18000924 */   addiu     $t1, $zero, 0x18
endlabel ResetEntryInt
    /* B790 801E3790 00000000 */  nop
