.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_801E3754

dlabel D_801E3754
    /* B754 801E3754 50730015 */ .word 0x15007350
    /* B758 801E3758 9C804000 */ .word 0x0040809C /* invalid instruction */
enddlabel D_801E3754

nonmatching _96_remove, 0xC

glabel _96_remove
    /* B75C 801E375C A0000A24 */  addiu      $t2, $zero, 0xA0
    /* B760 801E3760 08004001 */  jr         $t2
    /* B764 801E3764 72000924 */   addiu     $t1, $zero, 0x72
endlabel _96_remove
    /* B768 801E3768 00000000 */  nop
    /* B76C 801E376C 00000000 */  nop
    /* B770 801E3770 00000000 */  nop
