.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching _remove_ChgclrPAD, 0x5C

glabel _remove_ChgclrPAD
    /* ADF0 801E2DF0 1F80013C */  lui        $at, %hi(D_801F6608)
    /* ADF4 801E2DF4 08663FAC */  sw         $ra, %lo(D_801F6608)($at)
    /* ADF8 801E2DF8 6286070C */  jal        EnterCriticalSection
    /* ADFC 801E2DFC 00000000 */   nop
    /* AE00 801E2E00 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* AE04 801E2E04 09F84001 */  jalr       $t2
    /* AE08 801E2E08 57000924 */   addiu     $t1, $zero, 0x57
    /* AE0C 801E2E0C 6C01428C */  lw         $v0, 0x16C($v0)
    /* AE10 801E2E10 09000A24 */  addiu      $t2, $zero, 0x9
    /* AE14 801E2E14 2C064320 */  addi       $v1, $v0, 0x62C /* handwritten instruction */
  .L801E2E18:
    /* AE18 801E2E18 FFFF4A25 */  addiu      $t2, $t2, -0x1
    /* AE1C 801E2E1C 000060AC */  sw         $zero, 0x0($v1)
    /* AE20 801E2E20 FDFF4015 */  bnez       $t2, .L801E2E18
    /* AE24 801E2E24 04006324 */   addiu     $v1, $v1, 0x4
    /* AE28 801E2E28 488B070C */  jal        FlushCache
    /* AE2C 801E2E2C 00000000 */   nop
    /* AE30 801E2E30 6686070C */  jal        ExitCriticalSection
    /* AE34 801E2E34 00000000 */   nop
    /* AE38 801E2E38 1F801F3C */  lui        $ra, %hi(D_801F6608)
    /* AE3C 801E2E3C 0866FF8F */  lw         $ra, %lo(D_801F6608)($ra)
    /* AE40 801E2E40 00000000 */  nop
    /* AE44 801E2E44 0800E003 */  jr         $ra
    /* AE48 801E2E48 00000000 */   nop
endlabel _remove_ChgclrPAD
    /* AE4C 801E2E4C 00000000 */  nop
