.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching EnablePAD, 0x14

glabel EnablePAD
    /* AC90 801E2C90 1F80093C */  lui        $t1, %hi(jtbl_801F65F0)
    /* AC94 801E2C94 F065298D */  lw         $t1, %lo(jtbl_801F65F0)($t1)
    /* AC98 801E2C98 00000000 */  nop
    /* AC9C 801E2C9C 08002001 */  jr         $t1
    /* ACA0 801E2CA0 00000000 */   nop
endlabel EnablePAD

nonmatching DisablePAD, 0x14

glabel DisablePAD
    /* ACA4 801E2CA4 1F80093C */  lui        $t1, %hi(jtbl_801F65F4)
    /* ACA8 801E2CA8 F465298D */  lw         $t1, %lo(jtbl_801F65F4)($t1)
    /* ACAC 801E2CAC 00000000 */  nop
    /* ACB0 801E2CB0 08002001 */  jr         $t1
    /* ACB4 801E2CB4 00000000 */   nop
endlabel DisablePAD

/* Handwritten function */
nonmatching _patch_pad, 0x68

glabel _patch_pad
    /* ACB8 801E2CB8 1F80013C */  lui        $at, %hi(D_801F65E8)
    /* ACBC 801E2CBC E8653FAC */  sw         $ra, %lo(D_801F65E8)($at)
    /* ACC0 801E2CC0 6286070C */  jal        EnterCriticalSection
    /* ACC4 801E2CC4 00000000 */   nop
    /* ACC8 801E2CC8 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* ACCC 801E2CCC 09F84001 */  jalr       $t2
    /* ACD0 801E2CD0 57000924 */   addiu     $t1, $zero, 0x57
    /* ACD4 801E2CD4 6C01428C */  lw         $v0, 0x16C($v0)
    /* ACD8 801E2CD8 1F80013C */  lui        $at, %hi(jtbl_801F65F0)
    /* ACDC 801E2CDC 84084320 */  addi       $v1, $v0, 0x884 /* handwritten instruction */
    /* ACE0 801E2CE0 F06523AC */  sw         $v1, %lo(jtbl_801F65F0)($at)
    /* ACE4 801E2CE4 1F80013C */  lui        $at, %hi(jtbl_801F65F4)
    /* ACE8 801E2CE8 94084320 */  addi       $v1, $v0, 0x894 /* handwritten instruction */
    /* ACEC 801E2CEC 0B000924 */  addiu      $t1, $zero, 0xB
    /* ACF0 801E2CF0 F46523AC */  sw         $v1, %lo(jtbl_801F65F4)($at)
  .L801E2CF4:
    /* ACF4 801E2CF4 FFFF2925 */  addiu      $t1, $t1, -0x1
    /* ACF8 801E2CF8 940540AC */  sw         $zero, 0x594($v0)
    /* ACFC 801E2CFC FDFF2015 */  bnez       $t1, .L801E2CF4
    /* AD00 801E2D00 04004224 */   addiu     $v0, $v0, 0x4
    /* AD04 801E2D04 488B070C */  jal        FlushCache
    /* AD08 801E2D08 00000000 */   nop
    /* AD0C 801E2D0C 1F801F3C */  lui        $ra, %hi(D_801F65E8)
    /* AD10 801E2D10 E865FF8F */  lw         $ra, %lo(D_801F65E8)($ra)
    /* AD14 801E2D14 00000000 */  nop
    /* AD18 801E2D18 0800E003 */  jr         $ra
    /* AD1C 801E2D1C 00000000 */   nop
endlabel _patch_pad
