.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching InitPAD2, 0xC

glabel InitPAD2
    /* AC30 801E2C30 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* AC34 801E2C34 08004001 */  jr         $t2
    /* AC38 801E2C38 12000924 */   addiu     $t1, $zero, 0x12
endlabel InitPAD2
    /* AC3C 801E2C3C 00000000 */  nop
