.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching ChangeClearRCnt, 0xC

glabel ChangeClearRCnt
    /* B034 801E3034 C0000A24 */  addiu      $t2, $zero, 0xC0
    /* B038 801E3038 08004001 */  jr         $t2
    /* B03C 801E303C 0A000924 */   addiu     $t1, $zero, 0xA
endlabel ChangeClearRCnt
    /* B040 801E3040 00000000 */  nop
