.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching PAD_init2, 0xC

glabel PAD_init2
    /* AC60 801E2C60 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* AC64 801E2C64 08004001 */  jr         $t2
    /* AC68 801E2C68 15000924 */   addiu     $t1, $zero, 0x15
endlabel PAD_init2
    /* AC6C 801E2C6C 00000000 */  nop
