.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching EnterCriticalSection, 0x10

glabel EnterCriticalSection
    /* 9988 801E1988 01000424 */  addiu      $a0, $zero, 0x1
    /* 998C 801E198C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 9990 801E1990 0800E003 */  jr         $ra
    /* 9994 801E1994 00000000 */   nop
endlabel EnterCriticalSection
