.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching puts, 0x50

glabel puts
    /* 8F24 801E0F24 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 8F28 801E0F28 1000B0AF */  sw         $s0, 0x10($sp)
    /* 8F2C 801E0F2C 21808000 */  addu       $s0, $a0, $zero
    /* 8F30 801E0F30 07000016 */  bnez       $s0, .L801E0F50
    /* 8F34 801E0F34 1400BFAF */   sw        $ra, 0x14($sp)
    /* 8F38 801E0F38 1E80103C */  lui        $s0, %hi(D_801D9090)
    /* 8F3C 801E0F3C 90901026 */  addiu      $s0, $s0, %lo(D_801D9090)
    /* 8F40 801E0F40 D4830708 */  j          .L801E0F50
    /* 8F44 801E0F44 00000000 */   nop
  .L801E0F48:
    /* 8F48 801E0F48 026A070C */  jal        putchar
    /* 8F4C 801E0F4C 00000000 */   nop
  .L801E0F50:
    /* 8F50 801E0F50 00000492 */  lbu        $a0, 0x0($s0)
    /* 8F54 801E0F54 00000000 */  nop
    /* 8F58 801E0F58 FBFF8014 */  bnez       $a0, .L801E0F48
    /* 8F5C 801E0F5C 01001026 */   addiu     $s0, $s0, 0x1
    /* 8F60 801E0F60 1400BF8F */  lw         $ra, 0x14($sp)
    /* 8F64 801E0F64 1000B08F */  lw         $s0, 0x10($sp)
    /* 8F68 801E0F68 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 8F6C 801E0F6C 0800E003 */  jr         $ra
    /* 8F70 801E0F70 00000000 */   nop
endlabel puts
