.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching cb_read, 0x2D0

glabel cb_read
    /* 8F74 801E0F74 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 8F78 801E0F78 2000B0AF */  sw         $s0, 0x20($sp)
    /* 8F7C 801E0F7C 2180A000 */  addu       $s0, $a1, $zero
    /* 8F80 801E0F80 FF008430 */  andi       $a0, $a0, 0xFF
    /* 8F84 801E0F84 01000224 */  addiu      $v0, $zero, 0x1
    /* 8F88 801E0F88 2400BFAF */  sw         $ra, 0x24($sp)
    /* 8F8C 801E0F8C 1F80013C */  lui        $at, %hi(D_801F5390)
    /* 8F90 801E0F90 905330AC */  sw         $s0, %lo(D_801F5390)($at)
    /* 8F94 801E0F94 5E008214 */  bne        $a0, $v0, .L801E1110
    /* 8F98 801E0F98 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8F9C 801E0F9C 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 8FA0 801E0FA0 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 8FA4 801E0FA4 00000000 */  nop
    /* 8FA8 801E0FA8 5B004018 */  blez       $v0, .L801E1118
    /* 8FAC 801E0FAC 00000000 */   nop
    /* 8FB0 801E0FB0 1F80033C */  lui        $v1, %hi(D_801F536C)
    /* 8FB4 801E0FB4 6C53638C */  lw         $v1, %lo(D_801F536C)($v1)
    /* 8FB8 801E0FB8 00020224 */  addiu      $v0, $zero, 0x200
    /* 8FBC 801E0FBC 25006214 */  bne        $v1, $v0, .L801E1054
    /* 8FC0 801E0FC0 00000000 */   nop
    /* 8FC4 801E0FC4 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 8FC8 801E0FC8 8C53428C */  lw         $v0, %lo(D_801F538C)($v0)
    /* 8FCC 801E0FCC 00000000 */  nop
    /* 8FD0 801E0FD0 01004230 */  andi       $v0, $v0, 0x1
    /* 8FD4 801E0FD4 0E004010 */  beqz       $v0, .L801E1010
    /* 8FD8 801E0FD8 1000A427 */   addiu     $a0, $sp, 0x10
    /* 8FDC 801E0FDC 617D070C */  jal        CdDataCallback
    /* 8FE0 801E0FE0 21200000 */   addu      $a0, $zero, $zero
    /* 8FE4 801E0FE4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 8FE8 801E0FE8 597D070C */  jal        CdGetSector2
    /* 8FEC 801E0FEC 03000524 */   addiu     $a1, $zero, 0x3
    /* 8FF0 801E0FF0 6A7D070C */  jal        CdDataSync
    /* 8FF4 801E0FF4 21200000 */   addu      $a0, $zero, $zero
    /* 8FF8 801E0FF8 1E80043C */  lui        $a0, %hi(cb_data)
    /* 8FFC 801E0FFC 44128424 */  addiu      $a0, $a0, %lo(cb_data)
    /* 9000 801E1000 617D070C */  jal        CdDataCallback
    /* 9004 801E1004 00000000 */   nop
    /* 9008 801E1008 06840708 */  j          .L801E1018
    /* 900C 801E100C 00000000 */   nop
  .L801E1010:
    /* 9010 801E1010 517D070C */  jal        CdGetSector
    /* 9014 801E1014 03000524 */   addiu     $a1, $zero, 0x3
  .L801E1018:
    /* 9018 801E1018 B37D070C */  jal        CdPosToInt
    /* 901C 801E101C 1000A427 */   addiu     $a0, $sp, 0x10
    /* 9020 801E1020 1F80033C */  lui        $v1, %hi(D_801F537C)
    /* 9024 801E1024 7C536324 */  addiu      $v1, $v1, %lo(D_801F537C)
    /* 9028 801E1028 0000638C */  lw         $v1, 0x0($v1)
    /* 902C 801E102C 00000000 */  nop
    /* 9030 801E1030 08004310 */  beq        $v0, $v1, .L801E1054
    /* 9034 801E1034 00000000 */   nop
    /* 9038 801E1038 1E80043C */  lui        $a0, %hi(D_801D9098)
    /* 903C 801E103C 98908424 */  addiu      $a0, $a0, %lo(D_801D9098)
    /* 9040 801E1040 C983070C */  jal        puts
    /* 9044 801E1044 00000000 */   nop
    /* 9048 801E1048 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 904C 801E104C 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 9050 801E1050 705322AC */  sw         $v0, %lo(D_801F5370)($at)
  .L801E1054:
    /* 9054 801E1054 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 9058 801E1058 8C534224 */  addiu      $v0, $v0, %lo(D_801F538C)
    /* 905C 801E105C 0000428C */  lw         $v0, 0x0($v0)
    /* 9060 801E1060 00000000 */  nop
    /* 9064 801E1064 01004230 */  andi       $v0, $v0, 0x1
    /* 9068 801E1068 09004010 */  beqz       $v0, .L801E1090
    /* 906C 801E106C 00000000 */   nop
    /* 9070 801E1070 1F80043C */  lui        $a0, %hi(D_801F5364)
    /* 9074 801E1074 6453848C */  lw         $a0, %lo(D_801F5364)($a0)
    /* 9078 801E1078 1F80053C */  lui        $a1, %hi(D_801F536C)
    /* 907C 801E107C 6C53A58C */  lw         $a1, %lo(D_801F536C)($a1)
    /* 9080 801E1080 597D070C */  jal        CdGetSector2
    /* 9084 801E1084 00000000 */   nop
    /* 9088 801E1088 46840708 */  j          .L801E1118
    /* 908C 801E108C 00000000 */   nop
  .L801E1090:
    /* 9090 801E1090 1F80043C */  lui        $a0, %hi(D_801F5364)
    /* 9094 801E1094 6453848C */  lw         $a0, %lo(D_801F5364)($a0)
    /* 9098 801E1098 1F80053C */  lui        $a1, %hi(D_801F536C)
    /* 909C 801E109C 6C53A58C */  lw         $a1, %lo(D_801F536C)($a1)
    /* 90A0 801E10A0 517D070C */  jal        CdGetSector
    /* 90A4 801E10A4 00000000 */   nop
    /* 90A8 801E10A8 1F80023C */  lui        $v0, %hi(D_801F536C)
    /* 90AC 801E10AC 6C53428C */  lw         $v0, %lo(D_801F536C)($v0)
    /* 90B0 801E10B0 1F80033C */  lui        $v1, %hi(D_801F5364)
    /* 90B4 801E10B4 6453638C */  lw         $v1, %lo(D_801F5364)($v1)
    /* 90B8 801E10B8 80100200 */  sll        $v0, $v0, 2
    /* 90BC 801E10BC 21186200 */  addu       $v1, $v1, $v0
    /* 90C0 801E10C0 1F80013C */  lui        $at, %hi(D_801F5364)
    /* 90C4 801E10C4 645323AC */  sw         $v1, %lo(D_801F5364)($at)
    /* 90C8 801E10C8 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 90CC 801E10CC 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 90D0 801E10D0 00000000 */  nop
    /* 90D4 801E10D4 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 90D8 801E10D8 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 90DC 801E10DC 705322AC */  sw         $v0, %lo(D_801F5370)($at)
    /* 90E0 801E10E0 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 90E4 801E10E4 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 90E8 801E10E8 1F80023C */  lui        $v0, %hi(D_801F537C)
    /* 90EC 801E10EC 7C53428C */  lw         $v0, %lo(D_801F537C)($v0)
    /* 90F0 801E10F0 00000000 */  nop
    /* 90F4 801E10F4 01004224 */  addiu      $v0, $v0, 0x1
    /* 90F8 801E10F8 1F80013C */  lui        $at, %hi(D_801F537C)
    /* 90FC 801E10FC 7C5322AC */  sw         $v0, %lo(D_801F537C)($at)
    /* 9100 801E1100 1F80023C */  lui        $v0, %hi(D_801F537C)
    /* 9104 801E1104 7C53428C */  lw         $v0, %lo(D_801F537C)($v0)
    /* 9108 801E1108 46840708 */  j          .L801E1118
    /* 910C 801E110C 00000000 */   nop
  .L801E1110:
    /* 9110 801E1110 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 9114 801E1114 705322AC */  sw         $v0, %lo(D_801F5370)($at)
  .L801E1118:
    /* 9118 801E1118 948B070C */  jal        VSync
    /* 911C 801E111C FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 9120 801E1120 1F80013C */  lui        $at, %hi(D_801F5374)
    /* 9124 801E1124 745322AC */  sw         $v0, %lo(D_801F5374)($at)
    /* 9128 801E1128 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 912C 801E112C 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 9130 801E1130 00000000 */  nop
    /* 9134 801E1134 03004104 */  bgez       $v0, .L801E1144
    /* 9138 801E1138 00000000 */   nop
    /* 913C 801E113C D084070C */  jal        cd_read_retry
    /* 9140 801E1140 01000424 */   addiu     $a0, $zero, 0x1
  .L801E1144:
    /* 9144 801E1144 948B070C */  jal        VSync
    /* 9148 801E1148 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 914C 801E114C 1F80033C */  lui        $v1, %hi(D_801F5378)
    /* 9150 801E1150 7853638C */  lw         $v1, %lo(D_801F5378)($v1)
    /* 9154 801E1154 00000000 */  nop
    /* 9158 801E1158 B0046324 */  addiu      $v1, $v1, 0x4B0
    /* 915C 801E115C 2A186200 */  slt        $v1, $v1, $v0
    /* 9160 801E1160 03006010 */  beqz       $v1, .L801E1170
    /* 9164 801E1164 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 9168 801E1168 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 916C 801E116C 705322AC */  sw         $v0, %lo(D_801F5370)($at)
  .L801E1170:
    /* 9170 801E1170 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 9174 801E1174 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 9178 801E1178 00000000 */  nop
    /* 917C 801E117C 0A004010 */  beqz       $v0, .L801E11A8
    /* 9180 801E1180 00000000 */   nop
    /* 9184 801E1184 948B070C */  jal        VSync
    /* 9188 801E1188 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 918C 801E118C 1F80033C */  lui        $v1, %hi(D_801F5378)
    /* 9190 801E1190 7853638C */  lw         $v1, %lo(D_801F5378)($v1)
    /* 9194 801E1194 00000000 */  nop
    /* 9198 801E1198 B0046324 */  addiu      $v1, $v1, 0x4B0
    /* 919C 801E119C 2A186200 */  slt        $v1, $v1, $v0
    /* 91A0 801E11A0 23006010 */  beqz       $v1, .L801E1230
    /* 91A4 801E11A4 00000000 */   nop
  .L801E11A8:
    /* 91A8 801E11A8 1F80043C */  lui        $a0, %hi(D_801F5380)
    /* 91AC 801E11AC 8053848C */  lw         $a0, %lo(D_801F5380)($a0)
    /* 91B0 801E11B0 537C070C */  jal        CdSyncCallback
    /* 91B4 801E11B4 00000000 */   nop
    /* 91B8 801E11B8 1F80043C */  lui        $a0, %hi(D_801F5384)
    /* 91BC 801E11BC 8453848C */  lw         $a0, %lo(D_801F5384)($a0)
    /* 91C0 801E11C0 597C070C */  jal        CdReadyCallback
    /* 91C4 801E11C4 00000000 */   nop
    /* 91C8 801E11C8 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 91CC 801E11CC 8C53428C */  lw         $v0, %lo(D_801F538C)($v0)
    /* 91D0 801E11D0 00000000 */  nop
    /* 91D4 801E11D4 01004230 */  andi       $v0, $v0, 0x1
    /* 91D8 801E11D8 06004010 */  beqz       $v0, .L801E11F4
    /* 91DC 801E11DC 09000424 */   addiu     $a0, $zero, 0x9
    /* 91E0 801E11E0 1F80043C */  lui        $a0, %hi(D_801F5388)
    /* 91E4 801E11E4 8853848C */  lw         $a0, %lo(D_801F5388)($a0)
    /* 91E8 801E11E8 617D070C */  jal        CdDataCallback
    /* 91EC 801E11EC 00000000 */   nop
    /* 91F0 801E11F0 09000424 */  addiu      $a0, $zero, 0x9
  .L801E11F4:
    /* 91F4 801E11F4 AD7C070C */  jal        CdControlF
    /* 91F8 801E11F8 21280000 */   addu      $a1, $zero, $zero
    /* 91FC 801E11FC 1F80033C */  lui        $v1, %hi(D_801F5358)
    /* 9200 801E1200 5853638C */  lw         $v1, %lo(D_801F5358)($v1)
    /* 9204 801E1204 00000000 */  nop
    /* 9208 801E1208 09006010 */  beqz       $v1, .L801E1230
    /* 920C 801E120C 00000000 */   nop
    /* 9210 801E1210 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 9214 801E1214 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 9218 801E1218 00000000 */  nop
    /* 921C 801E121C 02004014 */  bnez       $v0, .L801E1228
    /* 9220 801E1220 05000424 */   addiu     $a0, $zero, 0x5
    /* 9224 801E1224 02000424 */  addiu      $a0, $zero, 0x2
  .L801E1228:
    /* 9228 801E1228 09F86000 */  jalr       $v1
    /* 922C 801E122C 21280002 */   addu      $a1, $s0, $zero
  .L801E1230:
    /* 9230 801E1230 2400BF8F */  lw         $ra, 0x24($sp)
    /* 9234 801E1234 2000B08F */  lw         $s0, 0x20($sp)
    /* 9238 801E1238 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 923C 801E123C 0800E003 */  jr         $ra
    /* 9240 801E1240 00000000 */   nop
endlabel cb_read

nonmatching cb_data, 0xFC

glabel cb_data
    /* 9244 801E1244 1F80023C */  lui        $v0, %hi(D_801F536C)
    /* 9248 801E1248 6C53428C */  lw         $v0, %lo(D_801F536C)($v0)
    /* 924C 801E124C 1F80033C */  lui        $v1, %hi(D_801F5364)
    /* 9250 801E1250 6453638C */  lw         $v1, %lo(D_801F5364)($v1)
    /* 9254 801E1254 80100200 */  sll        $v0, $v0, 2
    /* 9258 801E1258 21186200 */  addu       $v1, $v1, $v0
    /* 925C 801E125C 1F80013C */  lui        $at, %hi(D_801F5364)
    /* 9260 801E1260 645323AC */  sw         $v1, %lo(D_801F5364)($at)
    /* 9264 801E1264 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 9268 801E1268 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 926C 801E126C 00000000 */  nop
    /* 9270 801E1270 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 9274 801E1274 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 9278 801E1278 705322AC */  sw         $v0, %lo(D_801F5370)($at)
    /* 927C 801E127C 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 9280 801E1280 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 9284 801E1284 1F80023C */  lui        $v0, %hi(D_801F537C)
    /* 9288 801E1288 7C53428C */  lw         $v0, %lo(D_801F537C)($v0)
    /* 928C 801E128C 00000000 */  nop
    /* 9290 801E1290 01004224 */  addiu      $v0, $v0, 0x1
    /* 9294 801E1294 1F80013C */  lui        $at, %hi(D_801F537C)
    /* 9298 801E1298 7C5322AC */  sw         $v0, %lo(D_801F537C)($at)
    /* 929C 801E129C 1F80023C */  lui        $v0, %hi(D_801F537C)
    /* 92A0 801E12A0 7C53428C */  lw         $v0, %lo(D_801F537C)($v0)
    /* 92A4 801E12A4 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 92A8 801E12A8 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 92AC 801E12AC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 92B0 801E12B0 1F004014 */  bnez       $v0, .L801E1330
    /* 92B4 801E12B4 1000BFAF */   sw        $ra, 0x10($sp)
    /* 92B8 801E12B8 1F80043C */  lui        $a0, %hi(D_801F5380)
    /* 92BC 801E12BC 8053848C */  lw         $a0, %lo(D_801F5380)($a0)
    /* 92C0 801E12C0 537C070C */  jal        CdSyncCallback
    /* 92C4 801E12C4 00000000 */   nop
    /* 92C8 801E12C8 1F80043C */  lui        $a0, %hi(D_801F5384)
    /* 92CC 801E12CC 8453848C */  lw         $a0, %lo(D_801F5384)($a0)
    /* 92D0 801E12D0 597C070C */  jal        CdReadyCallback
    /* 92D4 801E12D4 00000000 */   nop
    /* 92D8 801E12D8 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 92DC 801E12DC 8C53428C */  lw         $v0, %lo(D_801F538C)($v0)
    /* 92E0 801E12E0 00000000 */  nop
    /* 92E4 801E12E4 01004230 */  andi       $v0, $v0, 0x1
    /* 92E8 801E12E8 06004010 */  beqz       $v0, .L801E1304
    /* 92EC 801E12EC 09000424 */   addiu     $a0, $zero, 0x9
    /* 92F0 801E12F0 1F80043C */  lui        $a0, %hi(D_801F5388)
    /* 92F4 801E12F4 8853848C */  lw         $a0, %lo(D_801F5388)($a0)
    /* 92F8 801E12F8 617D070C */  jal        CdDataCallback
    /* 92FC 801E12FC 00000000 */   nop
    /* 9300 801E1300 09000424 */  addiu      $a0, $zero, 0x9
  .L801E1304:
    /* 9304 801E1304 AD7C070C */  jal        CdControlF
    /* 9308 801E1308 21280000 */   addu      $a1, $zero, $zero
    /* 930C 801E130C 1F80023C */  lui        $v0, %hi(D_801F5358)
    /* 9310 801E1310 5853428C */  lw         $v0, %lo(D_801F5358)($v0)
    /* 9314 801E1314 00000000 */  nop
    /* 9318 801E1318 05004010 */  beqz       $v0, .L801E1330
    /* 931C 801E131C 00000000 */   nop
    /* 9320 801E1320 1F80053C */  lui        $a1, %hi(D_801F5390)
    /* 9324 801E1324 9053A58C */  lw         $a1, %lo(D_801F5390)($a1)
    /* 9328 801E1328 09F84000 */  jalr       $v0
    /* 932C 801E132C 02000424 */   addiu     $a0, $zero, 0x2
  .L801E1330:
    /* 9330 801E1330 1000BF8F */  lw         $ra, 0x10($sp)
    /* 9334 801E1334 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 9338 801E1338 0800E003 */  jr         $ra
    /* 933C 801E133C 00000000 */   nop
endlabel cb_data

nonmatching cd_read_retry, 0x214

glabel cd_read_retry
    /* 9340 801E1340 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 9344 801E1344 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 9348 801E1348 21888000 */  addu       $s1, $a0, $zero
    /* 934C 801E134C 21200000 */  addu       $a0, $zero, $zero
    /* 9350 801E1350 2000BFAF */  sw         $ra, 0x20($sp)
    /* 9354 801E1354 537C070C */  jal        CdSyncCallback
    /* 9358 801E1358 1800B0AF */   sw        $s0, 0x18($sp)
    /* 935C 801E135C 597C070C */  jal        CdReadyCallback
    /* 9360 801E1360 21200000 */   addu      $a0, $zero, $zero
    /* 9364 801E1364 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 9368 801E1368 8C534224 */  addiu      $v0, $v0, %lo(D_801F538C)
    /* 936C 801E136C 0000428C */  lw         $v0, 0x0($v0)
    /* 9370 801E1370 00000000 */  nop
    /* 9374 801E1374 01004230 */  andi       $v0, $v0, 0x1
    /* 9378 801E1378 03004010 */  beqz       $v0, .L801E1388
    /* 937C 801E137C 00000000 */   nop
    /* 9380 801E1380 617D070C */  jal        CdDataCallback
    /* 9384 801E1384 21200000 */   addu      $a0, $zero, $zero
  .L801E1388:
    /* 9388 801E1388 F07B070C */  jal        CdStatus
    /* 938C 801E138C 00000000 */   nop
    /* 9390 801E1390 10004230 */  andi       $v0, $v0, 0x10
    /* 9394 801E1394 16004010 */  beqz       $v0, .L801E13F0
    /* 9398 801E1398 00000000 */   nop
    /* 939C 801E139C 948B070C */  jal        VSync
    /* 93A0 801E13A0 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 93A4 801E13A4 3F004230 */  andi       $v0, $v0, 0x3F
    /* 93A8 801E13A8 06004014 */  bnez       $v0, .L801E13C4
    /* 93AC 801E13AC 01000424 */   addiu     $a0, $zero, 0x1
    /* 93B0 801E13B0 1E80043C */  lui        $a0, %hi(D_801D90B0)
    /* 93B4 801E13B4 B0908424 */  addiu      $a0, $a0, %lo(D_801D90B0)
    /* 93B8 801E13B8 C983070C */  jal        puts
    /* 93BC 801E13BC 00000000 */   nop
    /* 93C0 801E13C0 01000424 */  addiu      $a0, $zero, 0x1
  .L801E13C4:
    /* 93C4 801E13C4 AD7C070C */  jal        CdControlF
    /* 93C8 801E13C8 21280000 */   addu      $a1, $zero, $zero
    /* 93CC 801E13CC 948B070C */  jal        VSync
    /* 93D0 801E13D0 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 93D4 801E13D4 1F80013C */  lui        $at, %hi(D_801F5378)
    /* 93D8 801E13D8 785322AC */  sw         $v0, %lo(D_801F5378)($at)
    /* 93DC 801E13DC FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 93E0 801E13E0 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 93E4 801E13E4 705322AC */  sw         $v0, %lo(D_801F5370)($at)
    /* 93E8 801E13E8 4D850708 */  j          .L801E1534
    /* 93EC 801E13EC 00000000 */   nop
  .L801E13F0:
    /* 93F0 801E13F0 15002012 */  beqz       $s1, .L801E1448
    /* 93F4 801E13F4 00000000 */   nop
    /* 93F8 801E13F8 1E80043C */  lui        $a0, %hi(D_801D90C8)
    /* 93FC 801E13FC C8908424 */  addiu      $a0, $a0, %lo(D_801D90C8)
    /* 9400 801E1400 C983070C */  jal        puts
    /* 9404 801E1404 00000000 */   nop
    /* 9408 801E1408 09000424 */  addiu      $a0, $zero, 0x9
    /* 940C 801E140C 21280000 */  addu       $a1, $zero, $zero
    /* 9410 801E1410 5F7C070C */  jal        CdControl
    /* 9414 801E1414 21300000 */   addu      $a2, $zero, $zero
    /* 9418 801E1418 FC7B070C */  jal        CdLastPos
    /* 941C 801E141C 00000000 */   nop
    /* 9420 801E1420 02000424 */  addiu      $a0, $zero, 0x2
    /* 9424 801E1424 21284000 */  addu       $a1, $v0, $zero
    /* 9428 801E1428 5F7C070C */  jal        CdControl
    /* 942C 801E142C 21300000 */   addu      $a2, $zero, $zero
    /* 9430 801E1430 05004014 */  bnez       $v0, .L801E1448
    /* 9434 801E1434 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 9438 801E1438 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 943C 801E143C 705322AC */  sw         $v0, %lo(D_801F5370)($at)
    /* 9440 801E1440 4D850708 */  j          .L801E1534
    /* 9444 801E1444 00000000 */   nop
  .L801E1448:
    /* 9448 801E1448 1B7C070C */  jal        CdFlush
    /* 944C 801E144C 00000000 */   nop
    /* 9450 801E1450 1F80023C */  lui        $v0, %hi(D_801F5368)
    /* 9454 801E1454 68534224 */  addiu      $v0, $v0, %lo(D_801F5368)
    /* 9458 801E1458 0000508C */  lw         $s0, 0x0($v0)
    /* 945C 801E145C 00000000 */  nop
    /* 9460 801E1460 1000B0A3 */  sb         $s0, 0x10($sp)
    /* 9464 801E1464 F47B070C */  jal        CdMode
    /* 9468 801E1468 FF001032 */   andi      $s0, $s0, 0xFF
    /* 946C 801E146C 03000216 */  bne        $s0, $v0, .L801E147C
    /* 9470 801E1470 0E000424 */   addiu     $a0, $zero, 0xE
    /* 9474 801E1474 0A002012 */  beqz       $s1, .L801E14A0
    /* 9478 801E1478 00000000 */   nop
  .L801E147C:
    /* 947C 801E147C 1000A527 */  addiu      $a1, $sp, 0x10
    /* 9480 801E1480 5F7C070C */  jal        CdControl
    /* 9484 801E1484 21300000 */   addu      $a2, $zero, $zero
    /* 9488 801E1488 05004014 */  bnez       $v0, .L801E14A0
    /* 948C 801E148C FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 9490 801E1490 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 9494 801E1494 705322AC */  sw         $v0, %lo(D_801F5370)($at)
    /* 9498 801E1498 4D850708 */  j          .L801E1534
    /* 949C 801E149C 00000000 */   nop
  .L801E14A0:
    /* 94A0 801E14A0 FC7B070C */  jal        CdLastPos
    /* 94A4 801E14A4 00000000 */   nop
    /* 94A8 801E14A8 B37D070C */  jal        CdPosToInt
    /* 94AC 801E14AC 21204000 */   addu      $a0, $v0, $zero
    /* 94B0 801E14B0 1E80043C */  lui        $a0, %hi(cb_read)
    /* 94B4 801E14B4 740F8424 */  addiu      $a0, $a0, %lo(cb_read)
    /* 94B8 801E14B8 1F80013C */  lui        $at, %hi(D_801F537C)
    /* 94BC 801E14BC 7C5322AC */  sw         $v0, %lo(D_801F537C)($at)
    /* 94C0 801E14C0 597C070C */  jal        CdReadyCallback
    /* 94C4 801E14C4 00000000 */   nop
    /* 94C8 801E14C8 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 94CC 801E14CC 8C53428C */  lw         $v0, %lo(D_801F538C)($v0)
    /* 94D0 801E14D0 00000000 */  nop
    /* 94D4 801E14D4 01004230 */  andi       $v0, $v0, 0x1
    /* 94D8 801E14D8 06004010 */  beqz       $v0, .L801E14F4
    /* 94DC 801E14DC 06000424 */   addiu     $a0, $zero, 0x6
    /* 94E0 801E14E0 1E80043C */  lui        $a0, %hi(cb_data)
    /* 94E4 801E14E4 44128424 */  addiu      $a0, $a0, %lo(cb_data)
    /* 94E8 801E14E8 617D070C */  jal        CdDataCallback
    /* 94EC 801E14EC 00000000 */   nop
    /* 94F0 801E14F0 06000424 */  addiu      $a0, $zero, 0x6
  .L801E14F4:
    /* 94F4 801E14F4 1F80023C */  lui        $v0, %hi(D_801F5360)
    /* 94F8 801E14F8 6053428C */  lw         $v0, %lo(D_801F5360)($v0)
    /* 94FC 801E14FC 21280000 */  addu       $a1, $zero, $zero
    /* 9500 801E1500 1F80013C */  lui        $at, %hi(D_801F5364)
    /* 9504 801E1504 645322AC */  sw         $v0, %lo(D_801F5364)($at)
    /* 9508 801E1508 AD7C070C */  jal        CdControlF
    /* 950C 801E150C 00000000 */   nop
    /* 9510 801E1510 1F80023C */  lui        $v0, %hi(D_801F535C)
    /* 9514 801E1514 5C53428C */  lw         $v0, %lo(D_801F535C)($v0)
    /* 9518 801E1518 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 951C 801E151C 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 9520 801E1520 705322AC */  sw         $v0, %lo(D_801F5370)($at)
    /* 9524 801E1524 948B070C */  jal        VSync
    /* 9528 801E1528 00000000 */   nop
    /* 952C 801E152C 1F80013C */  lui        $at, %hi(D_801F5374)
    /* 9530 801E1530 745322AC */  sw         $v0, %lo(D_801F5374)($at)
  .L801E1534:
    /* 9534 801E1534 1F80023C */  lui        $v0, %hi(D_801F5370)
    /* 9538 801E1538 7053428C */  lw         $v0, %lo(D_801F5370)($v0)
    /* 953C 801E153C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 9540 801E1540 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 9544 801E1544 1800B08F */  lw         $s0, 0x18($sp)
    /* 9548 801E1548 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 954C 801E154C 0800E003 */  jr         $ra
    /* 9550 801E1550 00000000 */   nop
endlabel cd_read_retry

nonmatching CdReadBreak, 0x9C

glabel CdReadBreak
    /* 9554 801E1554 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 9558 801E1558 1000B0AF */  sw         $s0, 0x10($sp)
    /* 955C 801E155C 1F80103C */  lui        $s0, %hi(D_801F538C)
    /* 9560 801E1560 8C531026 */  addiu      $s0, $s0, %lo(D_801F538C)
    /* 9564 801E1564 1400BFAF */  sw         $ra, 0x14($sp)
    /* 9568 801E1568 0000028E */  lw         $v0, 0x0($s0)
    /* 956C 801E156C 00000000 */  nop
    /* 9570 801E1570 01004230 */  andi       $v0, $v0, 0x1
    /* 9574 801E1574 03004010 */  beqz       $v0, .L801E1584
    /* 9578 801E1578 00000000 */   nop
    /* 957C 801E157C 6A7D070C */  jal        CdDataSync
    /* 9580 801E1580 21200000 */   addu      $a0, $zero, $zero
  .L801E1584:
    /* 9584 801E1584 1F80013C */  lui        $at, %hi(D_801F5370)
    /* 9588 801E1588 705320AC */  sw         $zero, %lo(D_801F5370)($at)
    /* 958C 801E158C 1F80043C */  lui        $a0, %hi(D_801F5380)
    /* 9590 801E1590 8053848C */  lw         $a0, %lo(D_801F5380)($a0)
    /* 9594 801E1594 537C070C */  jal        CdSyncCallback
    /* 9598 801E1598 00000000 */   nop
    /* 959C 801E159C 1F80043C */  lui        $a0, %hi(D_801F5384)
    /* 95A0 801E15A0 8453848C */  lw         $a0, %lo(D_801F5384)($a0)
    /* 95A4 801E15A4 597C070C */  jal        CdReadyCallback
    /* 95A8 801E15A8 00000000 */   nop
    /* 95AC 801E15AC 0000028E */  lw         $v0, 0x0($s0)
    /* 95B0 801E15B0 00000000 */  nop
    /* 95B4 801E15B4 01004230 */  andi       $v0, $v0, 0x1
    /* 95B8 801E15B8 06004010 */  beqz       $v0, .L801E15D4
    /* 95BC 801E15BC 09000424 */   addiu     $a0, $zero, 0x9
    /* 95C0 801E15C0 1F80043C */  lui        $a0, %hi(D_801F5388)
    /* 95C4 801E15C4 8853848C */  lw         $a0, %lo(D_801F5388)($a0)
    /* 95C8 801E15C8 617D070C */  jal        CdDataCallback
    /* 95CC 801E15CC 00000000 */   nop
    /* 95D0 801E15D0 09000424 */  addiu      $a0, $zero, 0x9
  .L801E15D4:
    /* 95D4 801E15D4 AD7C070C */  jal        CdControlF
    /* 95D8 801E15D8 21280000 */   addu      $a1, $zero, $zero
    /* 95DC 801E15DC 1400BF8F */  lw         $ra, 0x14($sp)
    /* 95E0 801E15E0 1000B08F */  lw         $s0, 0x10($sp)
    /* 95E4 801E15E4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 95E8 801E15E8 0800E003 */  jr         $ra
    /* 95EC 801E15EC 00000000 */   nop
endlabel CdReadBreak

nonmatching CdRead, 0x104

glabel CdRead
    /* 95F0 801E15F0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 95F4 801E15F4 1F80013C */  lui        $at, %hi(D_801F5368)
    /* 95F8 801E15F8 685326AC */  sw         $a2, %lo(D_801F5368)($at)
    /* 95FC 801E15FC 1F80023C */  lui        $v0, %hi(D_801F5368)
    /* 9600 801E1600 6853428C */  lw         $v0, %lo(D_801F5368)($v0)
    /* 9604 801E1604 21388000 */  addu       $a3, $a0, $zero
    /* 9608 801E1608 30004330 */  andi       $v1, $v0, 0x30
    /* 960C 801E160C 06006010 */  beqz       $v1, .L801E1628
    /* 9610 801E1610 1000BFAF */   sw        $ra, 0x10($sp)
    /* 9614 801E1614 20000224 */  addiu      $v0, $zero, 0x20
    /* 9618 801E1618 04006210 */  beq        $v1, $v0, .L801E162C
    /* 961C 801E161C 49020224 */   addiu     $v0, $zero, 0x249
    /* 9620 801E1620 8B850708 */  j          .L801E162C
    /* 9624 801E1624 46020224 */   addiu     $v0, $zero, 0x246
  .L801E1628:
    /* 9628 801E1628 00020224 */  addiu      $v0, $zero, 0x200
  .L801E162C:
    /* 962C 801E162C 1F80013C */  lui        $at, %hi(D_801F536C)
    /* 9630 801E1630 6C5322AC */  sw         $v0, %lo(D_801F536C)($at)
    /* 9634 801E1634 1F80023C */  lui        $v0, %hi(D_801F5368)
    /* 9638 801E1638 6853428C */  lw         $v0, %lo(D_801F5368)($v0)
    /* 963C 801E163C 21200000 */  addu       $a0, $zero, $zero
    /* 9640 801E1640 20004234 */  ori        $v0, $v0, 0x20
    /* 9644 801E1644 1F80013C */  lui        $at, %hi(D_801F5368)
    /* 9648 801E1648 685322AC */  sw         $v0, %lo(D_801F5368)($at)
    /* 964C 801E164C 1F80023C */  lui        $v0, %hi(D_801F535C)
    /* 9650 801E1650 5C534224 */  addiu      $v0, $v0, %lo(D_801F535C)
    /* 9654 801E1654 1F80013C */  lui        $at, %hi(D_801F5360)
    /* 9658 801E1658 605325AC */  sw         $a1, %lo(D_801F5360)($at)
    /* 965C 801E165C 000047AC */  sw         $a3, 0x0($v0)
    /* 9660 801E1660 537C070C */  jal        CdSyncCallback
    /* 9664 801E1664 00000000 */   nop
    /* 9668 801E1668 21200000 */  addu       $a0, $zero, $zero
    /* 966C 801E166C 1F80013C */  lui        $at, %hi(D_801F5380)
    /* 9670 801E1670 805322AC */  sw         $v0, %lo(D_801F5380)($at)
    /* 9674 801E1674 597C070C */  jal        CdReadyCallback
    /* 9678 801E1678 00000000 */   nop
    /* 967C 801E167C 1F80013C */  lui        $at, %hi(D_801F5384)
    /* 9680 801E1680 845322AC */  sw         $v0, %lo(D_801F5384)($at)
    /* 9684 801E1684 1F80023C */  lui        $v0, %hi(D_801F538C)
    /* 9688 801E1688 8C53428C */  lw         $v0, %lo(D_801F538C)($v0)
    /* 968C 801E168C 00000000 */  nop
    /* 9690 801E1690 01004230 */  andi       $v0, $v0, 0x1
    /* 9694 801E1694 05004010 */  beqz       $v0, .L801E16AC
    /* 9698 801E1698 00000000 */   nop
    /* 969C 801E169C 617D070C */  jal        CdDataCallback
    /* 96A0 801E16A0 21200000 */   addu      $a0, $zero, $zero
    /* 96A4 801E16A4 1F80013C */  lui        $at, %hi(D_801F5388)
    /* 96A8 801E16A8 885322AC */  sw         $v0, %lo(D_801F5388)($at)
  .L801E16AC:
    /* 96AC 801E16AC 948B070C */  jal        VSync
    /* 96B0 801E16B0 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 96B4 801E16B4 1F80013C */  lui        $at, %hi(D_801F5378)
    /* 96B8 801E16B8 785322AC */  sw         $v0, %lo(D_801F5378)($at)
    /* 96BC 801E16BC F07B070C */  jal        CdStatus
    /* 96C0 801E16C0 00000000 */   nop
    /* 96C4 801E16C4 E0004230 */  andi       $v0, $v0, 0xE0
    /* 96C8 801E16C8 04004010 */  beqz       $v0, .L801E16DC
    /* 96CC 801E16CC 09000424 */   addiu     $a0, $zero, 0x9
    /* 96D0 801E16D0 21280000 */  addu       $a1, $zero, $zero
    /* 96D4 801E16D4 F87C070C */  jal        CdControlB
    /* 96D8 801E16D8 21300000 */   addu      $a2, $zero, $zero
  .L801E16DC:
    /* 96DC 801E16DC D084070C */  jal        cd_read_retry
    /* 96E0 801E16E0 21200000 */   addu      $a0, $zero, $zero
    /* 96E4 801E16E4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 96E8 801E16E8 2A100200 */  slt        $v0, $zero, $v0
    /* 96EC 801E16EC 0800E003 */  jr         $ra
    /* 96F0 801E16F0 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel CdRead

nonmatching CdReadSync, 0xCC

glabel CdReadSync
    /* 96F4 801E16F4 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 96F8 801E16F8 1800B2AF */  sw         $s2, 0x18($sp)
    /* 96FC 801E16FC 21908000 */  addu       $s2, $a0, $zero
    /* 9700 801E1700 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 9704 801E1704 2198A000 */  addu       $s3, $a1, $zero
    /* 9708 801E1708 1400B1AF */  sw         $s1, 0x14($sp)
    /* 970C 801E170C 1F80113C */  lui        $s1, %hi(D_801F5378)
    /* 9710 801E1710 78533126 */  addiu      $s1, $s1, %lo(D_801F5378)
    /* 9714 801E1714 2000BFAF */  sw         $ra, 0x20($sp)
    /* 9718 801E1718 1000B0AF */  sw         $s0, 0x10($sp)
  .L801E171C:
    /* 971C 801E171C 948B070C */  jal        VSync
    /* 9720 801E1720 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 9724 801E1724 0000238E */  lw         $v1, 0x0($s1)
    /* 9728 801E1728 00000000 */  nop
    /* 972C 801E172C B0046324 */  addiu      $v1, $v1, 0x4B0
    /* 9730 801E1730 2A186200 */  slt        $v1, $v1, $v0
    /* 9734 801E1734 13006014 */  bnez       $v1, .L801E1784
    /* 9738 801E1738 FFFF1024 */   addiu     $s0, $zero, -0x1
    /* 973C 801E173C F8FF228E */  lw         $v0, -0x8($s1)
    /* 9740 801E1740 00000000 */  nop
    /* 9744 801E1744 09004004 */  bltz       $v0, .L801E176C
    /* 9748 801E1748 00000000 */   nop
    /* 974C 801E174C 948B070C */  jal        VSync
    /* 9750 801E1750 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 9754 801E1754 FCFF238E */  lw         $v1, -0x4($s1)
    /* 9758 801E1758 00000000 */  nop
    /* 975C 801E175C 3C006324 */  addiu      $v1, $v1, 0x3C
    /* 9760 801E1760 2A186200 */  slt        $v1, $v1, $v0
    /* 9764 801E1764 06006010 */  beqz       $v1, .L801E1780
    /* 9768 801E1768 00000000 */   nop
  .L801E176C:
    /* 976C 801E176C D084070C */  jal        cd_read_retry
    /* 9770 801E1770 01000424 */   addiu     $a0, $zero, 0x1
    /* 9774 801E1774 E4FF308E */  lw         $s0, -0x1C($s1)
    /* 9778 801E1778 E1850708 */  j          .L801E1784
    /* 977C 801E177C 00000000 */   nop
  .L801E1780:
    /* 9780 801E1780 F8FF308E */  lw         $s0, -0x8($s1)
  .L801E1784:
    /* 9784 801E1784 03004016 */  bnez       $s2, .L801E1794
    /* 9788 801E1788 01000424 */   addiu     $a0, $zero, 0x1
    /* 978C 801E178C E3FF001E */  bgtz       $s0, .L801E171C
    /* 9790 801E1790 00000000 */   nop
  .L801E1794:
    /* 9794 801E1794 4B7C070C */  jal        CdReady
    /* 9798 801E1798 21286002 */   addu      $a1, $s3, $zero
    /* 979C 801E179C 21100002 */  addu       $v0, $s0, $zero
    /* 97A0 801E17A0 2000BF8F */  lw         $ra, 0x20($sp)
    /* 97A4 801E17A4 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 97A8 801E17A8 1800B28F */  lw         $s2, 0x18($sp)
    /* 97AC 801E17AC 1400B18F */  lw         $s1, 0x14($sp)
    /* 97B0 801E17B0 1000B08F */  lw         $s0, 0x10($sp)
    /* 97B4 801E17B4 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 97B8 801E17B8 0800E003 */  jr         $ra
    /* 97BC 801E17BC 00000000 */   nop
endlabel CdReadSync

nonmatching CdReadCallback, 0x18

glabel CdReadCallback
    /* 97C0 801E17C0 1F80023C */  lui        $v0, %hi(D_801F5358)
    /* 97C4 801E17C4 5853428C */  lw         $v0, %lo(D_801F5358)($v0)
    /* 97C8 801E17C8 1F80013C */  lui        $at, %hi(D_801F5358)
    /* 97CC 801E17CC 585324AC */  sw         $a0, %lo(D_801F5358)($at)
    /* 97D0 801E17D0 0800E003 */  jr         $ra
    /* 97D4 801E17D4 00000000 */   nop
endlabel CdReadCallback

nonmatching CdReadMode, 0x18

glabel CdReadMode
    /* 97D8 801E17D8 1F80033C */  lui        $v1, %hi(D_801F538C)
    /* 97DC 801E17DC 8C536324 */  addiu      $v1, $v1, %lo(D_801F538C)
    /* 97E0 801E17E0 0000628C */  lw         $v0, 0x0($v1)
    /* 97E4 801E17E4 000064AC */  sw         $a0, 0x0($v1)
    /* 97E8 801E17E8 0800E003 */  jr         $ra
    /* 97EC 801E17EC 00000000 */   nop
endlabel CdReadMode
