.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StFreeRing, 0xB8

glabel StFreeRing
    /* 9B20 801E1B20 0882053C */  lui        $a1, (0x82082083 >> 16)
    /* 9B24 801E1B24 8320A534 */  ori        $a1, $a1, (0x82082083 & 0xFFFF)
    /* 9B28 801E1B28 2080023C */  lui        $v0, %hi(D_801F8070)
    /* 9B2C 801E1B2C 7080428C */  lw         $v0, %lo(D_801F8070)($v0)
    /* 9B30 801E1B30 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 9B34 801E1B34 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 9B38 801E1B38 40110200 */  sll        $v0, $v0, 5
    /* 9B3C 801E1B3C 21106200 */  addu       $v0, $v1, $v0
    /* 9B40 801E1B40 23208200 */  subu       $a0, $a0, $v0
    /* 9B44 801E1B44 83100400 */  sra        $v0, $a0, 2
    /* 9B48 801E1B48 18004500 */  mult       $v0, $a1
    /* 9B4C 801E1B4C C3270400 */  sra        $a0, $a0, 31
    /* 9B50 801E1B50 10380000 */  mfhi       $a3
    /* 9B54 801E1B54 2110E200 */  addu       $v0, $a3, $v0
    /* 9B58 801E1B58 03120200 */  sra        $v0, $v0, 8
    /* 9B5C 801E1B5C 23284400 */  subu       $a1, $v0, $a0
    /* 9B60 801E1B60 40110500 */  sll        $v0, $a1, 5
    /* 9B64 801E1B64 21186200 */  addu       $v1, $v1, $v0
    /* 9B68 801E1B68 04000424 */  addiu      $a0, $zero, 0x4
    /* 9B6C 801E1B6C 00006284 */  lh         $v0, 0x0($v1)
    /* 9B70 801E1B70 06006394 */  lhu        $v1, 0x6($v1)
    /* 9B74 801E1B74 03004410 */  beq        $v0, $a0, .L801E1B84
    /* 9B78 801E1B78 F8FFBD27 */   addiu     $sp, $sp, -0x8
    /* 9B7C 801E1B7C F3860708 */  j          .L801E1BCC
    /* 9B80 801E1B80 01000224 */   addiu     $v0, $zero, 0x1
  .L801E1B84:
    /* 9B84 801E1B84 00140300 */  sll        $v0, $v1, 16
    /* 9B88 801E1B88 03140200 */  sra        $v0, $v0, 16
    /* 9B8C 801E1B8C 0B004018 */  blez       $v0, .L801E1BBC
    /* 9B90 801E1B90 21200000 */   addu      $a0, $zero, $zero
    /* 9B94 801E1B94 21304000 */  addu       $a2, $v0, $zero
  .L801E1B98:
    /* 9B98 801E1B98 21108500 */  addu       $v0, $a0, $a1
    /* 9B9C 801E1B9C 01008424 */  addiu      $a0, $a0, 0x1
    /* 9BA0 801E1BA0 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 9BA4 801E1BA4 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 9BA8 801E1BA8 40110200 */  sll        $v0, $v0, 5
    /* 9BAC 801E1BAC 21186200 */  addu       $v1, $v1, $v0
    /* 9BB0 801E1BB0 2A108600 */  slt        $v0, $a0, $a2
    /* 9BB4 801E1BB4 F8FF4014 */  bnez       $v0, .L801E1B98
    /* 9BB8 801E1BB8 000060A4 */   sh        $zero, 0x0($v1)
  .L801E1BBC:
    /* 9BBC 801E1BBC 21108500 */  addu       $v0, $a0, $a1
    /* 9BC0 801E1BC0 2080013C */  lui        $at, %hi(D_801F8058)
    /* 9BC4 801E1BC4 588022AC */  sw         $v0, %lo(D_801F8058)($at)
    /* 9BC8 801E1BC8 21100000 */  addu       $v0, $zero, $zero
  .L801E1BCC:
    /* 9BCC 801E1BCC 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 9BD0 801E1BD0 0800E003 */  jr         $ra
    /* 9BD4 801E1BD4 00000000 */   nop
endlabel StFreeRing
