.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching strlen, 0x30

glabel strlen
    /* 28CC 801DA8CC 04008014 */  bnez       $a0, .L801DA8E0
    /* 28D0 801DA8D0 21180000 */   addu      $v1, $zero, $zero
    /* 28D4 801DA8D4 3D6A0708 */  j          .L801DA8F4
    /* 28D8 801DA8D8 21100000 */   addu      $v0, $zero, $zero
  .L801DA8DC:
    /* 28DC 801DA8DC 01006324 */  addiu      $v1, $v1, 0x1
  .L801DA8E0:
    /* 28E0 801DA8E0 00008290 */  lbu        $v0, 0x0($a0)
    /* 28E4 801DA8E4 00000000 */  nop
    /* 28E8 801DA8E8 FCFF4014 */  bnez       $v0, .L801DA8DC
    /* 28EC 801DA8EC 01008424 */   addiu     $a0, $a0, 0x1
    /* 28F0 801DA8F0 21106000 */  addu       $v0, $v1, $zero
  .L801DA8F4:
    /* 28F4 801DA8F4 0800E003 */  jr         $ra
    /* 28F8 801DA8F8 00000000 */   nop
endlabel strlen
