.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching getintr, 0x588

glabel getintr
    /* 774C 801DF74C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 7750 801DF750 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 7754 801DF754 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 7758 801DF758 01000224 */  addiu      $v0, $zero, 0x1
    /* 775C 801DF75C 2800BFAF */  sw         $ra, 0x28($sp)
    /* 7760 801DF760 2400B1AF */  sw         $s1, 0x24($sp)
    /* 7764 801DF764 2000B0AF */  sw         $s0, 0x20($sp)
    /* 7768 801DF768 000062A0 */  sb         $v0, 0x0($v1)
    /* 776C 801DF76C 1F80043C */  lui        $a0, %hi(D_801F5314)
    /* 7770 801DF770 1453848C */  lw         $a0, %lo(D_801F5314)($a0)
    /* 7774 801DF774 00000000 */  nop
    /* 7778 801DF778 00008290 */  lbu        $v0, 0x0($a0)
    /* 777C 801DF77C 00000000 */  nop
    /* 7780 801DF780 07004230 */  andi       $v0, $v0, 0x7
    /* 7784 801DF784 1000A2A3 */  sb         $v0, 0x10($sp)
    /* 7788 801DF788 1000A293 */  lbu        $v0, 0x10($sp)
    /* 778C 801DF78C 00000000 */  nop
    /* 7790 801DF790 49014010 */  beqz       $v0, .L801DFCB8
    /* 7794 801DF794 21880000 */   addu      $s1, $zero, $zero
    /* 7798 801DF798 EC7D0708 */  j          .L801DF7B0
    /* 779C 801DF79C 00000000 */   nop
  .L801DF7A0:
    /* 77A0 801DF7A0 00008290 */  lbu        $v0, 0x0($a0)
    /* 77A4 801DF7A4 00000000 */  nop
    /* 77A8 801DF7A8 07004230 */  andi       $v0, $v0, 0x7
    /* 77AC 801DF7AC 1000A2A3 */  sb         $v0, 0x10($sp)
  .L801DF7B0:
    /* 77B0 801DF7B0 00008290 */  lbu        $v0, 0x0($a0)
    /* 77B4 801DF7B4 1000A393 */  lbu        $v1, 0x10($sp)
    /* 77B8 801DF7B8 07004230 */  andi       $v0, $v0, 0x7
    /* 77BC 801DF7BC F8FF6214 */  bne        $v1, $v0, .L801DF7A0
    /* 77C0 801DF7C0 21800000 */   addu      $s0, $zero, $zero
    /* 77C4 801DF7C4 1800A327 */  addiu      $v1, $sp, 0x18
  .L801DF7C8:
    /* 77C8 801DF7C8 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 77CC 801DF7CC 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 77D0 801DF7D0 00000000 */  nop
    /* 77D4 801DF7D4 00004290 */  lbu        $v0, 0x0($v0)
    /* 77D8 801DF7D8 00000000 */  nop
    /* 77DC 801DF7DC 20004230 */  andi       $v0, $v0, 0x20
    /* 77E0 801DF7E0 0B004010 */  beqz       $v0, .L801DF810
    /* 77E4 801DF7E4 0800022A */   slti      $v0, $s0, 0x8
    /* 77E8 801DF7E8 1F80023C */  lui        $v0, %hi(D_801F530C)
    /* 77EC 801DF7EC 0C53428C */  lw         $v0, %lo(D_801F530C)($v0)
    /* 77F0 801DF7F0 00000000 */  nop
    /* 77F4 801DF7F4 00004290 */  lbu        $v0, 0x0($v0)
    /* 77F8 801DF7F8 01001026 */  addiu      $s0, $s0, 0x1
    /* 77FC 801DF7FC 000062A0 */  sb         $v0, 0x0($v1)
    /* 7800 801DF800 0800022A */  slti       $v0, $s0, 0x8
    /* 7804 801DF804 F0FF4014 */  bnez       $v0, .L801DF7C8
    /* 7808 801DF808 01006324 */   addiu     $v1, $v1, 0x1
    /* 780C 801DF80C 0800022A */  slti       $v0, $s0, 0x8
  .L801DF810:
    /* 7810 801DF810 08004010 */  beqz       $v0, .L801DF834
    /* 7814 801DF814 1800A227 */   addiu     $v0, $sp, 0x18
    /* 7818 801DF818 21180202 */  addu       $v1, $s0, $v0
    /* 781C 801DF81C 2000A427 */  addiu      $a0, $sp, 0x20
  .L801DF820:
    /* 7820 801DF820 000060A0 */  sb         $zero, 0x0($v1)
    /* 7824 801DF824 01006324 */  addiu      $v1, $v1, 0x1
    /* 7828 801DF828 2A106400 */  slt        $v0, $v1, $a0
    /* 782C 801DF82C FCFF4014 */  bnez       $v0, .L801DF820
    /* 7830 801DF830 00000000 */   nop
  .L801DF834:
    /* 7834 801DF834 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 7838 801DF838 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 783C 801DF83C 01000224 */  addiu      $v0, $zero, 0x1
    /* 7840 801DF840 000062A0 */  sb         $v0, 0x0($v1)
    /* 7844 801DF844 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 7848 801DF848 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 784C 801DF84C 07000324 */  addiu      $v1, $zero, 0x7
    /* 7850 801DF850 000043A0 */  sb         $v1, 0x0($v0)
    /* 7854 801DF854 1F80023C */  lui        $v0, %hi(D_801F5310)
    /* 7858 801DF858 1053428C */  lw         $v0, %lo(D_801F5310)($v0)
    /* 785C 801DF85C 00000000 */  nop
    /* 7860 801DF860 000043A0 */  sb         $v1, 0x0($v0)
    /* 7864 801DF864 1000A293 */  lbu        $v0, 0x10($sp)
    /* 7868 801DF868 03000324 */  addiu      $v1, $zero, 0x3
    /* 786C 801DF86C FF004230 */  andi       $v0, $v0, 0xFF
    /* 7870 801DF870 0B004314 */  bne        $v0, $v1, .L801DF8A0
    /* 7874 801DF874 00000000 */   nop
    /* 7878 801DF878 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 787C 801DF87C 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 7880 801DF880 00000000 */  nop
    /* 7884 801DF884 80100200 */  sll        $v0, $v0, 2
    /* 7888 801DF888 1F80013C */  lui        $at, %hi(D_801F5208)
    /* 788C 801DF88C 21082200 */  addu       $at, $at, $v0
    /* 7890 801DF890 0852228C */  lw         $v0, %lo(D_801F5208)($at)
    /* 7894 801DF894 00000000 */  nop
    /* 7898 801DF898 1A004010 */  beqz       $v0, .L801DF904
    /* 789C 801DF89C 00000000 */   nop
  .L801DF8A0:
    /* 78A0 801DF8A0 1F80023C */  lui        $v0, %hi(D_801F5050)
    /* 78A4 801DF8A4 5050428C */  lw         $v0, %lo(D_801F5050)($v0)
    /* 78A8 801DF8A8 00000000 */  nop
    /* 78AC 801DF8AC 10004230 */  andi       $v0, $v0, 0x10
    /* 78B0 801DF8B0 0C004014 */  bnez       $v0, .L801DF8E4
    /* 78B4 801DF8B4 00000000 */   nop
    /* 78B8 801DF8B8 1800A293 */  lbu        $v0, 0x18($sp)
    /* 78BC 801DF8BC 00000000 */  nop
    /* 78C0 801DF8C0 10004230 */  andi       $v0, $v0, 0x10
    /* 78C4 801DF8C4 07004010 */  beqz       $v0, .L801DF8E4
    /* 78C8 801DF8C8 00000000 */   nop
    /* 78CC 801DF8CC 1F80023C */  lui        $v0, %hi(D_801F5058)
    /* 78D0 801DF8D0 5850428C */  lw         $v0, %lo(D_801F5058)($v0)
    /* 78D4 801DF8D4 00000000 */  nop
    /* 78D8 801DF8D8 01004224 */  addiu      $v0, $v0, 0x1
    /* 78DC 801DF8DC 1F80013C */  lui        $at, %hi(D_801F5058)
    /* 78E0 801DF8E0 585022AC */  sw         $v0, %lo(D_801F5058)($at)
  .L801DF8E4:
    /* 78E4 801DF8E4 1800A293 */  lbu        $v0, 0x18($sp)
    /* 78E8 801DF8E8 1900A393 */  lbu        $v1, 0x19($sp)
    /* 78EC 801DF8EC FF004230 */  andi       $v0, $v0, 0xFF
    /* 78F0 801DF8F0 1D005130 */  andi       $s1, $v0, 0x1D
    /* 78F4 801DF8F4 1F80013C */  lui        $at, %hi(D_801F5050)
    /* 78F8 801DF8F8 505022AC */  sw         $v0, %lo(D_801F5050)($at)
    /* 78FC 801DF8FC 1F80013C */  lui        $at, %hi(D_801F5054)
    /* 7900 801DF900 545023AC */  sw         $v1, %lo(D_801F5054)($at)
  .L801DF904:
    /* 7904 801DF904 1000A293 */  lbu        $v0, 0x10($sp)
    /* 7908 801DF908 05000324 */  addiu      $v1, $zero, 0x5
    /* 790C 801DF90C FF004230 */  andi       $v0, $v0, 0xFF
    /* 7910 801DF910 1D004314 */  bne        $v0, $v1, .L801DF988
    /* 7914 801DF914 00000000 */   nop
    /* 7918 801DF918 1F80023C */  lui        $v0, %hi(D_801F504C)
    /* 791C 801DF91C 4C50428C */  lw         $v0, %lo(D_801F504C)($v0)
    /* 7920 801DF920 00000000 */  nop
    /* 7924 801DF924 18004018 */  blez       $v0, .L801DF988
    /* 7928 801DF928 00000000 */   nop
    /* 792C 801DF92C 1E80043C */  lui        $a0, %hi(D_801D8FA8)
    /* 7930 801DF930 A88F8424 */  addiu      $a0, $a0, %lo(D_801D8FA8)
    /* 7934 801DF934 2568070C */  jal        printf
    /* 7938 801DF938 00000000 */   nop
    /* 793C 801DF93C 1F80023C */  lui        $v0, %hi(D_801F504C)
    /* 7940 801DF940 4C50428C */  lw         $v0, %lo(D_801F504C)($v0)
    /* 7944 801DF944 00000000 */  nop
    /* 7948 801DF948 0F004018 */  blez       $v0, .L801DF988
    /* 794C 801DF94C 00000000 */   nop
    /* 7950 801DF950 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 7954 801DF954 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 7958 801DF958 1F80063C */  lui        $a2, %hi(D_801F5050)
    /* 795C 801DF95C 5050C68C */  lw         $a2, %lo(D_801F5050)($a2)
    /* 7960 801DF960 1F80073C */  lui        $a3, %hi(D_801F5054)
    /* 7964 801DF964 5450E78C */  lw         $a3, %lo(D_801F5054)($a3)
    /* 7968 801DF968 80100200 */  sll        $v0, $v0, 2
    /* 796C 801DF96C 1F80013C */  lui        $at, %hi(D_801F5068)
    /* 7970 801DF970 21082200 */  addu       $at, $at, $v0
    /* 7974 801DF974 6850258C */  lw         $a1, %lo(D_801F5068)($at)
    /* 7978 801DF978 1E80043C */  lui        $a0, %hi(D_801D8FB4)
    /* 797C 801DF97C B48F8424 */  addiu      $a0, $a0, %lo(D_801D8FB4)
    /* 7980 801DF980 2568070C */  jal        printf
    /* 7984 801DF984 00000000 */   nop
  .L801DF988:
    /* 7988 801DF988 1000A293 */  lbu        $v0, 0x10($sp)
    /* 798C 801DF98C 00000000 */  nop
    /* 7990 801DF990 FFFF4324 */  addiu      $v1, $v0, -0x1
    /* 7994 801DF994 0500622C */  sltiu      $v0, $v1, 0x5
    /* 7998 801DF998 BE004010 */  beqz       $v0, .L801DFC94
    /* 799C 801DF99C 80100300 */   sll       $v0, $v1, 2
    /* 79A0 801DF9A0 1E80013C */  lui        $at, %hi(jtbl_801D8FF0)
    /* 79A4 801DF9A4 21082200 */  addu       $at, $at, $v0
    /* 79A8 801DF9A8 F08F228C */  lw         $v0, %lo(jtbl_801D8FF0)($at)
    /* 79AC 801DF9AC 00000000 */  nop
    /* 79B0 801DF9B0 08004000 */  jr         $v0
    /* 79B4 801DF9B4 00000000 */   nop
  jlabel .L801DF9B8
    /* 79B8 801DF9B8 12002012 */  beqz       $s1, .L801DFA04
    /* 79BC 801DF9BC 05000224 */   addiu     $v0, $zero, 0x5
    /* 79C0 801DF9C0 1F80033C */  lui        $v1, %hi(D_801F5320)
    /* 79C4 801DF9C4 20536324 */  addiu      $v1, $v1, %lo(D_801F5320)
    /* 79C8 801DF9C8 000062A0 */  sb         $v0, 0x0($v1)
    /* 79CC 801DF9CC 1F80033C */  lui        $v1, %hi(D_801F6780)
    /* 79D0 801DF9D0 80676324 */  addiu      $v1, $v1, %lo(D_801F6780)
    /* 79D4 801DF9D4 49006010 */  beqz       $v1, .L801DFAFC
    /* 79D8 801DF9D8 1800A527 */   addiu     $a1, $sp, 0x18
    /* 79DC 801DF9DC 07000424 */  addiu      $a0, $zero, 0x7
    /* 79E0 801DF9E0 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DF9E4:
    /* 79E4 801DF9E4 0000A290 */  lbu        $v0, 0x0($a1)
    /* 79E8 801DF9E8 0100A524 */  addiu      $a1, $a1, 0x1
    /* 79EC 801DF9EC FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 79F0 801DF9F0 000062A0 */  sb         $v0, 0x0($v1)
    /* 79F4 801DF9F4 FBFF8614 */  bne        $a0, $a2, .L801DF9E4
    /* 79F8 801DF9F8 01006324 */   addiu     $v1, $v1, 0x1
    /* 79FC 801DF9FC 2F7F0708 */  j          .L801DFCBC
    /* 7A00 801DFA00 02000224 */   addiu     $v0, $zero, 0x2
  .L801DFA04:
    /* 7A04 801DFA04 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 7A08 801DFA08 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 7A0C 801DFA0C 00000000 */  nop
    /* 7A10 801DFA10 80100200 */  sll        $v0, $v0, 2
    /* 7A14 801DFA14 1F80013C */  lui        $at, %hi(D_801F5108)
    /* 7A18 801DFA18 21082200 */  addu       $at, $at, $v0
    /* 7A1C 801DFA1C 0851228C */  lw         $v0, %lo(D_801F5108)($at)
    /* 7A20 801DFA20 00000000 */  nop
    /* 7A24 801DFA24 12004010 */  beqz       $v0, .L801DFA70
    /* 7A28 801DFA28 03000224 */   addiu     $v0, $zero, 0x3
    /* 7A2C 801DFA2C 1F80033C */  lui        $v1, %hi(D_801F5320)
    /* 7A30 801DFA30 20536324 */  addiu      $v1, $v1, %lo(D_801F5320)
    /* 7A34 801DFA34 000062A0 */  sb         $v0, 0x0($v1)
    /* 7A38 801DFA38 1F80033C */  lui        $v1, %hi(D_801F6780)
    /* 7A3C 801DFA3C 80676324 */  addiu      $v1, $v1, %lo(D_801F6780)
    /* 7A40 801DFA40 09006010 */  beqz       $v1, .L801DFA68
    /* 7A44 801DFA44 1800A527 */   addiu     $a1, $sp, 0x18
    /* 7A48 801DFA48 07000424 */  addiu      $a0, $zero, 0x7
    /* 7A4C 801DFA4C FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFA50:
    /* 7A50 801DFA50 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7A54 801DFA54 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7A58 801DFA58 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 7A5C 801DFA5C 000062A0 */  sb         $v0, 0x0($v1)
    /* 7A60 801DFA60 FBFF8614 */  bne        $a0, $a2, .L801DFA50
    /* 7A64 801DFA64 01006324 */   addiu     $v1, $v1, 0x1
  .L801DFA68:
    /* 7A68 801DFA68 2F7F0708 */  j          .L801DFCBC
    /* 7A6C 801DFA6C 01000224 */   addiu     $v0, $zero, 0x1
  .L801DFA70:
    /* 7A70 801DFA70 1F80033C */  lui        $v1, %hi(D_801F5320)
    /* 7A74 801DFA74 20536324 */  addiu      $v1, $v1, %lo(D_801F5320)
    /* 7A78 801DFA78 02000224 */  addiu      $v0, $zero, 0x2
    /* 7A7C 801DFA7C 000062A0 */  sb         $v0, 0x0($v1)
    /* 7A80 801DFA80 1F80033C */  lui        $v1, %hi(D_801F6780)
    /* 7A84 801DFA84 80676324 */  addiu      $v1, $v1, %lo(D_801F6780)
    /* 7A88 801DFA88 1C006010 */  beqz       $v1, .L801DFAFC
    /* 7A8C 801DFA8C 1800A527 */   addiu     $a1, $sp, 0x18
    /* 7A90 801DFA90 07000424 */  addiu      $a0, $zero, 0x7
    /* 7A94 801DFA94 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFA98:
    /* 7A98 801DFA98 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7A9C 801DFA9C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7AA0 801DFAA0 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 7AA4 801DFAA4 000062A0 */  sb         $v0, 0x0($v1)
    /* 7AA8 801DFAA8 FBFF8614 */  bne        $a0, $a2, .L801DFA98
    /* 7AAC 801DFAAC 01006324 */   addiu     $v1, $v1, 0x1
    /* 7AB0 801DFAB0 2F7F0708 */  j          .L801DFCBC
    /* 7AB4 801DFAB4 02000224 */   addiu     $v0, $zero, 0x2
  jlabel .L801DFAB8
    /* 7AB8 801DFAB8 02002012 */  beqz       $s1, .L801DFAC4
    /* 7ABC 801DFABC 02000224 */   addiu     $v0, $zero, 0x2
    /* 7AC0 801DFAC0 05000224 */  addiu      $v0, $zero, 0x5
  .L801DFAC4:
    /* 7AC4 801DFAC4 1F80013C */  lui        $at, %hi(D_801F5320)
    /* 7AC8 801DFAC8 205322A0 */  sb         $v0, %lo(D_801F5320)($at)
    /* 7ACC 801DFACC 1F80033C */  lui        $v1, %hi(D_801F6780)
    /* 7AD0 801DFAD0 80676324 */  addiu      $v1, $v1, %lo(D_801F6780)
    /* 7AD4 801DFAD4 09006010 */  beqz       $v1, .L801DFAFC
    /* 7AD8 801DFAD8 1800A527 */   addiu     $a1, $sp, 0x18
    /* 7ADC 801DFADC 07000424 */  addiu      $a0, $zero, 0x7
    /* 7AE0 801DFAE0 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFAE4:
    /* 7AE4 801DFAE4 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7AE8 801DFAE8 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7AEC 801DFAEC FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 7AF0 801DFAF0 000062A0 */  sb         $v0, 0x0($v1)
    /* 7AF4 801DFAF4 FBFF8614 */  bne        $a0, $a2, .L801DFAE4
    /* 7AF8 801DFAF8 01006324 */   addiu     $v1, $v1, 0x1
  .L801DFAFC:
    /* 7AFC 801DFAFC 2F7F0708 */  j          .L801DFCBC
    /* 7B00 801DFB00 02000224 */   addiu     $v0, $zero, 0x2
  jlabel .L801DFB04
    /* 7B04 801DFB04 08002012 */  beqz       $s1, .L801DFB28
    /* 7B08 801DFB08 01000224 */   addiu     $v0, $zero, 0x1
    /* 7B0C 801DFB0C 01000224 */  addiu      $v0, $zero, 0x1
    /* 7B10 801DFB10 02000216 */  bne        $s0, $v0, .L801DFB1C
    /* 7B14 801DFB14 00000000 */   nop
    /* 7B18 801DFB18 21880000 */  addu       $s1, $zero, $zero
  .L801DFB1C:
    /* 7B1C 801DFB1C 02002012 */  beqz       $s1, .L801DFB28
    /* 7B20 801DFB20 01000224 */   addiu     $v0, $zero, 0x1
    /* 7B24 801DFB24 05000224 */  addiu      $v0, $zero, 0x5
  .L801DFB28:
    /* 7B28 801DFB28 1F80013C */  lui        $at, %hi(D_801F5321)
    /* 7B2C 801DFB2C 215322A0 */  sb         $v0, %lo(D_801F5321)($at)
    /* 7B30 801DFB30 1F80033C */  lui        $v1, %hi(D_801F6788)
    /* 7B34 801DFB34 88676324 */  addiu      $v1, $v1, %lo(D_801F6788)
    /* 7B38 801DFB38 09006010 */  beqz       $v1, .L801DFB60
    /* 7B3C 801DFB3C 1800A527 */   addiu     $a1, $sp, 0x18
    /* 7B40 801DFB40 07000424 */  addiu      $a0, $zero, 0x7
    /* 7B44 801DFB44 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFB48:
    /* 7B48 801DFB48 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7B4C 801DFB4C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7B50 801DFB50 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 7B54 801DFB54 000062A0 */  sb         $v0, 0x0($v1)
    /* 7B58 801DFB58 FBFF8614 */  bne        $a0, $a2, .L801DFB48
    /* 7B5C 801DFB5C 01006324 */   addiu     $v1, $v1, 0x1
  .L801DFB60:
    /* 7B60 801DFB60 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 7B64 801DFB64 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 7B68 801DFB68 00000000 */  nop
    /* 7B6C 801DFB6C 000040A0 */  sb         $zero, 0x0($v0)
    /* 7B70 801DFB70 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 7B74 801DFB74 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 7B78 801DFB78 04000224 */  addiu      $v0, $zero, 0x4
    /* 7B7C 801DFB7C 000060A0 */  sb         $zero, 0x0($v1)
    /* 7B80 801DFB80 2F7F0708 */  j          .L801DFCBC
    /* 7B84 801DFB84 00000000 */   nop
  jlabel .L801DFB88
    /* 7B88 801DFB88 1F80043C */  lui        $a0, %hi(D_801F6790)
    /* 7B8C 801DFB8C 90678424 */  addiu      $a0, $a0, %lo(D_801F6790)
    /* 7B90 801DFB90 04000224 */  addiu      $v0, $zero, 0x4
    /* 7B94 801DFB94 1F80013C */  lui        $at, %hi(D_801F5322)
    /* 7B98 801DFB98 225322A0 */  sb         $v0, %lo(D_801F5322)($at)
    /* 7B9C 801DFB9C 1F80023C */  lui        $v0, %hi(D_801F5322)
    /* 7BA0 801DFBA0 22534290 */  lbu        $v0, %lo(D_801F5322)($v0)
    /* 7BA4 801DFBA4 1800A527 */  addiu      $a1, $sp, 0x18
    /* 7BA8 801DFBA8 1F80013C */  lui        $at, %hi(D_801F5321)
    /* 7BAC 801DFBAC 215322A0 */  sb         $v0, %lo(D_801F5321)($at)
    /* 7BB0 801DFBB0 08008010 */  beqz       $a0, .L801DFBD4
    /* 7BB4 801DFBB4 07000324 */   addiu     $v1, $zero, 0x7
    /* 7BB8 801DFBB8 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFBBC:
    /* 7BBC 801DFBBC 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7BC0 801DFBC0 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7BC4 801DFBC4 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 7BC8 801DFBC8 000082A0 */  sb         $v0, 0x0($a0)
    /* 7BCC 801DFBCC FBFF6614 */  bne        $v1, $a2, .L801DFBBC
    /* 7BD0 801DFBD0 01008424 */   addiu     $a0, $a0, 0x1
  .L801DFBD4:
    /* 7BD4 801DFBD4 1F80033C */  lui        $v1, %hi(D_801F6788)
    /* 7BD8 801DFBD8 88676324 */  addiu      $v1, $v1, %lo(D_801F6788)
    /* 7BDC 801DFBDC 09006010 */  beqz       $v1, .L801DFC04
    /* 7BE0 801DFBE0 1800A527 */   addiu     $a1, $sp, 0x18
    /* 7BE4 801DFBE4 07000424 */  addiu      $a0, $zero, 0x7
    /* 7BE8 801DFBE8 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFBEC:
    /* 7BEC 801DFBEC 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7BF0 801DFBF0 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7BF4 801DFBF4 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 7BF8 801DFBF8 000062A0 */  sb         $v0, 0x0($v1)
    /* 7BFC 801DFBFC FBFF8614 */  bne        $a0, $a2, .L801DFBEC
    /* 7C00 801DFC00 01006324 */   addiu     $v1, $v1, 0x1
  .L801DFC04:
    /* 7C04 801DFC04 2F7F0708 */  j          .L801DFCBC
    /* 7C08 801DFC08 04000224 */   addiu     $v0, $zero, 0x4
  jlabel .L801DFC0C
    /* 7C0C 801DFC0C 1F80043C */  lui        $a0, %hi(D_801F6780)
    /* 7C10 801DFC10 80678424 */  addiu      $a0, $a0, %lo(D_801F6780)
    /* 7C14 801DFC14 1800A527 */  addiu      $a1, $sp, 0x18
    /* 7C18 801DFC18 05000224 */  addiu      $v0, $zero, 0x5
    /* 7C1C 801DFC1C 1F80013C */  lui        $at, %hi(D_801F5321)
    /* 7C20 801DFC20 215322A0 */  sb         $v0, %lo(D_801F5321)($at)
    /* 7C24 801DFC24 1F80033C */  lui        $v1, %hi(D_801F5321)
    /* 7C28 801DFC28 21536390 */  lbu        $v1, %lo(D_801F5321)($v1)
    /* 7C2C 801DFC2C 1F80023C */  lui        $v0, %hi(D_801F5320)
    /* 7C30 801DFC30 20534224 */  addiu      $v0, $v0, %lo(D_801F5320)
    /* 7C34 801DFC34 000043A0 */  sb         $v1, 0x0($v0)
    /* 7C38 801DFC38 08008010 */  beqz       $a0, .L801DFC5C
    /* 7C3C 801DFC3C 07000324 */   addiu     $v1, $zero, 0x7
    /* 7C40 801DFC40 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFC44:
    /* 7C44 801DFC44 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7C48 801DFC48 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7C4C 801DFC4C FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 7C50 801DFC50 000082A0 */  sb         $v0, 0x0($a0)
    /* 7C54 801DFC54 FBFF6614 */  bne        $v1, $a2, .L801DFC44
    /* 7C58 801DFC58 01008424 */   addiu     $a0, $a0, 0x1
  .L801DFC5C:
    /* 7C5C 801DFC5C 1F80033C */  lui        $v1, %hi(D_801F6788)
    /* 7C60 801DFC60 88676324 */  addiu      $v1, $v1, %lo(D_801F6788)
    /* 7C64 801DFC64 09006010 */  beqz       $v1, .L801DFC8C
    /* 7C68 801DFC68 1800A527 */   addiu     $a1, $sp, 0x18
    /* 7C6C 801DFC6C 07000424 */  addiu      $a0, $zero, 0x7
    /* 7C70 801DFC70 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DFC74:
    /* 7C74 801DFC74 0000A290 */  lbu        $v0, 0x0($a1)
    /* 7C78 801DFC78 0100A524 */  addiu      $a1, $a1, 0x1
    /* 7C7C 801DFC7C FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 7C80 801DFC80 000062A0 */  sb         $v0, 0x0($v1)
    /* 7C84 801DFC84 FBFF8614 */  bne        $a0, $a2, .L801DFC74
    /* 7C88 801DFC88 01006324 */   addiu     $v1, $v1, 0x1
  .L801DFC8C:
    /* 7C8C 801DFC8C 2F7F0708 */  j          .L801DFCBC
    /* 7C90 801DFC90 06000224 */   addiu     $v0, $zero, 0x6
  .L801DFC94:
    /* 7C94 801DFC94 1E80043C */  lui        $a0, %hi(D_801D8FD0)
    /* 7C98 801DFC98 D08F8424 */  addiu      $a0, $a0, %lo(D_801D8FD0)
    /* 7C9C 801DFC9C C983070C */  jal        puts
    /* 7CA0 801DFCA0 00000000 */   nop
    /* 7CA4 801DFCA4 1000A593 */  lbu        $a1, 0x10($sp)
    /* 7CA8 801DFCA8 1E80043C */  lui        $a0, %hi(D_801D8FE4)
    /* 7CAC 801DFCAC E48F8424 */  addiu      $a0, $a0, %lo(D_801D8FE4)
    /* 7CB0 801DFCB0 2568070C */  jal        printf
    /* 7CB4 801DFCB4 00000000 */   nop
  .L801DFCB8:
    /* 7CB8 801DFCB8 21100000 */  addu       $v0, $zero, $zero
  .L801DFCBC:
    /* 7CBC 801DFCBC 2800BF8F */  lw         $ra, 0x28($sp)
    /* 7CC0 801DFCC0 2400B18F */  lw         $s1, 0x24($sp)
    /* 7CC4 801DFCC4 2000B08F */  lw         $s0, 0x20($sp)
    /* 7CC8 801DFCC8 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 7CCC 801DFCCC 0800E003 */  jr         $ra
    /* 7CD0 801DFCD0 00000000 */   nop
endlabel getintr

nonmatching CD_sync, 0x280

glabel CD_sync
    /* 7CD4 801DFCD4 C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* 7CD8 801DFCD8 2C00B5AF */  sw         $s5, 0x2C($sp)
    /* 7CDC 801DFCDC 21A88000 */  addu       $s5, $a0, $zero
    /* 7CE0 801DFCE0 3000B6AF */  sw         $s6, 0x30($sp)
    /* 7CE4 801DFCE4 21B0A000 */  addu       $s6, $a1, $zero
    /* 7CE8 801DFCE8 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 7CEC 801DFCEC 3400BFAF */  sw         $ra, 0x34($sp)
    /* 7CF0 801DFCF0 2800B4AF */  sw         $s4, 0x28($sp)
    /* 7CF4 801DFCF4 2400B3AF */  sw         $s3, 0x24($sp)
    /* 7CF8 801DFCF8 2000B2AF */  sw         $s2, 0x20($sp)
    /* 7CFC 801DFCFC 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 7D00 801DFD00 948B070C */  jal        VSync
    /* 7D04 801DFD04 1800B0AF */   sw        $s0, 0x18($sp)
    /* 7D08 801DFD08 1F80133C */  lui        $s3, %hi(D_801F50E8)
    /* 7D0C 801DFD0C E8507326 */  addiu      $s3, $s3, %lo(D_801F50E8)
    /* 7D10 801DFD10 1F80123C */  lui        $s2, %hi(D_801F5320)
    /* 7D14 801DFD14 20535226 */  addiu      $s2, $s2, %lo(D_801F5320)
    /* 7D18 801DFD18 01005426 */  addiu      $s4, $s2, 0x1
    /* 7D1C 801DFD1C C0034224 */  addiu      $v0, $v0, 0x3C0
    /* 7D20 801DFD20 1F80013C */  lui        $at, %hi(D_801F6798)
    /* 7D24 801DFD24 986722AC */  sw         $v0, %lo(D_801F6798)($at)
    /* 7D28 801DFD28 1E80023C */  lui        $v0, %hi(D_801D9004)
    /* 7D2C 801DFD2C 04904224 */  addiu      $v0, $v0, %lo(D_801D9004)
    /* 7D30 801DFD30 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 7D34 801DFD34 9C6720AC */  sw         $zero, %lo(D_801F679C)($at)
    /* 7D38 801DFD38 1F80013C */  lui        $at, %hi(D_801F67A0)
    /* 7D3C 801DFD3C A06722AC */  sw         $v0, %lo(D_801F67A0)($at)
  .L801DFD40:
    /* 7D40 801DFD40 948B070C */  jal        VSync
    /* 7D44 801DFD44 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 7D48 801DFD48 1F80033C */  lui        $v1, %hi(D_801F6798)
    /* 7D4C 801DFD4C 9867638C */  lw         $v1, %lo(D_801F6798)($v1)
    /* 7D50 801DFD50 00000000 */  nop
    /* 7D54 801DFD54 2A186200 */  slt        $v1, $v1, $v0
    /* 7D58 801DFD58 0B006014 */  bnez       $v1, .L801DFD88
    /* 7D5C 801DFD5C 00000000 */   nop
    /* 7D60 801DFD60 1F80033C */  lui        $v1, %hi(D_801F679C)
    /* 7D64 801DFD64 9C67638C */  lw         $v1, %lo(D_801F679C)($v1)
    /* 7D68 801DFD68 00000000 */  nop
    /* 7D6C 801DFD6C 01006224 */  addiu      $v0, $v1, 0x1
    /* 7D70 801DFD70 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 7D74 801DFD74 9C6722AC */  sw         $v0, %lo(D_801F679C)($at)
    /* 7D78 801DFD78 3C00023C */  lui        $v0, (0x3C0000 >> 16)
    /* 7D7C 801DFD7C 2A104300 */  slt        $v0, $v0, $v1
    /* 7D80 801DFD80 1E004010 */  beqz       $v0, .L801DFDFC
    /* 7D84 801DFD84 00000000 */   nop
  .L801DFD88:
    /* 7D88 801DFD88 1E80043C */  lui        $a0, %hi(D_801D8F7C)
    /* 7D8C 801DFD8C 7C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F7C)
    /* 7D90 801DFD90 C983070C */  jal        puts
    /* 7D94 801DFD94 00000000 */   nop
    /* 7D98 801DFD98 00004492 */  lbu        $a0, 0x0($s2)
    /* 7D9C 801DFD9C 01004292 */  lbu        $v0, 0x1($s2)
    /* 7DA0 801DFDA0 1F80053C */  lui        $a1, %hi(D_801F67A0)
    /* 7DA4 801DFDA4 A067A58C */  lw         $a1, %lo(D_801F67A0)($a1)
    /* 7DA8 801DFDA8 80100200 */  sll        $v0, $v0, 2
    /* 7DAC 801DFDAC 21105300 */  addu       $v0, $v0, $s3
    /* 7DB0 801DFDB0 80200400 */  sll        $a0, $a0, 2
    /* 7DB4 801DFDB4 0000438C */  lw         $v1, 0x0($v0)
    /* 7DB8 801DFDB8 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 7DBC 801DFDBC 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 7DC0 801DFDC0 21209300 */  addu       $a0, $a0, $s3
    /* 7DC4 801DFDC4 80100200 */  sll        $v0, $v0, 2
    /* 7DC8 801DFDC8 1000A3AF */  sw         $v1, 0x10($sp)
    /* 7DCC 801DFDCC 1F80013C */  lui        $at, %hi(D_801F5068)
    /* 7DD0 801DFDD0 21082200 */  addu       $at, $at, $v0
    /* 7DD4 801DFDD4 6850268C */  lw         $a2, %lo(D_801F5068)($at)
    /* 7DD8 801DFDD8 0000878C */  lw         $a3, 0x0($a0)
    /* 7DDC 801DFDDC 1E80043C */  lui        $a0, %hi(D_801D8F8C)
    /* 7DE0 801DFDE0 8C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F8C)
    /* 7DE4 801DFDE4 2568070C */  jal        printf
    /* 7DE8 801DFDE8 00000000 */   nop
    /* 7DEC 801DFDEC B181070C */  jal        CD_flush
    /* 7DF0 801DFDF0 00000000 */   nop
    /* 7DF4 801DFDF4 807F0708 */  j          .L801DFE00
    /* 7DF8 801DFDF8 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L801DFDFC:
    /* 7DFC 801DFDFC 21100000 */  addu       $v0, $zero, $zero
  .L801DFE00:
    /* 7E00 801DFE00 49004014 */  bnez       $v0, .L801DFF28
    /* 7E04 801DFE04 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 7E08 801DFE08 668C070C */  jal        CheckCallback
    /* 7E0C 801DFE0C 00000000 */   nop
    /* 7E10 801DFE10 2B004010 */  beqz       $v0, .L801DFEC0
    /* 7E14 801DFE14 00000000 */   nop
    /* 7E18 801DFE18 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 7E1C 801DFE1C 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 7E20 801DFE20 00000000 */  nop
    /* 7E24 801DFE24 00004290 */  lbu        $v0, 0x0($v0)
    /* 7E28 801DFE28 00000000 */  nop
    /* 7E2C 801DFE2C 03005130 */  andi       $s1, $v0, 0x3
  .L801DFE30:
    /* 7E30 801DFE30 D37D070C */  jal        getintr
    /* 7E34 801DFE34 00000000 */   nop
    /* 7E38 801DFE38 21804000 */  addu       $s0, $v0, $zero
    /* 7E3C 801DFE3C 1C000012 */  beqz       $s0, .L801DFEB0
    /* 7E40 801DFE40 04000232 */   andi      $v0, $s0, 0x4
    /* 7E44 801DFE44 0C004010 */  beqz       $v0, .L801DFE78
    /* 7E48 801DFE48 02000232 */   andi      $v0, $s0, 0x2
    /* 7E4C 801DFE4C 1F80023C */  lui        $v0, %hi(D_801F5044)
    /* 7E50 801DFE50 4450428C */  lw         $v0, %lo(D_801F5044)($v0)
    /* 7E54 801DFE54 00000000 */  nop
    /* 7E58 801DFE58 06004010 */  beqz       $v0, .L801DFE74
    /* 7E5C 801DFE5C 00000000 */   nop
    /* 7E60 801DFE60 00008492 */  lbu        $a0, 0x0($s4)
    /* 7E64 801DFE64 1F80053C */  lui        $a1, %hi(D_801F6788)
    /* 7E68 801DFE68 8867A524 */  addiu      $a1, $a1, %lo(D_801F6788)
    /* 7E6C 801DFE6C 09F84000 */  jalr       $v0
    /* 7E70 801DFE70 00000000 */   nop
  .L801DFE74:
    /* 7E74 801DFE74 02000232 */  andi       $v0, $s0, 0x2
  .L801DFE78:
    /* 7E78 801DFE78 EDFF4010 */  beqz       $v0, .L801DFE30
    /* 7E7C 801DFE7C 00000000 */   nop
    /* 7E80 801DFE80 1F80023C */  lui        $v0, %hi(D_801F5040)
    /* 7E84 801DFE84 4050428C */  lw         $v0, %lo(D_801F5040)($v0)
    /* 7E88 801DFE88 00000000 */  nop
    /* 7E8C 801DFE8C E8FF4010 */  beqz       $v0, .L801DFE30
    /* 7E90 801DFE90 00000000 */   nop
    /* 7E94 801DFE94 00004492 */  lbu        $a0, 0x0($s2)
    /* 7E98 801DFE98 1F80053C */  lui        $a1, %hi(D_801F6780)
    /* 7E9C 801DFE9C 8067A524 */  addiu      $a1, $a1, %lo(D_801F6780)
    /* 7EA0 801DFEA0 09F84000 */  jalr       $v0
    /* 7EA4 801DFEA4 00000000 */   nop
    /* 7EA8 801DFEA8 8C7F0708 */  j          .L801DFE30
    /* 7EAC 801DFEAC 00000000 */   nop
  .L801DFEB0:
    /* 7EB0 801DFEB0 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 7EB4 801DFEB4 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 7EB8 801DFEB8 00000000 */  nop
    /* 7EBC 801DFEBC 000051A0 */  sb         $s1, 0x0($v0)
  .L801DFEC0:
    /* 7EC0 801DFEC0 00004292 */  lbu        $v0, 0x0($s2)
    /* 7EC4 801DFEC4 00000000 */  nop
    /* 7EC8 801DFEC8 FF004630 */  andi       $a2, $v0, 0xFF
    /* 7ECC 801DFECC 02000224 */  addiu      $v0, $zero, 0x2
    /* 7ED0 801DFED0 0300C210 */  beq        $a2, $v0, .L801DFEE0
    /* 7ED4 801DFED4 05000224 */   addiu     $v0, $zero, 0x5
    /* 7ED8 801DFED8 1100C214 */  bne        $a2, $v0, .L801DFF20
    /* 7EDC 801DFEDC 00000000 */   nop
  .L801DFEE0:
    /* 7EE0 801DFEE0 02000224 */  addiu      $v0, $zero, 0x2
    /* 7EE4 801DFEE4 000042A2 */  sb         $v0, 0x0($s2)
    /* 7EE8 801DFEE8 2128C002 */  addu       $a1, $s6, $zero
    /* 7EEC 801DFEEC 1F80043C */  lui        $a0, %hi(D_801F6780)
    /* 7EF0 801DFEF0 80678424 */  addiu      $a0, $a0, %lo(D_801F6780)
    /* 7EF4 801DFEF4 0800A010 */  beqz       $a1, .L801DFF18
    /* 7EF8 801DFEF8 07000324 */   addiu     $v1, $zero, 0x7
    /* 7EFC 801DFEFC FFFF0724 */  addiu      $a3, $zero, -0x1
  .L801DFF00:
    /* 7F00 801DFF00 00008290 */  lbu        $v0, 0x0($a0)
    /* 7F04 801DFF04 01008424 */  addiu      $a0, $a0, 0x1
    /* 7F08 801DFF08 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 7F0C 801DFF0C 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 7F10 801DFF10 FBFF6714 */  bne        $v1, $a3, .L801DFF00
    /* 7F14 801DFF14 0100A524 */   addiu     $a1, $a1, 0x1
  .L801DFF18:
    /* 7F18 801DFF18 CA7F0708 */  j          .L801DFF28
    /* 7F1C 801DFF1C 2110C000 */   addu      $v0, $a2, $zero
  .L801DFF20:
    /* 7F20 801DFF20 87FFA012 */  beqz       $s5, .L801DFD40
    /* 7F24 801DFF24 21100000 */   addu      $v0, $zero, $zero
  .L801DFF28:
    /* 7F28 801DFF28 3400BF8F */  lw         $ra, 0x34($sp)
    /* 7F2C 801DFF2C 3000B68F */  lw         $s6, 0x30($sp)
    /* 7F30 801DFF30 2C00B58F */  lw         $s5, 0x2C($sp)
    /* 7F34 801DFF34 2800B48F */  lw         $s4, 0x28($sp)
    /* 7F38 801DFF38 2400B38F */  lw         $s3, 0x24($sp)
    /* 7F3C 801DFF3C 2000B28F */  lw         $s2, 0x20($sp)
    /* 7F40 801DFF40 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 7F44 801DFF44 1800B08F */  lw         $s0, 0x18($sp)
    /* 7F48 801DFF48 3800BD27 */  addiu      $sp, $sp, 0x38
    /* 7F4C 801DFF4C 0800E003 */  jr         $ra
    /* 7F50 801DFF50 00000000 */   nop
endlabel CD_sync

nonmatching CD_ready, 0x2CC

glabel CD_ready
    /* 7F54 801DFF54 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 7F58 801DFF58 3400B7AF */  sw         $s7, 0x34($sp)
    /* 7F5C 801DFF5C 21B88000 */  addu       $s7, $a0, $zero
    /* 7F60 801DFF60 2800B4AF */  sw         $s4, 0x28($sp)
    /* 7F64 801DFF64 21A0A000 */  addu       $s4, $a1, $zero
    /* 7F68 801DFF68 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 7F6C 801DFF6C 3800BFAF */  sw         $ra, 0x38($sp)
    /* 7F70 801DFF70 3000B6AF */  sw         $s6, 0x30($sp)
    /* 7F74 801DFF74 2C00B5AF */  sw         $s5, 0x2C($sp)
    /* 7F78 801DFF78 2400B3AF */  sw         $s3, 0x24($sp)
    /* 7F7C 801DFF7C 2000B2AF */  sw         $s2, 0x20($sp)
    /* 7F80 801DFF80 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 7F84 801DFF84 948B070C */  jal        VSync
    /* 7F88 801DFF88 1800B0AF */   sw        $s0, 0x18($sp)
    /* 7F8C 801DFF8C 1F80153C */  lui        $s5, %hi(D_801F50E8)
    /* 7F90 801DFF90 E850B526 */  addiu      $s5, $s5, %lo(D_801F50E8)
    /* 7F94 801DFF94 1F80123C */  lui        $s2, %hi(D_801F5320)
    /* 7F98 801DFF98 20535226 */  addiu      $s2, $s2, %lo(D_801F5320)
    /* 7F9C 801DFF9C 01005626 */  addiu      $s6, $s2, 0x1
    /* 7FA0 801DFFA0 02005326 */  addiu      $s3, $s2, 0x2
    /* 7FA4 801DFFA4 C0034224 */  addiu      $v0, $v0, 0x3C0
    /* 7FA8 801DFFA8 1F80013C */  lui        $at, %hi(D_801F6798)
    /* 7FAC 801DFFAC 986722AC */  sw         $v0, %lo(D_801F6798)($at)
    /* 7FB0 801DFFB0 1E80023C */  lui        $v0, %hi(D_801D900C)
    /* 7FB4 801DFFB4 0C904224 */  addiu      $v0, $v0, %lo(D_801D900C)
    /* 7FB8 801DFFB8 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 7FBC 801DFFBC 9C6720AC */  sw         $zero, %lo(D_801F679C)($at)
    /* 7FC0 801DFFC0 1F80013C */  lui        $at, %hi(D_801F67A0)
    /* 7FC4 801DFFC4 A06722AC */  sw         $v0, %lo(D_801F67A0)($at)
  .L801DFFC8:
    /* 7FC8 801DFFC8 948B070C */  jal        VSync
    /* 7FCC 801DFFCC FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 7FD0 801DFFD0 1F80033C */  lui        $v1, %hi(D_801F6798)
    /* 7FD4 801DFFD4 9867638C */  lw         $v1, %lo(D_801F6798)($v1)
    /* 7FD8 801DFFD8 00000000 */  nop
    /* 7FDC 801DFFDC 2A186200 */  slt        $v1, $v1, $v0
    /* 7FE0 801DFFE0 0B006014 */  bnez       $v1, .L801E0010
    /* 7FE4 801DFFE4 00000000 */   nop
    /* 7FE8 801DFFE8 1F80033C */  lui        $v1, %hi(D_801F679C)
    /* 7FEC 801DFFEC 9C67638C */  lw         $v1, %lo(D_801F679C)($v1)
    /* 7FF0 801DFFF0 00000000 */  nop
    /* 7FF4 801DFFF4 01006224 */  addiu      $v0, $v1, 0x1
    /* 7FF8 801DFFF8 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 7FFC 801DFFFC 9C6722AC */  sw         $v0, %lo(D_801F679C)($at)
    /* 8000 801E0000 3C00023C */  lui        $v0, (0x3C0000 >> 16)
    /* 8004 801E0004 2A104300 */  slt        $v0, $v0, $v1
    /* 8008 801E0008 1E004010 */  beqz       $v0, .L801E0084
    /* 800C 801E000C 00000000 */   nop
  .L801E0010:
    /* 8010 801E0010 1E80043C */  lui        $a0, %hi(D_801D8F7C)
    /* 8014 801E0014 7C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F7C)
    /* 8018 801E0018 C983070C */  jal        puts
    /* 801C 801E001C 00000000 */   nop
    /* 8020 801E0020 00004492 */  lbu        $a0, 0x0($s2)
    /* 8024 801E0024 01004292 */  lbu        $v0, 0x1($s2)
    /* 8028 801E0028 1F80053C */  lui        $a1, %hi(D_801F67A0)
    /* 802C 801E002C A067A58C */  lw         $a1, %lo(D_801F67A0)($a1)
    /* 8030 801E0030 80100200 */  sll        $v0, $v0, 2
    /* 8034 801E0034 21105500 */  addu       $v0, $v0, $s5
    /* 8038 801E0038 80200400 */  sll        $a0, $a0, 2
    /* 803C 801E003C 0000438C */  lw         $v1, 0x0($v0)
    /* 8040 801E0040 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 8044 801E0044 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 8048 801E0048 21209500 */  addu       $a0, $a0, $s5
    /* 804C 801E004C 80100200 */  sll        $v0, $v0, 2
    /* 8050 801E0050 1000A3AF */  sw         $v1, 0x10($sp)
    /* 8054 801E0054 1F80013C */  lui        $at, %hi(D_801F5068)
    /* 8058 801E0058 21082200 */  addu       $at, $at, $v0
    /* 805C 801E005C 6850268C */  lw         $a2, %lo(D_801F5068)($at)
    /* 8060 801E0060 0000878C */  lw         $a3, 0x0($a0)
    /* 8064 801E0064 1E80043C */  lui        $a0, %hi(D_801D8F8C)
    /* 8068 801E0068 8C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F8C)
    /* 806C 801E006C 2568070C */  jal        printf
    /* 8070 801E0070 00000000 */   nop
    /* 8074 801E0074 B181070C */  jal        CD_flush
    /* 8078 801E0078 00000000 */   nop
    /* 807C 801E007C 22800708 */  j          .L801E0088
    /* 8080 801E0080 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L801E0084:
    /* 8084 801E0084 21100000 */  addu       $v0, $zero, $zero
  .L801E0088:
    /* 8088 801E0088 59004014 */  bnez       $v0, .L801E01F0
    /* 808C 801E008C FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8090 801E0090 668C070C */  jal        CheckCallback
    /* 8094 801E0094 00000000 */   nop
    /* 8098 801E0098 2B004010 */  beqz       $v0, .L801E0148
    /* 809C 801E009C 00000000 */   nop
    /* 80A0 801E00A0 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 80A4 801E00A4 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 80A8 801E00A8 00000000 */  nop
    /* 80AC 801E00AC 00004290 */  lbu        $v0, 0x0($v0)
    /* 80B0 801E00B0 00000000 */  nop
    /* 80B4 801E00B4 03005130 */  andi       $s1, $v0, 0x3
  .L801E00B8:
    /* 80B8 801E00B8 D37D070C */  jal        getintr
    /* 80BC 801E00BC 00000000 */   nop
    /* 80C0 801E00C0 21804000 */  addu       $s0, $v0, $zero
    /* 80C4 801E00C4 1C000012 */  beqz       $s0, .L801E0138
    /* 80C8 801E00C8 04000232 */   andi      $v0, $s0, 0x4
    /* 80CC 801E00CC 0C004010 */  beqz       $v0, .L801E0100
    /* 80D0 801E00D0 02000232 */   andi      $v0, $s0, 0x2
    /* 80D4 801E00D4 1F80023C */  lui        $v0, %hi(D_801F5044)
    /* 80D8 801E00D8 4450428C */  lw         $v0, %lo(D_801F5044)($v0)
    /* 80DC 801E00DC 00000000 */  nop
    /* 80E0 801E00E0 06004010 */  beqz       $v0, .L801E00FC
    /* 80E4 801E00E4 00000000 */   nop
    /* 80E8 801E00E8 0000C492 */  lbu        $a0, 0x0($s6)
    /* 80EC 801E00EC 1F80053C */  lui        $a1, %hi(D_801F6788)
    /* 80F0 801E00F0 8867A524 */  addiu      $a1, $a1, %lo(D_801F6788)
    /* 80F4 801E00F4 09F84000 */  jalr       $v0
    /* 80F8 801E00F8 00000000 */   nop
  .L801E00FC:
    /* 80FC 801E00FC 02000232 */  andi       $v0, $s0, 0x2
  .L801E0100:
    /* 8100 801E0100 EDFF4010 */  beqz       $v0, .L801E00B8
    /* 8104 801E0104 00000000 */   nop
    /* 8108 801E0108 1F80023C */  lui        $v0, %hi(D_801F5040)
    /* 810C 801E010C 4050428C */  lw         $v0, %lo(D_801F5040)($v0)
    /* 8110 801E0110 00000000 */  nop
    /* 8114 801E0114 E8FF4010 */  beqz       $v0, .L801E00B8
    /* 8118 801E0118 00000000 */   nop
    /* 811C 801E011C 00004492 */  lbu        $a0, 0x0($s2)
    /* 8120 801E0120 1F80053C */  lui        $a1, %hi(D_801F6780)
    /* 8124 801E0124 8067A524 */  addiu      $a1, $a1, %lo(D_801F6780)
    /* 8128 801E0128 09F84000 */  jalr       $v0
    /* 812C 801E012C 00000000 */   nop
    /* 8130 801E0130 2E800708 */  j          .L801E00B8
    /* 8134 801E0134 00000000 */   nop
  .L801E0138:
    /* 8138 801E0138 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 813C 801E013C 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8140 801E0140 00000000 */  nop
    /* 8144 801E0144 000051A0 */  sb         $s1, 0x0($v0)
  .L801E0148:
    /* 8148 801E0148 00006292 */  lbu        $v0, 0x0($s3)
    /* 814C 801E014C 00000000 */  nop
    /* 8150 801E0150 FF004630 */  andi       $a2, $v0, 0xFF
    /* 8154 801E0154 1000C010 */  beqz       $a2, .L801E0198
    /* 8158 801E0158 00000000 */   nop
    /* 815C 801E015C 000060A2 */  sb         $zero, 0x0($s3)
    /* 8160 801E0160 1F80043C */  lui        $a0, %hi(D_801F6790)
    /* 8164 801E0164 90678424 */  addiu      $a0, $a0, %lo(D_801F6790)
    /* 8168 801E0168 1D008012 */  beqz       $s4, .L801E01E0
    /* 816C 801E016C 21288002 */   addu      $a1, $s4, $zero
    /* 8170 801E0170 07000324 */  addiu      $v1, $zero, 0x7
    /* 8174 801E0174 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L801E0178:
    /* 8178 801E0178 00008290 */  lbu        $v0, 0x0($a0)
    /* 817C 801E017C 01008424 */  addiu      $a0, $a0, 0x1
    /* 8180 801E0180 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 8184 801E0184 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 8188 801E0188 FBFF6714 */  bne        $v1, $a3, .L801E0178
    /* 818C 801E018C 0100A524 */   addiu     $a1, $a1, 0x1
    /* 8190 801E0190 7C800708 */  j          .L801E01F0
    /* 8194 801E0194 2110C000 */   addu      $v0, $a2, $zero
  .L801E0198:
    /* 8198 801E0198 FFFF6292 */  lbu        $v0, -0x1($s3)
    /* 819C 801E019C 00000000 */  nop
    /* 81A0 801E01A0 FF004630 */  andi       $a2, $v0, 0xFF
    /* 81A4 801E01A4 1000C010 */  beqz       $a2, .L801E01E8
    /* 81A8 801E01A8 00000000 */   nop
    /* 81AC 801E01AC FFFF60A2 */  sb         $zero, -0x1($s3)
    /* 81B0 801E01B0 21288002 */  addu       $a1, $s4, $zero
    /* 81B4 801E01B4 1F80043C */  lui        $a0, %hi(D_801F6788)
    /* 81B8 801E01B8 88678424 */  addiu      $a0, $a0, %lo(D_801F6788)
    /* 81BC 801E01BC 0800A010 */  beqz       $a1, .L801E01E0
    /* 81C0 801E01C0 07000324 */   addiu     $v1, $zero, 0x7
    /* 81C4 801E01C4 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L801E01C8:
    /* 81C8 801E01C8 00008290 */  lbu        $v0, 0x0($a0)
    /* 81CC 801E01CC 01008424 */  addiu      $a0, $a0, 0x1
    /* 81D0 801E01D0 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 81D4 801E01D4 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 81D8 801E01D8 FBFF6714 */  bne        $v1, $a3, .L801E01C8
    /* 81DC 801E01DC 0100A524 */   addiu     $a1, $a1, 0x1
  .L801E01E0:
    /* 81E0 801E01E0 7C800708 */  j          .L801E01F0
    /* 81E4 801E01E4 2110C000 */   addu      $v0, $a2, $zero
  .L801E01E8:
    /* 81E8 801E01E8 77FFE012 */  beqz       $s7, .L801DFFC8
    /* 81EC 801E01EC 21100000 */   addu      $v0, $zero, $zero
  .L801E01F0:
    /* 81F0 801E01F0 3800BF8F */  lw         $ra, 0x38($sp)
    /* 81F4 801E01F4 3400B78F */  lw         $s7, 0x34($sp)
    /* 81F8 801E01F8 3000B68F */  lw         $s6, 0x30($sp)
    /* 81FC 801E01FC 2C00B58F */  lw         $s5, 0x2C($sp)
    /* 8200 801E0200 2800B48F */  lw         $s4, 0x28($sp)
    /* 8204 801E0204 2400B38F */  lw         $s3, 0x24($sp)
    /* 8208 801E0208 2000B28F */  lw         $s2, 0x20($sp)
    /* 820C 801E020C 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 8210 801E0210 1800B08F */  lw         $s0, 0x18($sp)
    /* 8214 801E0214 4000BD27 */  addiu      $sp, $sp, 0x40
    /* 8218 801E0218 0800E003 */  jr         $ra
    /* 821C 801E021C 00000000 */   nop
endlabel CD_ready

nonmatching CD_cw, 0x41C

glabel CD_cw
    /* 8220 801E0220 1F80023C */  lui        $v0, %hi(D_801F504C)
    /* 8224 801E0224 4C50428C */  lw         $v0, %lo(D_801F504C)($v0)
    /* 8228 801E0228 B8FFBD27 */  addiu      $sp, $sp, -0x48
    /* 822C 801E022C 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* 8230 801E0230 2188A000 */  addu       $s1, $a1, $zero
    /* 8234 801E0234 3C00B5AF */  sw         $s5, 0x3C($sp)
    /* 8238 801E0238 21A8C000 */  addu       $s5, $a2, $zero
    /* 823C 801E023C 3000B2AF */  sw         $s2, 0x30($sp)
    /* 8240 801E0240 2190E000 */  addu       $s2, $a3, $zero
    /* 8244 801E0244 2800B0AF */  sw         $s0, 0x28($sp)
    /* 8248 801E0248 21808000 */  addu       $s0, $a0, $zero
    /* 824C 801E024C 4000BFAF */  sw         $ra, 0x40($sp)
    /* 8250 801E0250 3800B4AF */  sw         $s4, 0x38($sp)
    /* 8254 801E0254 02004228 */  slti       $v0, $v0, 0x2
    /* 8258 801E0258 0A004014 */  bnez       $v0, .L801E0284
    /* 825C 801E025C 3400B3AF */   sw        $s3, 0x34($sp)
    /* 8260 801E0260 FF000232 */  andi       $v0, $s0, 0xFF
    /* 8264 801E0264 80100200 */  sll        $v0, $v0, 2
    /* 8268 801E0268 1F80013C */  lui        $at, %hi(D_801F5068)
    /* 826C 801E026C 21082200 */  addu       $at, $at, $v0
    /* 8270 801E0270 6850258C */  lw         $a1, %lo(D_801F5068)($at)
    /* 8274 801E0274 1E80043C */  lui        $a0, %hi(D_801D9018)
    /* 8278 801E0278 18908424 */  addiu      $a0, $a0, %lo(D_801D9018)
    /* 827C 801E027C 2568070C */  jal        printf
    /* 8280 801E0280 00000000 */   nop
  .L801E0284:
    /* 8284 801E0284 FF000232 */  andi       $v0, $s0, 0xFF
    /* 8288 801E0288 80180200 */  sll        $v1, $v0, 2
    /* 828C 801E028C 1F80013C */  lui        $at, %hi(D_801F5288)
    /* 8290 801E0290 21082300 */  addu       $at, $at, $v1
    /* 8294 801E0294 8852228C */  lw         $v0, %lo(D_801F5288)($at)
    /* 8298 801E0298 00000000 */  nop
    /* 829C 801E029C 11004010 */  beqz       $v0, .L801E02E4
    /* 82A0 801E02A0 21200000 */   addu      $a0, $zero, $zero
    /* 82A4 801E02A4 0F002016 */  bnez       $s1, .L801E02E4
    /* 82A8 801E02A8 00000000 */   nop
    /* 82AC 801E02AC 1F80023C */  lui        $v0, %hi(D_801F504C)
    /* 82B0 801E02B0 4C50428C */  lw         $v0, %lo(D_801F504C)($v0)
    /* 82B4 801E02B4 00000000 */  nop
    /* 82B8 801E02B8 D6004018 */  blez       $v0, .L801E0614
    /* 82BC 801E02BC FEFF0224 */   addiu     $v0, $zero, -0x2
    /* 82C0 801E02C0 1F80013C */  lui        $at, %hi(D_801F5068)
    /* 82C4 801E02C4 21082300 */  addu       $at, $at, $v1
    /* 82C8 801E02C8 6850258C */  lw         $a1, %lo(D_801F5068)($at)
    /* 82CC 801E02CC 1E80043C */  lui        $a0, %hi(D_801D9020)
    /* 82D0 801E02D0 20908424 */  addiu      $a0, $a0, %lo(D_801D9020)
    /* 82D4 801E02D4 2568070C */  jal        printf
    /* 82D8 801E02D8 00000000 */   nop
    /* 82DC 801E02DC 85810708 */  j          .L801E0614
    /* 82E0 801E02E0 FEFF0224 */   addiu     $v0, $zero, -0x2
  .L801E02E4:
    /* 82E4 801E02E4 357F070C */  jal        CD_sync
    /* 82E8 801E02E8 21280000 */   addu      $a1, $zero, $zero
    /* 82EC 801E02EC FF000332 */  andi       $v1, $s0, 0xFF
    /* 82F0 801E02F0 02000224 */  addiu      $v0, $zero, 0x2
    /* 82F4 801E02F4 0D006214 */  bne        $v1, $v0, .L801E032C
    /* 82F8 801E02F8 0E000224 */   addiu     $v0, $zero, 0xE
    /* 82FC 801E02FC 21200000 */  addu       $a0, $zero, $zero
    /* 8300 801E0300 21182002 */  addu       $v1, $s1, $zero
  .L801E0304:
    /* 8304 801E0304 00006290 */  lbu        $v0, 0x0($v1)
    /* 8308 801E0308 1F80013C */  lui        $at, %hi(D_801F505C)
    /* 830C 801E030C 21082400 */  addu       $at, $at, $a0
    /* 8310 801E0310 5C5022A0 */  sb         $v0, %lo(D_801F505C)($at)
    /* 8314 801E0314 01008424 */  addiu      $a0, $a0, 0x1
    /* 8318 801E0318 04008228 */  slti       $v0, $a0, 0x4
    /* 831C 801E031C F9FF4014 */  bnez       $v0, .L801E0304
    /* 8320 801E0320 01006324 */   addiu     $v1, $v1, 0x1
    /* 8324 801E0324 FF000332 */  andi       $v1, $s0, 0xFF
    /* 8328 801E0328 0E000224 */  addiu      $v0, $zero, 0xE
  .L801E032C:
    /* 832C 801E032C 04006214 */  bne        $v1, $v0, .L801E0340
    /* 8330 801E0330 00000000 */   nop
    /* 8334 801E0334 00002292 */  lbu        $v0, 0x0($s1)
    /* 8338 801E0338 1F80013C */  lui        $at, %hi(D_801F5060)
    /* 833C 801E033C 605022A0 */  sb         $v0, %lo(D_801F5060)($at)
  .L801E0340:
    /* 8340 801E0340 1F80023C */  lui        $v0, %hi(D_801F5320)
    /* 8344 801E0344 20534224 */  addiu      $v0, $v0, %lo(D_801F5320)
    /* 8348 801E0348 80200300 */  sll        $a0, $v1, 2
    /* 834C 801E034C 000040A0 */  sb         $zero, 0x0($v0)
    /* 8350 801E0350 1F80013C */  lui        $at, %hi(D_801F5188)
    /* 8354 801E0354 21082400 */  addu       $at, $at, $a0
    /* 8358 801E0358 8851228C */  lw         $v0, %lo(D_801F5188)($at)
    /* 835C 801E035C 1F80033C */  lui        $v1, %hi(D_801F5188)
    /* 8360 801E0360 88516324 */  addiu      $v1, $v1, %lo(D_801F5188)
    /* 8364 801E0364 03004010 */  beqz       $v0, .L801E0374
    /* 8368 801E0368 00000000 */   nop
    /* 836C 801E036C 1F80013C */  lui        $at, %hi(D_801F5321)
    /* 8370 801E0370 215320A0 */  sb         $zero, %lo(D_801F5321)($at)
  .L801E0374:
    /* 8374 801E0374 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8378 801E0378 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 837C 801E037C 00000000 */  nop
    /* 8380 801E0380 000040A0 */  sb         $zero, 0x0($v0)
    /* 8384 801E0384 00016224 */  addiu      $v0, $v1, 0x100
    /* 8388 801E0388 21188200 */  addu       $v1, $a0, $v0
    /* 838C 801E038C 0000628C */  lw         $v0, 0x0($v1)
    /* 8390 801E0390 00000000 */  nop
    /* 8394 801E0394 0D004018 */  blez       $v0, .L801E03CC
    /* 8398 801E0398 21200000 */   addu      $a0, $zero, $zero
    /* 839C 801E039C 21306000 */  addu       $a2, $v1, $zero
    /* 83A0 801E03A0 21282002 */  addu       $a1, $s1, $zero
  .L801E03A4:
    /* 83A4 801E03A4 1F80033C */  lui        $v1, %hi(D_801F5310)
    /* 83A8 801E03A8 1053638C */  lw         $v1, %lo(D_801F5310)($v1)
    /* 83AC 801E03AC 0000A290 */  lbu        $v0, 0x0($a1)
    /* 83B0 801E03B0 0100A524 */  addiu      $a1, $a1, 0x1
    /* 83B4 801E03B4 000062A0 */  sb         $v0, 0x0($v1)
    /* 83B8 801E03B8 0000C28C */  lw         $v0, 0x0($a2)
    /* 83BC 801E03BC 01008424 */  addiu      $a0, $a0, 0x1
    /* 83C0 801E03C0 2A108200 */  slt        $v0, $a0, $v0
    /* 83C4 801E03C4 F7FF4014 */  bnez       $v0, .L801E03A4
    /* 83C8 801E03C8 00000000 */   nop
  .L801E03CC:
    /* 83CC 801E03CC 1F80023C */  lui        $v0, %hi(D_801F530C)
    /* 83D0 801E03D0 0C53428C */  lw         $v0, %lo(D_801F530C)($v0)
    /* 83D4 801E03D4 1F80013C */  lui        $at, %hi(D_801F5061)
    /* 83D8 801E03D8 615030A0 */  sb         $s0, %lo(D_801F5061)($at)
    /* 83DC 801E03DC 000050A0 */  sb         $s0, 0x0($v0)
    /* 83E0 801E03E0 8C004016 */  bnez       $s2, .L801E0614
    /* 83E4 801E03E4 21100000 */   addu      $v0, $zero, $zero
    /* 83E8 801E03E8 948B070C */  jal        VSync
    /* 83EC 801E03EC FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 83F0 801E03F0 C0034224 */  addiu      $v0, $v0, 0x3C0
    /* 83F4 801E03F4 1F80043C */  lui        $a0, %hi(D_801F5320)
    /* 83F8 801E03F8 20538424 */  addiu      $a0, $a0, %lo(D_801F5320)
    /* 83FC 801E03FC 1F80013C */  lui        $at, %hi(D_801F6798)
    /* 8400 801E0400 986722AC */  sw         $v0, %lo(D_801F6798)($at)
    /* 8404 801E0404 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 8408 801E0408 9C6720AC */  sw         $zero, %lo(D_801F679C)($at)
    /* 840C 801E040C 00008390 */  lbu        $v1, 0x0($a0)
    /* 8410 801E0410 1E80023C */  lui        $v0, %hi(D_801D9030)
    /* 8414 801E0414 30904224 */  addiu      $v0, $v0, %lo(D_801D9030)
    /* 8418 801E0418 1F80013C */  lui        $at, %hi(D_801F67A0)
    /* 841C 801E041C A06722AC */  sw         $v0, %lo(D_801F67A0)($at)
    /* 8420 801E0420 69006014 */  bnez       $v1, .L801E05C8
    /* 8424 801E0424 2130A002 */   addu      $a2, $s5, $zero
    /* 8428 801E0428 1F80133C */  lui        $s3, %hi(D_801F50E8)
    /* 842C 801E042C E8507326 */  addiu      $s3, $s3, %lo(D_801F50E8)
    /* 8430 801E0430 21908000 */  addu       $s2, $a0, $zero
    /* 8434 801E0434 01005426 */  addiu      $s4, $s2, 0x1
  .L801E0438:
    /* 8438 801E0438 948B070C */  jal        VSync
    /* 843C 801E043C FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 8440 801E0440 1F80033C */  lui        $v1, %hi(D_801F6798)
    /* 8444 801E0444 9867638C */  lw         $v1, %lo(D_801F6798)($v1)
    /* 8448 801E0448 00000000 */  nop
    /* 844C 801E044C 2A186200 */  slt        $v1, $v1, $v0
    /* 8450 801E0450 0B006014 */  bnez       $v1, .L801E0480
    /* 8454 801E0454 00000000 */   nop
    /* 8458 801E0458 1F80033C */  lui        $v1, %hi(D_801F679C)
    /* 845C 801E045C 9C67638C */  lw         $v1, %lo(D_801F679C)($v1)
    /* 8460 801E0460 00000000 */  nop
    /* 8464 801E0464 01006224 */  addiu      $v0, $v1, 0x1
    /* 8468 801E0468 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 846C 801E046C 9C6722AC */  sw         $v0, %lo(D_801F679C)($at)
    /* 8470 801E0470 3C00023C */  lui        $v0, (0x3C0000 >> 16)
    /* 8474 801E0474 2A104300 */  slt        $v0, $v0, $v1
    /* 8478 801E0478 1E004010 */  beqz       $v0, .L801E04F4
    /* 847C 801E047C 00000000 */   nop
  .L801E0480:
    /* 8480 801E0480 1E80043C */  lui        $a0, %hi(D_801D8F7C)
    /* 8484 801E0484 7C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F7C)
    /* 8488 801E0488 C983070C */  jal        puts
    /* 848C 801E048C 00000000 */   nop
    /* 8490 801E0490 00004492 */  lbu        $a0, 0x0($s2)
    /* 8494 801E0494 01004292 */  lbu        $v0, 0x1($s2)
    /* 8498 801E0498 1F80053C */  lui        $a1, %hi(D_801F67A0)
    /* 849C 801E049C A067A58C */  lw         $a1, %lo(D_801F67A0)($a1)
    /* 84A0 801E04A0 80100200 */  sll        $v0, $v0, 2
    /* 84A4 801E04A4 21105300 */  addu       $v0, $v0, $s3
    /* 84A8 801E04A8 80200400 */  sll        $a0, $a0, 2
    /* 84AC 801E04AC 0000438C */  lw         $v1, 0x0($v0)
    /* 84B0 801E04B0 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 84B4 801E04B4 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 84B8 801E04B8 21209300 */  addu       $a0, $a0, $s3
    /* 84BC 801E04BC 80100200 */  sll        $v0, $v0, 2
    /* 84C0 801E04C0 1000A3AF */  sw         $v1, 0x10($sp)
    /* 84C4 801E04C4 1F80013C */  lui        $at, %hi(D_801F5068)
    /* 84C8 801E04C8 21082200 */  addu       $at, $at, $v0
    /* 84CC 801E04CC 6850268C */  lw         $a2, %lo(D_801F5068)($at)
    /* 84D0 801E04D0 0000878C */  lw         $a3, 0x0($a0)
    /* 84D4 801E04D4 1E80043C */  lui        $a0, %hi(D_801D8F8C)
    /* 84D8 801E04D8 8C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F8C)
    /* 84DC 801E04DC 2568070C */  jal        printf
    /* 84E0 801E04E0 00000000 */   nop
    /* 84E4 801E04E4 B181070C */  jal        CD_flush
    /* 84E8 801E04E8 00000000 */   nop
    /* 84EC 801E04EC 3E810708 */  j          .L801E04F8
    /* 84F0 801E04F0 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L801E04F4:
    /* 84F4 801E04F4 21100000 */  addu       $v0, $zero, $zero
  .L801E04F8:
    /* 84F8 801E04F8 46004014 */  bnez       $v0, .L801E0614
    /* 84FC 801E04FC FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8500 801E0500 668C070C */  jal        CheckCallback
    /* 8504 801E0504 00000000 */   nop
    /* 8508 801E0508 2B004010 */  beqz       $v0, .L801E05B8
    /* 850C 801E050C 00000000 */   nop
    /* 8510 801E0510 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8514 801E0514 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8518 801E0518 00000000 */  nop
    /* 851C 801E051C 00004290 */  lbu        $v0, 0x0($v0)
    /* 8520 801E0520 00000000 */  nop
    /* 8524 801E0524 03005130 */  andi       $s1, $v0, 0x3
  .L801E0528:
    /* 8528 801E0528 D37D070C */  jal        getintr
    /* 852C 801E052C 00000000 */   nop
    /* 8530 801E0530 21804000 */  addu       $s0, $v0, $zero
    /* 8534 801E0534 1C000012 */  beqz       $s0, .L801E05A8
    /* 8538 801E0538 04000232 */   andi      $v0, $s0, 0x4
    /* 853C 801E053C 0C004010 */  beqz       $v0, .L801E0570
    /* 8540 801E0540 02000232 */   andi      $v0, $s0, 0x2
    /* 8544 801E0544 1F80023C */  lui        $v0, %hi(D_801F5044)
    /* 8548 801E0548 4450428C */  lw         $v0, %lo(D_801F5044)($v0)
    /* 854C 801E054C 00000000 */  nop
    /* 8550 801E0550 06004010 */  beqz       $v0, .L801E056C
    /* 8554 801E0554 00000000 */   nop
    /* 8558 801E0558 00008492 */  lbu        $a0, 0x0($s4)
    /* 855C 801E055C 1F80053C */  lui        $a1, %hi(D_801F6788)
    /* 8560 801E0560 8867A524 */  addiu      $a1, $a1, %lo(D_801F6788)
    /* 8564 801E0564 09F84000 */  jalr       $v0
    /* 8568 801E0568 00000000 */   nop
  .L801E056C:
    /* 856C 801E056C 02000232 */  andi       $v0, $s0, 0x2
  .L801E0570:
    /* 8570 801E0570 EDFF4010 */  beqz       $v0, .L801E0528
    /* 8574 801E0574 00000000 */   nop
    /* 8578 801E0578 1F80023C */  lui        $v0, %hi(D_801F5040)
    /* 857C 801E057C 4050428C */  lw         $v0, %lo(D_801F5040)($v0)
    /* 8580 801E0580 00000000 */  nop
    /* 8584 801E0584 E8FF4010 */  beqz       $v0, .L801E0528
    /* 8588 801E0588 00000000 */   nop
    /* 858C 801E058C 00004492 */  lbu        $a0, 0x0($s2)
    /* 8590 801E0590 1F80053C */  lui        $a1, %hi(D_801F6780)
    /* 8594 801E0594 8067A524 */  addiu      $a1, $a1, %lo(D_801F6780)
    /* 8598 801E0598 09F84000 */  jalr       $v0
    /* 859C 801E059C 00000000 */   nop
    /* 85A0 801E05A0 4A810708 */  j          .L801E0528
    /* 85A4 801E05A4 00000000 */   nop
  .L801E05A8:
    /* 85A8 801E05A8 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 85AC 801E05AC 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 85B0 801E05B0 00000000 */  nop
    /* 85B4 801E05B4 000051A0 */  sb         $s1, 0x0($v0)
  .L801E05B8:
    /* 85B8 801E05B8 00004292 */  lbu        $v0, 0x0($s2)
    /* 85BC 801E05BC 00000000 */  nop
    /* 85C0 801E05C0 9DFF4010 */  beqz       $v0, .L801E0438
    /* 85C4 801E05C4 2130A002 */   addu      $a2, $s5, $zero
  .L801E05C8:
    /* 85C8 801E05C8 1F80043C */  lui        $a0, %hi(D_801F6780)
    /* 85CC 801E05CC 80678424 */  addiu      $a0, $a0, %lo(D_801F6780)
    /* 85D0 801E05D0 0900C010 */  beqz       $a2, .L801E05F8
    /* 85D4 801E05D4 00000000 */   nop
    /* 85D8 801E05D8 07000324 */  addiu      $v1, $zero, 0x7
    /* 85DC 801E05DC FFFF0524 */  addiu      $a1, $zero, -0x1
  .L801E05E0:
    /* 85E0 801E05E0 00008290 */  lbu        $v0, 0x0($a0)
    /* 85E4 801E05E4 01008424 */  addiu      $a0, $a0, 0x1
    /* 85E8 801E05E8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 85EC 801E05EC 0000C2A0 */  sb         $v0, 0x0($a2)
    /* 85F0 801E05F0 FBFF6514 */  bne        $v1, $a1, .L801E05E0
    /* 85F4 801E05F4 0100C624 */   addiu     $a2, $a2, 0x1
  .L801E05F8:
    /* 85F8 801E05F8 1F80023C */  lui        $v0, %hi(D_801F5320)
    /* 85FC 801E05FC 20534224 */  addiu      $v0, $v0, %lo(D_801F5320)
    /* 8600 801E0600 00004290 */  lbu        $v0, 0x0($v0)
    /* 8604 801E0604 00000000 */  nop
    /* 8608 801E0608 05004238 */  xori       $v0, $v0, 0x5
    /* 860C 801E060C 0100422C */  sltiu      $v0, $v0, 0x1
    /* 8610 801E0610 23100200 */  negu       $v0, $v0
  .L801E0614:
    /* 8614 801E0614 4000BF8F */  lw         $ra, 0x40($sp)
    /* 8618 801E0618 3C00B58F */  lw         $s5, 0x3C($sp)
    /* 861C 801E061C 3800B48F */  lw         $s4, 0x38($sp)
    /* 8620 801E0620 3400B38F */  lw         $s3, 0x34($sp)
    /* 8624 801E0624 3000B28F */  lw         $s2, 0x30($sp)
    /* 8628 801E0628 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 862C 801E062C 2800B08F */  lw         $s0, 0x28($sp)
    /* 8630 801E0630 4800BD27 */  addiu      $sp, $sp, 0x48
    /* 8634 801E0634 0800E003 */  jr         $ra
    /* 8638 801E0638 00000000 */   nop
endlabel CD_cw

nonmatching CD_vol, 0x88

glabel CD_vol
    /* 863C 801E063C 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 8640 801E0640 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 8644 801E0644 02000224 */  addiu      $v0, $zero, 0x2
    /* 8648 801E0648 000062A0 */  sb         $v0, 0x0($v1)
    /* 864C 801E064C 1F80033C */  lui        $v1, %hi(D_801F5310)
    /* 8650 801E0650 1053638C */  lw         $v1, %lo(D_801F5310)($v1)
    /* 8654 801E0654 00008290 */  lbu        $v0, 0x0($a0)
    /* 8658 801E0658 00000000 */  nop
    /* 865C 801E065C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8660 801E0660 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 8664 801E0664 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 8668 801E0668 01008290 */  lbu        $v0, 0x1($a0)
    /* 866C 801E066C 00000000 */  nop
    /* 8670 801E0670 000062A0 */  sb         $v0, 0x0($v1)
    /* 8674 801E0674 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 8678 801E0678 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 867C 801E067C 03000224 */  addiu      $v0, $zero, 0x3
    /* 8680 801E0680 000062A0 */  sb         $v0, 0x0($v1)
    /* 8684 801E0684 1F80033C */  lui        $v1, %hi(D_801F530C)
    /* 8688 801E0688 0C53638C */  lw         $v1, %lo(D_801F530C)($v1)
    /* 868C 801E068C 02008290 */  lbu        $v0, 0x2($a0)
    /* 8690 801E0690 00000000 */  nop
    /* 8694 801E0694 000062A0 */  sb         $v0, 0x0($v1)
    /* 8698 801E0698 1F80033C */  lui        $v1, %hi(D_801F5310)
    /* 869C 801E069C 1053638C */  lw         $v1, %lo(D_801F5310)($v1)
    /* 86A0 801E06A0 03008290 */  lbu        $v0, 0x3($a0)
    /* 86A4 801E06A4 00000000 */  nop
    /* 86A8 801E06A8 000062A0 */  sb         $v0, 0x0($v1)
    /* 86AC 801E06AC 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 86B0 801E06B0 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 86B4 801E06B4 20000224 */  addiu      $v0, $zero, 0x20
    /* 86B8 801E06B8 000062A0 */  sb         $v0, 0x0($v1)
    /* 86BC 801E06BC 0800E003 */  jr         $ra
    /* 86C0 801E06C0 21100000 */   addu      $v0, $zero, $zero
endlabel CD_vol

nonmatching CD_flush, 0xE0

glabel CD_flush
    /* 86C4 801E06C4 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 86C8 801E06C8 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 86CC 801E06CC 01000224 */  addiu      $v0, $zero, 0x1
    /* 86D0 801E06D0 000062A0 */  sb         $v0, 0x0($v1)
    /* 86D4 801E06D4 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 86D8 801E06D8 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 86DC 801E06DC 00000000 */  nop
    /* 86E0 801E06E0 00004290 */  lbu        $v0, 0x0($v0)
    /* 86E4 801E06E4 00000000 */  nop
    /* 86E8 801E06E8 07004230 */  andi       $v0, $v0, 0x7
    /* 86EC 801E06EC 16004010 */  beqz       $v0, .L801E0748
    /* 86F0 801E06F0 01000424 */   addiu     $a0, $zero, 0x1
    /* 86F4 801E06F4 07000324 */  addiu      $v1, $zero, 0x7
  .L801E06F8:
    /* 86F8 801E06F8 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 86FC 801E06FC 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8700 801E0700 00000000 */  nop
    /* 8704 801E0704 000044A0 */  sb         $a0, 0x0($v0)
    /* 8708 801E0708 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 870C 801E070C 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 8710 801E0710 00000000 */  nop
    /* 8714 801E0714 000043A0 */  sb         $v1, 0x0($v0)
    /* 8718 801E0718 1F80023C */  lui        $v0, %hi(D_801F5310)
    /* 871C 801E071C 1053428C */  lw         $v0, %lo(D_801F5310)($v0)
    /* 8720 801E0720 00000000 */  nop
    /* 8724 801E0724 000043A0 */  sb         $v1, 0x0($v0)
    /* 8728 801E0728 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 872C 801E072C 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 8730 801E0730 00000000 */  nop
    /* 8734 801E0734 00004290 */  lbu        $v0, 0x0($v0)
    /* 8738 801E0738 00000000 */  nop
    /* 873C 801E073C 07004230 */  andi       $v0, $v0, 0x7
    /* 8740 801E0740 EDFF4014 */  bnez       $v0, .L801E06F8
    /* 8744 801E0744 00000000 */   nop
  .L801E0748:
    /* 8748 801E0748 1F80013C */  lui        $at, %hi(D_801F5322)
    /* 874C 801E074C 225320A0 */  sb         $zero, %lo(D_801F5322)($at)
    /* 8750 801E0750 1F80023C */  lui        $v0, %hi(D_801F5322)
    /* 8754 801E0754 22534290 */  lbu        $v0, %lo(D_801F5322)($v0)
    /* 8758 801E0758 1F80043C */  lui        $a0, %hi(D_801F5308)
    /* 875C 801E075C 0853848C */  lw         $a0, %lo(D_801F5308)($a0)
    /* 8760 801E0760 1F80033C */  lui        $v1, %hi(D_801F5320)
    /* 8764 801E0764 20536324 */  addiu      $v1, $v1, %lo(D_801F5320)
    /* 8768 801E0768 1F80013C */  lui        $at, %hi(D_801F5321)
    /* 876C 801E076C 215322A0 */  sb         $v0, %lo(D_801F5321)($at)
    /* 8770 801E0770 02000224 */  addiu      $v0, $zero, 0x2
    /* 8774 801E0774 000062A0 */  sb         $v0, 0x0($v1)
    /* 8778 801E0778 000080A0 */  sb         $zero, 0x0($a0)
    /* 877C 801E077C 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 8780 801E0780 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 8784 801E0784 00000000 */  nop
    /* 8788 801E0788 000040A0 */  sb         $zero, 0x0($v0)
    /* 878C 801E078C 1F80033C */  lui        $v1, %hi(D_801F5318)
    /* 8790 801E0790 1853638C */  lw         $v1, %lo(D_801F5318)($v1)
    /* 8794 801E0794 25130224 */  addiu      $v0, $zero, 0x1325
    /* 8798 801E0798 000062AC */  sw         $v0, 0x0($v1)
    /* 879C 801E079C 0800E003 */  jr         $ra
    /* 87A0 801E07A0 00000000 */   nop
endlabel CD_flush

nonmatching CD_initvol, 0xF4

glabel CD_initvol
    /* 87A4 801E07A4 1F80033C */  lui        $v1, %hi(D_801F531C)
    /* 87A8 801E07A8 1C53638C */  lw         $v1, %lo(D_801F531C)($v1)
    /* 87AC 801E07AC 00000000 */  nop
    /* 87B0 801E07B0 B8016294 */  lhu        $v0, 0x1B8($v1)
    /* 87B4 801E07B4 00000000 */  nop
    /* 87B8 801E07B8 09004014 */  bnez       $v0, .L801E07E0
    /* 87BC 801E07BC F8FFBD27 */   addiu     $sp, $sp, -0x8
    /* 87C0 801E07C0 BA016294 */  lhu        $v0, 0x1BA($v1)
    /* 87C4 801E07C4 00000000 */  nop
    /* 87C8 801E07C8 06004014 */  bnez       $v0, .L801E07E4
    /* 87CC 801E07CC FF3F0224 */   addiu     $v0, $zero, 0x3FFF
    /* 87D0 801E07D0 800162A4 */  sh         $v0, 0x180($v1)
    /* 87D4 801E07D4 820162A4 */  sh         $v0, 0x182($v1)
    /* 87D8 801E07D8 1F80033C */  lui        $v1, %hi(D_801F531C)
    /* 87DC 801E07DC 1C53638C */  lw         $v1, %lo(D_801F531C)($v1)
  .L801E07E0:
    /* 87E0 801E07E0 FF3F0224 */  addiu      $v0, $zero, 0x3FFF
  .L801E07E4:
    /* 87E4 801E07E4 B00162A4 */  sh         $v0, 0x1B0($v1)
    /* 87E8 801E07E8 B20162A4 */  sh         $v0, 0x1B2($v1)
    /* 87EC 801E07EC 01C00234 */  ori        $v0, $zero, 0xC001
    /* 87F0 801E07F0 AA0162A4 */  sh         $v0, 0x1AA($v1)
    /* 87F4 801E07F4 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 87F8 801E07F8 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 87FC 801E07FC 80000224 */  addiu      $v0, $zero, 0x80
    /* 8800 801E0800 0200A2A3 */  sb         $v0, 0x2($sp)
    /* 8804 801E0804 0000A2A3 */  sb         $v0, 0x0($sp)
    /* 8808 801E0808 02000224 */  addiu      $v0, $zero, 0x2
    /* 880C 801E080C 0300A0A3 */  sb         $zero, 0x3($sp)
    /* 8810 801E0810 0100A0A3 */  sb         $zero, 0x1($sp)
    /* 8814 801E0814 000062A0 */  sb         $v0, 0x0($v1)
    /* 8818 801E0818 1F80033C */  lui        $v1, %hi(D_801F5310)
    /* 881C 801E081C 1053638C */  lw         $v1, %lo(D_801F5310)($v1)
    /* 8820 801E0820 0000A293 */  lbu        $v0, 0x0($sp)
    /* 8824 801E0824 00000000 */  nop
    /* 8828 801E0828 000062A0 */  sb         $v0, 0x0($v1)
    /* 882C 801E082C 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 8830 801E0830 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 8834 801E0834 0100A293 */  lbu        $v0, 0x1($sp)
    /* 8838 801E0838 00000000 */  nop
    /* 883C 801E083C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8840 801E0840 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 8844 801E0844 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 8848 801E0848 03000224 */  addiu      $v0, $zero, 0x3
    /* 884C 801E084C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8850 801E0850 1F80033C */  lui        $v1, %hi(D_801F530C)
    /* 8854 801E0854 0C53638C */  lw         $v1, %lo(D_801F530C)($v1)
    /* 8858 801E0858 0200A293 */  lbu        $v0, 0x2($sp)
    /* 885C 801E085C 00000000 */  nop
    /* 8860 801E0860 000062A0 */  sb         $v0, 0x0($v1)
    /* 8864 801E0864 1F80033C */  lui        $v1, %hi(D_801F5310)
    /* 8868 801E0868 1053638C */  lw         $v1, %lo(D_801F5310)($v1)
    /* 886C 801E086C 0300A293 */  lbu        $v0, 0x3($sp)
    /* 8870 801E0870 00000000 */  nop
    /* 8874 801E0874 000062A0 */  sb         $v0, 0x0($v1)
    /* 8878 801E0878 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 887C 801E087C 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 8880 801E0880 20000224 */  addiu      $v0, $zero, 0x20
    /* 8884 801E0884 000062A0 */  sb         $v0, 0x0($v1)
    /* 8888 801E0888 21100000 */  addu       $v0, $zero, $zero
    /* 888C 801E088C 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 8890 801E0890 0800E003 */  jr         $ra
    /* 8894 801E0894 00000000 */   nop
endlabel CD_initvol

nonmatching CD_initintr, 0x50

glabel CD_initintr
    /* 8898 801E0898 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 889C 801E089C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 88A0 801E08A0 1F80013C */  lui        $at, %hi(D_801F5044)
    /* 88A4 801E08A4 445020AC */  sw         $zero, %lo(D_801F5044)($at)
    /* 88A8 801E08A8 1F80013C */  lui        $at, %hi(D_801F5040)
    /* 88AC 801E08AC 405020AC */  sw         $zero, %lo(D_801F5040)($at)
    /* 88B0 801E08B0 1F80013C */  lui        $at, %hi(D_801F5054)
    /* 88B4 801E08B4 545020AC */  sw         $zero, %lo(D_801F5054)($at)
    /* 88B8 801E08B8 1F80013C */  lui        $at, %hi(D_801F5050)
    /* 88BC 801E08BC 505020AC */  sw         $zero, %lo(D_801F5050)($at)
    /* 88C0 801E08C0 118C070C */  jal        ResetCallback
    /* 88C4 801E08C4 00000000 */   nop
    /* 88C8 801E08C8 1E80053C */  lui        $a1, %hi(callback)
    /* 88CC 801E08CC 400EA524 */  addiu      $a1, $a1, %lo(callback)
    /* 88D0 801E08D0 1D8C070C */  jal        InterruptCallback
    /* 88D4 801E08D4 02000424 */   addiu     $a0, $zero, 0x2
    /* 88D8 801E08D8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 88DC 801E08DC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 88E0 801E08E0 0800E003 */  jr         $ra
    /* 88E4 801E08E4 00000000 */   nop
endlabel CD_initintr

nonmatching CD_init, 0x1EC

glabel CD_init
    /* 88E8 801E08E8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 88EC 801E08EC 1E80043C */  lui        $a0, %hi(D_801D906C)
    /* 88F0 801E08F0 6C908424 */  addiu      $a0, $a0, %lo(D_801D906C)
    /* 88F4 801E08F4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 88F8 801E08F8 C983070C */  jal        puts
    /* 88FC 801E08FC 00000000 */   nop
    /* 8900 801E0900 1E80043C */  lui        $a0, %hi(D_801D9078)
    /* 8904 801E0904 78908424 */  addiu      $a0, $a0, %lo(D_801D9078)
    /* 8908 801E0908 1F80053C */  lui        $a1, %hi(D_801F5324)
    /* 890C 801E090C 2453A524 */  addiu      $a1, $a1, %lo(D_801F5324)
    /* 8910 801E0910 2568070C */  jal        printf
    /* 8914 801E0914 00000000 */   nop
    /* 8918 801E0918 1F80013C */  lui        $at, %hi(D_801F5061)
    /* 891C 801E091C 615020A0 */  sb         $zero, %lo(D_801F5061)($at)
    /* 8920 801E0920 1F80013C */  lui        $at, %hi(D_801F5060)
    /* 8924 801E0924 605020A0 */  sb         $zero, %lo(D_801F5060)($at)
    /* 8928 801E0928 1F80013C */  lui        $at, %hi(D_801F5044)
    /* 892C 801E092C 445020AC */  sw         $zero, %lo(D_801F5044)($at)
    /* 8930 801E0930 1F80013C */  lui        $at, %hi(D_801F5040)
    /* 8934 801E0934 405020AC */  sw         $zero, %lo(D_801F5040)($at)
    /* 8938 801E0938 1F80013C */  lui        $at, %hi(D_801F5054)
    /* 893C 801E093C 545020AC */  sw         $zero, %lo(D_801F5054)($at)
    /* 8940 801E0940 1F80013C */  lui        $at, %hi(D_801F5050)
    /* 8944 801E0944 505020AC */  sw         $zero, %lo(D_801F5050)($at)
    /* 8948 801E0948 118C070C */  jal        ResetCallback
    /* 894C 801E094C 00000000 */   nop
    /* 8950 801E0950 1E80053C */  lui        $a1, %hi(callback)
    /* 8954 801E0954 400EA524 */  addiu      $a1, $a1, %lo(callback)
    /* 8958 801E0958 1D8C070C */  jal        InterruptCallback
    /* 895C 801E095C 02000424 */   addiu     $a0, $zero, 0x2
    /* 8960 801E0960 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 8964 801E0964 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 8968 801E0968 01000224 */  addiu      $v0, $zero, 0x1
    /* 896C 801E096C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8970 801E0970 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 8974 801E0974 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 8978 801E0978 00000000 */  nop
    /* 897C 801E097C 00004290 */  lbu        $v0, 0x0($v0)
    /* 8980 801E0980 00000000 */  nop
    /* 8984 801E0984 07004230 */  andi       $v0, $v0, 0x7
    /* 8988 801E0988 16004010 */  beqz       $v0, .L801E09E4
    /* 898C 801E098C 01000424 */   addiu     $a0, $zero, 0x1
    /* 8990 801E0990 07000324 */  addiu      $v1, $zero, 0x7
  .L801E0994:
    /* 8994 801E0994 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8998 801E0998 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 899C 801E099C 00000000 */  nop
    /* 89A0 801E09A0 000044A0 */  sb         $a0, 0x0($v0)
    /* 89A4 801E09A4 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 89A8 801E09A8 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 89AC 801E09AC 00000000 */  nop
    /* 89B0 801E09B0 000043A0 */  sb         $v1, 0x0($v0)
    /* 89B4 801E09B4 1F80023C */  lui        $v0, %hi(D_801F5310)
    /* 89B8 801E09B8 1053428C */  lw         $v0, %lo(D_801F5310)($v0)
    /* 89BC 801E09BC 00000000 */  nop
    /* 89C0 801E09C0 000043A0 */  sb         $v1, 0x0($v0)
    /* 89C4 801E09C4 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 89C8 801E09C8 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 89CC 801E09CC 00000000 */  nop
    /* 89D0 801E09D0 00004290 */  lbu        $v0, 0x0($v0)
    /* 89D4 801E09D4 00000000 */  nop
    /* 89D8 801E09D8 07004230 */  andi       $v0, $v0, 0x7
    /* 89DC 801E09DC EDFF4014 */  bnez       $v0, .L801E0994
    /* 89E0 801E09E0 00000000 */   nop
  .L801E09E4:
    /* 89E4 801E09E4 01000424 */  addiu      $a0, $zero, 0x1
    /* 89E8 801E09E8 21280000 */  addu       $a1, $zero, $zero
    /* 89EC 801E09EC 21300000 */  addu       $a2, $zero, $zero
    /* 89F0 801E09F0 1F80013C */  lui        $at, %hi(D_801F5322)
    /* 89F4 801E09F4 225320A0 */  sb         $zero, %lo(D_801F5322)($at)
    /* 89F8 801E09F8 1F80023C */  lui        $v0, %hi(D_801F5322)
    /* 89FC 801E09FC 22534290 */  lbu        $v0, %lo(D_801F5322)($v0)
    /* 8A00 801E0A00 1F80073C */  lui        $a3, %hi(D_801F5308)
    /* 8A04 801E0A04 0853E78C */  lw         $a3, %lo(D_801F5308)($a3)
    /* 8A08 801E0A08 1F80033C */  lui        $v1, %hi(D_801F5320)
    /* 8A0C 801E0A0C 20536324 */  addiu      $v1, $v1, %lo(D_801F5320)
    /* 8A10 801E0A10 1F80013C */  lui        $at, %hi(D_801F5321)
    /* 8A14 801E0A14 215322A0 */  sb         $v0, %lo(D_801F5321)($at)
    /* 8A18 801E0A18 02000224 */  addiu      $v0, $zero, 0x2
    /* 8A1C 801E0A1C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8A20 801E0A20 0000E0A0 */  sb         $zero, 0x0($a3)
    /* 8A24 801E0A24 1F80023C */  lui        $v0, %hi(D_801F5314)
    /* 8A28 801E0A28 1453428C */  lw         $v0, %lo(D_801F5314)($v0)
    /* 8A2C 801E0A2C 21380000 */  addu       $a3, $zero, $zero
    /* 8A30 801E0A30 000040A0 */  sb         $zero, 0x0($v0)
    /* 8A34 801E0A34 1F80033C */  lui        $v1, %hi(D_801F5318)
    /* 8A38 801E0A38 1853638C */  lw         $v1, %lo(D_801F5318)($v1)
    /* 8A3C 801E0A3C 25130224 */  addiu      $v0, $zero, 0x1325
    /* 8A40 801E0A40 000062AC */  sw         $v0, 0x0($v1)
    /* 8A44 801E0A44 8880070C */  jal        CD_cw
    /* 8A48 801E0A48 00000000 */   nop
    /* 8A4C 801E0A4C 1F80023C */  lui        $v0, %hi(D_801F5050)
    /* 8A50 801E0A50 5050428C */  lw         $v0, %lo(D_801F5050)($v0)
    /* 8A54 801E0A54 00000000 */  nop
    /* 8A58 801E0A58 10004230 */  andi       $v0, $v0, 0x10
    /* 8A5C 801E0A5C 05004010 */  beqz       $v0, .L801E0A74
    /* 8A60 801E0A60 01000424 */   addiu     $a0, $zero, 0x1
    /* 8A64 801E0A64 21280000 */  addu       $a1, $zero, $zero
    /* 8A68 801E0A68 21300000 */  addu       $a2, $zero, $zero
    /* 8A6C 801E0A6C 8880070C */  jal        CD_cw
    /* 8A70 801E0A70 21380000 */   addu      $a3, $zero, $zero
  .L801E0A74:
    /* 8A74 801E0A74 0A000424 */  addiu      $a0, $zero, 0xA
    /* 8A78 801E0A78 21280000 */  addu       $a1, $zero, $zero
    /* 8A7C 801E0A7C 21300000 */  addu       $a2, $zero, $zero
    /* 8A80 801E0A80 8880070C */  jal        CD_cw
    /* 8A84 801E0A84 21380000 */   addu      $a3, $zero, $zero
    /* 8A88 801E0A88 0E004014 */  bnez       $v0, .L801E0AC4
    /* 8A8C 801E0A8C FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8A90 801E0A90 0C000424 */  addiu      $a0, $zero, 0xC
    /* 8A94 801E0A94 21280000 */  addu       $a1, $zero, $zero
    /* 8A98 801E0A98 21300000 */  addu       $a2, $zero, $zero
    /* 8A9C 801E0A9C 8880070C */  jal        CD_cw
    /* 8AA0 801E0AA0 21380000 */   addu      $a3, $zero, $zero
    /* 8AA4 801E0AA4 07004014 */  bnez       $v0, .L801E0AC4
    /* 8AA8 801E0AA8 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8AAC 801E0AAC 21200000 */  addu       $a0, $zero, $zero
    /* 8AB0 801E0AB0 357F070C */  jal        CD_sync
    /* 8AB4 801E0AB4 21280000 */   addu      $a1, $zero, $zero
    /* 8AB8 801E0AB8 02004238 */  xori       $v0, $v0, 0x2
    /* 8ABC 801E0ABC 2B100200 */  sltu       $v0, $zero, $v0
    /* 8AC0 801E0AC0 23100200 */  negu       $v0, $v0
  .L801E0AC4:
    /* 8AC4 801E0AC4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 8AC8 801E0AC8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 8ACC 801E0ACC 0800E003 */  jr         $ra
    /* 8AD0 801E0AD0 00000000 */   nop
endlabel CD_init

nonmatching CD_datasync, 0x16C

glabel CD_datasync
    /* 8AD4 801E0AD4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 8AD8 801E0AD8 2000B2AF */  sw         $s2, 0x20($sp)
    /* 8ADC 801E0ADC 21908000 */  addu       $s2, $a0, $zero
    /* 8AE0 801E0AE0 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 8AE4 801E0AE4 2800BFAF */  sw         $ra, 0x28($sp)
    /* 8AE8 801E0AE8 2400B3AF */  sw         $s3, 0x24($sp)
    /* 8AEC 801E0AEC 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 8AF0 801E0AF0 948B070C */  jal        VSync
    /* 8AF4 801E0AF4 1800B0AF */   sw        $s0, 0x18($sp)
    /* 8AF8 801E0AF8 1F80133C */  lui        $s3, %hi(D_801F5068)
    /* 8AFC 801E0AFC 68507326 */  addiu      $s3, $s3, %lo(D_801F5068)
    /* 8B00 801E0B00 1F80113C */  lui        $s1, %hi(D_801F5320)
    /* 8B04 801E0B04 20533126 */  addiu      $s1, $s1, %lo(D_801F5320)
    /* 8B08 801E0B08 1F80103C */  lui        $s0, %hi(D_801F50E8)
    /* 8B0C 801E0B0C E8501026 */  addiu      $s0, $s0, %lo(D_801F50E8)
    /* 8B10 801E0B10 C0034224 */  addiu      $v0, $v0, 0x3C0
    /* 8B14 801E0B14 1F80013C */  lui        $at, %hi(D_801F6798)
    /* 8B18 801E0B18 986722AC */  sw         $v0, %lo(D_801F6798)($at)
    /* 8B1C 801E0B1C 1E80023C */  lui        $v0, %hi(D_801D9084)
    /* 8B20 801E0B20 84904224 */  addiu      $v0, $v0, %lo(D_801D9084)
    /* 8B24 801E0B24 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 8B28 801E0B28 9C6720AC */  sw         $zero, %lo(D_801F679C)($at)
    /* 8B2C 801E0B2C 1F80013C */  lui        $at, %hi(D_801F67A0)
    /* 8B30 801E0B30 A06722AC */  sw         $v0, %lo(D_801F67A0)($at)
  .L801E0B34:
    /* 8B34 801E0B34 948B070C */  jal        VSync
    /* 8B38 801E0B38 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 8B3C 801E0B3C 1F80033C */  lui        $v1, %hi(D_801F6798)
    /* 8B40 801E0B40 9867638C */  lw         $v1, %lo(D_801F6798)($v1)
    /* 8B44 801E0B44 00000000 */  nop
    /* 8B48 801E0B48 2A186200 */  slt        $v1, $v1, $v0
    /* 8B4C 801E0B4C 0B006014 */  bnez       $v1, .L801E0B7C
    /* 8B50 801E0B50 00000000 */   nop
    /* 8B54 801E0B54 1F80033C */  lui        $v1, %hi(D_801F679C)
    /* 8B58 801E0B58 9C67638C */  lw         $v1, %lo(D_801F679C)($v1)
    /* 8B5C 801E0B5C 00000000 */  nop
    /* 8B60 801E0B60 01006224 */  addiu      $v0, $v1, 0x1
    /* 8B64 801E0B64 1F80013C */  lui        $at, %hi(D_801F679C)
    /* 8B68 801E0B68 9C6722AC */  sw         $v0, %lo(D_801F679C)($at)
    /* 8B6C 801E0B6C 3C00023C */  lui        $v0, (0x3C0000 >> 16)
    /* 8B70 801E0B70 2A104300 */  slt        $v0, $v0, $v1
    /* 8B74 801E0B74 1D004010 */  beqz       $v0, .L801E0BEC
    /* 8B78 801E0B78 00000000 */   nop
  .L801E0B7C:
    /* 8B7C 801E0B7C 1E80043C */  lui        $a0, %hi(D_801D8F7C)
    /* 8B80 801E0B80 7C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F7C)
    /* 8B84 801E0B84 C983070C */  jal        puts
    /* 8B88 801E0B88 00000000 */   nop
    /* 8B8C 801E0B8C 00002492 */  lbu        $a0, 0x0($s1)
    /* 8B90 801E0B90 01002292 */  lbu        $v0, 0x1($s1)
    /* 8B94 801E0B94 1F80053C */  lui        $a1, %hi(D_801F67A0)
    /* 8B98 801E0B98 A067A58C */  lw         $a1, %lo(D_801F67A0)($a1)
    /* 8B9C 801E0B9C 80100200 */  sll        $v0, $v0, 2
    /* 8BA0 801E0BA0 21105000 */  addu       $v0, $v0, $s0
    /* 8BA4 801E0BA4 80200400 */  sll        $a0, $a0, 2
    /* 8BA8 801E0BA8 0000438C */  lw         $v1, 0x0($v0)
    /* 8BAC 801E0BAC 1F80023C */  lui        $v0, %hi(D_801F5061)
    /* 8BB0 801E0BB0 61504290 */  lbu        $v0, %lo(D_801F5061)($v0)
    /* 8BB4 801E0BB4 21209000 */  addu       $a0, $a0, $s0
    /* 8BB8 801E0BB8 80100200 */  sll        $v0, $v0, 2
    /* 8BBC 801E0BBC 21105300 */  addu       $v0, $v0, $s3
    /* 8BC0 801E0BC0 1000A3AF */  sw         $v1, 0x10($sp)
    /* 8BC4 801E0BC4 0000468C */  lw         $a2, 0x0($v0)
    /* 8BC8 801E0BC8 0000878C */  lw         $a3, 0x0($a0)
    /* 8BCC 801E0BCC 1E80043C */  lui        $a0, %hi(D_801D8F8C)
    /* 8BD0 801E0BD0 8C8F8424 */  addiu      $a0, $a0, %lo(D_801D8F8C)
    /* 8BD4 801E0BD4 2568070C */  jal        printf
    /* 8BD8 801E0BD8 00000000 */   nop
    /* 8BDC 801E0BDC B181070C */  jal        CD_flush
    /* 8BE0 801E0BE0 00000000 */   nop
    /* 8BE4 801E0BE4 FC820708 */  j          .L801E0BF0
    /* 8BE8 801E0BE8 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L801E0BEC:
    /* 8BEC 801E0BEC 21100000 */  addu       $v0, $zero, $zero
  .L801E0BF0:
    /* 8BF0 801E0BF0 0B004014 */  bnez       $v0, .L801E0C20
    /* 8BF4 801E0BF4 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 8BF8 801E0BF8 1F80023C */  lui        $v0, %hi(D_801F534C)
    /* 8BFC 801E0BFC 4C53428C */  lw         $v0, %lo(D_801F534C)($v0)
    /* 8C00 801E0C00 00000000 */  nop
    /* 8C04 801E0C04 0000428C */  lw         $v0, 0x0($v0)
    /* 8C08 801E0C08 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 8C0C 801E0C0C 24104300 */  and        $v0, $v0, $v1
    /* 8C10 801E0C10 03004010 */  beqz       $v0, .L801E0C20
    /* 8C14 801E0C14 21100000 */   addu      $v0, $zero, $zero
    /* 8C18 801E0C18 C6FF4012 */  beqz       $s2, .L801E0B34
    /* 8C1C 801E0C1C 01000224 */   addiu     $v0, $zero, 0x1
  .L801E0C20:
    /* 8C20 801E0C20 2800BF8F */  lw         $ra, 0x28($sp)
    /* 8C24 801E0C24 2400B38F */  lw         $s3, 0x24($sp)
    /* 8C28 801E0C28 2000B28F */  lw         $s2, 0x20($sp)
    /* 8C2C 801E0C2C 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 8C30 801E0C30 1800B08F */  lw         $s0, 0x18($sp)
    /* 8C34 801E0C34 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 8C38 801E0C38 0800E003 */  jr         $ra
    /* 8C3C 801E0C3C 00000000 */   nop
endlabel CD_datasync

nonmatching CD_getsector, 0x100

glabel CD_getsector
    /* 8C40 801E0C40 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8C44 801E0C44 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8C48 801E0C48 0200063C */  lui        $a2, (0x20943 >> 16)
    /* 8C4C 801E0C4C 000040A0 */  sb         $zero, 0x0($v0)
    /* 8C50 801E0C50 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 8C54 801E0C54 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 8C58 801E0C58 80000224 */  addiu      $v0, $zero, 0x80
    /* 8C5C 801E0C5C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8C60 801E0C60 1F80023C */  lui        $v0, %hi(D_801F533C)
    /* 8C64 801E0C64 3C53428C */  lw         $v0, %lo(D_801F533C)($v0)
    /* 8C68 801E0C68 4309C634 */  ori        $a2, $a2, (0x20943 & 0xFFFF)
    /* 8C6C 801E0C6C 000046AC */  sw         $a2, 0x0($v0)
    /* 8C70 801E0C70 1F80033C */  lui        $v1, %hi(D_801F5318)
    /* 8C74 801E0C74 1853638C */  lw         $v1, %lo(D_801F5318)($v1)
    /* 8C78 801E0C78 23130224 */  addiu      $v0, $zero, 0x1323
    /* 8C7C 801E0C7C 000062AC */  sw         $v0, 0x0($v1)
    /* 8C80 801E0C80 1F80033C */  lui        $v1, %hi(D_801F5340)
    /* 8C84 801E0C84 4053638C */  lw         $v1, %lo(D_801F5340)($v1)
    /* 8C88 801E0C88 00000000 */  nop
    /* 8C8C 801E0C8C 0000628C */  lw         $v0, 0x0($v1)
    /* 8C90 801E0C90 00000000 */  nop
    /* 8C94 801E0C94 00804234 */  ori        $v0, $v0, 0x8000
    /* 8C98 801E0C98 000062AC */  sw         $v0, 0x0($v1)
    /* 8C9C 801E0C9C 1F80023C */  lui        $v0, %hi(D_801F5344)
    /* 8CA0 801E0CA0 4453428C */  lw         $v0, %lo(D_801F5344)($v0)
    /* 8CA4 801E0CA4 00000000 */  nop
    /* 8CA8 801E0CA8 000044AC */  sw         $a0, 0x0($v0)
    /* 8CAC 801E0CAC 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 8CB0 801E0CB0 1F80033C */  lui        $v1, %hi(D_801F5348)
    /* 8CB4 801E0CB4 4853638C */  lw         $v1, %lo(D_801F5348)($v1)
    /* 8CB8 801E0CB8 2528A200 */  or         $a1, $a1, $v0
    /* 8CBC 801E0CBC 000065AC */  sw         $a1, 0x0($v1)
    /* 8CC0 801E0CC0 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 8CC4 801E0CC4 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
  .L801E0CC8:
    /* 8CC8 801E0CC8 00000000 */  nop
    /* 8CCC 801E0CCC 00006290 */  lbu        $v0, 0x0($v1)
    /* 8CD0 801E0CD0 00000000 */  nop
    /* 8CD4 801E0CD4 40004230 */  andi       $v0, $v0, 0x40
    /* 8CD8 801E0CD8 FBFF4010 */  beqz       $v0, .L801E0CC8
    /* 8CDC 801E0CDC 0011023C */   lui       $v0, (0x11000000 >> 16)
    /* 8CE0 801E0CE0 1F80033C */  lui        $v1, %hi(D_801F534C)
    /* 8CE4 801E0CE4 4C53638C */  lw         $v1, %lo(D_801F534C)($v1)
    /* 8CE8 801E0CE8 00000000 */  nop
    /* 8CEC 801E0CEC 000062AC */  sw         $v0, 0x0($v1)
    /* 8CF0 801E0CF0 1F80043C */  lui        $a0, %hi(D_801F534C)
    /* 8CF4 801E0CF4 4C53848C */  lw         $a0, %lo(D_801F534C)($a0)
    /* 8CF8 801E0CF8 00000000 */  nop
    /* 8CFC 801E0CFC 0000828C */  lw         $v0, 0x0($a0)
    /* 8D00 801E0D00 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 8D04 801E0D04 24104300 */  and        $v0, $v0, $v1
    /* 8D08 801E0D08 07004010 */  beqz       $v0, .L801E0D28
    /* 8D0C 801E0D0C 21188000 */   addu      $v1, $a0, $zero
    /* 8D10 801E0D10 0001043C */  lui        $a0, (0x1000000 >> 16)
  .L801E0D14:
    /* 8D14 801E0D14 0000628C */  lw         $v0, 0x0($v1)
    /* 8D18 801E0D18 00000000 */  nop
    /* 8D1C 801E0D1C 24104400 */  and        $v0, $v0, $a0
    /* 8D20 801E0D20 FCFF4014 */  bnez       $v0, .L801E0D14
    /* 8D24 801E0D24 00000000 */   nop
  .L801E0D28:
    /* 8D28 801E0D28 1F80033C */  lui        $v1, %hi(D_801F5318)
    /* 8D2C 801E0D2C 1853638C */  lw         $v1, %lo(D_801F5318)($v1)
    /* 8D30 801E0D30 25130224 */  addiu      $v0, $zero, 0x1325
    /* 8D34 801E0D34 000062AC */  sw         $v0, 0x0($v1)
    /* 8D38 801E0D38 0800E003 */  jr         $ra
    /* 8D3C 801E0D3C 21100000 */   addu      $v0, $zero, $zero
endlabel CD_getsector

nonmatching CD_getsector2, 0xF0

glabel CD_getsector2
    /* 8D40 801E0D40 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8D44 801E0D44 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8D48 801E0D48 0221063C */  lui        $a2, (0x21020843 >> 16)
    /* 8D4C 801E0D4C 000040A0 */  sb         $zero, 0x0($v0)
    /* 8D50 801E0D50 1F80033C */  lui        $v1, %hi(D_801F5314)
    /* 8D54 801E0D54 1453638C */  lw         $v1, %lo(D_801F5314)($v1)
    /* 8D58 801E0D58 80000224 */  addiu      $v0, $zero, 0x80
    /* 8D5C 801E0D5C 000062A0 */  sb         $v0, 0x0($v1)
    /* 8D60 801E0D60 1F80023C */  lui        $v0, %hi(D_801F533C)
    /* 8D64 801E0D64 3C53428C */  lw         $v0, %lo(D_801F533C)($v0)
    /* 8D68 801E0D68 4308C634 */  ori        $a2, $a2, (0x21020843 & 0xFFFF)
    /* 8D6C 801E0D6C 000046AC */  sw         $a2, 0x0($v0)
    /* 8D70 801E0D70 1F80033C */  lui        $v1, %hi(D_801F5318)
    /* 8D74 801E0D74 1853638C */  lw         $v1, %lo(D_801F5318)($v1)
    /* 8D78 801E0D78 25130224 */  addiu      $v0, $zero, 0x1325
    /* 8D7C 801E0D7C 000062AC */  sw         $v0, 0x0($v1)
    /* 8D80 801E0D80 1F80033C */  lui        $v1, %hi(D_801F5340)
    /* 8D84 801E0D84 4053638C */  lw         $v1, %lo(D_801F5340)($v1)
    /* 8D88 801E0D88 00000000 */  nop
    /* 8D8C 801E0D8C 0000628C */  lw         $v0, 0x0($v1)
    /* 8D90 801E0D90 00000000 */  nop
    /* 8D94 801E0D94 00804234 */  ori        $v0, $v0, 0x8000
    /* 8D98 801E0D98 000062AC */  sw         $v0, 0x0($v1)
    /* 8D9C 801E0D9C 1F80023C */  lui        $v0, %hi(D_801F5344)
    /* 8DA0 801E0DA0 4453428C */  lw         $v0, %lo(D_801F5344)($v0)
    /* 8DA4 801E0DA4 00000000 */  nop
    /* 8DA8 801E0DA8 000044AC */  sw         $a0, 0x0($v0)
    /* 8DAC 801E0DAC 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 8DB0 801E0DB0 1F80033C */  lui        $v1, %hi(D_801F5348)
    /* 8DB4 801E0DB4 4853638C */  lw         $v1, %lo(D_801F5348)($v1)
    /* 8DB8 801E0DB8 2528A200 */  or         $a1, $a1, $v0
    /* 8DBC 801E0DBC 000065AC */  sw         $a1, 0x0($v1)
    /* 8DC0 801E0DC0 1F80033C */  lui        $v1, %hi(D_801F5308)
    /* 8DC4 801E0DC4 0853638C */  lw         $v1, %lo(D_801F5308)($v1)
    /* 8DC8 801E0DC8 00000000 */  nop
    /* 8DCC 801E0DCC 00006290 */  lbu        $v0, 0x0($v1)
    /* 8DD0 801E0DD0 00000000 */  nop
    /* 8DD4 801E0DD4 40004230 */  andi       $v0, $v0, 0x40
    /* 8DD8 801E0DD8 06004014 */  bnez       $v0, .L801E0DF4
    /* 8DDC 801E0DDC F8FFBD27 */   addiu     $sp, $sp, -0x8
  .L801E0DE0:
    /* 8DE0 801E0DE0 00006290 */  lbu        $v0, 0x0($v1)
    /* 8DE4 801E0DE4 00000000 */  nop
    /* 8DE8 801E0DE8 40004230 */  andi       $v0, $v0, 0x40
    /* 8DEC 801E0DEC FCFF4010 */  beqz       $v0, .L801E0DE0
    /* 8DF0 801E0DF0 00000000 */   nop
  .L801E0DF4:
    /* 8DF4 801E0DF4 4011033C */  lui        $v1, (0x11400100 >> 16)
    /* 8DF8 801E0DF8 1F80023C */  lui        $v0, %hi(D_801F534C)
    /* 8DFC 801E0DFC 4C53428C */  lw         $v0, %lo(D_801F534C)($v0)
    /* 8E00 801E0E00 00016334 */  ori        $v1, $v1, (0x11400100 & 0xFFFF)
    /* 8E04 801E0E04 000043AC */  sw         $v1, 0x0($v0)
    /* 8E08 801E0E08 1F80023C */  lui        $v0, %hi(D_801F534C)
    /* 8E0C 801E0E0C 4C53428C */  lw         $v0, %lo(D_801F534C)($v0)
    /* 8E10 801E0E10 00000000 */  nop
    /* 8E14 801E0E14 0000428C */  lw         $v0, 0x0($v0)
    /* 8E18 801E0E18 00000000 */  nop
    /* 8E1C 801E0E1C 0000A2AF */  sw         $v0, 0x0($sp)
    /* 8E20 801E0E20 21100000 */  addu       $v0, $zero, $zero
    /* 8E24 801E0E24 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 8E28 801E0E28 0800E003 */  jr         $ra
    /* 8E2C 801E0E2C 00000000 */   nop
endlabel CD_getsector2

nonmatching CD_set_test_parmnum, 0x10

glabel CD_set_test_parmnum
    /* 8E30 801E0E30 1F80013C */  lui        $at, %hi(D_801F52EC)
    /* 8E34 801E0E34 EC5224AC */  sw         $a0, %lo(D_801F52EC)($at)
    /* 8E38 801E0E38 0800E003 */  jr         $ra
    /* 8E3C 801E0E3C 00000000 */   nop
endlabel CD_set_test_parmnum

nonmatching callback, 0xE4

glabel callback
    /* 8E40 801E0E40 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8E44 801E0E44 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8E48 801E0E48 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 8E4C 801E0E4C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 8E50 801E0E50 1F80113C */  lui        $s1, %hi(D_801F5321)
    /* 8E54 801E0E54 21533126 */  addiu      $s1, $s1, %lo(D_801F5321)
    /* 8E58 801E0E58 2000BFAF */  sw         $ra, 0x20($sp)
    /* 8E5C 801E0E5C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 8E60 801E0E60 1800B2AF */  sw         $s2, 0x18($sp)
    /* 8E64 801E0E64 1000B0AF */  sw         $s0, 0x10($sp)
    /* 8E68 801E0E68 00004290 */  lbu        $v0, 0x0($v0)
    /* 8E6C 801E0E6C FFFF3326 */  addiu      $s3, $s1, -0x1
    /* 8E70 801E0E70 03005230 */  andi       $s2, $v0, 0x3
  .L801E0E74:
    /* 8E74 801E0E74 D37D070C */  jal        getintr
    /* 8E78 801E0E78 00000000 */   nop
    /* 8E7C 801E0E7C 21804000 */  addu       $s0, $v0, $zero
    /* 8E80 801E0E80 1C000012 */  beqz       $s0, .L801E0EF4
    /* 8E84 801E0E84 04000232 */   andi      $v0, $s0, 0x4
    /* 8E88 801E0E88 0C004010 */  beqz       $v0, .L801E0EBC
    /* 8E8C 801E0E8C 02000232 */   andi      $v0, $s0, 0x2
    /* 8E90 801E0E90 1F80023C */  lui        $v0, %hi(D_801F5044)
    /* 8E94 801E0E94 4450428C */  lw         $v0, %lo(D_801F5044)($v0)
    /* 8E98 801E0E98 00000000 */  nop
    /* 8E9C 801E0E9C 06004010 */  beqz       $v0, .L801E0EB8
    /* 8EA0 801E0EA0 00000000 */   nop
    /* 8EA4 801E0EA4 00002492 */  lbu        $a0, 0x0($s1)
    /* 8EA8 801E0EA8 1F80053C */  lui        $a1, %hi(D_801F6788)
    /* 8EAC 801E0EAC 8867A524 */  addiu      $a1, $a1, %lo(D_801F6788)
    /* 8EB0 801E0EB0 09F84000 */  jalr       $v0
    /* 8EB4 801E0EB4 00000000 */   nop
  .L801E0EB8:
    /* 8EB8 801E0EB8 02000232 */  andi       $v0, $s0, 0x2
  .L801E0EBC:
    /* 8EBC 801E0EBC EDFF4010 */  beqz       $v0, .L801E0E74
    /* 8EC0 801E0EC0 00000000 */   nop
    /* 8EC4 801E0EC4 1F80023C */  lui        $v0, %hi(D_801F5040)
    /* 8EC8 801E0EC8 4050428C */  lw         $v0, %lo(D_801F5040)($v0)
    /* 8ECC 801E0ECC 00000000 */  nop
    /* 8ED0 801E0ED0 E8FF4010 */  beqz       $v0, .L801E0E74
    /* 8ED4 801E0ED4 00000000 */   nop
    /* 8ED8 801E0ED8 00006492 */  lbu        $a0, 0x0($s3)
    /* 8EDC 801E0EDC 1F80053C */  lui        $a1, %hi(D_801F6780)
    /* 8EE0 801E0EE0 8067A524 */  addiu      $a1, $a1, %lo(D_801F6780)
    /* 8EE4 801E0EE4 09F84000 */  jalr       $v0
    /* 8EE8 801E0EE8 00000000 */   nop
    /* 8EEC 801E0EEC 9D830708 */  j          .L801E0E74
    /* 8EF0 801E0EF0 00000000 */   nop
  .L801E0EF4:
    /* 8EF4 801E0EF4 1F80023C */  lui        $v0, %hi(D_801F5308)
    /* 8EF8 801E0EF8 0853428C */  lw         $v0, %lo(D_801F5308)($v0)
    /* 8EFC 801E0EFC 00000000 */  nop
    /* 8F00 801E0F00 000052A0 */  sb         $s2, 0x0($v0)
    /* 8F04 801E0F04 2000BF8F */  lw         $ra, 0x20($sp)
    /* 8F08 801E0F08 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 8F0C 801E0F0C 1800B28F */  lw         $s2, 0x18($sp)
    /* 8F10 801E0F10 1400B18F */  lw         $s1, 0x14($sp)
    /* 8F14 801E0F14 1000B08F */  lw         $s0, 0x10($sp)
    /* 8F18 801E0F18 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 8F1C 801E0F1C 0800E003 */  jr         $ra
    /* 8F20 801E0F20 00000000 */   nop
endlabel callback
