.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching prnt, 0x688

glabel prnt
    /* 20D0 801DA0D0 78FFBD27 */  addiu      $sp, $sp, -0x88
    /* 20D4 801DA0D4 6400B1AF */  sw         $s1, 0x64($sp)
    /* 20D8 801DA0D8 2188C000 */  addu       $s1, $a2, $zero
    /* 20DC 801DA0DC 8400BFAF */  sw         $ra, 0x84($sp)
    /* 20E0 801DA0E0 8000BEAF */  sw         $fp, 0x80($sp)
    /* 20E4 801DA0E4 7C00B7AF */  sw         $s7, 0x7C($sp)
    /* 20E8 801DA0E8 7800B6AF */  sw         $s6, 0x78($sp)
    /* 20EC 801DA0EC 7400B5AF */  sw         $s5, 0x74($sp)
    /* 20F0 801DA0F0 7000B4AF */  sw         $s4, 0x70($sp)
    /* 20F4 801DA0F4 6C00B3AF */  sw         $s3, 0x6C($sp)
    /* 20F8 801DA0F8 6800B2AF */  sw         $s2, 0x68($sp)
    /* 20FC 801DA0FC 0300A014 */  bnez       $a1, .L801DA10C
    /* 2100 801DA100 6000B0AF */   sw        $s0, 0x60($sp)
    /* 2104 801DA104 C9690708 */  j          .L801DA724
    /* 2108 801DA108 21100000 */   addu      $v0, $zero, $zero
  .L801DA10C:
    /* 210C 801DA10C 21B8A000 */  addu       $s7, $a1, $zero
    /* 2110 801DA110 1E80073C */  lui        $a3, %hi(D_801D885C)
    /* 2114 801DA114 5C88E724 */  addiu      $a3, $a3, %lo(D_801D885C)
    /* 2118 801DA118 5800A7AF */  sw         $a3, 0x58($sp)
    /* 211C 801DA11C 3800A0AF */  sw         $zero, 0x38($sp)
  .L801DA120:
    /* 2120 801DA120 0000E492 */  lbu        $a0, 0x0($s7)
    /* 2124 801DA124 00000000 */  nop
    /* 2128 801DA128 04008014 */  bnez       $a0, .L801DA13C
    /* 212C 801DA12C 25000224 */   addiu     $v0, $zero, 0x25
  jlabel .L801DA130
    /* 2130 801DA130 3800A28F */  lw         $v0, 0x38($sp)
    /* 2134 801DA134 C9690708 */  j          .L801DA724
    /* 2138 801DA138 00000000 */   nop
  .L801DA13C:
    /* 213C 801DA13C 75018214 */  bne        $a0, $v0, .L801DA714
    /* 2140 801DA140 21980000 */   addu      $s3, $zero, $zero
    /* 2144 801DA144 FFFF1424 */  addiu      $s4, $zero, -0x1
    /* 2148 801DA148 21F00000 */  addu       $fp, $zero, $zero
    /* 214C 801DA14C 4000A0AF */  sw         $zero, 0x40($sp)
    /* 2150 801DA150 4800A0AF */  sw         $zero, 0x48($sp)
    /* 2154 801DA154 5000A0AF */  sw         $zero, 0x50($sp)
  .L801DA158:
    /* 2158 801DA158 0100F726 */  addiu      $s7, $s7, 0x1
    /* 215C 801DA15C 0000E392 */  lbu        $v1, 0x0($s7)
    /* 2160 801DA160 00000000 */  nop
    /* 2164 801DA164 7900622C */  sltiu      $v0, $v1, 0x79
    /* 2168 801DA168 66014010 */  beqz       $v0, .L801DA704
    /* 216C 801DA16C 80100300 */   sll       $v0, $v1, 2
    /* 2170 801DA170 1E80013C */  lui        $at, %hi(jtbl_801D888C)
    /* 2174 801DA174 21082200 */  addu       $at, $at, $v0
    /* 2178 801DA178 8C88228C */  lw         $v0, %lo(jtbl_801D888C)($at)
    /* 217C 801DA17C 00000000 */  nop
    /* 2180 801DA180 08004000 */  jr         $v0
    /* 2184 801DA184 00000000 */   nop
  jlabel .L801DA188
    /* 2188 801DA188 F3FFC017 */  bnez       $fp, .L801DA158
    /* 218C 801DA18C 00000000 */   nop
    /* 2190 801DA190 56680708 */  j          .L801DA158
    /* 2194 801DA194 20001E24 */   addiu     $fp, $zero, 0x20
  jlabel .L801DA198
    /* 2198 801DA198 56680708 */  j          .L801DA158
    /* 219C 801DA19C 08007336 */   ori       $s3, $s3, 0x8
  jlabel .L801DA1A0
    /* 21A0 801DA1A0 04003126 */  addiu      $s1, $s1, 0x4
    /* 21A4 801DA1A4 FCFF278E */  lw         $a3, -0x4($s1)
    /* 21A8 801DA1A8 00000000 */  nop
    /* 21AC 801DA1AC EAFFE104 */  bgez       $a3, .L801DA158
    /* 21B0 801DA1B0 5000A7AF */   sw        $a3, 0x50($sp)
    /* 21B4 801DA1B4 23380700 */  negu       $a3, $a3
    /* 21B8 801DA1B8 5000A7AF */  sw         $a3, 0x50($sp)
  jlabel .L801DA1BC
    /* 21BC 801DA1BC 56680708 */  j          .L801DA158
    /* 21C0 801DA1C0 10007336 */   ori       $s3, $s3, 0x10
  jlabel .L801DA1C4
    /* 21C4 801DA1C4 56680708 */  j          .L801DA158
    /* 21C8 801DA1C8 2B001E24 */   addiu     $fp, $zero, 0x2B
  jlabel .L801DA1CC
    /* 21CC 801DA1CC 0100F726 */  addiu      $s7, $s7, 0x1
    /* 21D0 801DA1D0 0000E392 */  lbu        $v1, 0x0($s7)
    /* 21D4 801DA1D4 2A000224 */  addiu      $v0, $zero, 0x2A
    /* 21D8 801DA1D8 05006214 */  bne        $v1, $v0, .L801DA1F0
    /* 21DC 801DA1DC 00000000 */   nop
    /* 21E0 801DA1E0 04003126 */  addiu      $s1, $s1, 0x4
    /* 21E4 801DA1E4 FCFF308E */  lw         $s0, -0x4($s1)
    /* 21E8 801DA1E8 92680708 */  j          .L801DA248
    /* 21EC 801DA1EC 00000000 */   nop
  .L801DA1F0:
    /* 21F0 801DA1F0 8000622C */  sltiu      $v0, $v1, 0x80
    /* 21F4 801DA1F4 13004010 */  beqz       $v0, .L801DA244
    /* 21F8 801DA1F8 21800000 */   addu      $s0, $zero, $zero
  .L801DA1FC:
    /* 21FC 801DA1FC 0000E492 */  lbu        $a0, 0x0($s7)
    /* 2200 801DA200 1E80013C */  lui        $at, %hi(D_801E3C69)
    /* 2204 801DA204 21082400 */  addu       $at, $at, $a0
    /* 2208 801DA208 693C2290 */  lbu        $v0, %lo(D_801E3C69)($at)
    /* 220C 801DA20C 00000000 */  nop
    /* 2210 801DA210 04004230 */  andi       $v0, $v0, 0x4
    /* 2214 801DA214 0B004010 */  beqz       $v0, .L801DA244
    /* 2218 801DA218 00000000 */   nop
    /* 221C 801DA21C 0100F726 */  addiu      $s7, $s7, 0x1
    /* 2220 801DA220 80101000 */  sll        $v0, $s0, 2
    /* 2224 801DA224 21105000 */  addu       $v0, $v0, $s0
    /* 2228 801DA228 40100200 */  sll        $v0, $v0, 1
    /* 222C 801DA22C D0FF4224 */  addiu      $v0, $v0, -0x30
    /* 2230 801DA230 0000E392 */  lbu        $v1, 0x0($s7)
    /* 2234 801DA234 00000000 */  nop
    /* 2238 801DA238 8000632C */  sltiu      $v1, $v1, 0x80
    /* 223C 801DA23C EFFF6014 */  bnez       $v1, .L801DA1FC
    /* 2240 801DA240 21804400 */   addu      $s0, $v0, $a0
  .L801DA244:
    /* 2244 801DA244 FFFFF726 */  addiu      $s7, $s7, -0x1
  .L801DA248:
    /* 2248 801DA248 C3FF0106 */  bgez       $s0, .L801DA158
    /* 224C 801DA24C 21A00002 */   addu      $s4, $s0, $zero
    /* 2250 801DA250 56680708 */  j          .L801DA158
    /* 2254 801DA254 FFFF1424 */   addiu     $s4, $zero, -0x1
  jlabel .L801DA258
    /* 2258 801DA258 56680708 */  j          .L801DA158
    /* 225C 801DA25C 20007336 */   ori       $s3, $s3, 0x20
  jlabel .L801DA260
    /* 2260 801DA260 21800000 */  addu       $s0, $zero, $zero
  .L801DA264:
    /* 2264 801DA264 0000E292 */  lbu        $v0, 0x0($s7)
    /* 2268 801DA268 0100F726 */  addiu      $s7, $s7, 0x1
    /* 226C 801DA26C 80181000 */  sll        $v1, $s0, 2
    /* 2270 801DA270 21187000 */  addu       $v1, $v1, $s0
    /* 2274 801DA274 40180300 */  sll        $v1, $v1, 1
    /* 2278 801DA278 D0FF6324 */  addiu      $v1, $v1, -0x30
    /* 227C 801DA27C 0000E492 */  lbu        $a0, 0x0($s7)
    /* 2280 801DA280 21806200 */  addu       $s0, $v1, $v0
    /* 2284 801DA284 8000822C */  sltiu      $v0, $a0, 0x80
    /* 2288 801DA288 08004010 */  beqz       $v0, .L801DA2AC
    /* 228C 801DA28C 00000000 */   nop
    /* 2290 801DA290 1E80013C */  lui        $at, %hi(D_801E3C69)
    /* 2294 801DA294 21082400 */  addu       $at, $at, $a0
    /* 2298 801DA298 693C2290 */  lbu        $v0, %lo(D_801E3C69)($at)
    /* 229C 801DA29C 00000000 */  nop
    /* 22A0 801DA2A0 04004230 */  andi       $v0, $v0, 0x4
    /* 22A4 801DA2A4 EFFF4014 */  bnez       $v0, .L801DA264
    /* 22A8 801DA2A8 00000000 */   nop
  .L801DA2AC:
    /* 22AC 801DA2AC 5000B0AF */  sw         $s0, 0x50($sp)
    /* 22B0 801DA2B0 56680708 */  j          .L801DA158
    /* 22B4 801DA2B4 FFFFF726 */   addiu     $s7, $s7, -0x1
  jlabel .L801DA2B8
    /* 22B8 801DA2B8 56680708 */  j          .L801DA158
    /* 22BC 801DA2BC 02007336 */   ori       $s3, $s3, 0x2
  jlabel .L801DA2C0
    /* 22C0 801DA2C0 56680708 */  j          .L801DA158
    /* 22C4 801DA2C4 04007336 */   ori       $s3, $s3, 0x4
  jlabel .L801DA2C8
    /* 22C8 801DA2C8 56680708 */  j          .L801DA158
    /* 22CC 801DA2CC 01007336 */   ori       $s3, $s3, 0x1
  jlabel .L801DA2D0
    /* 22D0 801DA2D0 1000B227 */  addiu      $s2, $sp, 0x10
    /* 22D4 801DA2D4 04003126 */  addiu      $s1, $s1, 0x4
    /* 22D8 801DA2D8 01001624 */  addiu      $s6, $zero, 0x1
    /* 22DC 801DA2DC FCFF228E */  lw         $v0, -0x4($s1)
    /* 22E0 801DA2E0 21F00000 */  addu       $fp, $zero, $zero
    /* 22E4 801DA2E4 50690708 */  j          .L801DA540
    /* 22E8 801DA2E8 1000A2A3 */   sb        $v0, 0x10($sp)
  jlabel .L801DA2EC
    /* 22EC 801DA2EC 01007336 */  ori        $s3, $s3, 0x1
  jlabel .L801DA2F0
    /* 22F0 801DA2F0 01006232 */  andi       $v0, $s3, 0x1
    /* 22F4 801DA2F4 07004014 */  bnez       $v0, .L801DA314
    /* 22F8 801DA2F8 04006232 */   andi      $v0, $s3, 0x4
    /* 22FC 801DA2FC 05004010 */  beqz       $v0, .L801DA314
    /* 2300 801DA300 00000000 */   nop
    /* 2304 801DA304 04003126 */  addiu      $s1, $s1, 0x4
    /* 2308 801DA308 FCFF2386 */  lh         $v1, -0x4($s1)
    /* 230C 801DA30C C7680708 */  j          .L801DA31C
    /* 2310 801DA310 00000000 */   nop
  .L801DA314:
    /* 2314 801DA314 04003126 */  addiu      $s1, $s1, 0x4
    /* 2318 801DA318 FCFF238E */  lw         $v1, -0x4($s1)
  .L801DA31C:
    /* 231C 801DA31C 00000000 */  nop
    /* 2320 801DA320 60006104 */  bgez       $v1, .L801DA4A4
    /* 2324 801DA324 0A000524 */   addiu     $a1, $zero, 0xA
    /* 2328 801DA328 23180300 */  negu       $v1, $v1
    /* 232C 801DA32C 29690708 */  j          .L801DA4A4
    /* 2330 801DA330 2D001E24 */   addiu     $fp, $zero, 0x2D
  jlabel .L801DA334
    /* 2334 801DA334 01006232 */  andi       $v0, $s3, 0x1
    /* 2338 801DA338 08004014 */  bnez       $v0, .L801DA35C
    /* 233C 801DA33C 04006232 */   andi      $v0, $s3, 0x4
    /* 2340 801DA340 06004010 */  beqz       $v0, .L801DA35C
    /* 2344 801DA344 00000000 */   nop
    /* 2348 801DA348 04003126 */  addiu      $s1, $s1, 0x4
    /* 234C 801DA34C FCFF228E */  lw         $v0, -0x4($s1)
    /* 2350 801DA350 3800A797 */  lhu        $a3, 0x38($sp)
    /* 2354 801DA354 C7690708 */  j          .L801DA71C
    /* 2358 801DA358 000047A4 */   sh        $a3, 0x0($v0)
  .L801DA35C:
    /* 235C 801DA35C 04003126 */  addiu      $s1, $s1, 0x4
    /* 2360 801DA360 FCFF228E */  lw         $v0, -0x4($s1)
    /* 2364 801DA364 3800A78F */  lw         $a3, 0x38($sp)
    /* 2368 801DA368 C7690708 */  j          .L801DA71C
    /* 236C 801DA36C 000047AC */   sw        $a3, 0x0($v0)
  jlabel .L801DA370
    /* 2370 801DA370 01007336 */  ori        $s3, $s3, 0x1
  jlabel .L801DA374
    /* 2374 801DA374 01006232 */  andi       $v0, $s3, 0x1
    /* 2378 801DA378 07004014 */  bnez       $v0, .L801DA398
    /* 237C 801DA37C 04006232 */   andi      $v0, $s3, 0x4
    /* 2380 801DA380 05004010 */  beqz       $v0, .L801DA398
    /* 2384 801DA384 08000524 */   addiu     $a1, $zero, 0x8
    /* 2388 801DA388 04003126 */  addiu      $s1, $s1, 0x4
    /* 238C 801DA38C FCFF2386 */  lh         $v1, -0x4($s1)
    /* 2390 801DA390 28690708 */  j          .L801DA4A0
    /* 2394 801DA394 00000000 */   nop
  .L801DA398:
    /* 2398 801DA398 04003126 */  addiu      $s1, $s1, 0x4
    /* 239C 801DA39C FCFF238E */  lw         $v1, -0x4($s1)
    /* 23A0 801DA3A0 28690708 */  j          .L801DA4A0
    /* 23A4 801DA3A4 08000524 */   addiu     $a1, $zero, 0x8
  jlabel .L801DA3A8
    /* 23A8 801DA3A8 04003126 */  addiu      $s1, $s1, 0x4
    /* 23AC 801DA3AC FCFF238E */  lw         $v1, -0x4($s1)
    /* 23B0 801DA3B0 28690708 */  j          .L801DA4A0
    /* 23B4 801DA3B4 10000524 */   addiu     $a1, $zero, 0x10
  jlabel .L801DA3B8
    /* 23B8 801DA3B8 04003126 */  addiu      $s1, $s1, 0x4
    /* 23BC 801DA3BC FCFF328E */  lw         $s2, -0x4($s1)
    /* 23C0 801DA3C0 00000000 */  nop
    /* 23C4 801DA3C4 03004016 */  bnez       $s2, .L801DA3D4
    /* 23C8 801DA3C8 00000000 */   nop
    /* 23CC 801DA3CC 1E80123C */  lui        $s2, %hi(D_801D8870)
    /* 23D0 801DA3D0 70885226 */  addiu      $s2, $s2, %lo(D_801D8870)
  .L801DA3D4:
    /* 23D4 801DA3D4 0B008006 */  bltz       $s4, .L801DA404
    /* 23D8 801DA3D8 21204002 */   addu      $a0, $s2, $zero
    /* 23DC 801DA3DC 21280000 */  addu       $a1, $zero, $zero
    /* 23E0 801DA3E0 EE69070C */  jal        memchr
    /* 23E4 801DA3E4 21308002 */   addu      $a2, $s4, $zero
    /* 23E8 801DA3E8 04004010 */  beqz       $v0, .L801DA3FC
    /* 23EC 801DA3EC 23B05200 */   subu      $s6, $v0, $s2
    /* 23F0 801DA3F0 2A109602 */  slt        $v0, $s4, $s6
    /* 23F4 801DA3F4 52004010 */  beqz       $v0, .L801DA540
    /* 23F8 801DA3F8 21F00000 */   addu      $fp, $zero, $zero
  .L801DA3FC:
    /* 23FC 801DA3FC 04690708 */  j          .L801DA410
    /* 2400 801DA400 21B08002 */   addu      $s6, $s4, $zero
  .L801DA404:
    /* 2404 801DA404 336A070C */  jal        strlen
    /* 2408 801DA408 21204002 */   addu      $a0, $s2, $zero
    /* 240C 801DA40C 21B04000 */  addu       $s6, $v0, $zero
  .L801DA410:
    /* 2410 801DA410 50690708 */  j          .L801DA540
    /* 2414 801DA414 21F00000 */   addu      $fp, $zero, $zero
  jlabel .L801DA418
    /* 2418 801DA418 01007336 */  ori        $s3, $s3, 0x1
  jlabel .L801DA41C
    /* 241C 801DA41C 01006232 */  andi       $v0, $s3, 0x1
    /* 2420 801DA420 07004014 */  bnez       $v0, .L801DA440
    /* 2424 801DA424 04006232 */   andi      $v0, $s3, 0x4
    /* 2428 801DA428 05004010 */  beqz       $v0, .L801DA440
    /* 242C 801DA42C 0A000524 */   addiu     $a1, $zero, 0xA
    /* 2430 801DA430 04003126 */  addiu      $s1, $s1, 0x4
    /* 2434 801DA434 FCFF2386 */  lh         $v1, -0x4($s1)
    /* 2438 801DA438 28690708 */  j          .L801DA4A0
    /* 243C 801DA43C 00000000 */   nop
  .L801DA440:
    /* 2440 801DA440 04003126 */  addiu      $s1, $s1, 0x4
    /* 2444 801DA444 FCFF238E */  lw         $v1, -0x4($s1)
    /* 2448 801DA448 28690708 */  j          .L801DA4A0
    /* 244C 801DA44C 0A000524 */   addiu     $a1, $zero, 0xA
  jlabel .L801DA450
    /* 2450 801DA450 1E80073C */  lui        $a3, %hi(D_801D8878)
    /* 2454 801DA454 7888E724 */  addiu      $a3, $a3, %lo(D_801D8878)
    /* 2458 801DA458 5800A7AF */  sw         $a3, 0x58($sp)
  jlabel .L801DA45C
    /* 245C 801DA45C 01006232 */  andi       $v0, $s3, 0x1
    /* 2460 801DA460 07004014 */  bnez       $v0, .L801DA480
    /* 2464 801DA464 04006232 */   andi      $v0, $s3, 0x4
    /* 2468 801DA468 05004010 */  beqz       $v0, .L801DA480
    /* 246C 801DA46C 08006232 */   andi      $v0, $s3, 0x8
    /* 2470 801DA470 04003126 */  addiu      $s1, $s1, 0x4
    /* 2474 801DA474 FCFF2386 */  lh         $v1, -0x4($s1)
    /* 2478 801DA478 23690708 */  j          .L801DA48C
    /* 247C 801DA47C 00000000 */   nop
  .L801DA480:
    /* 2480 801DA480 04003126 */  addiu      $s1, $s1, 0x4
    /* 2484 801DA484 FCFF238E */  lw         $v1, -0x4($s1)
    /* 2488 801DA488 08006232 */  andi       $v0, $s3, 0x8
  .L801DA48C:
    /* 248C 801DA48C 04004010 */  beqz       $v0, .L801DA4A0
    /* 2490 801DA490 10000524 */   addiu     $a1, $zero, 0x10
    /* 2494 801DA494 03006010 */  beqz       $v1, .L801DA4A4
    /* 2498 801DA498 21F00000 */   addu      $fp, $zero, $zero
    /* 249C 801DA49C 40007336 */  ori        $s3, $s3, 0x40
  .L801DA4A0:
    /* 24A0 801DA4A0 21F00000 */  addu       $fp, $zero, $zero
  .L801DA4A4:
    /* 24A4 801DA4A4 03008006 */  bltz       $s4, .L801DA4B4
    /* 24A8 801DA4A8 4000B4AF */   sw        $s4, 0x40($sp)
    /* 24AC 801DA4AC DFFF0224 */  addiu      $v0, $zero, -0x21
    /* 24B0 801DA4B0 24986202 */  and        $s3, $s3, $v0
  .L801DA4B4:
    /* 24B4 801DA4B4 05006014 */  bnez       $v1, .L801DA4CC
    /* 24B8 801DA4B8 3800B227 */   addiu     $s2, $sp, 0x38
    /* 24BC 801DA4BC 4000A78F */  lw         $a3, 0x40($sp)
    /* 24C0 801DA4C0 00000000 */  nop
    /* 24C4 801DA4C4 1D00E010 */  beqz       $a3, .L801DA53C
    /* 24C8 801DA4C8 2310B203 */   subu      $v0, $sp, $s2
  .L801DA4CC:
    /* 24CC 801DA4CC 1B006500 */  divu       $zero, $v1, $a1
    /* 24D0 801DA4D0 0200A014 */  bnez       $a1, .L801DA4DC
    /* 24D4 801DA4D4 00000000 */   nop
    /* 24D8 801DA4D8 0D000700 */  break      7
  .L801DA4DC:
    /* 24DC 801DA4DC 12180000 */  mflo       $v1
    /* 24E0 801DA4E0 10100000 */  mfhi       $v0
    /* 24E4 801DA4E4 5800A78F */  lw         $a3, 0x58($sp)
    /* 24E8 801DA4E8 00000000 */  nop
    /* 24EC 801DA4EC 2110E200 */  addu       $v0, $a3, $v0
    /* 24F0 801DA4F0 00004490 */  lbu        $a0, 0x0($v0)
    /* 24F4 801DA4F4 FFFF5226 */  addiu      $s2, $s2, -0x1
    /* 24F8 801DA4F8 F4FF6014 */  bnez       $v1, .L801DA4CC
    /* 24FC 801DA4FC 000044A2 */   sb        $a0, 0x0($s2)
    /* 2500 801DA500 1E80073C */  lui        $a3, %hi(D_801D885C)
    /* 2504 801DA504 5C88E724 */  addiu      $a3, $a3, %lo(D_801D885C)
    /* 2508 801DA508 08006232 */  andi       $v0, $s3, 0x8
    /* 250C 801DA50C 0A004010 */  beqz       $v0, .L801DA538
    /* 2510 801DA510 5800A7AF */   sw        $a3, 0x58($sp)
    /* 2514 801DA514 08000224 */  addiu      $v0, $zero, 0x8
    /* 2518 801DA518 0800A214 */  bne        $a1, $v0, .L801DA53C
    /* 251C 801DA51C 2310B203 */   subu      $v0, $sp, $s2
    /* 2520 801DA520 FF008330 */  andi       $v1, $a0, 0xFF
    /* 2524 801DA524 30000224 */  addiu      $v0, $zero, 0x30
    /* 2528 801DA528 03006210 */  beq        $v1, $v0, .L801DA538
    /* 252C 801DA52C 30000224 */   addiu     $v0, $zero, 0x30
    /* 2530 801DA530 FFFF5226 */  addiu      $s2, $s2, -0x1
    /* 2534 801DA534 000042A2 */  sb         $v0, 0x0($s2)
  .L801DA538:
    /* 2538 801DA538 2310B203 */  subu       $v0, $sp, $s2
  .L801DA53C:
    /* 253C 801DA53C 38005624 */  addiu      $s6, $v0, 0x38
  .L801DA540:
    /* 2540 801DA540 4800A78F */  lw         $a3, 0x48($sp)
    /* 2544 801DA544 0200C013 */  beqz       $fp, .L801DA550
    /* 2548 801DA548 21A0C702 */   addu      $s4, $s6, $a3
    /* 254C 801DA54C 01009426 */  addiu      $s4, $s4, 0x1
  .L801DA550:
    /* 2550 801DA550 40006232 */  andi       $v0, $s3, 0x40
    /* 2554 801DA554 02004010 */  beqz       $v0, .L801DA560
    /* 2558 801DA558 00000000 */   nop
    /* 255C 801DA55C 02009426 */  addiu      $s4, $s4, 0x2
  .L801DA560:
    /* 2560 801DA560 4000B58F */  lw         $s5, 0x40($sp)
    /* 2564 801DA564 00000000 */  nop
    /* 2568 801DA568 2A10B402 */  slt        $v0, $s5, $s4
    /* 256C 801DA56C 02004010 */  beqz       $v0, .L801DA578
    /* 2570 801DA570 30006232 */   andi      $v0, $s3, 0x30
    /* 2574 801DA574 21A88002 */  addu       $s5, $s4, $zero
  .L801DA578:
    /* 2578 801DA578 0E004014 */  bnez       $v0, .L801DA5B4
    /* 257C 801DA57C FF00C433 */   andi      $a0, $fp, 0xFF
    /* 2580 801DA580 5000A78F */  lw         $a3, 0x50($sp)
    /* 2584 801DA584 00000000 */  nop
    /* 2588 801DA588 0A00E010 */  beqz       $a3, .L801DA5B4
    /* 258C 801DA58C 2A10A702 */   slt       $v0, $s5, $a3
    /* 2590 801DA590 08004010 */  beqz       $v0, .L801DA5B4
    /* 2594 801DA594 2180A002 */   addu      $s0, $s5, $zero
  .L801DA598:
    /* 2598 801DA598 026A070C */  jal        putchar
    /* 259C 801DA59C 20000424 */   addiu     $a0, $zero, 0x20
    /* 25A0 801DA5A0 5000A78F */  lw         $a3, 0x50($sp)
    /* 25A4 801DA5A4 01001026 */  addiu      $s0, $s0, 0x1
    /* 25A8 801DA5A8 2A100702 */  slt        $v0, $s0, $a3
    /* 25AC 801DA5AC FAFF4014 */  bnez       $v0, .L801DA598
    /* 25B0 801DA5B0 FF00C433 */   andi      $a0, $fp, 0xFF
  .L801DA5B4:
    /* 25B4 801DA5B4 04008010 */  beqz       $a0, .L801DA5C8
    /* 25B8 801DA5B8 40006232 */   andi      $v0, $s3, 0x40
    /* 25BC 801DA5BC 026A070C */  jal        putchar
    /* 25C0 801DA5C0 00000000 */   nop
    /* 25C4 801DA5C4 40006232 */  andi       $v0, $s3, 0x40
  .L801DA5C8:
    /* 25C8 801DA5C8 07004010 */  beqz       $v0, .L801DA5E8
    /* 25CC 801DA5CC 30006332 */   andi      $v1, $s3, 0x30
    /* 25D0 801DA5D0 026A070C */  jal        putchar
    /* 25D4 801DA5D4 30000424 */   addiu     $a0, $zero, 0x30
    /* 25D8 801DA5D8 0000E492 */  lbu        $a0, 0x0($s7)
    /* 25DC 801DA5DC 026A070C */  jal        putchar
    /* 25E0 801DA5E0 00000000 */   nop
    /* 25E4 801DA5E4 30006332 */  andi       $v1, $s3, 0x30
  .L801DA5E8:
    /* 25E8 801DA5E8 20000224 */  addiu      $v0, $zero, 0x20
    /* 25EC 801DA5EC 0D006214 */  bne        $v1, $v0, .L801DA624
    /* 25F0 801DA5F0 00000000 */   nop
    /* 25F4 801DA5F4 5000A78F */  lw         $a3, 0x50($sp)
    /* 25F8 801DA5F8 00000000 */  nop
    /* 25FC 801DA5FC 2A10A702 */  slt        $v0, $s5, $a3
    /* 2600 801DA600 08004010 */  beqz       $v0, .L801DA624
    /* 2604 801DA604 2180A002 */   addu      $s0, $s5, $zero
  .L801DA608:
    /* 2608 801DA608 026A070C */  jal        putchar
    /* 260C 801DA60C 30000424 */   addiu     $a0, $zero, 0x30
    /* 2610 801DA610 5000A78F */  lw         $a3, 0x50($sp)
    /* 2614 801DA614 01001026 */  addiu      $s0, $s0, 0x1
    /* 2618 801DA618 2A100702 */  slt        $v0, $s0, $a3
    /* 261C 801DA61C FAFF4014 */  bnez       $v0, .L801DA608
    /* 2620 801DA620 00000000 */   nop
  .L801DA624:
    /* 2624 801DA624 4000A78F */  lw         $a3, 0x40($sp)
    /* 2628 801DA628 21808002 */  addu       $s0, $s4, $zero
    /* 262C 801DA62C 2A100702 */  slt        $v0, $s0, $a3
    /* 2630 801DA630 08004010 */  beqz       $v0, .L801DA654
    /* 2634 801DA634 00000000 */   nop
  .L801DA638:
    /* 2638 801DA638 026A070C */  jal        putchar
    /* 263C 801DA63C 30000424 */   addiu     $a0, $zero, 0x30
    /* 2640 801DA640 4000A78F */  lw         $a3, 0x40($sp)
    /* 2644 801DA644 01001026 */  addiu      $s0, $s0, 0x1
    /* 2648 801DA648 2A100702 */  slt        $v0, $s0, $a3
    /* 264C 801DA64C FAFF4014 */  bnez       $v0, .L801DA638
    /* 2650 801DA650 00000000 */   nop
  .L801DA654:
    /* 2654 801DA654 FFFFD026 */  addiu      $s0, $s6, -0x1
    /* 2658 801DA658 0B000006 */  bltz       $s0, .L801DA688
    /* 265C 801DA65C 00000000 */   nop
  .L801DA660:
    /* 2660 801DA660 00004492 */  lbu        $a0, 0x0($s2)
    /* 2664 801DA664 01005226 */  addiu      $s2, $s2, 0x1
    /* 2668 801DA668 026A070C */  jal        putchar
    /* 266C 801DA66C FFFF1026 */   addiu     $s0, $s0, -0x1
    /* 2670 801DA670 05000006 */  bltz       $s0, .L801DA688
    /* 2674 801DA674 00000000 */   nop
    /* 2678 801DA678 98690708 */  j          .L801DA660
    /* 267C 801DA67C 00000000 */   nop
  .L801DA680:
    /* 2680 801DA680 026A070C */  jal        putchar
    /* 2684 801DA684 30000424 */   addiu     $a0, $zero, 0x30
  .L801DA688:
    /* 2688 801DA688 4800A78F */  lw         $a3, 0x48($sp)
    /* 268C 801DA68C 00000000 */  nop
    /* 2690 801DA690 FFFFE724 */  addiu      $a3, $a3, -0x1
    /* 2694 801DA694 FAFFE104 */  bgez       $a3, .L801DA680
    /* 2698 801DA698 4800A7AF */   sw        $a3, 0x48($sp)
    /* 269C 801DA69C 10006232 */  andi       $v0, $s3, 0x10
    /* 26A0 801DA6A0 0D004010 */  beqz       $v0, .L801DA6D8
    /* 26A4 801DA6A4 00000000 */   nop
    /* 26A8 801DA6A8 5000A78F */  lw         $a3, 0x50($sp)
    /* 26AC 801DA6AC 00000000 */  nop
    /* 26B0 801DA6B0 2A10A702 */  slt        $v0, $s5, $a3
    /* 26B4 801DA6B4 08004010 */  beqz       $v0, .L801DA6D8
    /* 26B8 801DA6B8 2180A002 */   addu      $s0, $s5, $zero
  .L801DA6BC:
    /* 26BC 801DA6BC 026A070C */  jal        putchar
    /* 26C0 801DA6C0 20000424 */   addiu     $a0, $zero, 0x20
    /* 26C4 801DA6C4 5000A78F */  lw         $a3, 0x50($sp)
    /* 26C8 801DA6C8 01001026 */  addiu      $s0, $s0, 0x1
    /* 26CC 801DA6CC 2A100702 */  slt        $v0, $s0, $a3
    /* 26D0 801DA6D0 FAFF4014 */  bnez       $v0, .L801DA6BC
    /* 26D4 801DA6D4 00000000 */   nop
  .L801DA6D8:
    /* 26D8 801DA6D8 5000A38F */  lw         $v1, 0x50($sp)
    /* 26DC 801DA6DC 00000000 */  nop
    /* 26E0 801DA6E0 2A107500 */  slt        $v0, $v1, $s5
    /* 26E4 801DA6E4 02004010 */  beqz       $v0, .L801DA6F0
    /* 26E8 801DA6E8 00000000 */   nop
    /* 26EC 801DA6EC 2118A002 */  addu       $v1, $s5, $zero
  .L801DA6F0:
    /* 26F0 801DA6F0 3800A78F */  lw         $a3, 0x38($sp)
    /* 26F4 801DA6F4 00000000 */  nop
    /* 26F8 801DA6F8 2138E300 */  addu       $a3, $a3, $v1
    /* 26FC 801DA6FC C7690708 */  j          .L801DA71C
    /* 2700 801DA700 3800A7AF */   sw        $a3, 0x38($sp)
  jlabel .L801DA704
    /* 2704 801DA704 3800A78F */  lw         $a3, 0x38($sp)
    /* 2708 801DA708 0000E492 */  lbu        $a0, 0x0($s7)
    /* 270C 801DA70C 0100E724 */  addiu      $a3, $a3, 0x1
    /* 2710 801DA710 3800A7AF */  sw         $a3, 0x38($sp)
  .L801DA714:
    /* 2714 801DA714 026A070C */  jal        putchar
    /* 2718 801DA718 00000000 */   nop
  .L801DA71C:
    /* 271C 801DA71C 48680708 */  j          .L801DA120
    /* 2720 801DA720 0100F726 */   addiu     $s7, $s7, 0x1
  .L801DA724:
    /* 2724 801DA724 8400BF8F */  lw         $ra, 0x84($sp)
    /* 2728 801DA728 8000BE8F */  lw         $fp, 0x80($sp)
    /* 272C 801DA72C 7C00B78F */  lw         $s7, 0x7C($sp)
    /* 2730 801DA730 7800B68F */  lw         $s6, 0x78($sp)
    /* 2734 801DA734 7400B58F */  lw         $s5, 0x74($sp)
    /* 2738 801DA738 7000B48F */  lw         $s4, 0x70($sp)
    /* 273C 801DA73C 6C00B38F */  lw         $s3, 0x6C($sp)
    /* 2740 801DA740 6800B28F */  lw         $s2, 0x68($sp)
    /* 2744 801DA744 6400B18F */  lw         $s1, 0x64($sp)
    /* 2748 801DA748 6000B08F */  lw         $s0, 0x60($sp)
    /* 274C 801DA74C 8800BD27 */  addiu      $sp, $sp, 0x88
    /* 2750 801DA750 0800E003 */  jr         $ra
    /* 2754 801DA754 00000000 */   nop
endlabel prnt
