.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching setjmp, 0x3C

glabel setjmp
    /* B7A4 801E37A4 00009FAC */  sw         $ra, 0x0($a0)
    /* B7A8 801E37A8 2C009CAC */  sw         $gp, 0x2C($a0)
    /* B7AC 801E37AC 04009DAC */  sw         $sp, 0x4($a0)
    /* B7B0 801E37B0 08009EAC */  sw         $fp, 0x8($a0)
    /* B7B4 801E37B4 0C0090AC */  sw         $s0, 0xC($a0)
    /* B7B8 801E37B8 100091AC */  sw         $s1, 0x10($a0)
    /* B7BC 801E37BC 140092AC */  sw         $s2, 0x14($a0)
    /* B7C0 801E37C0 180093AC */  sw         $s3, 0x18($a0)
    /* B7C4 801E37C4 1C0094AC */  sw         $s4, 0x1C($a0)
    /* B7C8 801E37C8 200095AC */  sw         $s5, 0x20($a0)
    /* B7CC 801E37CC 240096AC */  sw         $s6, 0x24($a0)
    /* B7D0 801E37D0 280097AC */  sw         $s7, 0x28($a0)
    /* B7D4 801E37D4 21100000 */  addu       $v0, $zero, $zero
    /* B7D8 801E37D8 0800E003 */  jr         $ra
    /* B7DC 801E37DC 00000000 */   nop
endlabel setjmp

nonmatching longjmp, 0x3C

glabel longjmp
    /* B7E0 801E37E0 00009F8C */  lw         $ra, 0x0($a0)
    /* B7E4 801E37E4 2C009C8C */  lw         $gp, 0x2C($a0)
    /* B7E8 801E37E8 04009D8C */  lw         $sp, 0x4($a0)
    /* B7EC 801E37EC 08009E8C */  lw         $fp, 0x8($a0)
    /* B7F0 801E37F0 0C00908C */  lw         $s0, 0xC($a0)
    /* B7F4 801E37F4 1000918C */  lw         $s1, 0x10($a0)
    /* B7F8 801E37F8 1400928C */  lw         $s2, 0x14($a0)
    /* B7FC 801E37FC 1800938C */  lw         $s3, 0x18($a0)
    /* B800 801E3800 1C00948C */  lw         $s4, 0x1C($a0)
    /* B804 801E3804 2000958C */  lw         $s5, 0x20($a0)
    /* B808 801E3808 2400968C */  lw         $s6, 0x24($a0)
    /* B80C 801E380C 2800978C */  lw         $s7, 0x28($a0)
    /* B810 801E3810 2110A000 */  addu       $v0, $a1, $zero
    /* B814 801E3814 0800E003 */  jr         $ra
    /* B818 801E3818 00000000 */   nop
endlabel longjmp
    /* B81C 801E381C 00000000 */  nop
    /* B820 801E3820 00000000 */  nop
