.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching printf, 0x3C

glabel printf
    /* 2094 801DA094 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2098 801DA098 21108000 */  addu       $v0, $a0, $zero
    /* 209C 801DA09C 01000424 */  addiu      $a0, $zero, 0x1
    /* 20A0 801DA0A0 1C00A5AF */  sw         $a1, 0x1C($sp)
    /* 20A4 801DA0A4 21284000 */  addu       $a1, $v0, $zero
    /* 20A8 801DA0A8 2000A6AF */  sw         $a2, 0x20($sp)
    /* 20AC 801DA0AC 1C00A627 */  addiu      $a2, $sp, 0x1C
    /* 20B0 801DA0B0 1000BFAF */  sw         $ra, 0x10($sp)
    /* 20B4 801DA0B4 1800A2AF */  sw         $v0, 0x18($sp)
    /* 20B8 801DA0B8 3468070C */  jal        prnt
    /* 20BC 801DA0BC 2400A7AF */   sw        $a3, 0x24($sp)
    /* 20C0 801DA0C0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 20C4 801DA0C4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 20C8 801DA0C8 0800E003 */  jr         $ra
    /* 20CC 801DA0CC 00000000 */   nop
endlabel printf
