.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StGetNext, 0xC4

glabel StGetNext
    /* 9C14 801E1C14 21388000 */  addu       $a3, $a0, $zero
    /* 9C18 801E1C18 2080023C */  lui        $v0, %hi(D_801F8058)
    /* 9C1C 801E1C1C 5880428C */  lw         $v0, %lo(D_801F8058)($v0)
    /* 9C20 801E1C20 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 9C24 801E1C24 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 9C28 801E1C28 40110200 */  sll        $v0, $v0, 5
    /* 9C2C 801E1C2C 21306200 */  addu       $a2, $v1, $v0
    /* 9C30 801E1C30 0000C294 */  lhu        $v0, 0x0($a2)
    /* 9C34 801E1C34 01000324 */  addiu      $v1, $zero, 0x1
    /* 9C38 801E1C38 FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 9C3C 801E1C3C 0E004314 */  bne        $v0, $v1, .L801E1C78
    /* 9C40 801E1C40 2140A000 */   addu      $t0, $a1, $zero
    /* 9C44 801E1C44 2080023C */  lui        $v0, %hi(D_801F8060)
    /* 9C48 801E1C48 6080428C */  lw         $v0, %lo(D_801F8060)($v0)
    /* 9C4C 801E1C4C 2080013C */  lui        $at, %hi(D_801F8058)
    /* 9C50 801E1C50 588020AC */  sw         $zero, %lo(D_801F8058)($at)
    /* 9C54 801E1C54 02004010 */  beqz       $v0, .L801E1C60
    /* 9C58 801E1C58 00000000 */   nop
    /* 9C5C 801E1C5C 0000C0A4 */  sh         $zero, 0x0($a2)
  .L801E1C60:
    /* 9C60 801E1C60 2080023C */  lui        $v0, %hi(D_801F8058)
    /* 9C64 801E1C64 5880428C */  lw         $v0, %lo(D_801F8058)($v0)
    /* 9C68 801E1C68 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 9C6C 801E1C6C 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 9C70 801E1C70 40110200 */  sll        $v0, $v0, 5
    /* 9C74 801E1C74 21306200 */  addu       $a2, $v1, $v0
  .L801E1C78:
    /* 9C78 801E1C78 0000C294 */  lhu        $v0, 0x0($a2)
    /* 9C7C 801E1C7C 02000324 */  addiu      $v1, $zero, 0x2
    /* 9C80 801E1C80 FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 9C84 801E1C84 12004314 */  bne        $v0, $v1, .L801E1CD0
    /* 9C88 801E1C88 01000224 */   addiu     $v0, $zero, 0x1
    /* 9C8C 801E1C8C 04000224 */  addiu      $v0, $zero, 0x4
    /* 9C90 801E1C90 0000C2A4 */  sh         $v0, 0x0($a2)
    /* 9C94 801E1C94 21100000 */  addu       $v0, $zero, $zero
    /* 9C98 801E1C98 2080033C */  lui        $v1, %hi(D_801F8070)
    /* 9C9C 801E1C9C 7080638C */  lw         $v1, %lo(D_801F8070)($v1)
    /* 9CA0 801E1CA0 2080043C */  lui        $a0, %hi(D_801F806C)
    /* 9CA4 801E1CA4 6C80848C */  lw         $a0, %lo(D_801F806C)($a0)
    /* 9CA8 801E1CA8 2080053C */  lui        $a1, %hi(D_801F8058)
    /* 9CAC 801E1CAC 5880A58C */  lw         $a1, %lo(D_801F8058)($a1)
    /* 9CB0 801E1CB0 40190300 */  sll        $v1, $v1, 5
    /* 9CB4 801E1CB4 21208300 */  addu       $a0, $a0, $v1
    /* 9CB8 801E1CB8 80190500 */  sll        $v1, $a1, 6
    /* 9CBC 801E1CBC 23186500 */  subu       $v1, $v1, $a1
    /* 9CC0 801E1CC0 40190300 */  sll        $v1, $v1, 5
    /* 9CC4 801E1CC4 21208300 */  addu       $a0, $a0, $v1
    /* 9CC8 801E1CC8 0000E4AC */  sw         $a0, 0x0($a3)
    /* 9CCC 801E1CCC 000006AD */  sw         $a2, 0x0($t0)
  .L801E1CD0:
    /* 9CD0 801E1CD0 0800E003 */  jr         $ra
    /* 9CD4 801E1CD4 00000000 */   nop
endlabel StGetNext
