.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching data_ready_callback, 0x90

glabel data_ready_callback
    /* 99A8 801E19A8 2080023C */  lui        $v0, %hi(D_801F8054)
    /* 99AC 801E19AC 5480428C */  lw         $v0, %lo(D_801F8054)($v0)
    /* 99B0 801E19B0 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 99B4 801E19B4 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 99B8 801E19B8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 99BC 801E19BC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 99C0 801E19C0 40110200 */  sll        $v0, $v0, 5
    /* 99C4 801E19C4 21186200 */  addu       $v1, $v1, $v0
    /* 99C8 801E19C8 02000224 */  addiu      $v0, $zero, 0x2
    /* 99CC 801E19CC 000062A4 */  sh         $v0, 0x0($v1)
    /* 99D0 801E19D0 1F80063C */  lui        $a2, %hi(D_801F67A8)
    /* 99D4 801E19D4 A867C624 */  addiu      $a2, $a2, %lo(D_801F67A8)
    /* 99D8 801E19D8 1F006288 */  lwl        $v0, 0x1F($v1)
    /* 99DC 801E19DC 1C006298 */  lwr        $v0, 0x1C($v1)
    /* 99E0 801E19E0 00000000 */  nop
    /* 99E4 801E19E4 0300C2A8 */  swl        $v0, 0x3($a2)
    /* 99E8 801E19E8 0000C2B8 */  swr        $v0, 0x0($a2)
    /* 99EC 801E19EC 0800628C */  lw         $v0, 0x8($v1)
    /* 99F0 801E19F0 2080033C */  lui        $v1, %hi(D_801F8050)
    /* 99F4 801E19F4 5080638C */  lw         $v1, %lo(D_801F8050)($v1)
    /* 99F8 801E19F8 1F80043C */  lui        $a0, %hi(D_801F67E0)
    /* 99FC 801E19FC E067848C */  lw         $a0, %lo(D_801F67E0)($a0)
    /* 9A00 801E1A00 1F80013C */  lui        $at, %hi(D_801F67AC)
    /* 9A04 801E1A04 AC6722AC */  sw         $v0, %lo(D_801F67AC)($at)
    /* 9A08 801E1A08 2080013C */  lui        $at, %hi(D_801F8054)
    /* 9A0C 801E1A0C 548023AC */  sw         $v1, %lo(D_801F8054)($at)
    /* 9A10 801E1A10 03008010 */  beqz       $a0, .L801E1A20
    /* 9A14 801E1A14 00000000 */   nop
    /* 9A18 801E1A18 09F88000 */  jalr       $a0
    /* 9A1C 801E1A1C 00000000 */   nop
  .L801E1A20:
    /* 9A20 801E1A20 1F80013C */  lui        $at, %hi(D_801F67FC)
    /* 9A24 801E1A24 FC6720AC */  sw         $zero, %lo(D_801F67FC)($at)
    /* 9A28 801E1A28 1000BF8F */  lw         $ra, 0x10($sp)
    /* 9A2C 801E1A2C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 9A30 801E1A30 0800E003 */  jr         $ra
    /* 9A34 801E1A34 00000000 */   nop
endlabel data_ready_callback

nonmatching StGetBackloc, 0x60

glabel StGetBackloc
    /* 9A38 801E1A38 1F80023C */  lui        $v0, %hi(D_801F67DC)
    /* 9A3C 801E1A3C DC67428C */  lw         $v0, %lo(D_801F67DC)($v0)
    /* 9A40 801E1A40 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 9A44 801E1A44 1000B0AF */  sw         $s0, 0x10($sp)
    /* 9A48 801E1A48 21808000 */  addu       $s0, $a0, $zero
    /* 9A4C 801E1A4C 0C004014 */  bnez       $v0, .L801E1A80
    /* 9A50 801E1A50 1400BFAF */   sw        $ra, 0x14($sp)
    /* 9A54 801E1A54 1F80043C */  lui        $a0, %hi(D_801F67A8)
    /* 9A58 801E1A58 A8678424 */  addiu      $a0, $a0, %lo(D_801F67A8)
    /* 9A5C 801E1A5C B37D070C */  jal        CdPosToInt
    /* 9A60 801E1A60 00000000 */   nop
    /* 9A64 801E1A64 01004424 */  addiu      $a0, $v0, 0x1
    /* 9A68 801E1A68 727D070C */  jal        CdIntToPos
    /* 9A6C 801E1A6C 21280002 */   addu      $a1, $s0, $zero
    /* 9A70 801E1A70 1F80023C */  lui        $v0, %hi(D_801F67AC)
    /* 9A74 801E1A74 AC67428C */  lw         $v0, %lo(D_801F67AC)($v0)
    /* 9A78 801E1A78 A1860708 */  j          .L801E1A84
    /* 9A7C 801E1A7C 00000000 */   nop
  .L801E1A80:
    /* 9A80 801E1A80 FFFF0224 */  addiu      $v0, $zero, -0x1
  .L801E1A84:
    /* 9A84 801E1A84 1400BF8F */  lw         $ra, 0x14($sp)
    /* 9A88 801E1A88 1000B08F */  lw         $s0, 0x10($sp)
    /* 9A8C 801E1A8C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 9A90 801E1A90 0800E003 */  jr         $ra
    /* 9A94 801E1A94 00000000 */   nop
endlabel StGetBackloc
