.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StCdInterrupt, 0x970

glabel StCdInterrupt
    /* 9CF8 801E1CF8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 9CFC 801E1CFC 1F80023C */  lui        $v0, %hi(D_801F67FC)
    /* 9D00 801E1D00 FC67428C */  lw         $v0, %lo(D_801F67FC)($v0)
    /* 9D04 801E1D04 01000424 */  addiu      $a0, $zero, 0x1
    /* 9D08 801E1D08 53024410 */  beq        $v0, $a0, .L801E2658
    /* 9D0C 801E1D0C 3800BFAF */   sw        $ra, 0x38($sp)
    /* 9D10 801E1D10 1F80023C */  lui        $v0, %hi(D_801F67D8)
    /* 9D14 801E1D14 D867428C */  lw         $v0, %lo(D_801F67D8)($v0)
    /* 9D18 801E1D18 00000000 */  nop
    /* 9D1C 801E1D1C 19004010 */  beqz       $v0, .L801E1D84
    /* 9D20 801E1D20 00000000 */   nop
    /* 9D24 801E1D24 1F80023C */  lui        $v0, %hi(D_801F5434)
    /* 9D28 801E1D28 3454428C */  lw         $v0, %lo(D_801F5434)($v0)
    /* 9D2C 801E1D2C 00000000 */  nop
    /* 9D30 801E1D30 0000428C */  lw         $v0, 0x0($v0)
    /* 9D34 801E1D34 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 9D38 801E1D38 24104300 */  and        $v0, $v0, $v1
    /* 9D3C 801E1D3C 11004010 */  beqz       $v0, .L801E1D84
    /* 9D40 801E1D40 00000000 */   nop
    /* 9D44 801E1D44 2080023C */  lui        $v0, %hi(D_801F805C)
    /* 9D48 801E1D48 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* 9D4C 801E1D4C 1F80013C */  lui        $at, %hi(D_801F67E8)
    /* 9D50 801E1D50 E86724AC */  sw         $a0, %lo(D_801F67E8)($at)
    /* 9D54 801E1D54 07004010 */  beqz       $v0, .L801E1D74
    /* 9D58 801E1D58 00000000 */   nop
    /* 9D5C 801E1D5C 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* 9D60 801E1D60 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* 9D64 801E1D64 00000000 */  nop
    /* 9D68 801E1D68 01004224 */  addiu      $v0, $v0, 0x1
    /* 9D6C 801E1D6C 1F80013C */  lui        $at, %hi(D_801F6848)
    /* 9D70 801E1D70 486822AC */  sw         $v0, %lo(D_801F6848)($at)
  .L801E1D74:
    /* 9D74 801E1D74 1F80013C */  lui        $at, %hi(D_801F545C)
    /* 9D78 801E1D78 5C5424AC */  sw         $a0, %lo(D_801F545C)($at)
    /* 9D7C 801E1D7C 96890708 */  j          .L801E2658
    /* 9D80 801E1D80 00000000 */   nop
  .L801E1D84:
    /* 9D84 801E1D84 4B7C070C */  jal        CdReady
    /* 9D88 801E1D88 3000A527 */   addiu     $a1, $sp, 0x30
    /* 9D8C 801E1D8C 05000324 */  addiu      $v1, $zero, 0x5
    /* 9D90 801E1D90 31024310 */  beq        $v0, $v1, .L801E2658
    /* 9D94 801E1D94 00000000 */   nop
    /* 9D98 801E1D98 3000A293 */  lbu        $v0, 0x30($sp)
    /* 9D9C 801E1D9C 3100A393 */  lbu        $v1, 0x31($sp)
    /* 9DA0 801E1DA0 2200A2A7 */  sh         $v0, 0x22($sp)
    /* 9DA4 801E1DA4 2400A3A7 */  sh         $v1, 0x24($sp)
    /* 9DA8 801E1DA8 2200A297 */  lhu        $v0, 0x22($sp)
    /* 9DAC 801E1DAC 00000000 */  nop
    /* 9DB0 801E1DB0 04004230 */  andi       $v0, $v0, 0x4
    /* 9DB4 801E1DB4 05004010 */  beqz       $v0, .L801E1DCC
    /* 9DB8 801E1DB8 03000224 */   addiu     $v0, $zero, 0x3
    /* 9DBC 801E1DBC 1F80013C */  lui        $at, %hi(D_801F545C)
    /* 9DC0 801E1DC0 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* 9DC4 801E1DC4 96890708 */  j          .L801E2658
    /* 9DC8 801E1DC8 00000000 */   nop
  .L801E1DCC:
    /* 9DCC 801E1DCC 2080023C */  lui        $v0, %hi(D_801F8050)
    /* 9DD0 801E1DD0 5080428C */  lw         $v0, %lo(D_801F8050)($v0)
    /* 9DD4 801E1DD4 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 9DD8 801E1DD8 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 9DDC 801E1DDC 40110200 */  sll        $v0, $v0, 5
    /* 9DE0 801E1DE0 21186200 */  addu       $v1, $v1, $v0
    /* 9DE4 801E1DE4 1F80013C */  lui        $at, %hi(D_801F67B0)
    /* 9DE8 801E1DE8 B06723AC */  sw         $v1, %lo(D_801F67B0)($at)
    /* 9DEC 801E1DEC 00006294 */  lhu        $v0, 0x0($v1)
    /* 9DF0 801E1DF0 00000000 */  nop
    /* 9DF4 801E1DF4 11004010 */  beqz       $v0, .L801E1E3C
    /* 9DF8 801E1DF8 00000000 */   nop
    /* 9DFC 801E1DFC 2080023C */  lui        $v0, %hi(D_801F805C)
    /* 9E00 801E1E00 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* 9E04 801E1E04 00000000 */  nop
    /* 9E08 801E1E08 08004010 */  beqz       $v0, .L801E1E2C
    /* 9E0C 801E1E0C 04000224 */   addiu     $v0, $zero, 0x4
    /* 9E10 801E1E10 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* 9E14 801E1E14 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* 9E18 801E1E18 00000000 */  nop
    /* 9E1C 801E1E1C 01004224 */  addiu      $v0, $v0, 0x1
    /* 9E20 801E1E20 1F80013C */  lui        $at, %hi(D_801F6848)
    /* 9E24 801E1E24 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* 9E28 801E1E28 04000224 */  addiu      $v0, $zero, 0x4
  .L801E1E2C:
    /* 9E2C 801E1E2C 1F80013C */  lui        $at, %hi(D_801F545C)
    /* 9E30 801E1E30 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* 9E34 801E1E34 96890708 */  j          .L801E2658
    /* 9E38 801E1E38 00000000 */   nop
  .L801E1E3C:
    /* 9E3C 801E1E3C 1F80023C */  lui        $v0, %hi(D_801F5414)
    /* 9E40 801E1E40 1454428C */  lw         $v0, %lo(D_801F5414)($v0)
    /* 9E44 801E1E44 00000000 */  nop
    /* 9E48 801E1E48 000040A0 */  sb         $zero, 0x0($v0)
    /* 9E4C 801E1E4C 1F80023C */  lui        $v0, %hi(D_801F5420)
    /* 9E50 801E1E50 2054428C */  lw         $v0, %lo(D_801F5420)($v0)
    /* 9E54 801E1E54 00000000 */  nop
    /* 9E58 801E1E58 000040A0 */  sb         $zero, 0x0($v0)
    /* 9E5C 801E1E5C 1F80023C */  lui        $v0, %hi(D_801F5414)
    /* 9E60 801E1E60 1454428C */  lw         $v0, %lo(D_801F5414)($v0)
    /* 9E64 801E1E64 0200043C */  lui        $a0, (0x20943 >> 16)
    /* 9E68 801E1E68 000040A0 */  sb         $zero, 0x0($v0)
    /* 9E6C 801E1E6C 1F80033C */  lui        $v1, %hi(D_801F5420)
    /* 9E70 801E1E70 2054638C */  lw         $v1, %lo(D_801F5420)($v1)
    /* 9E74 801E1E74 80000224 */  addiu      $v0, $zero, 0x80
    /* 9E78 801E1E78 000062A0 */  sb         $v0, 0x0($v1)
    /* 9E7C 801E1E7C 1F80023C */  lui        $v0, %hi(D_801F5424)
    /* 9E80 801E1E80 2454428C */  lw         $v0, %lo(D_801F5424)($v0)
    /* 9E84 801E1E84 43098434 */  ori        $a0, $a0, (0x20943 & 0xFFFF)
    /* 9E88 801E1E88 000044AC */  sw         $a0, 0x0($v0)
    /* 9E8C 801E1E8C 1F80033C */  lui        $v1, %hi(D_801F5428)
    /* 9E90 801E1E90 2854638C */  lw         $v1, %lo(D_801F5428)($v1)
    /* 9E94 801E1E94 23130224 */  addiu      $v0, $zero, 0x1323
    /* 9E98 801E1E98 000062AC */  sw         $v0, 0x0($v1)
    /* 9E9C 801E1E9C 1F80023C */  lui        $v0, %hi(D_801F67DC)
    /* 9EA0 801E1EA0 DC67428C */  lw         $v0, %lo(D_801F67DC)($v0)
    /* 9EA4 801E1EA4 00000000 */  nop
    /* 9EA8 801E1EA8 16004014 */  bnez       $v0, .L801E1F04
    /* 9EAC 801E1EAC 00000000 */   nop
    /* 9EB0 801E1EB0 2800A327 */  addiu      $v1, $sp, 0x28
    /* 9EB4 801E1EB4 2C00A427 */  addiu      $a0, $sp, 0x2C
  .L801E1EB8:
    /* 9EB8 801E1EB8 1F80023C */  lui        $v0, %hi(D_801F541C)
    /* 9EBC 801E1EBC 1C54428C */  lw         $v0, %lo(D_801F541C)($v0)
    /* 9EC0 801E1EC0 00000000 */  nop
    /* 9EC4 801E1EC4 00004290 */  lbu        $v0, 0x0($v0)
    /* 9EC8 801E1EC8 00000000 */  nop
    /* 9ECC 801E1ECC 000062A0 */  sb         $v0, 0x0($v1)
    /* 9ED0 801E1ED0 01006324 */  addiu      $v1, $v1, 0x1
    /* 9ED4 801E1ED4 2B106400 */  sltu       $v0, $v1, $a0
    /* 9ED8 801E1ED8 F7FF4014 */  bnez       $v0, .L801E1EB8
    /* 9EDC 801E1EDC 00000000 */   nop
    /* 9EE0 801E1EE0 21180000 */  addu       $v1, $zero, $zero
    /* 9EE4 801E1EE4 1F80043C */  lui        $a0, %hi(D_801F541C)
    /* 9EE8 801E1EE8 1C54848C */  lw         $a0, %lo(D_801F541C)($a0)
  .L801E1EEC:
    /* 9EEC 801E1EEC 00000000 */  nop
    /* 9EF0 801E1EF0 00008290 */  lbu        $v0, 0x0($a0)
    /* 9EF4 801E1EF4 01006324 */  addiu      $v1, $v1, 0x1
    /* 9EF8 801E1EF8 0800622C */  sltiu      $v0, $v1, 0x8
    /* 9EFC 801E1EFC FBFF4014 */  bnez       $v0, .L801E1EEC
    /* 9F00 801E1F00 00000000 */   nop
  .L801E1F04:
    /* 9F04 801E1F04 2080023C */  lui        $v0, %hi(D_801F805C)
    /* 9F08 801E1F08 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* 9F0C 801E1F0C 00000000 */  nop
    /* 9F10 801E1F10 0C004010 */  beqz       $v0, .L801E1F44
    /* 9F14 801E1F14 0011083C */   lui       $t0, (0x11000000 >> 16)
    /* 9F18 801E1F18 08000624 */  addiu      $a2, $zero, 0x8
    /* 9F1C 801E1F1C 21380000 */  addu       $a3, $zero, $zero
    /* 9F20 801E1F20 1F80053C */  lui        $a1, %hi(D_801F6848)
    /* 9F24 801E1F24 4868A58C */  lw         $a1, %lo(D_801F6848)($a1)
    /* 9F28 801E1F28 1F80043C */  lui        $a0, %hi(D_801F67B0)
    /* 9F2C 801E1F2C B067848C */  lw         $a0, %lo(D_801F67B0)($a0)
    /* 9F30 801E1F30 C02A0500 */  sll        $a1, $a1, 11
    /* 9F34 801E1F34 9A89070C */  jal        mem2mem
    /* 9F38 801E1F38 21284500 */   addu      $a1, $v0, $a1
    /* 9F3C 801E1F3C DA870708 */  j          .L801E1F68
    /* 9F40 801E1F40 00000000 */   nop
  .L801E1F44:
    /* 9F44 801E1F44 03000424 */  addiu      $a0, $zero, 0x3
    /* 9F48 801E1F48 21300000 */  addu       $a2, $zero, $zero
    /* 9F4C 801E1F4C 1F80053C */  lui        $a1, %hi(D_801F67B0)
    /* 9F50 801E1F50 B067A58C */  lw         $a1, %lo(D_801F67B0)($a1)
    /* 9F54 801E1F54 08000724 */  addiu      $a3, $zero, 0x8
    /* 9F58 801E1F58 1000A8AF */  sw         $t0, 0x10($sp)
    /* 9F5C 801E1F5C 1400A0AF */  sw         $zero, 0x14($sp)
    /* 9F60 801E1F60 A789070C */  jal        dma_execute
    /* 9F64 801E1F64 1800A0AF */   sw        $zero, 0x18($sp)
  .L801E1F68:
    /* 9F68 801E1F68 1F80043C */  lui        $a0, %hi(D_801F5444)
    /* 9F6C 801E1F6C 4454848C */  lw         $a0, %lo(D_801F5444)($a0)
    /* 9F70 801E1F70 00000000 */  nop
    /* 9F74 801E1F74 0000828C */  lw         $v0, 0x0($a0)
    /* 9F78 801E1F78 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 9F7C 801E1F7C 24104300 */  and        $v0, $v0, $v1
    /* 9F80 801E1F80 07004010 */  beqz       $v0, .L801E1FA0
    /* 9F84 801E1F84 21188000 */   addu      $v1, $a0, $zero
    /* 9F88 801E1F88 0001043C */  lui        $a0, (0x1000000 >> 16)
  .L801E1F8C:
    /* 9F8C 801E1F8C 0000628C */  lw         $v0, 0x0($v1)
    /* 9F90 801E1F90 00000000 */  nop
    /* 9F94 801E1F94 24104400 */  and        $v0, $v0, $a0
    /* 9F98 801E1F98 FCFF4014 */  bnez       $v0, .L801E1F8C
    /* 9F9C 801E1F9C 00000000 */   nop
  .L801E1FA0:
    /* 9FA0 801E1FA0 1F80023C */  lui        $v0, %hi(D_801F67B0)
    /* 9FA4 801E1FA4 B067428C */  lw         $v0, %lo(D_801F67B0)($v0)
    /* 9FA8 801E1FA8 0200033C */  lui        $v1, (0x20843 >> 16)
    /* 9FAC 801E1FAC 2B00A48B */  lwl        $a0, 0x2B($sp)
    /* 9FB0 801E1FB0 2800A49B */  lwr        $a0, 0x28($sp)
    /* 9FB4 801E1FB4 00000000 */  nop
    /* 9FB8 801E1FB8 1F0044A8 */  swl        $a0, 0x1F($v0)
    /* 9FBC 801E1FBC 1C0044B8 */  swr        $a0, 0x1C($v0)
    /* 9FC0 801E1FC0 1F80023C */  lui        $v0, %hi(D_801F5424)
    /* 9FC4 801E1FC4 2454428C */  lw         $v0, %lo(D_801F5424)($v0)
    /* 9FC8 801E1FC8 43086334 */  ori        $v1, $v1, (0x20843 & 0xFFFF)
    /* 9FCC 801E1FCC 000043AC */  sw         $v1, 0x0($v0)
    /* 9FD0 801E1FD0 1F80033C */  lui        $v1, %hi(D_801F5428)
    /* 9FD4 801E1FD4 2854638C */  lw         $v1, %lo(D_801F5428)($v1)
    /* 9FD8 801E1FD8 25130224 */  addiu      $v0, $zero, 0x1325
    /* 9FDC 801E1FDC 000062AC */  sw         $v0, 0x0($v1)
    /* 9FE0 801E1FE0 2080033C */  lui        $v1, %hi(D_801F8064)
    /* 9FE4 801E1FE4 6480638C */  lw         $v1, %lo(D_801F8064)($v1)
    /* 9FE8 801E1FE8 01000224 */  addiu      $v0, $zero, 0x1
    /* 9FEC 801E1FEC 1D006214 */  bne        $v1, $v0, .L801E2064
    /* 9FF0 801E1FF0 00000000 */   nop
    /* 9FF4 801E1FF4 1F80043C */  lui        $a0, %hi(D_801F67F0)
    /* 9FF8 801E1FF8 F067848C */  lw         $a0, %lo(D_801F67F0)($a0)
    /* 9FFC 801E1FFC 00000000 */  nop
    /* A000 801E2000 18008010 */  beqz       $a0, .L801E2064
    /* A004 801E2004 00000000 */   nop
    /* A008 801E2008 1F80033C */  lui        $v1, %hi(D_801F67B0)
    /* A00C 801E200C B067638C */  lw         $v1, %lo(D_801F67B0)($v1)
    /* A010 801E2010 00000000 */  nop
    /* A014 801E2014 08006294 */  lhu        $v0, 0x8($v1)
    /* A018 801E2018 00000000 */  nop
    /* A01C 801E201C 0F008210 */  beq        $a0, $v0, .L801E205C
    /* A020 801E2020 00000000 */   nop
    /* A024 801E2024 000060A4 */  sh         $zero, 0x0($v1)
    /* A028 801E2028 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A02C 801E202C 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A030 801E2030 00000000 */  nop
    /* A034 801E2034 88014010 */  beqz       $v0, .L801E2658
    /* A038 801E2038 00000000 */   nop
    /* A03C 801E203C 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A040 801E2040 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A044 801E2044 00000000 */  nop
    /* A048 801E2048 01004224 */  addiu      $v0, $v0, 0x1
    /* A04C 801E204C 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A050 801E2050 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A054 801E2054 96890708 */  j          .L801E2658
    /* A058 801E2058 00000000 */   nop
  .L801E205C:
    /* A05C 801E205C 2080013C */  lui        $at, %hi(D_801F8064)
    /* A060 801E2060 648020AC */  sw         $zero, %lo(D_801F8064)($at)
  .L801E2064:
    /* A064 801E2064 1F80043C */  lui        $a0, %hi(D_801F67B0)
    /* A068 801E2068 B067848C */  lw         $a0, %lo(D_801F67B0)($a0)
    /* A06C 801E206C 00000000 */  nop
    /* A070 801E2070 00008294 */  lhu        $v0, 0x0($a0)
    /* A074 801E2074 60010324 */  addiu      $v1, $zero, 0x160
    /* A078 801E2078 FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* A07C 801E207C 08004314 */  bne        $v0, $v1, .L801E20A0
    /* A080 801E2080 00000000 */   nop
    /* A084 801E2084 02008294 */  lhu        $v0, 0x2($a0)
    /* A088 801E2088 1F80033C */  lui        $v1, %hi(D_801F67F4)
    /* A08C 801E208C F467638C */  lw         $v1, %lo(D_801F67F4)($v1)
    /* A090 801E2090 82120200 */  srl        $v0, $v0, 10
    /* A094 801E2094 1F004230 */  andi       $v0, $v0, 0x1F
    /* A098 801E2098 13004310 */  beq        $v0, $v1, .L801E20E8
    /* A09C 801E209C 00000000 */   nop
  .L801E20A0:
    /* A0A0 801E20A0 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A0A4 801E20A4 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A0A8 801E20A8 00000000 */  nop
    /* A0AC 801E20AC 05004010 */  beqz       $v0, .L801E20C4
    /* A0B0 801E20B0 00000000 */   nop
    /* A0B4 801E20B4 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A0B8 801E20B8 486820AC */  sw         $zero, %lo(D_801F6848)($at)
    /* A0BC 801E20BC 32880708 */  j          .L801E20C8
    /* A0C0 801E20C0 00000000 */   nop
  .L801E20C4:
    /* A0C4 801E20C4 00008294 */  lhu        $v0, 0x0($a0)
  .L801E20C8:
    /* A0C8 801E20C8 1F80033C */  lui        $v1, %hi(D_801F67B0)
    /* A0CC 801E20CC B067638C */  lw         $v1, %lo(D_801F67B0)($v1)
    /* A0D0 801E20D0 05000224 */  addiu      $v0, $zero, 0x5
    /* A0D4 801E20D4 1F80013C */  lui        $at, %hi(D_801F545C)
    /* A0D8 801E20D8 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* A0DC 801E20DC 000060A4 */  sh         $zero, 0x0($v1)
    /* A0E0 801E20E0 96890708 */  j          .L801E2658
    /* A0E4 801E20E4 00000000 */   nop
  .L801E20E8:
    /* A0E8 801E20E8 1F80033C */  lui        $v1, %hi(D_801F67D4)
    /* A0EC 801E20EC D4676384 */  lh         $v1, %lo(D_801F67D4)($v1)
    /* A0F0 801E20F0 04008294 */  lhu        $v0, 0x4($a0)
    /* A0F4 801E20F4 00000000 */  nop
    /* A0F8 801E20F8 0A006214 */  bne        $v1, $v0, .L801E2124
    /* A0FC 801E20FC 00000000 */   nop
    /* A100 801E2100 1F80033C */  lui        $v1, %hi(D_801F67D0)
    /* A104 801E2104 D067638C */  lw         $v1, %lo(D_801F67D0)($v1)
    /* A108 801E2108 00000000 */  nop
    /* A10C 801E210C 26006010 */  beqz       $v1, .L801E21A8
    /* A110 801E2110 00000000 */   nop
    /* A114 801E2114 08008294 */  lhu        $v0, 0x8($a0)
    /* A118 801E2118 00000000 */  nop
    /* A11C 801E211C 22006210 */  beq        $v1, $v0, .L801E21A8
    /* A120 801E2120 00000000 */   nop
  .L801E2124:
    /* A124 801E2124 2080043C */  lui        $a0, %hi(D_801F8054)
    /* A128 801E2128 5480848C */  lw         $a0, %lo(D_801F8054)($a0)
    /* A12C 801E212C 2080053C */  lui        $a1, %hi(D_801F8050)
    /* A130 801E2130 5080A58C */  lw         $a1, %lo(D_801F8050)($a1)
    /* A134 801E2134 1F80013C */  lui        $at, %hi(D_801F67D0)
    /* A138 801E2138 D06720AC */  sw         $zero, %lo(D_801F67D0)($at)
    /* A13C 801E213C 1F80013C */  lui        $at, %hi(D_801F67D4)
    /* A140 801E2140 D46720A4 */  sh         $zero, %lo(D_801F67D4)($at)
    /* A144 801E2144 F686070C */  jal        init_ring_status
    /* A148 801E2148 2328A400 */   subu      $a1, $a1, $a0
    /* A14C 801E214C 2080023C */  lui        $v0, %hi(D_801F8054)
    /* A150 801E2150 5480428C */  lw         $v0, %lo(D_801F8054)($v0)
    /* A154 801E2154 1F80033C */  lui        $v1, %hi(D_801F67B0)
    /* A158 801E2158 B067638C */  lw         $v1, %lo(D_801F67B0)($v1)
    /* A15C 801E215C 2080013C */  lui        $at, %hi(D_801F8050)
    /* A160 801E2160 508022AC */  sw         $v0, %lo(D_801F8050)($at)
    /* A164 801E2164 000060A4 */  sh         $zero, 0x0($v1)
    /* A168 801E2168 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A16C 801E216C 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A170 801E2170 00000000 */  nop
    /* A174 801E2174 08004010 */  beqz       $v0, .L801E2198
    /* A178 801E2178 06000224 */   addiu     $v0, $zero, 0x6
    /* A17C 801E217C 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A180 801E2180 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A184 801E2184 00000000 */  nop
    /* A188 801E2188 01004224 */  addiu      $v0, $v0, 0x1
    /* A18C 801E218C 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A190 801E2190 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A194 801E2194 06000224 */  addiu      $v0, $zero, 0x6
  .L801E2198:
    /* A198 801E2198 1F80013C */  lui        $at, %hi(D_801F545C)
    /* A19C 801E219C 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* A1A0 801E21A0 96890708 */  j          .L801E2658
    /* A1A4 801E21A4 00000000 */   nop
  .L801E21A8:
    /* A1A8 801E21A8 1F80033C */  lui        $v1, %hi(D_801F67B0)
    /* A1AC 801E21AC B067638C */  lw         $v1, %lo(D_801F67B0)($v1)
    /* A1B0 801E21B0 00000000 */  nop
    /* A1B4 801E21B4 04006294 */  lhu        $v0, 0x4($v1)
    /* A1B8 801E21B8 00000000 */  nop
    /* A1BC 801E21BC 92004014 */  bnez       $v0, .L801E2408
    /* A1C0 801E21C0 0A000224 */   addiu     $v0, $zero, 0xA
    /* A1C4 801E21C4 08006294 */  lhu        $v0, 0x8($v1)
    /* A1C8 801E21C8 2080033C */  lui        $v1, %hi(D_801F8060)
    /* A1CC 801E21CC 6080638C */  lw         $v1, %lo(D_801F8060)($v1)
    /* A1D0 801E21D0 1F80013C */  lui        $at, %hi(D_801F67D4)
    /* A1D4 801E21D4 D46720A4 */  sh         $zero, %lo(D_801F67D4)($at)
    /* A1D8 801E21D8 FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* A1DC 801E21DC 1F80013C */  lui        $at, %hi(D_801F67D0)
    /* A1E0 801E21E0 D06722AC */  sw         $v0, %lo(D_801F67D0)($at)
    /* A1E4 801E21E4 2D006010 */  beqz       $v1, .L801E229C
    /* A1E8 801E21E8 2B104300 */   sltu      $v0, $v0, $v1
    /* A1EC 801E21EC 2B004014 */  bnez       $v0, .L801E229C
    /* A1F0 801E21F0 00000000 */   nop
    /* A1F4 801E21F4 2080043C */  lui        $a0, %hi(D_801F8054)
    /* A1F8 801E21F8 5480848C */  lw         $a0, %lo(D_801F8054)($a0)
    /* A1FC 801E21FC 2080053C */  lui        $a1, %hi(D_801F8050)
    /* A200 801E2200 5080A58C */  lw         $a1, %lo(D_801F8050)($a1)
    /* A204 801E2204 1F80013C */  lui        $at, %hi(D_801F67D0)
    /* A208 801E2208 D06720AC */  sw         $zero, %lo(D_801F67D0)($at)
    /* A20C 801E220C 1F80013C */  lui        $at, %hi(D_801F67D4)
    /* A210 801E2210 D46720A4 */  sh         $zero, %lo(D_801F67D4)($at)
    /* A214 801E2214 F686070C */  jal        init_ring_status
    /* A218 801E2218 2328A400 */   subu      $a1, $a1, $a0
    /* A21C 801E221C 2080023C */  lui        $v0, %hi(D_801F8054)
    /* A220 801E2220 5480428C */  lw         $v0, %lo(D_801F8054)($v0)
    /* A224 801E2224 1F80033C */  lui        $v1, %hi(D_801F67B0)
    /* A228 801E2228 B067638C */  lw         $v1, %lo(D_801F67B0)($v1)
    /* A22C 801E222C 2080013C */  lui        $at, %hi(D_801F8050)
    /* A230 801E2230 508022AC */  sw         $v0, %lo(D_801F8050)($at)
    /* A234 801E2234 000060A4 */  sh         $zero, 0x0($v1)
    /* A238 801E2238 1F80033C */  lui        $v1, %hi(D_801F67E4)
    /* A23C 801E223C E467638C */  lw         $v1, %lo(D_801F67E4)($v1)
    /* A240 801E2240 01000224 */  addiu      $v0, $zero, 0x1
    /* A244 801E2244 2080013C */  lui        $at, %hi(D_801F8064)
    /* A248 801E2248 648022AC */  sw         $v0, %lo(D_801F8064)($at)
    /* A24C 801E224C 03006010 */  beqz       $v1, .L801E225C
    /* A250 801E2250 00000000 */   nop
    /* A254 801E2254 09F86000 */  jalr       $v1
    /* A258 801E2258 00000000 */   nop
  .L801E225C:
    /* A25C 801E225C 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A260 801E2260 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A264 801E2264 00000000 */  nop
    /* A268 801E2268 08004010 */  beqz       $v0, .L801E228C
    /* A26C 801E226C 07000224 */   addiu     $v0, $zero, 0x7
    /* A270 801E2270 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A274 801E2274 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A278 801E2278 00000000 */  nop
    /* A27C 801E227C 01004224 */  addiu      $v0, $v0, 0x1
    /* A280 801E2280 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A284 801E2284 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A288 801E2288 07000224 */  addiu      $v0, $zero, 0x7
  .L801E228C:
    /* A28C 801E228C 1F80013C */  lui        $at, %hi(D_801F545C)
    /* A290 801E2290 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* A294 801E2294 96890708 */  j          .L801E2658
    /* A298 801E2298 00000000 */   nop
  .L801E229C:
    /* A29C 801E229C 2080023C */  lui        $v0, %hi(D_801F8070)
    /* A2A0 801E22A0 7080428C */  lw         $v0, %lo(D_801F8070)($v0)
    /* A2A4 801E22A4 2080033C */  lui        $v1, %hi(D_801F8050)
    /* A2A8 801E22A8 5080638C */  lw         $v1, %lo(D_801F8050)($v1)
    /* A2AC 801E22AC 1F80043C */  lui        $a0, %hi(D_801F67B0)
    /* A2B0 801E22B0 B067848C */  lw         $a0, %lo(D_801F67B0)($a0)
    /* A2B4 801E22B4 23104300 */  subu       $v0, $v0, $v1
    /* A2B8 801E22B8 06008394 */  lhu        $v1, 0x6($a0)
    /* A2BC 801E22BC FFFF4224 */  addiu      $v0, $v0, -0x1
    /* A2C0 801E22C0 2B104300 */  sltu       $v0, $v0, $v1
    /* A2C4 801E22C4 4B004010 */  beqz       $v0, .L801E23F4
    /* A2C8 801E22C8 00000000 */   nop
    /* A2CC 801E22CC 2080023C */  lui        $v0, %hi(D_801F8060)
    /* A2D0 801E22D0 6080428C */  lw         $v0, %lo(D_801F8060)($v0)
    /* A2D4 801E22D4 00000000 */  nop
    /* A2D8 801E22D8 1B004014 */  bnez       $v0, .L801E2348
    /* A2DC 801E22DC 01000224 */   addiu     $v0, $zero, 0x1
    /* A2E0 801E22E0 000082A4 */  sh         $v0, 0x0($a0)
    /* A2E4 801E22E4 1F80033C */  lui        $v1, %hi(D_801F67E4)
    /* A2E8 801E22E8 E467638C */  lw         $v1, %lo(D_801F67E4)($v1)
    /* A2EC 801E22EC 01000224 */  addiu      $v0, $zero, 0x1
    /* A2F0 801E22F0 2080013C */  lui        $at, %hi(D_801F8064)
    /* A2F4 801E22F4 648022AC */  sw         $v0, %lo(D_801F8064)($at)
    /* A2F8 801E22F8 03006010 */  beqz       $v1, .L801E2308
    /* A2FC 801E22FC 00000000 */   nop
    /* A300 801E2300 09F86000 */  jalr       $v1
    /* A304 801E2304 00000000 */   nop
  .L801E2308:
    /* A308 801E2308 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A30C 801E230C 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A310 801E2310 00000000 */  nop
    /* A314 801E2314 08004010 */  beqz       $v0, .L801E2338
    /* A318 801E2318 08000224 */   addiu     $v0, $zero, 0x8
    /* A31C 801E231C 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A320 801E2320 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A324 801E2324 00000000 */  nop
    /* A328 801E2328 01004224 */  addiu      $v0, $v0, 0x1
    /* A32C 801E232C 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A330 801E2330 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A334 801E2334 08000224 */  addiu      $v0, $zero, 0x8
  .L801E2338:
    /* A338 801E2338 1F80013C */  lui        $at, %hi(D_801F545C)
    /* A33C 801E233C 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* A340 801E2340 96890708 */  j          .L801E2658
    /* A344 801E2344 00000000 */   nop
  .L801E2348:
    /* A348 801E2348 2080023C */  lui        $v0, %hi(D_801F806C)
    /* A34C 801E234C 6C80428C */  lw         $v0, %lo(D_801F806C)($v0)
    /* A350 801E2350 00000000 */  nop
    /* A354 801E2354 00004284 */  lh         $v0, 0x0($v0)
    /* A358 801E2358 00000000 */  nop
    /* A35C 801E235C 12004010 */  beqz       $v0, .L801E23A8
    /* A360 801E2360 01000224 */   addiu     $v0, $zero, 0x1
    /* A364 801E2364 000080A4 */  sh         $zero, 0x0($a0)
    /* A368 801E2368 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A36C 801E236C 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A370 801E2370 00000000 */  nop
    /* A374 801E2374 08004010 */  beqz       $v0, .L801E2398
    /* A378 801E2378 09000224 */   addiu     $v0, $zero, 0x9
    /* A37C 801E237C 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A380 801E2380 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A384 801E2384 00000000 */  nop
    /* A388 801E2388 01004224 */  addiu      $v0, $v0, 0x1
    /* A38C 801E238C 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A390 801E2390 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A394 801E2394 09000224 */  addiu      $v0, $zero, 0x9
  .L801E2398:
    /* A398 801E2398 1F80013C */  lui        $at, %hi(D_801F545C)
    /* A39C 801E239C 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* A3A0 801E23A0 96890708 */  j          .L801E2658
    /* A3A4 801E23A4 00000000 */   nop
  .L801E23A8:
    /* A3A8 801E23A8 000082A4 */  sh         $v0, 0x0($a0)
    /* A3AC 801E23AC 2080053C */  lui        $a1, %hi(D_801F806C)
    /* A3B0 801E23B0 6C80A58C */  lw         $a1, %lo(D_801F806C)($a1)
    /* A3B4 801E23B4 1F80043C */  lui        $a0, %hi(D_801F67B0)
    /* A3B8 801E23B8 B067848C */  lw         $a0, %lo(D_801F67B0)($a0)
    /* A3BC 801E23BC 21180000 */  addu       $v1, $zero, $zero
    /* A3C0 801E23C0 2080013C */  lui        $at, %hi(D_801F8050)
    /* A3C4 801E23C4 508020AC */  sw         $zero, %lo(D_801F8050)($at)
  .L801E23C8:
    /* A3C8 801E23C8 0000828C */  lw         $v0, 0x0($a0)
    /* A3CC 801E23CC 04008424 */  addiu      $a0, $a0, 0x4
    /* A3D0 801E23D0 01006324 */  addiu      $v1, $v1, 0x1
    /* A3D4 801E23D4 0000A2AC */  sw         $v0, 0x0($a1)
    /* A3D8 801E23D8 0800622C */  sltiu      $v0, $v1, 0x8
    /* A3DC 801E23DC FAFF4014 */  bnez       $v0, .L801E23C8
    /* A3E0 801E23E0 0400A524 */   addiu     $a1, $a1, 0x4
    /* A3E4 801E23E4 2080023C */  lui        $v0, %hi(D_801F806C)
    /* A3E8 801E23E8 6C80428C */  lw         $v0, %lo(D_801F806C)($v0)
    /* A3EC 801E23EC 1F80013C */  lui        $at, %hi(D_801F67B0)
    /* A3F0 801E23F0 B06722AC */  sw         $v0, %lo(D_801F67B0)($at)
  .L801E23F4:
    /* A3F4 801E23F4 2080023C */  lui        $v0, %hi(D_801F8050)
    /* A3F8 801E23F8 5080428C */  lw         $v0, %lo(D_801F8050)($v0)
    /* A3FC 801E23FC 2080013C */  lui        $at, %hi(D_801F8054)
    /* A400 801E2400 548022AC */  sw         $v0, %lo(D_801F8054)($at)
    /* A404 801E2404 0A000224 */  addiu      $v0, $zero, 0xA
  .L801E2408:
    /* A408 801E2408 1F80013C */  lui        $at, %hi(D_801F545C)
    /* A40C 801E240C 5C5422AC */  sw         $v0, %lo(D_801F545C)($at)
    /* A410 801E2410 1F80023C */  lui        $v0, %hi(D_801F67D4)
    /* A414 801E2414 D4674294 */  lhu        $v0, %lo(D_801F67D4)($v0)
    /* A418 801E2418 2080043C */  lui        $a0, %hi(D_801F8070)
    /* A41C 801E241C 7080848C */  lw         $a0, %lo(D_801F8070)($a0)
    /* A420 801E2420 2080033C */  lui        $v1, %hi(D_801F806C)
    /* A424 801E2424 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* A428 801E2428 2080053C */  lui        $a1, %hi(D_801F8050)
    /* A42C 801E242C 5080A58C */  lw         $a1, %lo(D_801F8050)($a1)
    /* A430 801E2430 01004224 */  addiu      $v0, $v0, 0x1
    /* A434 801E2434 40210400 */  sll        $a0, $a0, 5
    /* A438 801E2438 21186400 */  addu       $v1, $v1, $a0
    /* A43C 801E243C 1F80013C */  lui        $at, %hi(D_801F67D4)
    /* A440 801E2440 D46722A4 */  sh         $v0, %lo(D_801F67D4)($at)
    /* A444 801E2444 80110500 */  sll        $v0, $a1, 6
    /* A448 801E2448 23104500 */  subu       $v0, $v0, $a1
    /* A44C 801E244C 40110200 */  sll        $v0, $v0, 5
    /* A450 801E2450 1F80043C */  lui        $a0, %hi(D_801F67D8)
    /* A454 801E2454 D867848C */  lw         $a0, %lo(D_801F67D8)($a0)
    /* A458 801E2458 21186200 */  addu       $v1, $v1, $v0
    /* A45C 801E245C 2080013C */  lui        $at, %hi(D_801F8068)
    /* A460 801E2460 688023AC */  sw         $v1, %lo(D_801F8068)($at)
    /* A464 801E2464 0C008010 */  beqz       $a0, .L801E2498
    /* A468 801E2468 0011083C */   lui       $t0, (0x11000000 >> 16)
    /* A46C 801E246C 0200033C */  lui        $v1, (0x20943 >> 16)
    /* A470 801E2470 1F80023C */  lui        $v0, %hi(D_801F5424)
    /* A474 801E2474 2454428C */  lw         $v0, %lo(D_801F5424)($v0)
    /* A478 801E2478 43096334 */  ori        $v1, $v1, (0x20943 & 0xFFFF)
    /* A47C 801E247C 000043AC */  sw         $v1, 0x0($v0)
    /* A480 801E2480 1F80033C */  lui        $v1, %hi(D_801F5428)
    /* A484 801E2484 2854638C */  lw         $v1, %lo(D_801F5428)($v1)
    /* A488 801E2488 23130224 */  addiu      $v0, $zero, 0x1323
    /* A48C 801E248C 000062AC */  sw         $v0, 0x0($v1)
    /* A490 801E2490 2D890708 */  j          .L801E24B4
    /* A494 801E2494 00000000 */   nop
  .L801E2498:
    /* A498 801E2498 0221033C */  lui        $v1, (0x21020843 >> 16)
    /* A49C 801E249C 43086334 */  ori        $v1, $v1, (0x21020843 & 0xFFFF)
    /* A4A0 801E24A0 4011083C */  lui        $t0, (0x11400100 >> 16)
    /* A4A4 801E24A4 1F80023C */  lui        $v0, %hi(D_801F5424)
    /* A4A8 801E24A8 2454428C */  lw         $v0, %lo(D_801F5424)($v0)
    /* A4AC 801E24AC 00010835 */  ori        $t0, $t0, (0x11400100 & 0xFFFF)
    /* A4B0 801E24B0 000043AC */  sw         $v1, 0x0($v0)
  .L801E24B4:
    /* A4B4 801E24B4 1F80023C */  lui        $v0, %hi(D_801F67B0)
    /* A4B8 801E24B8 B067428C */  lw         $v0, %lo(D_801F67B0)($v0)
    /* A4BC 801E24BC 00000000 */  nop
    /* A4C0 801E24C0 06004394 */  lhu        $v1, 0x6($v0)
    /* A4C4 801E24C4 04004294 */  lhu        $v0, 0x4($v0)
    /* A4C8 801E24C8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* A4CC 801E24CC 2B006214 */  bne        $v1, $v0, .L801E257C
    /* A4D0 801E24D0 01000324 */   addiu     $v1, $zero, 0x1
    /* A4D4 801E24D4 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A4D8 801E24D8 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A4DC 801E24DC 1F80013C */  lui        $at, %hi(D_801F67FC)
    /* A4E0 801E24E0 FC6723AC */  sw         $v1, %lo(D_801F67FC)($at)
    /* A4E4 801E24E4 12004010 */  beqz       $v0, .L801E2530
    /* A4E8 801E24E8 F8010624 */   addiu     $a2, $zero, 0x1F8
    /* A4EC 801E24EC 01000724 */  addiu      $a3, $zero, 0x1
    /* A4F0 801E24F0 1F80053C */  lui        $a1, %hi(D_801F6848)
    /* A4F4 801E24F4 4868A58C */  lw         $a1, %lo(D_801F6848)($a1)
    /* A4F8 801E24F8 2080043C */  lui        $a0, %hi(D_801F8068)
    /* A4FC 801E24FC 6880848C */  lw         $a0, %lo(D_801F8068)($a0)
    /* A500 801E2500 C02A0500 */  sll        $a1, $a1, 11
    /* A504 801E2504 21284500 */  addu       $a1, $v0, $a1
    /* A508 801E2508 9A89070C */  jal        mem2mem
    /* A50C 801E250C 2000A524 */   addiu     $a1, $a1, 0x20
    /* A510 801E2510 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A514 801E2514 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A518 801E2518 00000000 */  nop
    /* A51C 801E251C 01004224 */  addiu      $v0, $v0, 0x1
    /* A520 801E2520 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A524 801E2524 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A528 801E2528 55890708 */  j          .L801E2554
    /* A52C 801E252C 00000000 */   nop
  .L801E2530:
    /* A530 801E2530 03000424 */  addiu      $a0, $zero, 0x3
    /* A534 801E2534 21300000 */  addu       $a2, $zero, $zero
    /* A538 801E2538 2080053C */  lui        $a1, %hi(D_801F8068)
    /* A53C 801E253C 6880A58C */  lw         $a1, %lo(D_801F8068)($a1)
    /* A540 801E2540 F8010724 */  addiu      $a3, $zero, 0x1F8
    /* A544 801E2544 1000A8AF */  sw         $t0, 0x10($sp)
    /* A548 801E2548 1400A3AF */  sw         $v1, 0x14($sp)
    /* A54C 801E254C A789070C */  jal        dma_execute
    /* A550 801E2550 1800A0AF */   sw        $zero, 0x18($sp)
  .L801E2554:
    /* A554 801E2554 1F80023C */  lui        $v0, %hi(D_801F67EC)
    /* A558 801E2558 EC67428C */  lw         $v0, %lo(D_801F67EC)($v0)
    /* A55C 801E255C 1F80013C */  lui        $at, %hi(D_801F67D4)
    /* A560 801E2560 D46720A4 */  sh         $zero, %lo(D_801F67D4)($at)
    /* A564 801E2564 1F80013C */  lui        $at, %hi(D_801F67D0)
    /* A568 801E2568 D06720AC */  sw         $zero, %lo(D_801F67D0)($at)
    /* A56C 801E256C 1F80013C */  lui        $at, %hi(D_801F67F4)
    /* A570 801E2570 F46722AC */  sw         $v0, %lo(D_801F67F4)($at)
    /* A574 801E2574 7E890708 */  j          .L801E25F8
    /* A578 801E2578 00000000 */   nop
  .L801E257C:
    /* A57C 801E257C 2080023C */  lui        $v0, %hi(D_801F805C)
    /* A580 801E2580 5C80428C */  lw         $v0, %lo(D_801F805C)($v0)
    /* A584 801E2584 00000000 */  nop
    /* A588 801E2588 12004010 */  beqz       $v0, .L801E25D4
    /* A58C 801E258C F8010624 */   addiu     $a2, $zero, 0x1F8
    /* A590 801E2590 21380000 */  addu       $a3, $zero, $zero
    /* A594 801E2594 1F80053C */  lui        $a1, %hi(D_801F6848)
    /* A598 801E2598 4868A58C */  lw         $a1, %lo(D_801F6848)($a1)
    /* A59C 801E259C 2080043C */  lui        $a0, %hi(D_801F8068)
    /* A5A0 801E25A0 6880848C */  lw         $a0, %lo(D_801F8068)($a0)
    /* A5A4 801E25A4 C02A0500 */  sll        $a1, $a1, 11
    /* A5A8 801E25A8 21284500 */  addu       $a1, $v0, $a1
    /* A5AC 801E25AC 9A89070C */  jal        mem2mem
    /* A5B0 801E25B0 2000A524 */   addiu     $a1, $a1, 0x20
    /* A5B4 801E25B4 1F80023C */  lui        $v0, %hi(D_801F6848)
    /* A5B8 801E25B8 4868428C */  lw         $v0, %lo(D_801F6848)($v0)
    /* A5BC 801E25BC 00000000 */  nop
    /* A5C0 801E25C0 01004224 */  addiu      $v0, $v0, 0x1
    /* A5C4 801E25C4 1F80013C */  lui        $at, %hi(D_801F6848)
    /* A5C8 801E25C8 486822AC */  sw         $v0, %lo(D_801F6848)($at)
    /* A5CC 801E25CC 7E890708 */  j          .L801E25F8
    /* A5D0 801E25D0 00000000 */   nop
  .L801E25D4:
    /* A5D4 801E25D4 03000424 */  addiu      $a0, $zero, 0x3
    /* A5D8 801E25D8 21300000 */  addu       $a2, $zero, $zero
    /* A5DC 801E25DC 2080053C */  lui        $a1, %hi(D_801F8068)
    /* A5E0 801E25E0 6880A58C */  lw         $a1, %lo(D_801F8068)($a1)
    /* A5E4 801E25E4 F8010724 */  addiu      $a3, $zero, 0x1F8
    /* A5E8 801E25E8 1000A8AF */  sw         $t0, 0x10($sp)
    /* A5EC 801E25EC 1400A0AF */  sw         $zero, 0x14($sp)
    /* A5F0 801E25F0 A789070C */  jal        dma_execute
    /* A5F4 801E25F4 1800A0AF */   sw        $zero, 0x18($sp)
  .L801E25F8:
    /* A5F8 801E25F8 1F80033C */  lui        $v1, %hi(D_801F5428)
    /* A5FC 801E25FC 2854638C */  lw         $v1, %lo(D_801F5428)($v1)
    /* A600 801E2600 25130224 */  addiu      $v0, $zero, 0x1325
    /* A604 801E2604 000062AC */  sw         $v0, 0x0($v1)
    /* A608 801E2608 1F80033C */  lui        $v1, %hi(D_801F67B0)
    /* A60C 801E260C B067638C */  lw         $v1, %lo(D_801F67B0)($v1)
    /* A610 801E2610 03000224 */  addiu      $v0, $zero, 0x3
    /* A614 801E2614 000062A4 */  sh         $v0, 0x0($v1)
    /* A618 801E2618 2080023C */  lui        $v0, %hi(D_801F8050)
    /* A61C 801E261C 5080428C */  lw         $v0, %lo(D_801F8050)($v0)
    /* A620 801E2620 2080033C */  lui        $v1, %hi(D_801F805C)
    /* A624 801E2624 5C80638C */  lw         $v1, %lo(D_801F805C)($v1)
    /* A628 801E2628 01004224 */  addiu      $v0, $v0, 0x1
    /* A62C 801E262C 2080013C */  lui        $at, %hi(D_801F8050)
    /* A630 801E2630 508022AC */  sw         $v0, %lo(D_801F8050)($at)
    /* A634 801E2634 08006010 */  beqz       $v1, .L801E2658
    /* A638 801E2638 00000000 */   nop
    /* A63C 801E263C 1F80023C */  lui        $v0, %hi(D_801F67FC)
    /* A640 801E2640 FC67428C */  lw         $v0, %lo(D_801F67FC)($v0)
    /* A644 801E2644 00000000 */  nop
    /* A648 801E2648 03004010 */  beqz       $v0, .L801E2658
    /* A64C 801E264C 00000000 */   nop
    /* A650 801E2650 6A86070C */  jal        data_ready_callback
    /* A654 801E2654 00000000 */   nop
  .L801E2658:
    /* A658 801E2658 3800BF8F */  lw         $ra, 0x38($sp)
    /* A65C 801E265C 4000BD27 */  addiu      $sp, $sp, 0x40
    /* A660 801E2660 0800E003 */  jr         $ra
    /* A664 801E2664 00000000 */   nop
endlabel StCdInterrupt

nonmatching mem2mem, 0x34

glabel mem2mem
    /* A668 801E2668 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* A66C 801E266C 0800C010 */  beqz       $a2, .L801E2690
    /* A670 801E2670 21180000 */   addu      $v1, $zero, $zero
  .L801E2674:
    /* A674 801E2674 0000A28C */  lw         $v0, 0x0($a1)
    /* A678 801E2678 0400A524 */  addiu      $a1, $a1, 0x4
    /* A67C 801E267C 01006324 */  addiu      $v1, $v1, 0x1
    /* A680 801E2680 000082AC */  sw         $v0, 0x0($a0)
    /* A684 801E2684 2B106600 */  sltu       $v0, $v1, $a2
    /* A688 801E2688 FAFF4014 */  bnez       $v0, .L801E2674
    /* A68C 801E268C 04008424 */   addiu     $a0, $a0, 0x4
  .L801E2690:
    /* A690 801E2690 0800BD27 */  addiu      $sp, $sp, 0x8
    /* A694 801E2694 0800E003 */  jr         $ra
    /* A698 801E2698 00000000 */   nop
endlabel mem2mem

nonmatching dma_execute, 0x1BC

glabel dma_execute
    /* A69C 801E269C C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* A6A0 801E26A0 1800B0AF */  sw         $s0, 0x18($sp)
    /* A6A4 801E26A4 21808000 */  addu       $s0, $a0, $zero
    /* A6A8 801E26A8 2000B2AF */  sw         $s2, 0x20($sp)
    /* A6AC 801E26AC 2190A000 */  addu       $s2, $a1, $zero
    /* A6B0 801E26B0 2400B3AF */  sw         $s3, 0x24($sp)
    /* A6B4 801E26B4 2198C000 */  addu       $s3, $a2, $zero
    /* A6B8 801E26B8 2800B4AF */  sw         $s4, 0x28($sp)
    /* A6BC 801E26BC 21A0E000 */  addu       $s4, $a3, $zero
    /* A6C0 801E26C0 21200000 */  addu       $a0, $zero, $zero
    /* A6C4 801E26C4 00291000 */  sll        $a1, $s0, 4
    /* A6C8 801E26C8 0001023C */  lui        $v0, (0x1000000 >> 16)
    /* A6CC 801E26CC 3000BFAF */  sw         $ra, 0x30($sp)
    /* A6D0 801E26D0 2C00B5AF */  sw         $s5, 0x2C($sp)
    /* A6D4 801E26D4 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* A6D8 801E26D8 801F013C */  lui        $at, (0x1F801088 >> 16)
    /* A6DC 801E26DC 2108A100 */  addu       $at, $a1, $at
    /* A6E0 801E26E0 8810238C */  lw         $v1, (0x1F801088 & 0xFFFF)($at)
    /* A6E4 801E26E4 4800B58F */  lw         $s5, 0x48($sp)
    /* A6E8 801E26E8 4C00B193 */  lbu        $s1, 0x4C($sp)
    /* A6EC 801E26EC 24186200 */  and        $v1, $v1, $v0
    /* A6F0 801E26F0 0D006010 */  beqz       $v1, .L801E2728
    /* A6F4 801E26F4 FF002232 */   andi      $v0, $s1, 0xFF
    /* A6F8 801E26F8 0100063C */  lui        $a2, (0x10000 >> 16)
    /* A6FC 801E26FC 0001033C */  lui        $v1, (0x1000000 >> 16)
  .L801E2700:
    /* A700 801E2700 12008610 */  beq        $a0, $a2, .L801E274C
    /* A704 801E2704 00000000 */   nop
    /* A708 801E2708 801F013C */  lui        $at, (0x1F801088 >> 16)
    /* A70C 801E270C 2108A100 */  addu       $at, $a1, $at
    /* A710 801E2710 8810228C */  lw         $v0, (0x1F801088 & 0xFFFF)($at)
    /* A714 801E2714 00000000 */  nop
    /* A718 801E2718 24104300 */  and        $v0, $v0, $v1
    /* A71C 801E271C F8FF4014 */  bnez       $v0, .L801E2700
    /* A720 801E2720 01008424 */   addiu     $a0, $a0, 0x1
    /* A724 801E2724 FF002232 */  andi       $v0, $s1, 0xFF
  .L801E2728:
    /* A728 801E2728 01000524 */  addiu      $a1, $zero, 0x1
    /* A72C 801E272C 10004514 */  bne        $v0, $a1, .L801E2770
    /* A730 801E2730 04100502 */   sllv      $v0, $a1, $s0
    /* A734 801E2734 1F80033C */  lui        $v1, %hi(D_801F5430)
    /* A738 801E2738 3054638C */  lw         $v1, %lo(D_801F5430)($v1)
    /* A73C 801E273C 00000000 */  nop
    /* A740 801E2740 02006490 */  lbu        $a0, 0x2($v1)
    /* A744 801E2744 E2890708 */  j          .L801E2788
    /* A748 801E2748 25208200 */   or        $a0, $a0, $v0
  .L801E274C:
    /* A74C 801E274C 801F013C */  lui        $at, (0x1F801088 >> 16)
    /* A750 801E2750 2108A100 */  addu       $at, $a1, $at
    /* A754 801E2754 8810258C */  lw         $a1, (0x1F801088 & 0xFFFF)($at)
    /* A758 801E2758 1E80043C */  lui        $a0, %hi(D_801D90DC)
    /* A75C 801E275C DC908424 */  addiu      $a0, $a0, %lo(D_801D90DC)
    /* A760 801E2760 2568070C */  jal        printf
    /* A764 801E2764 00000000 */   nop
    /* A768 801E2768 CA890708 */  j          .L801E2728
    /* A76C 801E276C FF002232 */   andi      $v0, $s1, 0xFF
  .L801E2770:
    /* A770 801E2770 1F80033C */  lui        $v1, %hi(D_801F5430)
    /* A774 801E2774 3054638C */  lw         $v1, %lo(D_801F5430)($v1)
    /* A778 801E2778 00000000 */  nop
    /* A77C 801E277C 02006490 */  lbu        $a0, 0x2($v1)
    /* A780 801E2780 27100200 */  nor        $v0, $zero, $v0
    /* A784 801E2784 24208200 */  and        $a0, $a0, $v0
  .L801E2788:
    /* A788 801E2788 020064A0 */  sb         $a0, 0x2($v1)
    /* A78C 801E278C 1F80023C */  lui        $v0, %hi(D_801F5430)
    /* A790 801E2790 3054428C */  lw         $v0, %lo(D_801F5430)($v0)
    /* A794 801E2794 00000000 */  nop
    /* A798 801E2798 0000428C */  lw         $v0, 0x0($v0)
    /* A79C 801E279C 00000000 */  nop
    /* A7A0 801E27A0 1000A2AF */  sw         $v0, 0x10($sp)
    /* A7A4 801E27A4 80301000 */  sll        $a2, $s0, 2
    /* A7A8 801E27A8 0300C624 */  addiu      $a2, $a2, 0x3
    /* A7AC 801E27AC 01000324 */  addiu      $v1, $zero, 0x1
    /* A7B0 801E27B0 0418C300 */  sllv       $v1, $v1, $a2
    /* A7B4 801E27B4 801F053C */  lui        $a1, (0x1F801080 >> 16)
    /* A7B8 801E27B8 8010A534 */  ori        $a1, $a1, (0x1F801080 & 0xFFFF)
    /* A7BC 801E27BC 00111000 */  sll        $v0, $s0, 4
    /* A7C0 801E27C0 21284500 */  addu       $a1, $v0, $a1
    /* A7C4 801E27C4 1F80043C */  lui        $a0, %hi(D_801F542C)
    /* A7C8 801E27C8 2C54848C */  lw         $a0, %lo(D_801F542C)($a0)
    /* A7CC 801E27CC 00141300 */  sll        $v0, $s3, 16
    /* A7D0 801E27D0 0000868C */  lw         $a2, 0x0($a0)
    /* A7D4 801E27D4 25105400 */  or         $v0, $v0, $s4
    /* A7D8 801E27D8 2530C300 */  or         $a2, $a2, $v1
    /* A7DC 801E27DC 000086AC */  sw         $a2, 0x0($a0)
    /* A7E0 801E27E0 0000B2AC */  sw         $s2, 0x0($a1)
    /* A7E4 801E27E4 0400A524 */  addiu      $a1, $a1, 0x4
    /* A7E8 801E27E8 0000A2AC */  sw         $v0, 0x0($a1)
    /* A7EC 801E27EC 1F80033C */  lui        $v1, %hi(D_801F5414)
    /* A7F0 801E27F0 1454638C */  lw         $v1, %lo(D_801F5414)($v1)
    /* A7F4 801E27F4 00000000 */  nop
    /* A7F8 801E27F8 00006290 */  lbu        $v0, 0x0($v1)
    /* A7FC 801E27FC 00000000 */  nop
    /* A800 801E2800 40004230 */  andi       $v0, $v0, 0x40
    /* A804 801E2804 06004014 */  bnez       $v0, .L801E2820
    /* A808 801E2808 0400A524 */   addiu     $a1, $a1, 0x4
  .L801E280C:
    /* A80C 801E280C 00006290 */  lbu        $v0, 0x0($v1)
    /* A810 801E2810 00000000 */  nop
    /* A814 801E2814 40004230 */  andi       $v0, $v0, 0x40
    /* A818 801E2818 FCFF4010 */  beqz       $v0, .L801E280C
    /* A81C 801E281C 00000000 */   nop
  .L801E2820:
    /* A820 801E2820 0000B5AC */  sw         $s5, 0x0($a1)
    /* A824 801E2824 0000A28C */  lw         $v0, 0x0($a1)
    /* A828 801E2828 00000000 */  nop
    /* A82C 801E282C 1000A2AF */  sw         $v0, 0x10($sp)
    /* A830 801E2830 3000BF8F */  lw         $ra, 0x30($sp)
    /* A834 801E2834 2C00B58F */  lw         $s5, 0x2C($sp)
    /* A838 801E2838 2800B48F */  lw         $s4, 0x28($sp)
    /* A83C 801E283C 2400B38F */  lw         $s3, 0x24($sp)
    /* A840 801E2840 2000B28F */  lw         $s2, 0x20($sp)
    /* A844 801E2844 1C00B18F */  lw         $s1, 0x1C($sp)
    /* A848 801E2848 1800B08F */  lw         $s0, 0x18($sp)
    /* A84C 801E284C 3800BD27 */  addiu      $sp, $sp, 0x38
    /* A850 801E2850 0800E003 */  jr         $ra
    /* A854 801E2854 00000000 */   nop
endlabel dma_execute
