.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StSetRing, 0x30

glabel StSetRing
    /* 6E70 801DEE70 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 6E74 801DEE74 1000BFAF */  sw         $ra, 0x10($sp)
    /* 6E78 801DEE78 2080013C */  lui        $at, %hi(D_801F806C)
    /* 6E7C 801DEE7C 6C8024AC */  sw         $a0, %lo(D_801F806C)($at)
    /* 6E80 801DEE80 2080013C */  lui        $at, %hi(D_801F8070)
    /* 6E84 801DEE84 708025AC */  sw         $a1, %lo(D_801F8070)($at)
    /* 6E88 801DEE88 2986070C */  jal        StClearRing
    /* 6E8C 801DEE8C 00000000 */   nop
    /* 6E90 801DEE90 1000BF8F */  lw         $ra, 0x10($sp)
    /* 6E94 801DEE94 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 6E98 801DEE98 0800E003 */  jr         $ra
    /* 6E9C 801DEE9C 00000000 */   nop
endlabel StSetRing
