.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching CdRead2, 0x94

glabel CdRead2
    /* 97F0 801E17F0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 97F4 801E17F4 1800B0AF */  sw         $s0, 0x18($sp)
    /* 97F8 801E17F8 21808000 */  addu       $s0, $a0, $zero
    /* 97FC 801E17FC 0E000424 */  addiu      $a0, $zero, 0xE
    /* 9800 801E1800 1000A527 */  addiu      $a1, $sp, 0x10
    /* 9804 801E1804 21300000 */  addu       $a2, $zero, $zero
    /* 9808 801E1808 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 980C 801E180C 5F7C070C */  jal        CdControl
    /* 9810 801E1810 1000B0A3 */   sb        $s0, 0x10($sp)
    /* 9814 801E1814 00010232 */  andi       $v0, $s0, 0x100
    /* 9818 801E1818 11004010 */  beqz       $v0, .L801E1860
    /* 981C 801E181C 20000232 */   andi      $v0, $s0, 0x20
    /* 9820 801E1820 05004010 */  beqz       $v0, .L801E1838
    /* 9824 801E1824 01000224 */   addiu     $v0, $zero, 0x1
    /* 9828 801E1828 1F80013C */  lui        $at, %hi(D_801F67DC)
    /* 982C 801E182C DC6720AC */  sw         $zero, %lo(D_801F67DC)($at)
    /* 9830 801E1830 10860708 */  j          .L801E1840
    /* 9834 801E1834 00000000 */   nop
  .L801E1838:
    /* 9838 801E1838 1F80013C */  lui        $at, %hi(D_801F67DC)
    /* 983C 801E183C DC6722AC */  sw         $v0, %lo(D_801F67DC)($at)
  .L801E1840:
    /* 9840 801E1840 1E80043C */  lui        $a0, %hi(data_ready_callback)
    /* 9844 801E1844 A8198424 */  addiu      $a0, $a0, %lo(data_ready_callback)
    /* 9848 801E1848 617D070C */  jal        CdDataCallback
    /* 984C 801E184C 00000000 */   nop
    /* 9850 801E1850 1E80043C */  lui        $a0, %hi(StCdInterrupt2)
    /* 9854 801E1854 84188424 */  addiu      $a0, $a0, %lo(StCdInterrupt2)
    /* 9858 801E1858 597C070C */  jal        CdReadyCallback
    /* 985C 801E185C 00000000 */   nop
  .L801E1860:
    /* 9860 801E1860 1B000424 */  addiu      $a0, $zero, 0x1B
    /* 9864 801E1864 21280000 */  addu       $a1, $zero, $zero
    /* 9868 801E1868 5F7C070C */  jal        CdControl
    /* 986C 801E186C 21300000 */   addu      $a2, $zero, $zero
    /* 9870 801E1870 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 9874 801E1874 1800B08F */  lw         $s0, 0x18($sp)
    /* 9878 801E1878 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 987C 801E187C 0800E003 */  jr         $ra
    /* 9880 801E1880 00000000 */   nop
endlabel CdRead2

nonmatching StCdInterrupt2, 0x20

glabel StCdInterrupt2
    /* 9884 801E1884 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 9888 801E1888 1000BFAF */  sw         $ra, 0x10($sp)
    /* 988C 801E188C 3E87070C */  jal        StCdInterrupt
    /* 9890 801E1890 00000000 */   nop
    /* 9894 801E1894 1000BF8F */  lw         $ra, 0x10($sp)
    /* 9898 801E1898 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 989C 801E189C 0800E003 */  jr         $ra
    /* 98A0 801E18A0 00000000 */   nop
endlabel StCdInterrupt2
