.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StUnSetRing, 0x84

glabel StUnSetRing
    /* 9904 801E1904 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 9908 801E1908 1000BFAF */  sw         $ra, 0x10($sp)
    /* 990C 801E190C 6286070C */  jal        EnterCriticalSection
    /* 9910 801E1910 00000000 */   nop
    /* 9914 801E1914 1F80033C */  lui        $v1, %hi(D_801F5064)
    /* 9918 801E1918 6450638C */  lw         $v1, %lo(D_801F5064)($v1)
    /* 991C 801E191C 01000224 */  addiu      $v0, $zero, 0x1
    /* 9920 801E1920 07006214 */  bne        $v1, $v0, .L801E1940
    /* 9924 801E1924 00000000 */   nop
    /* 9928 801E1928 118F070C */  jal        DsDataCallback
    /* 992C 801E192C 21200000 */   addu      $a0, $zero, $zero
    /* 9930 801E1930 0C8F070C */  jal        DsReadyCallback
    /* 9934 801E1934 21200000 */   addu      $a0, $zero, $zero
    /* 9938 801E1938 54860708 */  j          .L801E1950
    /* 993C 801E193C 00000000 */   nop
  .L801E1940:
    /* 9940 801E1940 617D070C */  jal        CdDataCallback
    /* 9944 801E1944 21200000 */   addu      $a0, $zero, $zero
    /* 9948 801E1948 597C070C */  jal        CdReadyCallback
    /* 994C 801E194C 21200000 */   addu      $a0, $zero, $zero
  .L801E1950:
    /* 9950 801E1950 1F80023C */  lui        $v0, %hi(D_801F53A4)
    /* 9954 801E1954 A453428C */  lw         $v0, %lo(D_801F53A4)($v0)
    /* 9958 801E1958 00000000 */  nop
    /* 995C 801E195C 000040A0 */  sb         $zero, 0x0($v0)
    /* 9960 801E1960 1F80023C */  lui        $v0, %hi(D_801F53B0)
    /* 9964 801E1964 B053428C */  lw         $v0, %lo(D_801F53B0)($v0)
    /* 9968 801E1968 00000000 */  nop
    /* 996C 801E196C 000040A0 */  sb         $zero, 0x0($v0)
    /* 9970 801E1970 6686070C */  jal        ExitCriticalSection
    /* 9974 801E1974 00000000 */   nop
    /* 9978 801E1978 1000BF8F */  lw         $ra, 0x10($sp)
    /* 997C 801E197C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 9980 801E1980 0800E003 */  jr         $ra
    /* 9984 801E1984 00000000 */   nop
endlabel StUnSetRing
