.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching init_ring_status, 0x3C

glabel init_ring_status
    /* 9BD8 801E1BD8 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 9BDC 801E1BDC 0A00A010 */  beqz       $a1, .L801E1C08
    /* 9BE0 801E1BE0 21300000 */   addu      $a2, $zero, $zero
  .L801E1BE4:
    /* 9BE4 801E1BE4 2110C400 */  addu       $v0, $a2, $a0
    /* 9BE8 801E1BE8 0100C624 */  addiu      $a2, $a2, 0x1
    /* 9BEC 801E1BEC 2080033C */  lui        $v1, %hi(D_801F806C)
    /* 9BF0 801E1BF0 6C80638C */  lw         $v1, %lo(D_801F806C)($v1)
    /* 9BF4 801E1BF4 40110200 */  sll        $v0, $v0, 5
    /* 9BF8 801E1BF8 21186200 */  addu       $v1, $v1, $v0
    /* 9BFC 801E1BFC 2B10C500 */  sltu       $v0, $a2, $a1
    /* 9C00 801E1C00 F8FF4014 */  bnez       $v0, .L801E1BE4
    /* 9C04 801E1C04 000060AC */   sw        $zero, 0x0($v1)
  .L801E1C08:
    /* 9C08 801E1C08 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 9C0C 801E1C0C 0800E003 */  jr         $ra
    /* 9C10 801E1C10 00000000 */   nop
endlabel init_ring_status
