.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StSetMask, 0x20

glabel StSetMask
    /* 9CD8 801E1CD8 2080013C */  lui        $at, %hi(D_801F8064)
    /* 9CDC 801E1CDC 648024AC */  sw         $a0, %lo(D_801F8064)($at)
    /* 9CE0 801E1CE0 1F80013C */  lui        $at, %hi(D_801F67F0)
    /* 9CE4 801E1CE4 F06725AC */  sw         $a1, %lo(D_801F67F0)($at)
    /* 9CE8 801E1CE8 2080013C */  lui        $at, %hi(D_801F8060)
    /* 9CEC 801E1CEC 608026AC */  sw         $a2, %lo(D_801F8060)($at)
    /* 9CF0 801E1CF0 0800E003 */  jr         $ra
    /* 9CF4 801E1CF4 00000000 */   nop
endlabel StSetMask
