.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching StClearRing, 0x60

glabel StClearRing
    /* 98A4 801E18A4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 98A8 801E18A8 2080053C */  lui        $a1, %hi(D_801F8070)
    /* 98AC 801E18AC 7080A58C */  lw         $a1, %lo(D_801F8070)($a1)
    /* 98B0 801E18B0 1000BFAF */  sw         $ra, 0x10($sp)
    /* 98B4 801E18B4 2080013C */  lui        $at, %hi(D_801F8058)
    /* 98B8 801E18B8 588020AC */  sw         $zero, %lo(D_801F8058)($at)
    /* 98BC 801E18BC 2080013C */  lui        $at, %hi(D_801F8054)
    /* 98C0 801E18C0 548020AC */  sw         $zero, %lo(D_801F8054)($at)
    /* 98C4 801E18C4 2080013C */  lui        $at, %hi(D_801F8050)
    /* 98C8 801E18C8 508020AC */  sw         $zero, %lo(D_801F8050)($at)
    /* 98CC 801E18CC 1F80013C */  lui        $at, %hi(D_801F67FC)
    /* 98D0 801E18D0 FC6720AC */  sw         $zero, %lo(D_801F67FC)($at)
    /* 98D4 801E18D4 F686070C */  jal        init_ring_status
    /* 98D8 801E18D8 21200000 */   addu      $a0, $zero, $zero
    /* 98DC 801E18DC 1F80013C */  lui        $at, %hi(D_801F67E8)
    /* 98E0 801E18E0 E86720AC */  sw         $zero, %lo(D_801F67E8)($at)
    /* 98E4 801E18E4 1F80013C */  lui        $at, %hi(D_801F67D4)
    /* 98E8 801E18E8 D46720A4 */  sh         $zero, %lo(D_801F67D4)($at)
    /* 98EC 801E18EC 1F80013C */  lui        $at, %hi(D_801F67D0)
    /* 98F0 801E18F0 D06720AC */  sw         $zero, %lo(D_801F67D0)($at)
    /* 98F4 801E18F4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 98F8 801E18F8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 98FC 801E18FC 0800E003 */  jr         $ra
    /* 9900 801E1900 00000000 */   nop
endlabel StClearRing
