.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching DsSyncCallback, 0x14

glabel DsSyncCallback
    /* BC1C 801E3C1C 1F80033C */  lui        $v1, %hi(D_801F6840)
    /* BC20 801E3C20 40686324 */  addiu      $v1, $v1, %lo(D_801F6840)
    /* BC24 801E3C24 0000628C */  lw         $v0, 0x0($v1)
    /* BC28 801E3C28 0800E003 */  jr         $ra
    /* BC2C 801E3C2C 000064AC */   sw        $a0, 0x0($v1)
endlabel DsSyncCallback

nonmatching DsReadyCallback, 0x14

glabel DsReadyCallback
    /* BC30 801E3C30 1F80033C */  lui        $v1, %hi(D_801F6844)
    /* BC34 801E3C34 44686324 */  addiu      $v1, $v1, %lo(D_801F6844)
    /* BC38 801E3C38 0000628C */  lw         $v0, 0x0($v1)
    /* BC3C 801E3C3C 0800E003 */  jr         $ra
    /* BC40 801E3C40 000064AC */   sw        $a0, 0x0($v1)
endlabel DsReadyCallback

nonmatching DsDataCallback, 0x24

glabel DsDataCallback
    /* BC44 801E3C44 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* BC48 801E3C48 1000BFAF */  sw         $ra, 0x10($sp)
    /* BC4C 801E3C4C 21288000 */  addu       $a1, $a0, $zero
    /* BC50 801E3C50 298C070C */  jal        DMACallback
    /* BC54 801E3C54 03000424 */   addiu     $a0, $zero, 0x3
    /* BC58 801E3C58 1000BF8F */  lw         $ra, 0x10($sp)
    /* BC5C 801E3C5C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* BC60 801E3C60 0800E003 */  jr         $ra
    /* BC64 801E3C64 00000000 */   nop
endlabel DsDataCallback
