.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching ResetCallback, 0x30

glabel ResetCallback
    /* B044 801E3044 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B048 801E3048 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B04C 801E304C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B050 801E3050 1000BFAF */  sw         $ra, 0x10($sp)
    /* B054 801E3054 0C00428C */  lw         $v0, 0xC($v0)
    /* B058 801E3058 00000000 */  nop
    /* B05C 801E305C 09F84000 */  jalr       $v0
    /* B060 801E3060 00000000 */   nop
    /* B064 801E3064 1000BF8F */  lw         $ra, 0x10($sp)
    /* B068 801E3068 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B06C 801E306C 0800E003 */  jr         $ra
    /* B070 801E3070 00000000 */   nop
endlabel ResetCallback

nonmatching InterruptCallback, 0x30

glabel InterruptCallback
    /* B074 801E3074 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B078 801E3078 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B07C 801E307C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B080 801E3080 1000BFAF */  sw         $ra, 0x10($sp)
    /* B084 801E3084 0800428C */  lw         $v0, 0x8($v0)
    /* B088 801E3088 00000000 */  nop
    /* B08C 801E308C 09F84000 */  jalr       $v0
    /* B090 801E3090 00000000 */   nop
    /* B094 801E3094 1000BF8F */  lw         $ra, 0x10($sp)
    /* B098 801E3098 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B09C 801E309C 0800E003 */  jr         $ra
    /* B0A0 801E30A0 00000000 */   nop
endlabel InterruptCallback

nonmatching DMACallback, 0x30

glabel DMACallback
    /* B0A4 801E30A4 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B0A8 801E30A8 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B0AC 801E30AC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B0B0 801E30B0 1000BFAF */  sw         $ra, 0x10($sp)
    /* B0B4 801E30B4 0400428C */  lw         $v0, 0x4($v0)
    /* B0B8 801E30B8 00000000 */  nop
    /* B0BC 801E30BC 09F84000 */  jalr       $v0
    /* B0C0 801E30C0 00000000 */   nop
    /* B0C4 801E30C4 1000BF8F */  lw         $ra, 0x10($sp)
    /* B0C8 801E30C8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B0CC 801E30CC 0800E003 */  jr         $ra
    /* B0D0 801E30D0 00000000 */   nop
endlabel DMACallback

nonmatching VSyncCallback, 0x34

glabel VSyncCallback
    /* B0D4 801E30D4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B0D8 801E30D8 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B0DC 801E30DC 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B0E0 801E30E0 21288000 */  addu       $a1, $a0, $zero
    /* B0E4 801E30E4 1000BFAF */  sw         $ra, 0x10($sp)
    /* B0E8 801E30E8 1400428C */  lw         $v0, 0x14($v0)
    /* B0EC 801E30EC 00000000 */  nop
    /* B0F0 801E30F0 09F84000 */  jalr       $v0
    /* B0F4 801E30F4 04000424 */   addiu     $a0, $zero, 0x4
    /* B0F8 801E30F8 1000BF8F */  lw         $ra, 0x10($sp)
    /* B0FC 801E30FC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B100 801E3100 0800E003 */  jr         $ra
    /* B104 801E3104 00000000 */   nop
endlabel VSyncCallback

nonmatching VSyncCallbacks, 0x30

glabel VSyncCallbacks
    /* B108 801E3108 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B10C 801E310C 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B110 801E3110 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B114 801E3114 1000BFAF */  sw         $ra, 0x10($sp)
    /* B118 801E3118 1400428C */  lw         $v0, 0x14($v0)
    /* B11C 801E311C 00000000 */  nop
    /* B120 801E3120 09F84000 */  jalr       $v0
    /* B124 801E3124 00000000 */   nop
    /* B128 801E3128 1000BF8F */  lw         $ra, 0x10($sp)
    /* B12C 801E312C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B130 801E3130 0800E003 */  jr         $ra
    /* B134 801E3134 00000000 */   nop
endlabel VSyncCallbacks

nonmatching StopCallback, 0x30

glabel StopCallback
    /* B138 801E3138 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B13C 801E313C 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B140 801E3140 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B144 801E3144 1000BFAF */  sw         $ra, 0x10($sp)
    /* B148 801E3148 1000428C */  lw         $v0, 0x10($v0)
    /* B14C 801E314C 00000000 */  nop
    /* B150 801E3150 09F84000 */  jalr       $v0
    /* B154 801E3154 00000000 */   nop
    /* B158 801E3158 1000BF8F */  lw         $ra, 0x10($sp)
    /* B15C 801E315C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B160 801E3160 0800E003 */  jr         $ra
    /* B164 801E3164 00000000 */   nop
endlabel StopCallback

nonmatching RestartCallback, 0x30

glabel RestartCallback
    /* B168 801E3168 1F80023C */  lui        $v0, %hi(D_801F6568)
    /* B16C 801E316C 6865428C */  lw         $v0, %lo(D_801F6568)($v0)
    /* B170 801E3170 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B174 801E3174 1000BFAF */  sw         $ra, 0x10($sp)
    /* B178 801E3178 1800428C */  lw         $v0, 0x18($v0)
    /* B17C 801E317C 00000000 */  nop
    /* B180 801E3180 09F84000 */  jalr       $v0
    /* B184 801E3184 00000000 */   nop
    /* B188 801E3188 1000BF8F */  lw         $ra, 0x10($sp)
    /* B18C 801E318C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B190 801E3190 0800E003 */  jr         $ra
    /* B194 801E3194 00000000 */   nop
endlabel RestartCallback

nonmatching CheckCallback, 0x10

glabel CheckCallback
    /* B198 801E3198 1F80023C */  lui        $v0, %hi(D_801F54E2)
    /* B19C 801E319C E2544294 */  lhu        $v0, %lo(D_801F54E2)($v0)
    /* B1A0 801E31A0 0800E003 */  jr         $ra
    /* B1A4 801E31A4 00000000 */   nop
endlabel CheckCallback

nonmatching GetIntrMask, 0x18

glabel GetIntrMask
    /* B1A8 801E31A8 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B1AC 801E31AC 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B1B0 801E31B0 00000000 */  nop
    /* B1B4 801E31B4 00004294 */  lhu        $v0, 0x0($v0)
    /* B1B8 801E31B8 0800E003 */  jr         $ra
    /* B1BC 801E31BC 00000000 */   nop
endlabel GetIntrMask

nonmatching SetIntrMask, 0x1C

glabel SetIntrMask
    /* B1C0 801E31C0 1F80033C */  lui        $v1, %hi(D_801F6570)
    /* B1C4 801E31C4 7065638C */  lw         $v1, %lo(D_801F6570)($v1)
    /* B1C8 801E31C8 00000000 */  nop
    /* B1CC 801E31CC 00006294 */  lhu        $v0, 0x0($v1)
    /* B1D0 801E31D0 000064A4 */  sh         $a0, 0x0($v1)
    /* B1D4 801E31D4 0800E003 */  jr         $ra
    /* B1D8 801E31D8 00000000 */   nop
endlabel SetIntrMask

nonmatching startIntr, 0xDC

glabel startIntr
    /* B1DC 801E31DC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B1E0 801E31E0 1000B0AF */  sw         $s0, 0x10($sp)
    /* B1E4 801E31E4 1F80103C */  lui        $s0, %hi(D_801F54E0)
    /* B1E8 801E31E8 E0541026 */  addiu      $s0, $s0, %lo(D_801F54E0)
    /* B1EC 801E31EC 1400BFAF */  sw         $ra, 0x14($sp)
    /* B1F0 801E31F0 00000296 */  lhu        $v0, 0x0($s0)
    /* B1F4 801E31F4 00000000 */  nop
    /* B1F8 801E31F8 2A004014 */  bnez       $v0, .L801E32A4
    /* B1FC 801E31FC 21100000 */   addu      $v0, $zero, $zero
    /* B200 801E3200 1F80033C */  lui        $v1, %hi(D_801F656C)
    /* B204 801E3204 6C65638C */  lw         $v1, %lo(D_801F656C)($v1)
    /* B208 801E3208 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B20C 801E320C 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B210 801E3210 3333053C */  lui        $a1, (0x33333333 >> 16)
    /* B214 801E3214 000040A4 */  sh         $zero, 0x0($v0)
    /* B218 801E3218 00004294 */  lhu        $v0, 0x0($v0)
    /* B21C 801E321C 3333A534 */  ori        $a1, $a1, (0x33333333 & 0xFFFF)
    /* B220 801E3220 000062A4 */  sh         $v0, 0x0($v1)
    /* B224 801E3224 1F80023C */  lui        $v0, %hi(D_801F6574)
    /* B228 801E3228 7465428C */  lw         $v0, %lo(D_801F6574)($v0)
    /* B22C 801E322C 21200002 */  addu       $a0, $s0, $zero
    /* B230 801E3230 000045AC */  sw         $a1, 0x0($v0)
    /* B234 801E3234 CA8D070C */  jal        memclr
    /* B238 801E3238 1A040524 */   addiu     $a1, $zero, 0x41A
    /* B23C 801E323C E98D070C */  jal        setjmp
    /* B240 801E3240 38000426 */   addiu     $a0, $s0, 0x38
    /* B244 801E3244 03004010 */  beqz       $v0, .L801E3254
    /* B248 801E3248 00000000 */   nop
    /* B24C 801E324C AE8C070C */  jal        trapIntr
    /* B250 801E3250 00000000 */   nop
  .L801E3254:
    /* B254 801E3254 1F80103C */  lui        $s0, %hi(D_801F551C)
    /* B258 801E3258 1C551026 */  addiu      $s0, $s0, %lo(D_801F551C)
    /* B25C 801E325C FCFF0426 */  addiu      $a0, $s0, -0x4
    /* B260 801E3260 DC0F0226 */  addiu      $v0, $s0, 0xFDC
    /* B264 801E3264 E58D070C */  jal        HookEntryInt
    /* B268 801E3268 000002AE */   sw        $v0, 0x0($s0)
    /* B26C 801E326C 01000224 */  addiu      $v0, $zero, 0x1
    /* B270 801E3270 098E070C */  jal        startIntrVSync
    /* B274 801E3274 C4FF02A6 */   sh        $v0, -0x3C($s0)
    /* B278 801E3278 1F80033C */  lui        $v1, %hi(D_801F6568)
    /* B27C 801E327C 6865638C */  lw         $v1, %lo(D_801F6568)($v1)
    /* B280 801E3280 538E070C */  jal        startIntrDMA
    /* B284 801E3284 140062AC */   sw        $v0, 0x14($v1)
    /* B288 801E3288 1F80043C */  lui        $a0, %hi(D_801F6568)
    /* B28C 801E328C 6865848C */  lw         $a0, %lo(D_801F6568)($a0)
    /* B290 801E3290 D78D070C */  jal        _96_remove
    /* B294 801E3294 040082AC */   sw        $v0, 0x4($a0)
    /* B298 801E3298 6686070C */  jal        ExitCriticalSection
    /* B29C 801E329C C4FF1026 */   addiu     $s0, $s0, -0x3C
    /* B2A0 801E32A0 21100002 */  addu       $v0, $s0, $zero
  .L801E32A4:
    /* B2A4 801E32A4 1400BF8F */  lw         $ra, 0x14($sp)
    /* B2A8 801E32A8 1000B08F */  lw         $s0, 0x10($sp)
    /* B2AC 801E32AC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B2B0 801E32B0 0800E003 */  jr         $ra
    /* B2B4 801E32B4 00000000 */   nop
endlabel startIntr

nonmatching trapIntr, 0x1E8

glabel trapIntr
    /* B2B8 801E32B8 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* B2BC 801E32BC 1400B1AF */  sw         $s1, 0x14($sp)
    /* B2C0 801E32C0 1F80113C */  lui        $s1, %hi(D_801F54E0)
    /* B2C4 801E32C4 E0543126 */  addiu      $s1, $s1, %lo(D_801F54E0)
    /* B2C8 801E32C8 2400BFAF */  sw         $ra, 0x24($sp)
    /* B2CC 801E32CC 2000B4AF */  sw         $s4, 0x20($sp)
    /* B2D0 801E32D0 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* B2D4 801E32D4 1800B2AF */  sw         $s2, 0x18($sp)
    /* B2D8 801E32D8 1000B0AF */  sw         $s0, 0x10($sp)
    /* B2DC 801E32DC 00002296 */  lhu        $v0, 0x0($s1)
    /* B2E0 801E32E0 00000000 */  nop
    /* B2E4 801E32E4 0B004014 */  bnez       $v0, .L801E3314
    /* B2E8 801E32E8 00000000 */   nop
    /* B2EC 801E32EC 1F80023C */  lui        $v0, %hi(D_801F656C)
    /* B2F0 801E32F0 6C65428C */  lw         $v0, %lo(D_801F656C)($v0)
    /* B2F4 801E32F4 00000000 */  nop
    /* B2F8 801E32F8 00004594 */  lhu        $a1, 0x0($v0)
    /* B2FC 801E32FC 1E80043C */  lui        $a0, %hi(D_801D9138)
    /* B300 801E3300 38918424 */  addiu      $a0, $a0, %lo(D_801D9138)
    /* B304 801E3304 2568070C */  jal        printf
    /* B308 801E3308 00000000 */   nop
    /* B30C 801E330C DD8D070C */  jal        ReturnFromException
    /* B310 801E3310 00000000 */   nop
  .L801E3314:
    /* B314 801E3314 1F80043C */  lui        $a0, %hi(D_801F656C)
    /* B318 801E3318 6C65848C */  lw         $a0, %lo(D_801F656C)($a0)
    /* B31C 801E331C 1F80033C */  lui        $v1, %hi(D_801F5510)
    /* B320 801E3320 10556394 */  lhu        $v1, %lo(D_801F5510)($v1)
    /* B324 801E3324 01000224 */  addiu      $v0, $zero, 0x1
    /* B328 801E3328 1F80013C */  lui        $at, %hi(D_801F54E2)
    /* B32C 801E332C E25422A4 */  sh         $v0, %lo(D_801F54E2)($at)
    /* B330 801E3330 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B334 801E3334 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B338 801E3338 00008494 */  lhu        $a0, 0x0($a0)
    /* B33C 801E333C 00004294 */  lhu        $v0, 0x0($v0)
    /* B340 801E3340 24186400 */  and        $v1, $v1, $a0
    /* B344 801E3344 24104300 */  and        $v0, $v0, $v1
    /* B348 801E3348 26004010 */  beqz       $v0, .L801E33E4
    /* B34C 801E334C 21804000 */   addu      $s0, $v0, $zero
    /* B350 801E3350 01001324 */  addiu      $s3, $zero, 0x1
    /* B354 801E3354 04003426 */  addiu      $s4, $s1, 0x4
  .L801E3358:
    /* B358 801E3358 16000012 */  beqz       $s0, .L801E33B4
    /* B35C 801E335C 21880000 */   addu      $s1, $zero, $zero
    /* B360 801E3360 21908002 */  addu       $s2, $s4, $zero
  .L801E3364:
    /* B364 801E3364 0B00222A */  slti       $v0, $s1, 0xB
    /* B368 801E3368 12004010 */  beqz       $v0, .L801E33B4
    /* B36C 801E336C 01000232 */   andi      $v0, $s0, 0x1
    /* B370 801E3370 0B004010 */  beqz       $v0, .L801E33A0
    /* B374 801E3374 04103302 */   sllv      $v0, $s3, $s1
    /* B378 801E3378 1F80033C */  lui        $v1, %hi(D_801F656C)
    /* B37C 801E337C 6C65638C */  lw         $v1, %lo(D_801F656C)($v1)
    /* B380 801E3380 27100200 */  nor        $v0, $zero, $v0
    /* B384 801E3384 000062A4 */  sh         $v0, 0x0($v1)
    /* B388 801E3388 0000428E */  lw         $v0, 0x0($s2)
    /* B38C 801E338C 00000000 */  nop
    /* B390 801E3390 03004010 */  beqz       $v0, .L801E33A0
    /* B394 801E3394 00000000 */   nop
    /* B398 801E3398 09F84000 */  jalr       $v0
    /* B39C 801E339C 00000000 */   nop
  .L801E33A0:
    /* B3A0 801E33A0 04005226 */  addiu      $s2, $s2, 0x4
    /* B3A4 801E33A4 42801000 */  srl        $s0, $s0, 1
    /* B3A8 801E33A8 FFFF0232 */  andi       $v0, $s0, 0xFFFF
    /* B3AC 801E33AC EDFF4014 */  bnez       $v0, .L801E3364
    /* B3B0 801E33B0 01003126 */   addiu     $s1, $s1, 0x1
  .L801E33B4:
    /* B3B4 801E33B4 1F80043C */  lui        $a0, %hi(D_801F656C)
    /* B3B8 801E33B8 6C65848C */  lw         $a0, %lo(D_801F656C)($a0)
    /* B3BC 801E33BC 1F80033C */  lui        $v1, %hi(D_801F5510)
    /* B3C0 801E33C0 10556394 */  lhu        $v1, %lo(D_801F5510)($v1)
    /* B3C4 801E33C4 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B3C8 801E33C8 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B3CC 801E33CC 00008494 */  lhu        $a0, 0x0($a0)
    /* B3D0 801E33D0 00004294 */  lhu        $v0, 0x0($v0)
    /* B3D4 801E33D4 24186400 */  and        $v1, $v1, $a0
    /* B3D8 801E33D8 24104300 */  and        $v0, $v0, $v1
    /* B3DC 801E33DC DEFF4014 */  bnez       $v0, .L801E3358
    /* B3E0 801E33E0 21804000 */   addu      $s0, $v0, $zero
  .L801E33E4:
    /* B3E4 801E33E4 1F80053C */  lui        $a1, %hi(D_801F656C)
    /* B3E8 801E33E8 6C65A58C */  lw         $a1, %lo(D_801F656C)($a1)
    /* B3EC 801E33EC 1F80063C */  lui        $a2, %hi(D_801F6570)
    /* B3F0 801E33F0 7065C68C */  lw         $a2, %lo(D_801F6570)($a2)
    /* B3F4 801E33F4 0000A394 */  lhu        $v1, 0x0($a1)
    /* B3F8 801E33F8 0000C294 */  lhu        $v0, 0x0($a2)
    /* B3FC 801E33FC 00000000 */  nop
    /* B400 801E3400 24104300 */  and        $v0, $v0, $v1
    /* B404 801E3404 17004010 */  beqz       $v0, .L801E3464
    /* B408 801E3408 00000000 */   nop
    /* B40C 801E340C 1F80023C */  lui        $v0, %hi(D_801F6578)
    /* B410 801E3410 7865428C */  lw         $v0, %lo(D_801F6578)($v0)
    /* B414 801E3414 00000000 */  nop
    /* B418 801E3418 01004324 */  addiu      $v1, $v0, 0x1
    /* B41C 801E341C 01084228 */  slti       $v0, $v0, 0x801
    /* B420 801E3420 1F80013C */  lui        $at, %hi(D_801F6578)
    /* B424 801E3424 786523AC */  sw         $v1, %lo(D_801F6578)($at)
    /* B428 801E3428 10004014 */  bnez       $v0, .L801E346C
    /* B42C 801E342C 00000000 */   nop
    /* B430 801E3430 1E80043C */  lui        $a0, %hi(D_801D9154)
    /* B434 801E3434 54918424 */  addiu      $a0, $a0, %lo(D_801D9154)
    /* B438 801E3438 0000A594 */  lhu        $a1, 0x0($a1)
    /* B43C 801E343C 0000C694 */  lhu        $a2, 0x0($a2)
    /* B440 801E3440 2568070C */  jal        printf
    /* B444 801E3444 00000000 */   nop
    /* B448 801E3448 1F80023C */  lui        $v0, %hi(D_801F656C)
    /* B44C 801E344C 6C65428C */  lw         $v0, %lo(D_801F656C)($v0)
    /* B450 801E3450 1F80013C */  lui        $at, %hi(D_801F6578)
    /* B454 801E3454 786520AC */  sw         $zero, %lo(D_801F6578)($at)
    /* B458 801E3458 000040A4 */  sh         $zero, 0x0($v0)
    /* B45C 801E345C 1B8D0708 */  j          .L801E346C
    /* B460 801E3460 00000000 */   nop
  .L801E3464:
    /* B464 801E3464 1F80013C */  lui        $at, %hi(D_801F6578)
    /* B468 801E3468 786520AC */  sw         $zero, %lo(D_801F6578)($at)
  .L801E346C:
    /* B46C 801E346C 1F80013C */  lui        $at, %hi(D_801F54E2)
    /* B470 801E3470 E25420A4 */  sh         $zero, %lo(D_801F54E2)($at)
    /* B474 801E3474 DD8D070C */  jal        ReturnFromException
    /* B478 801E3478 00000000 */   nop
    /* B47C 801E347C 2400BF8F */  lw         $ra, 0x24($sp)
    /* B480 801E3480 2000B48F */  lw         $s4, 0x20($sp)
    /* B484 801E3484 1C00B38F */  lw         $s3, 0x1C($sp)
    /* B488 801E3488 1800B28F */  lw         $s2, 0x18($sp)
    /* B48C 801E348C 1400B18F */  lw         $s1, 0x14($sp)
    /* B490 801E3490 1000B08F */  lw         $s0, 0x10($sp)
    /* B494 801E3494 2800BD27 */  addiu      $sp, $sp, 0x28
    /* B498 801E3498 0800E003 */  jr         $ra
    /* B49C 801E349C 00000000 */   nop
endlabel trapIntr

nonmatching setIntr, 0x154

glabel setIntr
    /* B4A0 801E34A0 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* B4A4 801E34A4 1400B1AF */  sw         $s1, 0x14($sp)
    /* B4A8 801E34A8 21888000 */  addu       $s1, $a0, $zero
    /* B4AC 801E34AC 1800B2AF */  sw         $s2, 0x18($sp)
    /* B4B0 801E34B0 2190A000 */  addu       $s2, $a1, $zero
    /* B4B4 801E34B4 1F80053C */  lui        $a1, %hi(D_801F54E4)
    /* B4B8 801E34B8 E454A524 */  addiu      $a1, $a1, %lo(D_801F54E4)
    /* B4BC 801E34BC 80101100 */  sll        $v0, $s1, 2
    /* B4C0 801E34C0 21204500 */  addu       $a0, $v0, $a1
    /* B4C4 801E34C4 2400BFAF */  sw         $ra, 0x24($sp)
    /* B4C8 801E34C8 2000B4AF */  sw         $s4, 0x20($sp)
    /* B4CC 801E34CC 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* B4D0 801E34D0 1000B0AF */  sw         $s0, 0x10($sp)
    /* B4D4 801E34D4 0000948C */  lw         $s4, 0x0($a0)
    /* B4D8 801E34D8 00000000 */  nop
    /* B4DC 801E34DC 3C005412 */  beq        $s2, $s4, .L801E35D0
    /* B4E0 801E34E0 21108002 */   addu      $v0, $s4, $zero
    /* B4E4 801E34E4 FCFFA294 */  lhu        $v0, -0x4($a1)
    /* B4E8 801E34E8 00000000 */  nop
    /* B4EC 801E34EC 38004010 */  beqz       $v0, .L801E35D0
    /* B4F0 801E34F0 21108002 */   addu      $v0, $s4, $zero
    /* B4F4 801E34F4 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B4F8 801E34F8 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B4FC 801E34FC 00000000 */  nop
    /* B500 801E3500 00004394 */  lhu        $v1, 0x0($v0)
    /* B504 801E3504 000040A4 */  sh         $zero, 0x0($v0)
    /* B508 801E3508 09004012 */  beqz       $s2, .L801E3530
    /* B50C 801E350C FFFF7330 */   andi      $s3, $v1, 0xFFFF
    /* B510 801E3510 01000324 */  addiu      $v1, $zero, 0x1
    /* B514 801E3514 04182302 */  sllv       $v1, $v1, $s1
    /* B518 801E3518 000092AC */  sw         $s2, 0x0($a0)
    /* B51C 801E351C 2C00A294 */  lhu        $v0, 0x2C($a1)
    /* B520 801E3520 25986302 */  or         $s3, $s3, $v1
    /* B524 801E3524 25104300 */  or         $v0, $v0, $v1
    /* B528 801E3528 568D0708 */  j          .L801E3558
    /* B52C 801E352C 2C00A2A4 */   sh        $v0, 0x2C($a1)
  .L801E3530:
    /* B530 801E3530 01000224 */  addiu      $v0, $zero, 0x1
    /* B534 801E3534 04102202 */  sllv       $v0, $v0, $s1
    /* B538 801E3538 27100200 */  nor        $v0, $zero, $v0
    /* B53C 801E353C 000080AC */  sw         $zero, 0x0($a0)
    /* B540 801E3540 1F80033C */  lui        $v1, %hi(D_801F5510)
    /* B544 801E3544 10556394 */  lhu        $v1, %lo(D_801F5510)($v1)
    /* B548 801E3548 24986202 */  and        $s3, $s3, $v0
    /* B54C 801E354C 24186200 */  and        $v1, $v1, $v0
    /* B550 801E3550 1F80013C */  lui        $at, %hi(D_801F5510)
    /* B554 801E3554 105523A4 */  sh         $v1, %lo(D_801F5510)($at)
  .L801E3558:
    /* B558 801E3558 08002016 */  bnez       $s1, .L801E357C
    /* B55C 801E355C 04000224 */   addiu     $v0, $zero, 0x4
    /* B560 801E3560 0100502E */  sltiu      $s0, $s2, 0x1
    /* B564 801E3564 408A070C */  jal        ChangeClearPAD
    /* B568 801E3568 21200002 */   addu      $a0, $s0, $zero
    /* B56C 801E356C 03000424 */  addiu      $a0, $zero, 0x3
    /* B570 801E3570 0D8C070C */  jal        ChangeClearRCnt
    /* B574 801E3574 21280002 */   addu      $a1, $s0, $zero
    /* B578 801E3578 04000224 */  addiu      $v0, $zero, 0x4
  .L801E357C:
    /* B57C 801E357C 05002216 */  bne        $s1, $v0, .L801E3594
    /* B580 801E3580 05000224 */   addiu     $v0, $zero, 0x5
    /* B584 801E3584 21200000 */  addu       $a0, $zero, $zero
    /* B588 801E3588 0D8C070C */  jal        ChangeClearRCnt
    /* B58C 801E358C 0100452E */   sltiu     $a1, $s2, 0x1
    /* B590 801E3590 05000224 */  addiu      $v0, $zero, 0x5
  .L801E3594:
    /* B594 801E3594 05002216 */  bne        $s1, $v0, .L801E35AC
    /* B598 801E3598 06000224 */   addiu     $v0, $zero, 0x6
    /* B59C 801E359C 01000424 */  addiu      $a0, $zero, 0x1
    /* B5A0 801E35A0 0D8C070C */  jal        ChangeClearRCnt
    /* B5A4 801E35A4 0100452E */   sltiu     $a1, $s2, 0x1
    /* B5A8 801E35A8 06000224 */  addiu      $v0, $zero, 0x6
  .L801E35AC:
    /* B5AC 801E35AC 03002216 */  bne        $s1, $v0, .L801E35BC
    /* B5B0 801E35B0 02000424 */   addiu     $a0, $zero, 0x2
    /* B5B4 801E35B4 0D8C070C */  jal        ChangeClearRCnt
    /* B5B8 801E35B8 0100452E */   sltiu     $a1, $s2, 0x1
  .L801E35BC:
    /* B5BC 801E35BC 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B5C0 801E35C0 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B5C4 801E35C4 00000000 */  nop
    /* B5C8 801E35C8 000053A4 */  sh         $s3, 0x0($v0)
    /* B5CC 801E35CC 21108002 */  addu       $v0, $s4, $zero
  .L801E35D0:
    /* B5D0 801E35D0 2400BF8F */  lw         $ra, 0x24($sp)
    /* B5D4 801E35D4 2000B48F */  lw         $s4, 0x20($sp)
    /* B5D8 801E35D8 1C00B38F */  lw         $s3, 0x1C($sp)
    /* B5DC 801E35DC 1800B28F */  lw         $s2, 0x18($sp)
    /* B5E0 801E35E0 1400B18F */  lw         $s1, 0x14($sp)
    /* B5E4 801E35E4 1000B08F */  lw         $s0, 0x10($sp)
    /* B5E8 801E35E8 2800BD27 */  addiu      $sp, $sp, 0x28
    /* B5EC 801E35EC 0800E003 */  jr         $ra
    /* B5F0 801E35F0 00000000 */   nop
endlabel setIntr

nonmatching stopIntr, 0xAC

glabel stopIntr
    /* B5F4 801E35F4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B5F8 801E35F8 1000B0AF */  sw         $s0, 0x10($sp)
    /* B5FC 801E35FC 1F80103C */  lui        $s0, %hi(D_801F54E0)
    /* B600 801E3600 E0541026 */  addiu      $s0, $s0, %lo(D_801F54E0)
    /* B604 801E3604 1400BFAF */  sw         $ra, 0x14($sp)
    /* B608 801E3608 00000296 */  lhu        $v0, 0x0($s0)
    /* B60C 801E360C 00000000 */  nop
    /* B610 801E3610 1E004010 */  beqz       $v0, .L801E368C
    /* B614 801E3614 21100000 */   addu      $v0, $zero, $zero
    /* B618 801E3618 6286070C */  jal        EnterCriticalSection
    /* B61C 801E361C 00000000 */   nop
    /* B620 801E3620 1F80023C */  lui        $v0, %hi(D_801F6570)
    /* B624 801E3624 7065428C */  lw         $v0, %lo(D_801F6570)($v0)
    /* B628 801E3628 1F80043C */  lui        $a0, %hi(D_801F6574)
    /* B62C 801E362C 7465848C */  lw         $a0, %lo(D_801F6574)($a0)
    /* B630 801E3630 00004394 */  lhu        $v1, 0x0($v0)
    /* B634 801E3634 1F80013C */  lui        $at, %hi(D_801F5512)
    /* B638 801E3638 125523A4 */  sh         $v1, %lo(D_801F5512)($at)
    /* B63C 801E363C 0000838C */  lw         $v1, 0x0($a0)
    /* B640 801E3640 1F80043C */  lui        $a0, %hi(D_801F656C)
    /* B644 801E3644 6C65848C */  lw         $a0, %lo(D_801F656C)($a0)
    /* B648 801E3648 1F80013C */  lui        $at, %hi(D_801F5514)
    /* B64C 801E364C 145523AC */  sw         $v1, %lo(D_801F5514)($at)
    /* B650 801E3650 000040A4 */  sh         $zero, 0x0($v0)
    /* B654 801E3654 00004294 */  lhu        $v0, 0x0($v0)
    /* B658 801E3658 00000000 */  nop
    /* B65C 801E365C 000082A4 */  sh         $v0, 0x0($a0)
    /* B660 801E3660 1F80043C */  lui        $a0, %hi(D_801F6574)
    /* B664 801E3664 7465848C */  lw         $a0, %lo(D_801F6574)($a0)
    /* B668 801E3668 7777033C */  lui        $v1, (0x77777777 >> 16)
    /* B66C 801E366C 0000828C */  lw         $v0, 0x0($a0)
    /* B670 801E3670 77776334 */  ori        $v1, $v1, (0x77777777 & 0xFFFF)
    /* B674 801E3674 24104300 */  and        $v0, $v0, $v1
    /* B678 801E3678 000082AC */  sw         $v0, 0x0($a0)
    /* B67C 801E367C E18D070C */  jal        ResetEntryInt
    /* B680 801E3680 00000000 */   nop
    /* B684 801E3684 21100002 */  addu       $v0, $s0, $zero
    /* B688 801E3688 000040A4 */  sh         $zero, 0x0($v0)
  .L801E368C:
    /* B68C 801E368C 1400BF8F */  lw         $ra, 0x14($sp)
    /* B690 801E3690 1000B08F */  lw         $s0, 0x10($sp)
    /* B694 801E3694 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B698 801E3698 0800E003 */  jr         $ra
    /* B69C 801E369C 00000000 */   nop
endlabel stopIntr

nonmatching restartIntr, 0x88

glabel restartIntr
    /* B6A0 801E36A0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B6A4 801E36A4 1000B0AF */  sw         $s0, 0x10($sp)
    /* B6A8 801E36A8 1F80103C */  lui        $s0, %hi(D_801F54E0)
    /* B6AC 801E36AC E0541026 */  addiu      $s0, $s0, %lo(D_801F54E0)
    /* B6B0 801E36B0 1400BFAF */  sw         $ra, 0x14($sp)
    /* B6B4 801E36B4 00000296 */  lhu        $v0, 0x0($s0)
    /* B6B8 801E36B8 00000000 */  nop
    /* B6BC 801E36BC 14004014 */  bnez       $v0, .L801E3710
    /* B6C0 801E36C0 00000000 */   nop
    /* B6C4 801E36C4 E58D070C */  jal        HookEntryInt
    /* B6C8 801E36C8 38000426 */   addiu     $a0, $s0, 0x38
    /* B6CC 801E36CC 1F80043C */  lui        $a0, %hi(D_801F6570)
    /* B6D0 801E36D0 7065848C */  lw         $a0, %lo(D_801F6570)($a0)
    /* B6D4 801E36D4 1F80033C */  lui        $v1, %hi(D_801F5512)
    /* B6D8 801E36D8 12556394 */  lhu        $v1, %lo(D_801F5512)($v1)
    /* B6DC 801E36DC 01000224 */  addiu      $v0, $zero, 0x1
    /* B6E0 801E36E0 000002A6 */  sh         $v0, 0x0($s0)
    /* B6E4 801E36E4 000083A4 */  sh         $v1, 0x0($a0)
    /* B6E8 801E36E8 1F80033C */  lui        $v1, %hi(D_801F6574)
    /* B6EC 801E36EC 7465638C */  lw         $v1, %lo(D_801F6574)($v1)
    /* B6F0 801E36F0 1F80023C */  lui        $v0, %hi(D_801F5514)
    /* B6F4 801E36F4 1455428C */  lw         $v0, %lo(D_801F5514)($v0)
    /* B6F8 801E36F8 00000000 */  nop
    /* B6FC 801E36FC 000062AC */  sw         $v0, 0x0($v1)
    /* B700 801E3700 6686070C */  jal        ExitCriticalSection
    /* B704 801E3704 00000000 */   nop
    /* B708 801E3708 C58D0708 */  j          .L801E3714
    /* B70C 801E370C 21100002 */   addu      $v0, $s0, $zero
  .L801E3710:
    /* B710 801E3710 21100000 */  addu       $v0, $zero, $zero
  .L801E3714:
    /* B714 801E3714 1400BF8F */  lw         $ra, 0x14($sp)
    /* B718 801E3718 1000B08F */  lw         $s0, 0x10($sp)
    /* B71C 801E371C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B720 801E3720 0800E003 */  jr         $ra
    /* B724 801E3724 00000000 */   nop
endlabel restartIntr

nonmatching memclr, 0x2C

glabel memclr
    /* B728 801E3728 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* B72C 801E372C 0600A010 */  beqz       $a1, .L801E3748
    /* B730 801E3730 FFFFA224 */   addiu     $v0, $a1, -0x1
    /* B734 801E3734 FFFF0324 */  addiu      $v1, $zero, -0x1
  .L801E3738:
    /* B738 801E3738 000080AC */  sw         $zero, 0x0($a0)
    /* B73C 801E373C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* B740 801E3740 FDFF4314 */  bne        $v0, $v1, .L801E3738
    /* B744 801E3744 04008424 */   addiu     $a0, $a0, 0x4
  .L801E3748:
    /* B748 801E3748 0800BD27 */  addiu      $sp, $sp, 0x8
    /* B74C 801E374C 0800E003 */  jr         $ra
    /* B750 801E3750 00000000 */   nop
endlabel memclr
