.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching startIntrVSync, 0x58

glabel startIntrVSync
    /* B824 801E3824 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B828 801E3828 1F80043C */  lui        $a0, %hi(D_801F657C)
    /* B82C 801E382C 7C658424 */  addiu      $a0, $a0, %lo(D_801F657C)
    /* B830 801E3830 1F80033C */  lui        $v1, %hi(D_801F65A0)
    /* B834 801E3834 A065638C */  lw         $v1, %lo(D_801F65A0)($v1)
    /* B838 801E3838 07010224 */  addiu      $v0, $zero, 0x107
    /* B83C 801E383C 1000BFAF */  sw         $ra, 0x10($sp)
    /* B840 801E3840 000062AC */  sw         $v0, 0x0($v1)
    /* B844 801E3844 1F80013C */  lui        $at, %hi(D_801F659C)
    /* B848 801E3848 9C6520AC */  sw         $zero, %lo(D_801F659C)($at)
    /* B84C 801E384C 488E070C */  jal        memclr_INTR_VB
    /* B850 801E3850 08000524 */   addiu     $a1, $zero, 0x8
    /* B854 801E3854 1E80053C */  lui        $a1, %hi(trapIntrVSync)
    /* B858 801E3858 7C38A524 */  addiu      $a1, $a1, %lo(trapIntrVSync)
    /* B85C 801E385C 1D8C070C */  jal        InterruptCallback
    /* B860 801E3860 21200000 */   addu      $a0, $zero, $zero
    /* B864 801E3864 1E80023C */  lui        $v0, %hi(setIntrVSync)
    /* B868 801E3868 F4384224 */  addiu      $v0, $v0, %lo(setIntrVSync)
    /* B86C 801E386C 1000BF8F */  lw         $ra, 0x10($sp)
    /* B870 801E3870 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B874 801E3874 0800E003 */  jr         $ra
    /* B878 801E3878 00000000 */   nop
endlabel startIntrVSync

nonmatching trapIntrVSync, 0x78

glabel trapIntrVSync
    /* B87C 801E387C 1F80023C */  lui        $v0, %hi(D_801F659C)
    /* B880 801E3880 9C65428C */  lw         $v0, %lo(D_801F659C)($v0)
    /* B884 801E3884 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* B888 801E3888 1400B1AF */  sw         $s1, 0x14($sp)
    /* B88C 801E388C 21880000 */  addu       $s1, $zero, $zero
    /* B890 801E3890 1000B0AF */  sw         $s0, 0x10($sp)
    /* B894 801E3894 1F80103C */  lui        $s0, %hi(D_801F657C)
    /* B898 801E3898 7C651026 */  addiu      $s0, $s0, %lo(D_801F657C)
    /* B89C 801E389C 1800BFAF */  sw         $ra, 0x18($sp)
    /* B8A0 801E38A0 01004224 */  addiu      $v0, $v0, 0x1
    /* B8A4 801E38A4 1F80013C */  lui        $at, %hi(D_801F659C)
    /* B8A8 801E38A8 9C6522AC */  sw         $v0, %lo(D_801F659C)($at)
    /* B8AC 801E38AC 1F80023C */  lui        $v0, %hi(D_801F659C)
    /* B8B0 801E38B0 9C65428C */  lw         $v0, %lo(D_801F659C)($v0)
  .L801E38B4:
    /* B8B4 801E38B4 0000028E */  lw         $v0, 0x0($s0)
    /* B8B8 801E38B8 00000000 */  nop
    /* B8BC 801E38BC 03004010 */  beqz       $v0, .L801E38CC
    /* B8C0 801E38C0 00000000 */   nop
    /* B8C4 801E38C4 09F84000 */  jalr       $v0
    /* B8C8 801E38C8 00000000 */   nop
  .L801E38CC:
    /* B8CC 801E38CC 01003126 */  addiu      $s1, $s1, 0x1
    /* B8D0 801E38D0 0800222A */  slti       $v0, $s1, 0x8
    /* B8D4 801E38D4 F7FF4014 */  bnez       $v0, .L801E38B4
    /* B8D8 801E38D8 04001026 */   addiu     $s0, $s0, 0x4
    /* B8DC 801E38DC 1800BF8F */  lw         $ra, 0x18($sp)
    /* B8E0 801E38E0 1400B18F */  lw         $s1, 0x14($sp)
    /* B8E4 801E38E4 1000B08F */  lw         $s0, 0x10($sp)
    /* B8E8 801E38E8 2000BD27 */  addiu      $sp, $sp, 0x20
    /* B8EC 801E38EC 0800E003 */  jr         $ra
    /* B8F0 801E38F0 00000000 */   nop
endlabel trapIntrVSync

nonmatching setIntrVSync, 0x2C

glabel setIntrVSync
    /* B8F4 801E38F4 1F80023C */  lui        $v0, %hi(D_801F657C)
    /* B8F8 801E38F8 7C654224 */  addiu      $v0, $v0, %lo(D_801F657C)
    /* B8FC 801E38FC 80200400 */  sll        $a0, $a0, 2
    /* B900 801E3900 21208200 */  addu       $a0, $a0, $v0
    /* B904 801E3904 0000828C */  lw         $v0, 0x0($a0)
    /* B908 801E3908 00000000 */  nop
    /* B90C 801E390C 0200A210 */  beq        $a1, $v0, .L801E3918
    /* B910 801E3910 00000000 */   nop
    /* B914 801E3914 000085AC */  sw         $a1, 0x0($a0)
  .L801E3918:
    /* B918 801E3918 0800E003 */  jr         $ra
    /* B91C 801E391C 00000000 */   nop
endlabel setIntrVSync

nonmatching memclr_INTR_VB, 0x2C

glabel memclr_INTR_VB
    /* B920 801E3920 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* B924 801E3924 0600A010 */  beqz       $a1, .L801E3940
    /* B928 801E3928 FFFFA224 */   addiu     $v0, $a1, -0x1
    /* B92C 801E392C FFFF0324 */  addiu      $v1, $zero, -0x1
  .L801E3930:
    /* B930 801E3930 000080AC */  sw         $zero, 0x0($a0)
    /* B934 801E3934 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* B938 801E3938 FDFF4314 */  bne        $v0, $v1, .L801E3930
    /* B93C 801E393C 04008424 */   addiu     $a0, $a0, 0x4
  .L801E3940:
    /* B940 801E3940 0800BD27 */  addiu      $sp, $sp, 0x8
    /* B944 801E3944 0800E003 */  jr         $ra
    /* B948 801E3948 00000000 */   nop
endlabel memclr_INTR_VB
