.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching startIntrDMA, 0x50

glabel startIntrDMA
    /* B94C 801E394C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* B950 801E3950 1F80043C */  lui        $a0, %hi(D_801F65A8)
    /* B954 801E3954 A8658424 */  addiu      $a0, $a0, %lo(D_801F65A8)
    /* B958 801E3958 1000BFAF */  sw         $ra, 0x10($sp)
    /* B95C 801E395C F28E070C */  jal        memclr_INTR_DMA
    /* B960 801E3960 08000524 */   addiu     $a1, $zero, 0x8
    /* B964 801E3964 03000424 */  addiu      $a0, $zero, 0x3
    /* B968 801E3968 1F80023C */  lui        $v0, %hi(D_801F65A4)
    /* B96C 801E396C A465428C */  lw         $v0, %lo(D_801F65A4)($v0)
    /* B970 801E3970 1E80053C */  lui        $a1, %hi(trapIntrDMA)
    /* B974 801E3974 9C39A524 */  addiu      $a1, $a1, %lo(trapIntrDMA)
    /* B978 801E3978 000040AC */  sw         $zero, 0x0($v0)
    /* B97C 801E397C 1D8C070C */  jal        InterruptCallback
    /* B980 801E3980 00000000 */   nop
    /* B984 801E3984 1E80023C */  lui        $v0, %hi(setIntrDMA)
    /* B988 801E3988 203B4224 */  addiu      $v0, $v0, %lo(setIntrDMA)
    /* B98C 801E398C 1000BF8F */  lw         $ra, 0x10($sp)
    /* B990 801E3990 1800BD27 */  addiu      $sp, $sp, 0x18
    /* B994 801E3994 0800E003 */  jr         $ra
    /* B998 801E3998 00000000 */   nop
endlabel startIntrDMA

nonmatching trapIntrDMA, 0x184

glabel trapIntrDMA
    /* B99C 801E399C 1F80023C */  lui        $v0, %hi(D_801F65A4)
    /* B9A0 801E39A0 A465428C */  lw         $v0, %lo(D_801F65A4)($v0)
    /* B9A4 801E39A4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* B9A8 801E39A8 2800BFAF */  sw         $ra, 0x28($sp)
    /* B9AC 801E39AC 2400B5AF */  sw         $s5, 0x24($sp)
    /* B9B0 801E39B0 2000B4AF */  sw         $s4, 0x20($sp)
    /* B9B4 801E39B4 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* B9B8 801E39B8 1800B2AF */  sw         $s2, 0x18($sp)
    /* B9BC 801E39BC 1400B1AF */  sw         $s1, 0x14($sp)
    /* B9C0 801E39C0 1000B0AF */  sw         $s0, 0x10($sp)
    /* B9C4 801E39C4 0000428C */  lw         $v0, 0x0($v0)
    /* B9C8 801E39C8 00000000 */  nop
    /* B9CC 801E39CC 02160200 */  srl        $v0, $v0, 24
    /* B9D0 801E39D0 7F005130 */  andi       $s1, $v0, 0x7F
    /* B9D4 801E39D4 28002012 */  beqz       $s1, .L801E3A78
    /* B9D8 801E39D8 00000000 */   nop
    /* B9DC 801E39DC 01001424 */  addiu      $s4, $zero, 0x1
    /* B9E0 801E39E0 FF00133C */  lui        $s3, (0xFFFFFF >> 16)
    /* B9E4 801E39E4 FFFF7336 */  ori        $s3, $s3, (0xFFFFFF & 0xFFFF)
    /* B9E8 801E39E8 1F80153C */  lui        $s5, %hi(D_801F65A8)
    /* B9EC 801E39EC A865B526 */  addiu      $s5, $s5, %lo(D_801F65A8)
  .L801E39F0:
    /* B9F0 801E39F0 18002012 */  beqz       $s1, .L801E3A54
    /* B9F4 801E39F4 21800000 */   addu      $s0, $zero, $zero
    /* B9F8 801E39F8 2190A002 */  addu       $s2, $s5, $zero
  .L801E39FC:
    /* B9FC 801E39FC 0700022A */  slti       $v0, $s0, 0x7
    /* BA00 801E3A00 14004010 */  beqz       $v0, .L801E3A54
    /* BA04 801E3A04 01002232 */   andi      $v0, $s1, 0x1
    /* BA08 801E3A08 0E004010 */  beqz       $v0, .L801E3A44
    /* BA0C 801E3A0C 18000226 */   addiu     $v0, $s0, 0x18
    /* BA10 801E3A10 1F80043C */  lui        $a0, %hi(D_801F65A4)
    /* BA14 801E3A14 A465848C */  lw         $a0, %lo(D_801F65A4)($a0)
    /* BA18 801E3A18 04105400 */  sllv       $v0, $s4, $v0
    /* BA1C 801E3A1C 0000838C */  lw         $v1, 0x0($a0)
    /* BA20 801E3A20 25105300 */  or         $v0, $v0, $s3
    /* BA24 801E3A24 24186200 */  and        $v1, $v1, $v0
    /* BA28 801E3A28 000083AC */  sw         $v1, 0x0($a0)
    /* BA2C 801E3A2C 0000428E */  lw         $v0, 0x0($s2)
    /* BA30 801E3A30 00000000 */  nop
    /* BA34 801E3A34 03004010 */  beqz       $v0, .L801E3A44
    /* BA38 801E3A38 00000000 */   nop
    /* BA3C 801E3A3C 09F84000 */  jalr       $v0
    /* BA40 801E3A40 00000000 */   nop
  .L801E3A44:
    /* BA44 801E3A44 04005226 */  addiu      $s2, $s2, 0x4
    /* BA48 801E3A48 42881100 */  srl        $s1, $s1, 1
    /* BA4C 801E3A4C EBFF2016 */  bnez       $s1, .L801E39FC
    /* BA50 801E3A50 01001026 */   addiu     $s0, $s0, 0x1
  .L801E3A54:
    /* BA54 801E3A54 1F80023C */  lui        $v0, %hi(D_801F65A4)
    /* BA58 801E3A58 A465428C */  lw         $v0, %lo(D_801F65A4)($v0)
    /* BA5C 801E3A5C 00000000 */  nop
    /* BA60 801E3A60 0000428C */  lw         $v0, 0x0($v0)
    /* BA64 801E3A64 00000000 */  nop
    /* BA68 801E3A68 02160200 */  srl        $v0, $v0, 24
    /* BA6C 801E3A6C 7F005130 */  andi       $s1, $v0, 0x7F
    /* BA70 801E3A70 DFFF2016 */  bnez       $s1, .L801E39F0
    /* BA74 801E3A74 00000000 */   nop
  .L801E3A78:
    /* BA78 801E3A78 1F80053C */  lui        $a1, %hi(D_801F65A4)
    /* BA7C 801E3A7C A465A58C */  lw         $a1, %lo(D_801F65A4)($a1)
    /* BA80 801E3A80 00000000 */  nop
    /* BA84 801E3A84 0000A28C */  lw         $v0, 0x0($a1)
    /* BA88 801E3A88 00FF033C */  lui        $v1, (0xFF000000 >> 16)
    /* BA8C 801E3A8C 24104300 */  and        $v0, $v0, $v1
    /* BA90 801E3A90 0080033C */  lui        $v1, (0x80000000 >> 16)
    /* BA94 801E3A94 06004310 */  beq        $v0, $v1, .L801E3AB0
    /* BA98 801E3A98 00000000 */   nop
    /* BA9C 801E3A9C 0000A28C */  lw         $v0, 0x0($a1)
    /* BAA0 801E3AA0 00000000 */  nop
    /* BAA4 801E3AA4 00804230 */  andi       $v0, $v0, 0x8000
    /* BAA8 801E3AA8 13004010 */  beqz       $v0, .L801E3AF8
    /* BAAC 801E3AAC 00000000 */   nop
  .L801E3AB0:
    /* BAB0 801E3AB0 1E80043C */  lui        $a0, %hi(D_801D9170)
    /* BAB4 801E3AB4 70918424 */  addiu      $a0, $a0, %lo(D_801D9170)
    /* BAB8 801E3AB8 0000A58C */  lw         $a1, 0x0($a1)
    /* BABC 801E3ABC 2568070C */  jal        printf
    /* BAC0 801E3AC0 21800000 */   addu      $s0, $zero, $zero
  .L801E3AC4:
    /* BAC4 801E3AC4 1E80043C */  lui        $a0, %hi(D_801D918C)
    /* BAC8 801E3AC8 8C918424 */  addiu      $a0, $a0, %lo(D_801D918C)
    /* BACC 801E3ACC 21280002 */  addu       $a1, $s0, $zero
    /* BAD0 801E3AD0 1F80023C */  lui        $v0, %hi(D_801F65C8)
    /* BAD4 801E3AD4 C865428C */  lw         $v0, %lo(D_801F65C8)($v0)
    /* BAD8 801E3AD8 00191000 */  sll        $v1, $s0, 4
    /* BADC 801E3ADC 21186200 */  addu       $v1, $v1, $v0
    /* BAE0 801E3AE0 0000668C */  lw         $a2, 0x0($v1)
    /* BAE4 801E3AE4 2568070C */  jal        printf
    /* BAE8 801E3AE8 01001026 */   addiu     $s0, $s0, 0x1
    /* BAEC 801E3AEC 0700022A */  slti       $v0, $s0, 0x7
    /* BAF0 801E3AF0 F4FF4014 */  bnez       $v0, .L801E3AC4
    /* BAF4 801E3AF4 00000000 */   nop
  .L801E3AF8:
    /* BAF8 801E3AF8 2800BF8F */  lw         $ra, 0x28($sp)
    /* BAFC 801E3AFC 2400B58F */  lw         $s5, 0x24($sp)
    /* BB00 801E3B00 2000B48F */  lw         $s4, 0x20($sp)
    /* BB04 801E3B04 1C00B38F */  lw         $s3, 0x1C($sp)
    /* BB08 801E3B08 1800B28F */  lw         $s2, 0x18($sp)
    /* BB0C 801E3B0C 1400B18F */  lw         $s1, 0x14($sp)
    /* BB10 801E3B10 1000B08F */  lw         $s0, 0x10($sp)
    /* BB14 801E3B14 3000BD27 */  addiu      $sp, $sp, 0x30
    /* BB18 801E3B18 0800E003 */  jr         $ra
    /* BB1C 801E3B1C 00000000 */   nop
endlabel trapIntrDMA

nonmatching setIntrDMA, 0xA8

glabel setIntrDMA
    /* BB20 801E3B20 21308000 */  addu       $a2, $a0, $zero
    /* BB24 801E3B24 1F80033C */  lui        $v1, %hi(D_801F65A8)
    /* BB28 801E3B28 A8656324 */  addiu      $v1, $v1, %lo(D_801F65A8)
    /* BB2C 801E3B2C 80100600 */  sll        $v0, $a2, 2
    /* BB30 801E3B30 21184300 */  addu       $v1, $v0, $v1
    /* BB34 801E3B34 0000678C */  lw         $a3, 0x0($v1)
    /* BB38 801E3B38 2120A000 */  addu       $a0, $a1, $zero
    /* BB3C 801E3B3C 20008710 */  beq        $a0, $a3, .L801E3BC0
    /* BB40 801E3B40 00000000 */   nop
    /* BB44 801E3B44 10008010 */  beqz       $a0, .L801E3B88
    /* BB48 801E3B48 FF00023C */   lui       $v0, (0xFFFFFF >> 16)
    /* BB4C 801E3B4C 1F80053C */  lui        $a1, %hi(D_801F65A4)
    /* BB50 801E3B50 A465A58C */  lw         $a1, %lo(D_801F65A4)($a1)
    /* BB54 801E3B54 FFFF4234 */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* BB58 801E3B58 000064AC */  sw         $a0, 0x0($v1)
    /* BB5C 801E3B5C 0000A48C */  lw         $a0, 0x0($a1)
    /* BB60 801E3B60 1000C324 */  addiu      $v1, $a2, 0x10
    /* BB64 801E3B64 24208200 */  and        $a0, $a0, $v0
    /* BB68 801E3B68 01000224 */  addiu      $v0, $zero, 0x1
    /* BB6C 801E3B6C 04106200 */  sllv       $v0, $v0, $v1
    /* BB70 801E3B70 8000033C */  lui        $v1, (0x800000 >> 16)
    /* BB74 801E3B74 25104300 */  or         $v0, $v0, $v1
    /* BB78 801E3B78 25208200 */  or         $a0, $a0, $v0
    /* BB7C 801E3B7C 0000A4AC */  sw         $a0, 0x0($a1)
    /* BB80 801E3B80 F08E0708 */  j          .L801E3BC0
    /* BB84 801E3B84 00000000 */   nop
  .L801E3B88:
    /* BB88 801E3B88 1F80053C */  lui        $a1, %hi(D_801F65A4)
    /* BB8C 801E3B8C A465A58C */  lw         $a1, %lo(D_801F65A4)($a1)
    /* BB90 801E3B90 FFFF4234 */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* BB94 801E3B94 000060AC */  sw         $zero, 0x0($v1)
    /* BB98 801E3B98 0000A38C */  lw         $v1, 0x0($a1)
    /* BB9C 801E3B9C 1000C424 */  addiu      $a0, $a2, 0x10
    /* BBA0 801E3BA0 24186200 */  and        $v1, $v1, $v0
    /* BBA4 801E3BA4 8000023C */  lui        $v0, (0x800000 >> 16)
    /* BBA8 801E3BA8 25186200 */  or         $v1, $v1, $v0
    /* BBAC 801E3BAC 01000224 */  addiu      $v0, $zero, 0x1
    /* BBB0 801E3BB0 04108200 */  sllv       $v0, $v0, $a0
    /* BBB4 801E3BB4 27100200 */  nor        $v0, $zero, $v0
    /* BBB8 801E3BB8 24186200 */  and        $v1, $v1, $v0
    /* BBBC 801E3BBC 0000A3AC */  sw         $v1, 0x0($a1)
  .L801E3BC0:
    /* BBC0 801E3BC0 0800E003 */  jr         $ra
    /* BBC4 801E3BC4 2110E000 */   addu      $v0, $a3, $zero
endlabel setIntrDMA

nonmatching memclr_INTR_DMA, 0x2C

glabel memclr_INTR_DMA
    /* BBC8 801E3BC8 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* BBCC 801E3BCC 0600A010 */  beqz       $a1, .L801E3BE8
    /* BBD0 801E3BD0 FFFFA224 */   addiu     $v0, $a1, -0x1
    /* BBD4 801E3BD4 FFFF0324 */  addiu      $v1, $zero, -0x1
  .L801E3BD8:
    /* BBD8 801E3BD8 000080AC */  sw         $zero, 0x0($a0)
    /* BBDC 801E3BDC FFFF4224 */  addiu      $v0, $v0, -0x1
    /* BBE0 801E3BE0 FDFF4314 */  bne        $v0, $v1, .L801E3BD8
    /* BBE4 801E3BE4 04008424 */   addiu     $a0, $a0, 0x4
  .L801E3BE8:
    /* BBE8 801E3BE8 0800BD27 */  addiu      $sp, $sp, 0x8
    /* BBEC 801E3BEC 0800E003 */  jr         $ra
    /* BBF0 801E3BF0 00000000 */   nop
endlabel memclr_INTR_DMA
