.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching PadInit, 0x50

glabel PadInit
    /* A858 801E2858 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* A85C 801E285C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* A860 801E2860 1000BFAF */  sw         $ra, 0x10($sp)
    /* A864 801E2864 1F80013C */  lui        $at, %hi(D_801F67F8)
    /* A868 801E2868 F86724AC */  sw         $a0, %lo(D_801F67F8)($at)
    /* A86C 801E286C 1F80013C */  lui        $at, %hi(D_801F67B8)
    /* A870 801E2870 B86722AC */  sw         $v0, %lo(D_801F67B8)($at)
    /* A874 801E2874 118C070C */  jal        ResetCallback
    /* A878 801E2878 00000000 */   nop
    /* A87C 801E287C 0020043C */  lui        $a0, (0x20000001 >> 16)
    /* A880 801E2880 1F80053C */  lui        $a1, %hi(D_801F67B8)
    /* A884 801E2884 B867A524 */  addiu      $a1, $a1, %lo(D_801F67B8)
    /* A888 801E2888 4C8A070C */  jal        PAD_init
    /* A88C 801E288C 01008434 */   ori       $a0, $a0, (0x20000001 & 0xFFFF)
    /* A890 801E2890 408A070C */  jal        ChangeClearPAD
    /* A894 801E2894 21200000 */   addu      $a0, $zero, $zero
    /* A898 801E2898 1000BF8F */  lw         $ra, 0x10($sp)
    /* A89C 801E289C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* A8A0 801E28A0 0800E003 */  jr         $ra
    /* A8A4 801E28A4 00000000 */   nop
endlabel PadInit

nonmatching PadRead, 0x28

glabel PadRead
    /* A8A8 801E28A8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* A8AC 801E28AC 1000BFAF */  sw         $ra, 0x10($sp)
    /* A8B0 801E28B0 3C8A070C */  jal        PAD_dr
    /* A8B4 801E28B4 00000000 */   nop
    /* A8B8 801E28B8 1F80023C */  lui        $v0, %hi(D_801F67B8)
    /* A8BC 801E28BC B867428C */  lw         $v0, %lo(D_801F67B8)($v0)
    /* A8C0 801E28C0 1000BF8F */  lw         $ra, 0x10($sp)
    /* A8C4 801E28C4 27100200 */  nor        $v0, $zero, $v0
    /* A8C8 801E28C8 0800E003 */  jr         $ra
    /* A8CC 801E28CC 1800BD27 */   addiu     $sp, $sp, 0x18
endlabel PadRead

nonmatching PadStop, 0x20

glabel PadStop
    /* A8D0 801E28D0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* A8D4 801E28D4 1000BFAF */  sw         $ra, 0x10($sp)
    /* A8D8 801E28D8 A68A070C */  jal        StopPAD
    /* A8DC 801E28DC 00000000 */   nop
    /* A8E0 801E28E0 1000BF8F */  lw         $ra, 0x10($sp)
    /* A8E4 801E28E4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* A8E8 801E28E8 0800E003 */  jr         $ra
    /* A8EC 801E28EC 00000000 */   nop
endlabel PadStop
