.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching VSync, 0x148

glabel VSync
    /* AE50 801E2E50 1F80023C */  lui        $v0, %hi(D_801F5478)
    /* AE54 801E2E54 7854428C */  lw         $v0, %lo(D_801F5478)($v0)
    /* AE58 801E2E58 1F80033C */  lui        $v1, %hi(D_801F547C)
    /* AE5C 801E2E5C 7C54638C */  lw         $v1, %lo(D_801F547C)($v1)
    /* AE60 801E2E60 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* AE64 801E2E64 1800BFAF */  sw         $ra, 0x18($sp)
    /* AE68 801E2E68 1400B1AF */  sw         $s1, 0x14($sp)
    /* AE6C 801E2E6C 1000B0AF */  sw         $s0, 0x10($sp)
    /* AE70 801E2E70 0000508C */  lw         $s0, 0x0($v0)
    /* AE74 801E2E74 0000628C */  lw         $v0, 0x0($v1)
    /* AE78 801E2E78 1F80033C */  lui        $v1, %hi(D_801F5480)
    /* AE7C 801E2E7C 8054638C */  lw         $v1, %lo(D_801F5480)($v1)
    /* AE80 801E2E80 00000000 */  nop
    /* AE84 801E2E84 23104300 */  subu       $v0, $v0, $v1
    /* AE88 801E2E88 05008104 */  bgez       $a0, .L801E2EA0
    /* AE8C 801E2E8C FFFF5130 */   andi      $s1, $v0, 0xFFFF
    /* AE90 801E2E90 1F80023C */  lui        $v0, %hi(D_801F659C)
    /* AE94 801E2E94 9C65428C */  lw         $v0, %lo(D_801F659C)($v0)
    /* AE98 801E2E98 E08B0708 */  j          .L801E2F80
    /* AE9C 801E2E9C 00000000 */   nop
  .L801E2EA0:
    /* AEA0 801E2EA0 01000224 */  addiu      $v0, $zero, 0x1
    /* AEA4 801E2EA4 36008210 */  beq        $a0, $v0, .L801E2F80
    /* AEA8 801E2EA8 21102002 */   addu      $v0, $s1, $zero
    /* AEAC 801E2EAC 07008018 */  blez       $a0, .L801E2ECC
    /* AEB0 801E2EB0 00000000 */   nop
    /* AEB4 801E2EB4 1F80023C */  lui        $v0, %hi(D_801F5484)
    /* AEB8 801E2EB8 8454428C */  lw         $v0, %lo(D_801F5484)($v0)
    /* AEBC 801E2EBC 00000000 */  nop
    /* AEC0 801E2EC0 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* AEC4 801E2EC4 B58B0708 */  j          .L801E2ED4
    /* AEC8 801E2EC8 21104400 */   addu      $v0, $v0, $a0
  .L801E2ECC:
    /* AECC 801E2ECC 1F80023C */  lui        $v0, %hi(D_801F5484)
    /* AED0 801E2ED0 8454428C */  lw         $v0, %lo(D_801F5484)($v0)
  .L801E2ED4:
    /* AED4 801E2ED4 02008018 */  blez       $a0, .L801E2EE0
    /* AED8 801E2ED8 21280000 */   addu      $a1, $zero, $zero
    /* AEDC 801E2EDC FFFF8524 */  addiu      $a1, $a0, -0x1
  .L801E2EE0:
    /* AEE0 801E2EE0 E68B070C */  jal        v_wait
    /* AEE4 801E2EE4 21204000 */   addu      $a0, $v0, $zero
    /* AEE8 801E2EE8 1F80023C */  lui        $v0, %hi(D_801F5478)
    /* AEEC 801E2EEC 7854428C */  lw         $v0, %lo(D_801F5478)($v0)
    /* AEF0 801E2EF0 00000000 */  nop
    /* AEF4 801E2EF4 0000508C */  lw         $s0, 0x0($v0)
    /* AEF8 801E2EF8 1F80043C */  lui        $a0, %hi(D_801F659C)
    /* AEFC 801E2EFC 9C65848C */  lw         $a0, %lo(D_801F659C)($a0)
    /* AF00 801E2F00 01000524 */  addiu      $a1, $zero, 0x1
    /* AF04 801E2F04 E68B070C */  jal        v_wait
    /* AF08 801E2F08 01008424 */   addiu     $a0, $a0, 0x1
    /* AF0C 801E2F0C 4000023C */  lui        $v0, (0x400000 >> 16)
    /* AF10 801E2F10 24100202 */  and        $v0, $s0, $v0
    /* AF14 801E2F14 10004010 */  beqz       $v0, .L801E2F58
    /* AF18 801E2F18 00000000 */   nop
    /* AF1C 801E2F1C 1F80033C */  lui        $v1, %hi(D_801F5478)
    /* AF20 801E2F20 7854638C */  lw         $v1, %lo(D_801F5478)($v1)
    /* AF24 801E2F24 00000000 */  nop
    /* AF28 801E2F28 0000628C */  lw         $v0, 0x0($v1)
    /* AF2C 801E2F2C 00000000 */  nop
    /* AF30 801E2F30 26100202 */  xor        $v0, $s0, $v0
    /* AF34 801E2F34 08004004 */  bltz       $v0, .L801E2F58
    /* AF38 801E2F38 00000000 */   nop
    /* AF3C 801E2F3C 0080043C */  lui        $a0, (0x80000000 >> 16)
  .L801E2F40:
    /* AF40 801E2F40 0000628C */  lw         $v0, 0x0($v1)
    /* AF44 801E2F44 00000000 */  nop
    /* AF48 801E2F48 26100202 */  xor        $v0, $s0, $v0
    /* AF4C 801E2F4C 24104400 */  and        $v0, $v0, $a0
    /* AF50 801E2F50 FBFF4010 */  beqz       $v0, .L801E2F40
    /* AF54 801E2F54 00000000 */   nop
  .L801E2F58:
    /* AF58 801E2F58 1F80023C */  lui        $v0, %hi(D_801F659C)
    /* AF5C 801E2F5C 9C65428C */  lw         $v0, %lo(D_801F659C)($v0)
    /* AF60 801E2F60 1F80033C */  lui        $v1, %hi(D_801F547C)
    /* AF64 801E2F64 7C54638C */  lw         $v1, %lo(D_801F547C)($v1)
    /* AF68 801E2F68 1F80013C */  lui        $at, %hi(D_801F5484)
    /* AF6C 801E2F6C 845422AC */  sw         $v0, %lo(D_801F5484)($at)
    /* AF70 801E2F70 0000638C */  lw         $v1, 0x0($v1)
    /* AF74 801E2F74 21102002 */  addu       $v0, $s1, $zero
    /* AF78 801E2F78 1F80013C */  lui        $at, %hi(D_801F5480)
    /* AF7C 801E2F7C 805423AC */  sw         $v1, %lo(D_801F5480)($at)
  .L801E2F80:
    /* AF80 801E2F80 1800BF8F */  lw         $ra, 0x18($sp)
    /* AF84 801E2F84 1400B18F */  lw         $s1, 0x14($sp)
    /* AF88 801E2F88 1000B08F */  lw         $s0, 0x10($sp)
    /* AF8C 801E2F8C 2000BD27 */  addiu      $sp, $sp, 0x20
    /* AF90 801E2F90 0800E003 */  jr         $ra
    /* AF94 801E2F94 00000000 */   nop
endlabel VSync

nonmatching v_wait, 0x9C

glabel v_wait
    /* AF98 801E2F98 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* AF9C 801E2F9C C02B0500 */  sll        $a1, $a1, 15
    /* AFA0 801E2FA0 1000A5AF */  sw         $a1, 0x10($sp)
    /* AFA4 801E2FA4 1F80023C */  lui        $v0, %hi(D_801F659C)
    /* AFA8 801E2FA8 9C65428C */  lw         $v0, %lo(D_801F659C)($v0)
    /* AFAC 801E2FAC 00000000 */  nop
    /* AFB0 801E2FB0 2A104400 */  slt        $v0, $v0, $a0
    /* AFB4 801E2FB4 1B004010 */  beqz       $v0, .L801E3024
    /* AFB8 801E2FB8 1800BFAF */   sw        $ra, 0x18($sp)
    /* AFBC 801E2FBC FFFF0324 */  addiu      $v1, $zero, -0x1
  .L801E2FC0:
    /* AFC0 801E2FC0 1000A28F */  lw         $v0, 0x10($sp)
    /* AFC4 801E2FC4 00000000 */  nop
    /* AFC8 801E2FC8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* AFCC 801E2FCC 1000A2AF */  sw         $v0, 0x10($sp)
    /* AFD0 801E2FD0 1000A28F */  lw         $v0, 0x10($sp)
    /* AFD4 801E2FD4 00000000 */  nop
    /* AFD8 801E2FD8 0C004314 */  bne        $v0, $v1, .L801E300C
    /* AFDC 801E2FDC 00000000 */   nop
    /* AFE0 801E2FE0 1E80043C */  lui        $a0, %hi(D_801D90F4)
    /* AFE4 801E2FE4 F4908424 */  addiu      $a0, $a0, %lo(D_801D90F4)
    /* AFE8 801E2FE8 C983070C */  jal        puts
    /* AFEC 801E2FEC 00000000 */   nop
    /* AFF0 801E2FF0 408A070C */  jal        ChangeClearPAD
    /* AFF4 801E2FF4 21200000 */   addu      $a0, $zero, $zero
    /* AFF8 801E2FF8 03000424 */  addiu      $a0, $zero, 0x3
    /* AFFC 801E2FFC 0D8C070C */  jal        ChangeClearRCnt
    /* B000 801E3000 21280000 */   addu      $a1, $zero, $zero
    /* B004 801E3004 098C0708 */  j          .L801E3024
    /* B008 801E3008 00000000 */   nop
  .L801E300C:
    /* B00C 801E300C 1F80023C */  lui        $v0, %hi(D_801F659C)
    /* B010 801E3010 9C65428C */  lw         $v0, %lo(D_801F659C)($v0)
    /* B014 801E3014 00000000 */  nop
    /* B018 801E3018 2A104400 */  slt        $v0, $v0, $a0
    /* B01C 801E301C E8FF4014 */  bnez       $v0, .L801E2FC0
    /* B020 801E3020 00000000 */   nop
  .L801E3024:
    /* B024 801E3024 1800BF8F */  lw         $ra, 0x18($sp)
    /* B028 801E3028 2000BD27 */  addiu      $sp, $sp, 0x20
    /* B02C 801E302C 0800E003 */  jr         $ra
    /* B030 801E3030 00000000 */   nop
endlabel v_wait
