.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching LoadTPage, 0xEC

glabel LoadTPage
    /* 33F4 801DB3F4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 33F8 801DB3F8 2400B3AF */  sw         $s3, 0x24($sp)
    /* 33FC 801DB3FC 4000B38F */  lw         $s3, 0x40($sp)
    /* 3400 801DB400 4400A38F */  lw         $v1, 0x44($sp)
    /* 3404 801DB404 4800A28F */  lw         $v0, 0x48($sp)
    /* 3408 801DB408 21408000 */  addu       $t0, $a0, $zero
    /* 340C 801DB40C 1800B0AF */  sw         $s0, 0x18($sp)
    /* 3410 801DB410 2180A000 */  addu       $s0, $a1, $zero
    /* 3414 801DB414 2000B2AF */  sw         $s2, 0x20($sp)
    /* 3418 801DB418 2190C000 */  addu       $s2, $a2, $zero
    /* 341C 801DB41C 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 3420 801DB420 2188E000 */  addu       $s1, $a3, $zero
    /* 3424 801DB424 2800BFAF */  sw         $ra, 0x28($sp)
    /* 3428 801DB428 1000B1A7 */  sh         $s1, 0x10($sp)
    /* 342C 801DB42C 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 3430 801DB430 01000224 */  addiu      $v0, $zero, 0x1
    /* 3434 801DB434 13000212 */  beq        $s0, $v0, .L801DB484
    /* 3438 801DB438 1200B3A7 */   sh        $s3, 0x12($sp)
    /* 343C 801DB43C 0200022A */  slti       $v0, $s0, 0x2
    /* 3440 801DB440 05004010 */  beqz       $v0, .L801DB458
    /* 3444 801DB444 00000000 */   nop
    /* 3448 801DB448 08000012 */  beqz       $s0, .L801DB46C
    /* 344C 801DB44C 1000A427 */   addiu     $a0, $sp, 0x10
    /* 3450 801DB450 286D0708 */  j          .L801DB4A0
    /* 3454 801DB454 00000000 */   nop
  .L801DB458:
    /* 3458 801DB458 02000224 */  addiu      $v0, $zero, 0x2
    /* 345C 801DB45C 0E000212 */  beq        $s0, $v0, .L801DB498
    /* 3460 801DB460 1000A427 */   addiu     $a0, $sp, 0x10
    /* 3464 801DB464 286D0708 */  j          .L801DB4A0
    /* 3468 801DB468 00000000 */   nop
  .L801DB46C:
    /* 346C 801DB46C 02006104 */  bgez       $v1, .L801DB478
    /* 3470 801DB470 21106000 */   addu      $v0, $v1, $zero
    /* 3474 801DB474 03006224 */  addiu      $v0, $v1, 0x3
  .L801DB478:
    /* 3478 801DB478 83100200 */  sra        $v0, $v0, 2
    /* 347C 801DB47C 276D0708 */  j          .L801DB49C
    /* 3480 801DB480 1400A2A7 */   sh        $v0, 0x14($sp)
  .L801DB484:
    /* 3484 801DB484 C2170300 */  srl        $v0, $v1, 31
    /* 3488 801DB488 21106200 */  addu       $v0, $v1, $v0
    /* 348C 801DB48C 43100200 */  sra        $v0, $v0, 1
    /* 3490 801DB490 276D0708 */  j          .L801DB49C
    /* 3494 801DB494 1400A2A7 */   sh        $v0, 0x14($sp)
  .L801DB498:
    /* 3498 801DB498 1400A3A7 */  sh         $v1, 0x14($sp)
  .L801DB49C:
    /* 349C 801DB49C 1000A427 */  addiu      $a0, $sp, 0x10
  .L801DB4A0:
    /* 34A0 801DB4A0 4771070C */  jal        LoadImage
    /* 34A4 801DB4A4 21280001 */   addu      $a1, $t0, $zero
    /* 34A8 801DB4A8 21200002 */  addu       $a0, $s0, $zero
    /* 34AC 801DB4AC 21284002 */  addu       $a1, $s2, $zero
    /* 34B0 801DB4B0 21302002 */  addu       $a2, $s1, $zero
    /* 34B4 801DB4B4 A96D070C */  jal        GetTPage
    /* 34B8 801DB4B8 21386002 */   addu      $a3, $s3, $zero
    /* 34BC 801DB4BC FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 34C0 801DB4C0 2800BF8F */  lw         $ra, 0x28($sp)
    /* 34C4 801DB4C4 2400B38F */  lw         $s3, 0x24($sp)
    /* 34C8 801DB4C8 2000B28F */  lw         $s2, 0x20($sp)
    /* 34CC 801DB4CC 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 34D0 801DB4D0 1800B08F */  lw         $s0, 0x18($sp)
    /* 34D4 801DB4D4 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 34D8 801DB4D8 0800E003 */  jr         $ra
    /* 34DC 801DB4DC 00000000 */   nop
endlabel LoadTPage

nonmatching LoadClut, 0x68

glabel LoadClut
    /* 34E0 801DB4E0 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 34E4 801DB4E4 21108000 */  addu       $v0, $a0, $zero
    /* 34E8 801DB4E8 1800B0AF */  sw         $s0, 0x18($sp)
    /* 34EC 801DB4EC 2180A000 */  addu       $s0, $a1, $zero
    /* 34F0 801DB4F0 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 34F4 801DB4F4 2188C000 */  addu       $s1, $a2, $zero
    /* 34F8 801DB4F8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 34FC 801DB4FC 21284000 */  addu       $a1, $v0, $zero
    /* 3500 801DB500 00010224 */  addiu      $v0, $zero, 0x100
    /* 3504 801DB504 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 3508 801DB508 01000224 */  addiu      $v0, $zero, 0x1
    /* 350C 801DB50C 2000BFAF */  sw         $ra, 0x20($sp)
    /* 3510 801DB510 1000B0A7 */  sh         $s0, 0x10($sp)
    /* 3514 801DB514 1200B1A7 */  sh         $s1, 0x12($sp)
    /* 3518 801DB518 4771070C */  jal        LoadImage
    /* 351C 801DB51C 1600A2A7 */   sh        $v0, 0x16($sp)
    /* 3520 801DB520 21200002 */  addu       $a0, $s0, $zero
    /* 3524 801DB524 B86D070C */  jal        GetClut
    /* 3528 801DB528 21282002 */   addu      $a1, $s1, $zero
    /* 352C 801DB52C FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 3530 801DB530 2000BF8F */  lw         $ra, 0x20($sp)
    /* 3534 801DB534 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 3538 801DB538 1800B08F */  lw         $s0, 0x18($sp)
    /* 353C 801DB53C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 3540 801DB540 0800E003 */  jr         $ra
    /* 3544 801DB544 00000000 */   nop
endlabel LoadClut

nonmatching LoadClut2, 0x68

glabel LoadClut2
    /* 3548 801DB548 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 354C 801DB54C 21108000 */  addu       $v0, $a0, $zero
    /* 3550 801DB550 1800B0AF */  sw         $s0, 0x18($sp)
    /* 3554 801DB554 2180A000 */  addu       $s0, $a1, $zero
    /* 3558 801DB558 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 355C 801DB55C 2188C000 */  addu       $s1, $a2, $zero
    /* 3560 801DB560 1000A427 */  addiu      $a0, $sp, 0x10
    /* 3564 801DB564 21284000 */  addu       $a1, $v0, $zero
    /* 3568 801DB568 10000224 */  addiu      $v0, $zero, 0x10
    /* 356C 801DB56C 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 3570 801DB570 01000224 */  addiu      $v0, $zero, 0x1
    /* 3574 801DB574 2000BFAF */  sw         $ra, 0x20($sp)
    /* 3578 801DB578 1000B0A7 */  sh         $s0, 0x10($sp)
    /* 357C 801DB57C 1200B1A7 */  sh         $s1, 0x12($sp)
    /* 3580 801DB580 4771070C */  jal        LoadImage
    /* 3584 801DB584 1600A2A7 */   sh        $v0, 0x16($sp)
    /* 3588 801DB588 21200002 */  addu       $a0, $s0, $zero
    /* 358C 801DB58C B86D070C */  jal        GetClut
    /* 3590 801DB590 21282002 */   addu      $a1, $s1, $zero
    /* 3594 801DB594 FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 3598 801DB598 2000BF8F */  lw         $ra, 0x20($sp)
    /* 359C 801DB59C 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 35A0 801DB5A0 1800B08F */  lw         $s0, 0x18($sp)
    /* 35A4 801DB5A4 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 35A8 801DB5A8 0800E003 */  jr         $ra
    /* 35AC 801DB5AC 00000000 */   nop
endlabel LoadClut2

nonmatching SetDefDrawEnv, 0xB8

glabel SetDefDrawEnv
    /* 35B0 801DB5B0 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 35B4 801DB5B4 1800B2AF */  sw         $s2, 0x18($sp)
    /* 35B8 801DB5B8 3800B28F */  lw         $s2, 0x38($sp)
    /* 35BC 801DB5BC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 35C0 801DB5C0 21888000 */  addu       $s1, $a0, $zero
    /* 35C4 801DB5C4 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 35C8 801DB5C8 2198A000 */  addu       $s3, $a1, $zero
    /* 35CC 801DB5CC 2000B4AF */  sw         $s4, 0x20($sp)
    /* 35D0 801DB5D0 21A0C000 */  addu       $s4, $a2, $zero
    /* 35D4 801DB5D4 1000B0AF */  sw         $s0, 0x10($sp)
    /* 35D8 801DB5D8 2400BFAF */  sw         $ra, 0x24($sp)
    /* 35DC 801DB5DC 038F070C */  jal        GetVideoMode
    /* 35E0 801DB5E0 2180E000 */   addu      $s0, $a3, $zero
    /* 35E4 801DB5E4 01000324 */  addiu      $v1, $zero, 0x1
    /* 35E8 801DB5E8 000033A6 */  sh         $s3, 0x0($s1)
    /* 35EC 801DB5EC 020034A6 */  sh         $s4, 0x2($s1)
    /* 35F0 801DB5F0 040030A6 */  sh         $s0, 0x4($s1)
    /* 35F4 801DB5F4 0C0020A6 */  sh         $zero, 0xC($s1)
    /* 35F8 801DB5F8 0E0020A6 */  sh         $zero, 0xE($s1)
    /* 35FC 801DB5FC 100020A6 */  sh         $zero, 0x10($s1)
    /* 3600 801DB600 120020A6 */  sh         $zero, 0x12($s1)
    /* 3604 801DB604 190020A2 */  sb         $zero, 0x19($s1)
    /* 3608 801DB608 1A0020A2 */  sb         $zero, 0x1A($s1)
    /* 360C 801DB60C 1B0020A2 */  sb         $zero, 0x1B($s1)
    /* 3610 801DB610 160023A2 */  sb         $v1, 0x16($s1)
    /* 3614 801DB614 03004010 */  beqz       $v0, .L801DB624
    /* 3618 801DB618 060032A6 */   sh        $s2, 0x6($s1)
    /* 361C 801DB61C 8A6D0708 */  j          .L801DB628
    /* 3620 801DB620 2101422A */   slti      $v0, $s2, 0x121
  .L801DB624:
    /* 3624 801DB624 0101422A */  slti       $v0, $s2, 0x101
  .L801DB628:
    /* 3628 801DB628 170022A2 */  sb         $v0, 0x17($s1)
    /* 362C 801DB62C 21102002 */  addu       $v0, $s1, $zero
    /* 3630 801DB630 0A000324 */  addiu      $v1, $zero, 0xA
    /* 3634 801DB634 080053A4 */  sh         $s3, 0x8($v0)
    /* 3638 801DB638 0A0054A4 */  sh         $s4, 0xA($v0)
    /* 363C 801DB63C 140043A4 */  sh         $v1, 0x14($v0)
    /* 3640 801DB640 180040A0 */  sb         $zero, 0x18($v0)
    /* 3644 801DB644 2400BF8F */  lw         $ra, 0x24($sp)
    /* 3648 801DB648 2000B48F */  lw         $s4, 0x20($sp)
    /* 364C 801DB64C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 3650 801DB650 1800B28F */  lw         $s2, 0x18($sp)
    /* 3654 801DB654 1400B18F */  lw         $s1, 0x14($sp)
    /* 3658 801DB658 1000B08F */  lw         $s0, 0x10($sp)
    /* 365C 801DB65C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 3660 801DB660 0800E003 */  jr         $ra
    /* 3664 801DB664 00000000 */   nop
endlabel SetDefDrawEnv

nonmatching SetDefDispEnv, 0x3C

glabel SetDefDispEnv
    /* 3668 801DB668 1000A38F */  lw         $v1, 0x10($sp)
    /* 366C 801DB66C 21108000 */  addu       $v0, $a0, $zero
    /* 3670 801DB670 000045A4 */  sh         $a1, 0x0($v0)
    /* 3674 801DB674 020046A4 */  sh         $a2, 0x2($v0)
    /* 3678 801DB678 040047A4 */  sh         $a3, 0x4($v0)
    /* 367C 801DB67C 080040A4 */  sh         $zero, 0x8($v0)
    /* 3680 801DB680 0A0040A4 */  sh         $zero, 0xA($v0)
    /* 3684 801DB684 0C0040A4 */  sh         $zero, 0xC($v0)
    /* 3688 801DB688 0E0040A4 */  sh         $zero, 0xE($v0)
    /* 368C 801DB68C 110040A0 */  sb         $zero, 0x11($v0)
    /* 3690 801DB690 100040A0 */  sb         $zero, 0x10($v0)
    /* 3694 801DB694 130040A0 */  sb         $zero, 0x13($v0)
    /* 3698 801DB698 120040A0 */  sb         $zero, 0x12($v0)
    /* 369C 801DB69C 0800E003 */  jr         $ra
    /* 36A0 801DB6A0 060043A4 */   sh        $v1, 0x6($v0)
endlabel SetDefDispEnv
