.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching DecDCTReset, 0x38

glabel DecDCTReset
    /* 28FC 801DA8FC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2900 801DA900 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2904 801DA904 21808000 */  addu       $s0, $a0, $zero
    /* 2908 801DA908 03000016 */  bnez       $s0, .L801DA918
    /* 290C 801DA90C 1400BFAF */   sw        $ra, 0x14($sp)
    /* 2910 801DA910 118C070C */  jal        ResetCallback
    /* 2914 801DA914 00000000 */   nop
  .L801DA918:
    /* 2918 801DA918 F16A070C */  jal        MDEC_reset
    /* 291C 801DA91C 21200002 */   addu      $a0, $s0, $zero
    /* 2920 801DA920 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2924 801DA924 1000B08F */  lw         $s0, 0x10($sp)
    /* 2928 801DA928 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 292C 801DA92C 0800E003 */  jr         $ra
    /* 2930 801DA930 00000000 */   nop
endlabel DecDCTReset

nonmatching DecDCTGetEnv, 0x8C

glabel DecDCTGetEnv
    /* 2934 801DA934 21308000 */  addu       $a2, $a0, $zero
    /* 2938 801DA938 1E80053C */  lui        $a1, %hi(D_801E3CF0)
    /* 293C 801DA93C F03CA524 */  addiu      $a1, $a1, %lo(D_801E3CF0)
    /* 2940 801DA940 0F000324 */  addiu      $v1, $zero, 0xF
    /* 2944 801DA944 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L801DA948:
    /* 2948 801DA948 0000A28C */  lw         $v0, 0x0($a1)
    /* 294C 801DA94C 0400A524 */  addiu      $a1, $a1, 0x4
    /* 2950 801DA950 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 2954 801DA954 0000C2AC */  sw         $v0, 0x0($a2)
    /* 2958 801DA958 FBFF6714 */  bne        $v1, $a3, .L801DA948
    /* 295C 801DA95C 0400C624 */   addiu     $a2, $a2, 0x4
    /* 2960 801DA960 40008624 */  addiu      $a2, $a0, 0x40
    /* 2964 801DA964 1E80053C */  lui        $a1, %hi(D_801E3D30)
    /* 2968 801DA968 303DA524 */  addiu      $a1, $a1, %lo(D_801E3D30)
    /* 296C 801DA96C 0F000324 */  addiu      $v1, $zero, 0xF
    /* 2970 801DA970 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L801DA974:
    /* 2974 801DA974 0000A28C */  lw         $v0, 0x0($a1)
    /* 2978 801DA978 0400A524 */  addiu      $a1, $a1, 0x4
    /* 297C 801DA97C FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 2980 801DA980 0000C2AC */  sw         $v0, 0x0($a2)
    /* 2984 801DA984 FBFF6714 */  bne        $v1, $a3, .L801DA974
    /* 2988 801DA988 0400C624 */   addiu     $a2, $a2, 0x4
    /* 298C 801DA98C 80008624 */  addiu      $a2, $a0, 0x80
    /* 2990 801DA990 1E80053C */  lui        $a1, %hi(D_801E3D74)
    /* 2994 801DA994 743DA524 */  addiu      $a1, $a1, %lo(D_801E3D74)
    /* 2998 801DA998 1F000324 */  addiu      $v1, $zero, 0x1F
    /* 299C 801DA99C FFFF0724 */  addiu      $a3, $zero, -0x1
  .L801DA9A0:
    /* 29A0 801DA9A0 0000A28C */  lw         $v0, 0x0($a1)
    /* 29A4 801DA9A4 0400A524 */  addiu      $a1, $a1, 0x4
    /* 29A8 801DA9A8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 29AC 801DA9AC 0000C2AC */  sw         $v0, 0x0($a2)
    /* 29B0 801DA9B0 FBFF6714 */  bne        $v1, $a3, .L801DA9A0
    /* 29B4 801DA9B4 0400C624 */   addiu     $a2, $a2, 0x4
    /* 29B8 801DA9B8 0800E003 */  jr         $ra
    /* 29BC 801DA9BC 21108000 */   addu      $v0, $a0, $zero
endlabel DecDCTGetEnv

nonmatching DecDCTPutEnv, 0x9C

glabel DecDCTPutEnv
    /* 29C0 801DA9C0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 29C4 801DA9C4 1000B0AF */  sw         $s0, 0x10($sp)
    /* 29C8 801DA9C8 21808000 */  addu       $s0, $a0, $zero
    /* 29CC 801DA9CC 1E80053C */  lui        $a1, %hi(D_801E3CF0)
    /* 29D0 801DA9D0 F03CA524 */  addiu      $a1, $a1, %lo(D_801E3CF0)
    /* 29D4 801DA9D4 0F000324 */  addiu      $v1, $zero, 0xF
    /* 29D8 801DA9D8 FFFF0624 */  addiu      $a2, $zero, -0x1
    /* 29DC 801DA9DC 1400BFAF */  sw         $ra, 0x14($sp)
  .L801DA9E0:
    /* 29E0 801DA9E0 0000828C */  lw         $v0, 0x0($a0)
    /* 29E4 801DA9E4 04008424 */  addiu      $a0, $a0, 0x4
    /* 29E8 801DA9E8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 29EC 801DA9EC 0000A2AC */  sw         $v0, 0x0($a1)
    /* 29F0 801DA9F0 FBFF6614 */  bne        $v1, $a2, .L801DA9E0
    /* 29F4 801DA9F4 0400A524 */   addiu     $a1, $a1, 0x4
    /* 29F8 801DA9F8 1E80053C */  lui        $a1, %hi(D_801E3D30)
    /* 29FC 801DA9FC 303DA524 */  addiu      $a1, $a1, %lo(D_801E3D30)
    /* 2A00 801DAA00 40000426 */  addiu      $a0, $s0, 0x40
    /* 2A04 801DAA04 0F000324 */  addiu      $v1, $zero, 0xF
    /* 2A08 801DAA08 FFFF0624 */  addiu      $a2, $zero, -0x1
  .L801DAA0C:
    /* 2A0C 801DAA0C 0000828C */  lw         $v0, 0x0($a0)
    /* 2A10 801DAA10 04008424 */  addiu      $a0, $a0, 0x4
    /* 2A14 801DAA14 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 2A18 801DAA18 0000A2AC */  sw         $v0, 0x0($a1)
    /* 2A1C 801DAA1C FBFF6614 */  bne        $v1, $a2, .L801DAA0C
    /* 2A20 801DAA20 0400A524 */   addiu     $a1, $a1, 0x4
    /* 2A24 801DAA24 1E80043C */  lui        $a0, %hi(D_801E3CEC)
    /* 2A28 801DAA28 EC3C8424 */  addiu      $a0, $a0, %lo(D_801E3CEC)
    /* 2A2C 801DAA2C 306B070C */  jal        MDEC_in
    /* 2A30 801DAA30 20000524 */   addiu     $a1, $zero, 0x20
    /* 2A34 801DAA34 1E80043C */  lui        $a0, %hi(D_801E3D70)
    /* 2A38 801DAA38 703D8424 */  addiu      $a0, $a0, %lo(D_801E3D70)
    /* 2A3C 801DAA3C 306B070C */  jal        MDEC_in
    /* 2A40 801DAA40 20000524 */   addiu     $a1, $zero, 0x20
    /* 2A44 801DAA44 21100002 */  addu       $v0, $s0, $zero
    /* 2A48 801DAA48 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2A4C 801DAA4C 1000B08F */  lw         $s0, 0x10($sp)
    /* 2A50 801DAA50 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2A54 801DAA54 0800E003 */  jr         $ra
    /* 2A58 801DAA58 00000000 */   nop
endlabel DecDCTPutEnv

nonmatching DecDCTBufSize, 0xC

glabel DecDCTBufSize
    /* 2A5C 801DAA5C 00008294 */  lhu        $v0, 0x0($a0)
    /* 2A60 801DAA60 0800E003 */  jr         $ra
    /* 2A64 801DAA64 00000000 */   nop
endlabel DecDCTBufSize

nonmatching DecDCTin, 0x7C

glabel DecDCTin
    /* 2A68 801DAA68 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2A6C 801DAA6C 0100A230 */  andi       $v0, $a1, 0x1
    /* 2A70 801DAA70 06004010 */  beqz       $v0, .L801DAA8C
    /* 2A74 801DAA74 1000BFAF */   sw        $ra, 0x10($sp)
    /* 2A78 801DAA78 FFF7033C */  lui        $v1, (0xF7FFFFFF >> 16)
    /* 2A7C 801DAA7C 0000828C */  lw         $v0, 0x0($a0)
    /* 2A80 801DAA80 FFFF6334 */  ori        $v1, $v1, (0xF7FFFFFF & 0xFFFF)
    /* 2A84 801DAA84 A66A0708 */  j          .L801DAA98
    /* 2A88 801DAA88 24104300 */   and       $v0, $v0, $v1
  .L801DAA8C:
    /* 2A8C 801DAA8C 0000828C */  lw         $v0, 0x0($a0)
    /* 2A90 801DAA90 0008033C */  lui        $v1, (0x8000000 >> 16)
    /* 2A94 801DAA94 25104300 */  or         $v0, $v0, $v1
  .L801DAA98:
    /* 2A98 801DAA98 000082AC */  sw         $v0, 0x0($a0)
    /* 2A9C 801DAA9C 0200A230 */  andi       $v0, $a1, 0x2
    /* 2AA0 801DAAA0 04004010 */  beqz       $v0, .L801DAAB4
    /* 2AA4 801DAAA4 0002033C */   lui       $v1, (0x2000000 >> 16)
    /* 2AA8 801DAAA8 0000828C */  lw         $v0, 0x0($a0)
    /* 2AAC 801DAAAC B16A0708 */  j          .L801DAAC4
    /* 2AB0 801DAAB0 25104300 */   or        $v0, $v0, $v1
  .L801DAAB4:
    /* 2AB4 801DAAB4 FFFD033C */  lui        $v1, (0xFDFFFFFF >> 16)
    /* 2AB8 801DAAB8 0000828C */  lw         $v0, 0x0($a0)
    /* 2ABC 801DAABC FFFF6334 */  ori        $v1, $v1, (0xFDFFFFFF & 0xFFFF)
    /* 2AC0 801DAAC0 24104300 */  and        $v0, $v0, $v1
  .L801DAAC4:
    /* 2AC4 801DAAC4 000082AC */  sw         $v0, 0x0($a0)
    /* 2AC8 801DAAC8 00008594 */  lhu        $a1, 0x0($a0)
    /* 2ACC 801DAACC 306B070C */  jal        MDEC_in
    /* 2AD0 801DAAD0 00000000 */   nop
    /* 2AD4 801DAAD4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2AD8 801DAAD8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2ADC 801DAADC 0800E003 */  jr         $ra
    /* 2AE0 801DAAE0 00000000 */   nop
endlabel DecDCTin

nonmatching DecDCTout, 0x20

glabel DecDCTout
    /* 2AE4 801DAAE4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2AE8 801DAAE8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2AEC 801DAAEC 556B070C */  jal        MDEC_out
    /* 2AF0 801DAAF0 00000000 */   nop
    /* 2AF4 801DAAF4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2AF8 801DAAF8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2AFC 801DAAFC 0800E003 */  jr         $ra
    /* 2B00 801DAB00 00000000 */   nop
endlabel DecDCTout

nonmatching DecDCTinSync, 0x3C

glabel DecDCTinSync
    /* 2B04 801DAB04 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2B08 801DAB08 05008014 */  bnez       $a0, .L801DAB20
    /* 2B0C 801DAB0C 1000BFAF */   sw        $ra, 0x10($sp)
    /* 2B10 801DAB10 796B070C */  jal        MDEC_in_sync
    /* 2B14 801DAB14 00000000 */   nop
    /* 2B18 801DAB18 CC6A0708 */  j          .L801DAB30
    /* 2B1C 801DAB1C 00000000 */   nop
  .L801DAB20:
    /* 2B20 801DAB20 C56B070C */  jal        MDEC_status
    /* 2B24 801DAB24 00000000 */   nop
    /* 2B28 801DAB28 42170200 */  srl        $v0, $v0, 29
    /* 2B2C 801DAB2C 01004230 */  andi       $v0, $v0, 0x1
  .L801DAB30:
    /* 2B30 801DAB30 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2B34 801DAB34 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2B38 801DAB38 0800E003 */  jr         $ra
    /* 2B3C 801DAB3C 00000000 */   nop
endlabel DecDCTinSync

nonmatching DecDCToutSync, 0x3C

glabel DecDCToutSync
    /* 2B40 801DAB40 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2B44 801DAB44 05008014 */  bnez       $a0, .L801DAB5C
    /* 2B48 801DAB48 1000BFAF */   sw        $ra, 0x10($sp)
    /* 2B4C 801DAB4C 9F6B070C */  jal        MDEC_out_sync
    /* 2B50 801DAB50 00000000 */   nop
    /* 2B54 801DAB54 DB6A0708 */  j          .L801DAB6C
    /* 2B58 801DAB58 00000000 */   nop
  .L801DAB5C:
    /* 2B5C 801DAB5C C56B070C */  jal        MDEC_status
    /* 2B60 801DAB60 00000000 */   nop
    /* 2B64 801DAB64 02160200 */  srl        $v0, $v0, 24
    /* 2B68 801DAB68 01004230 */  andi       $v0, $v0, 0x1
  .L801DAB6C:
    /* 2B6C 801DAB6C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2B70 801DAB70 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2B74 801DAB74 0800E003 */  jr         $ra
    /* 2B78 801DAB78 00000000 */   nop
endlabel DecDCToutSync

nonmatching DecDCTinCallback, 0x24

glabel DecDCTinCallback
    /* 2B7C 801DAB7C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2B80 801DAB80 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2B84 801DAB84 21288000 */  addu       $a1, $a0, $zero
    /* 2B88 801DAB88 298C070C */  jal        DMACallback
    /* 2B8C 801DAB8C 21200000 */   addu      $a0, $zero, $zero
    /* 2B90 801DAB90 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2B94 801DAB94 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2B98 801DAB98 0800E003 */  jr         $ra
    /* 2B9C 801DAB9C 00000000 */   nop
endlabel DecDCTinCallback

nonmatching DecDCToutCallback, 0x24

glabel DecDCToutCallback
    /* 2BA0 801DABA0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2BA4 801DABA4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2BA8 801DABA8 21288000 */  addu       $a1, $a0, $zero
    /* 2BAC 801DABAC 298C070C */  jal        DMACallback
    /* 2BB0 801DABB0 01000424 */   addiu     $a0, $zero, 0x1
    /* 2BB4 801DABB4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2BB8 801DABB8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2BBC 801DABBC 0800E003 */  jr         $ra
    /* 2BC0 801DABC0 00000000 */   nop
endlabel DecDCToutCallback

nonmatching MDEC_reset, 0xFC

glabel MDEC_reset
    /* 2BC4 801DABC4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2BC8 801DABC8 21288000 */  addu       $a1, $a0, $zero
    /* 2BCC 801DABCC 0600A010 */  beqz       $a1, .L801DABE8
    /* 2BD0 801DABD0 1000BFAF */   sw        $ra, 0x10($sp)
    /* 2BD4 801DABD4 01000224 */  addiu      $v0, $zero, 0x1
    /* 2BD8 801DABD8 1C00A210 */  beq        $a1, $v0, .L801DAC4C
    /* 2BDC 801DABDC 0080023C */   lui       $v0, (0x80000000 >> 16)
    /* 2BE0 801DABE0 286B0708 */  j          .L801DACA0
    /* 2BE4 801DABE4 00000000 */   nop
  .L801DABE8:
    /* 2BE8 801DABE8 1E80033C */  lui        $v1, %hi(D_801E3E30)
    /* 2BEC 801DABEC 303E638C */  lw         $v1, %lo(D_801E3E30)($v1)
    /* 2BF0 801DABF0 0080023C */  lui        $v0, (0x80000000 >> 16)
    /* 2BF4 801DABF4 000062AC */  sw         $v0, 0x0($v1)
    /* 2BF8 801DABF8 1E80023C */  lui        $v0, %hi(D_801E3E04)
    /* 2BFC 801DABFC 043E428C */  lw         $v0, %lo(D_801E3E04)($v0)
    /* 2C00 801DAC00 1E80043C */  lui        $a0, %hi(D_801E3CEC)
    /* 2C04 801DAC04 EC3C8424 */  addiu      $a0, $a0, %lo(D_801E3CEC)
    /* 2C08 801DAC08 000040AC */  sw         $zero, 0x0($v0)
    /* 2C0C 801DAC0C 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2C10 801DAC10 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2C14 801DAC14 20000524 */  addiu      $a1, $zero, 0x20
    /* 2C18 801DAC18 000040AC */  sw         $zero, 0x0($v0)
    /* 2C1C 801DAC1C 1E80033C */  lui        $v1, %hi(D_801E3E30)
    /* 2C20 801DAC20 303E638C */  lw         $v1, %lo(D_801E3E30)($v1)
    /* 2C24 801DAC24 0060023C */  lui        $v0, (0x60000000 >> 16)
    /* 2C28 801DAC28 000062AC */  sw         $v0, 0x0($v1)
    /* 2C2C 801DAC2C 306B070C */  jal        MDEC_in
    /* 2C30 801DAC30 00000000 */   nop
    /* 2C34 801DAC34 1E80043C */  lui        $a0, %hi(D_801E3D70)
    /* 2C38 801DAC38 703D8424 */  addiu      $a0, $a0, %lo(D_801E3D70)
    /* 2C3C 801DAC3C 306B070C */  jal        MDEC_in
    /* 2C40 801DAC40 20000524 */   addiu     $a1, $zero, 0x20
    /* 2C44 801DAC44 2C6B0708 */  j          .L801DACB0
    /* 2C48 801DAC48 00000000 */   nop
  .L801DAC4C:
    /* 2C4C 801DAC4C 1E80033C */  lui        $v1, %hi(D_801E3E30)
    /* 2C50 801DAC50 303E638C */  lw         $v1, %lo(D_801E3E30)($v1)
    /* 2C54 801DAC54 00000000 */  nop
    /* 2C58 801DAC58 000062AC */  sw         $v0, 0x0($v1)
    /* 2C5C 801DAC5C 1E80023C */  lui        $v0, %hi(D_801E3E04)
    /* 2C60 801DAC60 043E428C */  lw         $v0, %lo(D_801E3E04)($v0)
    /* 2C64 801DAC64 00000000 */  nop
    /* 2C68 801DAC68 000040AC */  sw         $zero, 0x0($v0)
    /* 2C6C 801DAC6C 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2C70 801DAC70 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2C74 801DAC74 00000000 */  nop
    /* 2C78 801DAC78 000040AC */  sw         $zero, 0x0($v0)
    /* 2C7C 801DAC7C 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2C80 801DAC80 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2C84 801DAC84 1E80033C */  lui        $v1, %hi(D_801E3E30)
    /* 2C88 801DAC88 303E638C */  lw         $v1, %lo(D_801E3E30)($v1)
    /* 2C8C 801DAC8C 0000428C */  lw         $v0, 0x0($v0)
    /* 2C90 801DAC90 0060023C */  lui        $v0, (0x60000000 >> 16)
    /* 2C94 801DAC94 000062AC */  sw         $v0, 0x0($v1)
    /* 2C98 801DAC98 2C6B0708 */  j          .L801DACB0
    /* 2C9C 801DAC9C 00000000 */   nop
  .L801DACA0:
    /* 2CA0 801DACA0 1E80043C */  lui        $a0, %hi(D_801D8A70)
    /* 2CA4 801DACA4 708A8424 */  addiu      $a0, $a0, %lo(D_801D8A70)
    /* 2CA8 801DACA8 2568070C */  jal        printf
    /* 2CAC 801DACAC 00000000 */   nop
  .L801DACB0:
    /* 2CB0 801DACB0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2CB4 801DACB4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2CB8 801DACB8 0800E003 */  jr         $ra
    /* 2CBC 801DACBC 00000000 */   nop
endlabel MDEC_reset

nonmatching MDEC_in, 0x94

glabel MDEC_in
    /* 2CC0 801DACC0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2CC4 801DACC4 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2CC8 801DACC8 21888000 */  addu       $s1, $a0, $zero
    /* 2CCC 801DACCC 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2CD0 801DACD0 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2CD4 801DACD4 796B070C */  jal        MDEC_in_sync
    /* 2CD8 801DACD8 2180A000 */   addu      $s0, $a1, $zero
    /* 2CDC 801DACDC 1E80033C */  lui        $v1, %hi(D_801E3E34)
    /* 2CE0 801DACE0 343E638C */  lw         $v1, %lo(D_801E3E34)($v1)
    /* 2CE4 801DACE4 42811000 */  srl        $s0, $s0, 5
    /* 2CE8 801DACE8 0000628C */  lw         $v0, 0x0($v1)
    /* 2CEC 801DACEC 00841000 */  sll        $s0, $s0, 16
    /* 2CF0 801DACF0 88004234 */  ori        $v0, $v0, 0x88
    /* 2CF4 801DACF4 000062AC */  sw         $v0, 0x0($v1)
    /* 2CF8 801DACF8 1E80033C */  lui        $v1, %hi(D_801E3DFC)
    /* 2CFC 801DACFC FC3D638C */  lw         $v1, %lo(D_801E3DFC)($v1)
    /* 2D00 801DAD00 04002226 */  addiu      $v0, $s1, 0x4
    /* 2D04 801DAD04 000062AC */  sw         $v0, 0x0($v1)
    /* 2D08 801DAD08 1E80023C */  lui        $v0, %hi(D_801E3E00)
    /* 2D0C 801DAD0C 003E428C */  lw         $v0, %lo(D_801E3E00)($v0)
    /* 2D10 801DAD10 20001036 */  ori        $s0, $s0, 0x20
    /* 2D14 801DAD14 000050AC */  sw         $s0, 0x0($v0)
    /* 2D18 801DAD18 1E80033C */  lui        $v1, %hi(D_801E3E2C)
    /* 2D1C 801DAD1C 2C3E638C */  lw         $v1, %lo(D_801E3E2C)($v1)
    /* 2D20 801DAD20 0000228E */  lw         $v0, 0x0($s1)
    /* 2D24 801DAD24 0001043C */  lui        $a0, (0x1000201 >> 16)
    /* 2D28 801DAD28 000062AC */  sw         $v0, 0x0($v1)
    /* 2D2C 801DAD2C 1E80023C */  lui        $v0, %hi(D_801E3E04)
    /* 2D30 801DAD30 043E428C */  lw         $v0, %lo(D_801E3E04)($v0)
    /* 2D34 801DAD34 01028434 */  ori        $a0, $a0, (0x1000201 & 0xFFFF)
    /* 2D38 801DAD38 000044AC */  sw         $a0, 0x0($v0)
    /* 2D3C 801DAD3C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2D40 801DAD40 1400B18F */  lw         $s1, 0x14($sp)
    /* 2D44 801DAD44 1000B08F */  lw         $s0, 0x10($sp)
    /* 2D48 801DAD48 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2D4C 801DAD4C 0800E003 */  jr         $ra
    /* 2D50 801DAD50 00000000 */   nop
endlabel MDEC_in

nonmatching MDEC_out, 0x90

glabel MDEC_out
    /* 2D54 801DAD54 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2D58 801DAD58 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2D5C 801DAD5C 21888000 */  addu       $s1, $a0, $zero
    /* 2D60 801DAD60 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2D64 801DAD64 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2D68 801DAD68 9F6B070C */  jal        MDEC_out_sync
    /* 2D6C 801DAD6C 2180A000 */   addu      $s0, $a1, $zero
    /* 2D70 801DAD70 1E80033C */  lui        $v1, %hi(D_801E3E34)
    /* 2D74 801DAD74 343E638C */  lw         $v1, %lo(D_801E3E34)($v1)
    /* 2D78 801DAD78 00000000 */  nop
    /* 2D7C 801DAD7C 0000628C */  lw         $v0, 0x0($v1)
    /* 2D80 801DAD80 42811000 */  srl        $s0, $s0, 5
    /* 2D84 801DAD84 88004234 */  ori        $v0, $v0, 0x88
    /* 2D88 801DAD88 000062AC */  sw         $v0, 0x0($v1)
    /* 2D8C 801DAD8C 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2D90 801DAD90 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2D94 801DAD94 00841000 */  sll        $s0, $s0, 16
    /* 2D98 801DAD98 000040AC */  sw         $zero, 0x0($v0)
    /* 2D9C 801DAD9C 1E80023C */  lui        $v0, %hi(D_801E3E08)
    /* 2DA0 801DADA0 083E428C */  lw         $v0, %lo(D_801E3E08)($v0)
    /* 2DA4 801DADA4 20001036 */  ori        $s0, $s0, 0x20
    /* 2DA8 801DADA8 000051AC */  sw         $s1, 0x0($v0)
    /* 2DAC 801DADAC 1E80023C */  lui        $v0, %hi(D_801E3E0C)
    /* 2DB0 801DADB0 0C3E428C */  lw         $v0, %lo(D_801E3E0C)($v0)
    /* 2DB4 801DADB4 0001033C */  lui        $v1, (0x1000200 >> 16)
    /* 2DB8 801DADB8 000050AC */  sw         $s0, 0x0($v0)
    /* 2DBC 801DADBC 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2DC0 801DADC0 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2DC4 801DADC4 00026334 */  ori        $v1, $v1, (0x1000200 & 0xFFFF)
    /* 2DC8 801DADC8 000043AC */  sw         $v1, 0x0($v0)
    /* 2DCC 801DADCC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2DD0 801DADD0 1400B18F */  lw         $s1, 0x14($sp)
    /* 2DD4 801DADD4 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DD8 801DADD8 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2DDC 801DADDC 0800E003 */  jr         $ra
    /* 2DE0 801DADE0 00000000 */   nop
endlabel MDEC_out

nonmatching MDEC_in_sync, 0x98

glabel MDEC_in_sync
    /* 2DE4 801DADE4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2DE8 801DADE8 1E80033C */  lui        $v1, %hi(D_801E3E30)
    /* 2DEC 801DADEC 303E638C */  lw         $v1, %lo(D_801E3E30)($v1)
    /* 2DF0 801DADF0 1000023C */  lui        $v0, (0x100000 >> 16)
    /* 2DF4 801DADF4 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2DF8 801DADF8 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2DFC 801DADFC 0000628C */  lw         $v0, 0x0($v1)
    /* 2E00 801DAE00 0020033C */  lui        $v1, (0x20000000 >> 16)
    /* 2E04 801DAE04 24104300 */  and        $v0, $v0, $v1
    /* 2E08 801DAE08 18004010 */  beqz       $v0, .L801DAE6C
    /* 2E0C 801DAE0C 21100000 */   addu      $v0, $zero, $zero
    /* 2E10 801DAE10 FFFF0424 */  addiu      $a0, $zero, -0x1
  .L801DAE14:
    /* 2E14 801DAE14 1000A28F */  lw         $v0, 0x10($sp)
    /* 2E18 801DAE18 00000000 */  nop
    /* 2E1C 801DAE1C FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2E20 801DAE20 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2E24 801DAE24 1000A28F */  lw         $v0, 0x10($sp)
    /* 2E28 801DAE28 00000000 */  nop
    /* 2E2C 801DAE2C 07004414 */  bne        $v0, $a0, .L801DAE4C
    /* 2E30 801DAE30 00000000 */   nop
    /* 2E34 801DAE34 1E80043C */  lui        $a0, %hi(D_801D8A8C)
    /* 2E38 801DAE38 8C8A8424 */  addiu      $a0, $a0, %lo(D_801D8A8C)
    /* 2E3C 801DAE3C CB6B070C */  jal        timeout
    /* 2E40 801DAE40 00000000 */   nop
    /* 2E44 801DAE44 9B6B0708 */  j          .L801DAE6C
    /* 2E48 801DAE48 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L801DAE4C:
    /* 2E4C 801DAE4C 1E80023C */  lui        $v0, %hi(D_801E3E30)
    /* 2E50 801DAE50 303E428C */  lw         $v0, %lo(D_801E3E30)($v0)
    /* 2E54 801DAE54 00000000 */  nop
    /* 2E58 801DAE58 0000428C */  lw         $v0, 0x0($v0)
    /* 2E5C 801DAE5C 00000000 */  nop
    /* 2E60 801DAE60 24104300 */  and        $v0, $v0, $v1
    /* 2E64 801DAE64 EBFF4014 */  bnez       $v0, .L801DAE14
    /* 2E68 801DAE68 21100000 */   addu      $v0, $zero, $zero
  .L801DAE6C:
    /* 2E6C 801DAE6C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2E70 801DAE70 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2E74 801DAE74 0800E003 */  jr         $ra
    /* 2E78 801DAE78 00000000 */   nop
endlabel MDEC_in_sync

nonmatching MDEC_out_sync, 0x98

glabel MDEC_out_sync
    /* 2E7C 801DAE7C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2E80 801DAE80 1E80033C */  lui        $v1, %hi(D_801E3E10)
    /* 2E84 801DAE84 103E638C */  lw         $v1, %lo(D_801E3E10)($v1)
    /* 2E88 801DAE88 1000023C */  lui        $v0, (0x100000 >> 16)
    /* 2E8C 801DAE8C 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2E90 801DAE90 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2E94 801DAE94 0000628C */  lw         $v0, 0x0($v1)
    /* 2E98 801DAE98 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 2E9C 801DAE9C 24104300 */  and        $v0, $v0, $v1
    /* 2EA0 801DAEA0 18004010 */  beqz       $v0, .L801DAF04
    /* 2EA4 801DAEA4 21100000 */   addu      $v0, $zero, $zero
    /* 2EA8 801DAEA8 FFFF0424 */  addiu      $a0, $zero, -0x1
  .L801DAEAC:
    /* 2EAC 801DAEAC 1000A28F */  lw         $v0, 0x10($sp)
    /* 2EB0 801DAEB0 00000000 */  nop
    /* 2EB4 801DAEB4 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2EB8 801DAEB8 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2EBC 801DAEBC 1000A28F */  lw         $v0, 0x10($sp)
    /* 2EC0 801DAEC0 00000000 */  nop
    /* 2EC4 801DAEC4 07004414 */  bne        $v0, $a0, .L801DAEE4
    /* 2EC8 801DAEC8 00000000 */   nop
    /* 2ECC 801DAECC 1E80043C */  lui        $a0, %hi(D_801D8A9C)
    /* 2ED0 801DAED0 9C8A8424 */  addiu      $a0, $a0, %lo(D_801D8A9C)
    /* 2ED4 801DAED4 CB6B070C */  jal        timeout
    /* 2ED8 801DAED8 00000000 */   nop
    /* 2EDC 801DAEDC C16B0708 */  j          .L801DAF04
    /* 2EE0 801DAEE0 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L801DAEE4:
    /* 2EE4 801DAEE4 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2EE8 801DAEE8 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2EEC 801DAEEC 00000000 */  nop
    /* 2EF0 801DAEF0 0000428C */  lw         $v0, 0x0($v0)
    /* 2EF4 801DAEF4 00000000 */  nop
    /* 2EF8 801DAEF8 24104300 */  and        $v0, $v0, $v1
    /* 2EFC 801DAEFC EBFF4014 */  bnez       $v0, .L801DAEAC
    /* 2F00 801DAF00 21100000 */   addu      $v0, $zero, $zero
  .L801DAF04:
    /* 2F04 801DAF04 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2F08 801DAF08 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2F0C 801DAF0C 0800E003 */  jr         $ra
    /* 2F10 801DAF10 00000000 */   nop
endlabel MDEC_out_sync

nonmatching MDEC_status, 0x18

glabel MDEC_status
    /* 2F14 801DAF14 1E80023C */  lui        $v0, %hi(D_801E3E30)
    /* 2F18 801DAF18 303E428C */  lw         $v0, %lo(D_801E3E30)($v0)
    /* 2F1C 801DAF1C 00000000 */  nop
    /* 2F20 801DAF20 0000428C */  lw         $v0, 0x0($v0)
    /* 2F24 801DAF24 0800E003 */  jr         $ra
    /* 2F28 801DAF28 00000000 */   nop
endlabel MDEC_status

nonmatching timeout, 0x130

glabel timeout
    /* 2F2C 801DAF2C D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2F30 801DAF30 21288000 */  addu       $a1, $a0, $zero
    /* 2F34 801DAF34 1E80043C */  lui        $a0, %hi(D_801D8B0C)
    /* 2F38 801DAF38 0C8B8424 */  addiu      $a0, $a0, %lo(D_801D8B0C)
    /* 2F3C 801DAF3C 2400BFAF */  sw         $ra, 0x24($sp)
    /* 2F40 801DAF40 2568070C */  jal        printf
    /* 2F44 801DAF44 2000B0AF */   sw        $s0, 0x20($sp)
    /* 2F48 801DAF48 1E80043C */  lui        $a0, %hi(D_801D8AAC)
    /* 2F4C 801DAF4C AC8A8424 */  addiu      $a0, $a0, %lo(D_801D8AAC)
    /* 2F50 801DAF50 1E80023C */  lui        $v0, %hi(D_801E3E30)
    /* 2F54 801DAF54 303E428C */  lw         $v0, %lo(D_801E3E30)($v0)
    /* 2F58 801DAF58 1E80033C */  lui        $v1, %hi(D_801E3E04)
    /* 2F5C 801DAF5C 043E638C */  lw         $v1, %lo(D_801E3E04)($v1)
    /* 2F60 801DAF60 0000508C */  lw         $s0, 0x0($v0)
    /* 2F64 801DAF64 0000658C */  lw         $a1, 0x0($v1)
    /* 2F68 801DAF68 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 2F6C 801DAF6C 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 2F70 801DAF70 1E80033C */  lui        $v1, %hi(D_801E3DFC)
    /* 2F74 801DAF74 FC3D638C */  lw         $v1, %lo(D_801E3DFC)($v1)
    /* 2F78 801DAF78 022E0500 */  srl        $a1, $a1, 24
    /* 2F7C 801DAF7C 0000468C */  lw         $a2, 0x0($v0)
    /* 2F80 801DAF80 1E80023C */  lui        $v0, %hi(D_801E3E08)
    /* 2F84 801DAF84 083E428C */  lw         $v0, %lo(D_801E3E08)($v0)
    /* 2F88 801DAF88 0100A530 */  andi       $a1, $a1, 0x1
    /* 2F8C 801DAF8C 0000428C */  lw         $v0, 0x0($v0)
    /* 2F90 801DAF90 02360600 */  srl        $a2, $a2, 24
    /* 2F94 801DAF94 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2F98 801DAF98 0000678C */  lw         $a3, 0x0($v1)
    /* 2F9C 801DAF9C 2568070C */  jal        printf
    /* 2FA0 801DAFA0 0100C630 */   andi      $a2, $a2, 0x1
    /* 2FA4 801DAFA4 1E80043C */  lui        $a0, %hi(D_801D8AD4)
    /* 2FA8 801DAFA8 D48A8424 */  addiu      $a0, $a0, %lo(D_801D8AD4)
    /* 2FAC 801DAFAC 27281000 */  nor        $a1, $zero, $s0
    /* 2FB0 801DAFB0 C22F0500 */  srl        $a1, $a1, 31
    /* 2FB4 801DAFB4 82371000 */  srl        $a2, $s0, 30
    /* 2FB8 801DAFB8 0100C630 */  andi       $a2, $a2, 0x1
    /* 2FBC 801DAFBC 423F1000 */  srl        $a3, $s0, 29
    /* 2FC0 801DAFC0 0100E730 */  andi       $a3, $a3, 0x1
    /* 2FC4 801DAFC4 02171000 */  srl        $v0, $s0, 28
    /* 2FC8 801DAFC8 01004230 */  andi       $v0, $v0, 0x1
    /* 2FCC 801DAFCC 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2FD0 801DAFD0 C2161000 */  srl        $v0, $s0, 27
    /* 2FD4 801DAFD4 01004230 */  andi       $v0, $v0, 0x1
    /* 2FD8 801DAFD8 1400A2AF */  sw         $v0, 0x14($sp)
    /* 2FDC 801DAFDC 42161000 */  srl        $v0, $s0, 25
    /* 2FE0 801DAFE0 01004230 */  andi       $v0, $v0, 0x1
    /* 2FE4 801DAFE4 C2851000 */  srl        $s0, $s0, 23
    /* 2FE8 801DAFE8 01001032 */  andi       $s0, $s0, 0x1
    /* 2FEC 801DAFEC 1800A2AF */  sw         $v0, 0x18($sp)
    /* 2FF0 801DAFF0 2568070C */  jal        printf
    /* 2FF4 801DAFF4 1C00B0AF */   sw        $s0, 0x1C($sp)
    /* 2FF8 801DAFF8 1E80033C */  lui        $v1, %hi(D_801E3E30)
    /* 2FFC 801DAFFC 303E638C */  lw         $v1, %lo(D_801E3E30)($v1)
    /* 3000 801DB000 0080023C */  lui        $v0, (0x80000000 >> 16)
    /* 3004 801DB004 000062AC */  sw         $v0, 0x0($v1)
    /* 3008 801DB008 1E80023C */  lui        $v0, %hi(D_801E3E04)
    /* 300C 801DB00C 043E428C */  lw         $v0, %lo(D_801E3E04)($v0)
    /* 3010 801DB010 00000000 */  nop
    /* 3014 801DB014 000040AC */  sw         $zero, 0x0($v0)
    /* 3018 801DB018 1E80023C */  lui        $v0, %hi(D_801E3E10)
    /* 301C 801DB01C 103E428C */  lw         $v0, %lo(D_801E3E10)($v0)
    /* 3020 801DB020 00000000 */  nop
    /* 3024 801DB024 000040AC */  sw         $zero, 0x0($v0)
    /* 3028 801DB028 21100000 */  addu       $v0, $zero, $zero
    /* 302C 801DB02C 1E80033C */  lui        $v1, %hi(D_801E3E10)
    /* 3030 801DB030 103E638C */  lw         $v1, %lo(D_801E3E10)($v1)
    /* 3034 801DB034 1E80043C */  lui        $a0, %hi(D_801E3E30)
    /* 3038 801DB038 303E848C */  lw         $a0, %lo(D_801E3E30)($a0)
    /* 303C 801DB03C 0000638C */  lw         $v1, 0x0($v1)
    /* 3040 801DB040 0060033C */  lui        $v1, (0x60000000 >> 16)
    /* 3044 801DB044 000083AC */  sw         $v1, 0x0($a0)
    /* 3048 801DB048 2400BF8F */  lw         $ra, 0x24($sp)
    /* 304C 801DB04C 2000B08F */  lw         $s0, 0x20($sp)
    /* 3050 801DB050 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 3054 801DB054 0800E003 */  jr         $ra
    /* 3058 801DB058 00000000 */   nop
endlabel timeout
