.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 2
nonmatching D_801D8800

dlabel D_801D8800
    /* 800 801D8800 */ .asciz "size of DECENV_R = 0x%08X\n"
    /* 73697A65206F6620444543454E565F52203D203078253038580A0000 */
.align 2
enddlabel D_801D8800

.align 2
nonmatching D_801D881C

dlabel D_801D881C
    /* 81C 801D881C */ .asciz "size of DECENV_B = 0x%08X\n"
    /* 73697A65206F6620444543454E565F42203D203078253038580A0000 */
.align 2
enddlabel D_801D881C

.align 2
nonmatching D_801D8838

dlabel D_801D8838
    /* 838 801D8838 */ .asciz "strNext is NULL\n"
    /* 7374724E657874206973204E554C4C0A00000000 */
.align 2
enddlabel D_801D8838

.align 2
nonmatching D_801D884C

dlabel D_801D884C
    /* 84C 801D884C */ .asciz "Cd error!!!\n"
    /* 4364206572726F722121210A00000000 */
.align 2
enddlabel D_801D884C

.align 2
nonmatching D_801D885C

dlabel D_801D885C
    /* 85C 801D885C */ .asciz "0123456789abcdef"
    /* 3031323334353637383961626364656600000000 */
.align 2
enddlabel D_801D885C

.align 2
nonmatching D_801D8870

dlabel D_801D8870
    /* 870 801D8870 */ .asciz "(null)"
    /* 286E756C6C290000 */
.align 2
enddlabel D_801D8870

.align 2
nonmatching D_801D8878

dlabel D_801D8878
    /* 878 801D8878 */ .asciz "0123456789ABCDEF"
    /* 3031323334353637383941424344454600000000 */
.align 2
enddlabel D_801D8878

nonmatching jtbl_801D888C

dlabel jtbl_801D888C
    /* 88C 801D888C 30A11D80 */ .word .L801DA130
    /* 890 801D8890 04A71D80 */ .word .L801DA704
    /* 894 801D8894 04A71D80 */ .word .L801DA704
    /* 898 801D8898 04A71D80 */ .word .L801DA704
    /* 89C 801D889C 04A71D80 */ .word .L801DA704
    /* 8A0 801D88A0 04A71D80 */ .word .L801DA704
    /* 8A4 801D88A4 04A71D80 */ .word .L801DA704
    /* 8A8 801D88A8 04A71D80 */ .word .L801DA704
    /* 8AC 801D88AC 04A71D80 */ .word .L801DA704
    /* 8B0 801D88B0 04A71D80 */ .word .L801DA704
    /* 8B4 801D88B4 04A71D80 */ .word .L801DA704
    /* 8B8 801D88B8 04A71D80 */ .word .L801DA704
    /* 8BC 801D88BC 04A71D80 */ .word .L801DA704
    /* 8C0 801D88C0 04A71D80 */ .word .L801DA704
    /* 8C4 801D88C4 04A71D80 */ .word .L801DA704
    /* 8C8 801D88C8 04A71D80 */ .word .L801DA704
    /* 8CC 801D88CC 04A71D80 */ .word .L801DA704
    /* 8D0 801D88D0 04A71D80 */ .word .L801DA704
    /* 8D4 801D88D4 04A71D80 */ .word .L801DA704
    /* 8D8 801D88D8 04A71D80 */ .word .L801DA704
    /* 8DC 801D88DC 04A71D80 */ .word .L801DA704
    /* 8E0 801D88E0 04A71D80 */ .word .L801DA704
    /* 8E4 801D88E4 04A71D80 */ .word .L801DA704
    /* 8E8 801D88E8 04A71D80 */ .word .L801DA704
    /* 8EC 801D88EC 04A71D80 */ .word .L801DA704
    /* 8F0 801D88F0 04A71D80 */ .word .L801DA704
    /* 8F4 801D88F4 04A71D80 */ .word .L801DA704
    /* 8F8 801D88F8 04A71D80 */ .word .L801DA704
    /* 8FC 801D88FC 04A71D80 */ .word .L801DA704
    /* 900 801D8900 04A71D80 */ .word .L801DA704
    /* 904 801D8904 04A71D80 */ .word .L801DA704
    /* 908 801D8908 04A71D80 */ .word .L801DA704
    /* 90C 801D890C 88A11D80 */ .word .L801DA188
    /* 910 801D8910 04A71D80 */ .word .L801DA704
    /* 914 801D8914 04A71D80 */ .word .L801DA704
    /* 918 801D8918 98A11D80 */ .word .L801DA198
    /* 91C 801D891C 04A71D80 */ .word .L801DA704
    /* 920 801D8920 04A71D80 */ .word .L801DA704
    /* 924 801D8924 04A71D80 */ .word .L801DA704
    /* 928 801D8928 04A71D80 */ .word .L801DA704
    /* 92C 801D892C 04A71D80 */ .word .L801DA704
    /* 930 801D8930 04A71D80 */ .word .L801DA704
    /* 934 801D8934 A0A11D80 */ .word .L801DA1A0
    /* 938 801D8938 C4A11D80 */ .word .L801DA1C4
    /* 93C 801D893C 04A71D80 */ .word .L801DA704
    /* 940 801D8940 BCA11D80 */ .word .L801DA1BC
    /* 944 801D8944 CCA11D80 */ .word .L801DA1CC
    /* 948 801D8948 04A71D80 */ .word .L801DA704
    /* 94C 801D894C 58A21D80 */ .word .L801DA258
    /* 950 801D8950 60A21D80 */ .word .L801DA260
    /* 954 801D8954 60A21D80 */ .word .L801DA260
    /* 958 801D8958 60A21D80 */ .word .L801DA260
    /* 95C 801D895C 60A21D80 */ .word .L801DA260
    /* 960 801D8960 60A21D80 */ .word .L801DA260
    /* 964 801D8964 60A21D80 */ .word .L801DA260
    /* 968 801D8968 60A21D80 */ .word .L801DA260
    /* 96C 801D896C 60A21D80 */ .word .L801DA260
    /* 970 801D8970 60A21D80 */ .word .L801DA260
    /* 974 801D8974 04A71D80 */ .word .L801DA704
    /* 978 801D8978 04A71D80 */ .word .L801DA704
    /* 97C 801D897C 04A71D80 */ .word .L801DA704
    /* 980 801D8980 04A71D80 */ .word .L801DA704
    /* 984 801D8984 04A71D80 */ .word .L801DA704
    /* 988 801D8988 04A71D80 */ .word .L801DA704
    /* 98C 801D898C 04A71D80 */ .word .L801DA704
    /* 990 801D8990 04A71D80 */ .word .L801DA704
    /* 994 801D8994 04A71D80 */ .word .L801DA704
    /* 998 801D8998 04A71D80 */ .word .L801DA704
    /* 99C 801D899C ECA21D80 */ .word .L801DA2EC
    /* 9A0 801D89A0 04A71D80 */ .word .L801DA704
    /* 9A4 801D89A4 04A71D80 */ .word .L801DA704
    /* 9A8 801D89A8 04A71D80 */ .word .L801DA704
    /* 9AC 801D89AC 04A71D80 */ .word .L801DA704
    /* 9B0 801D89B0 04A71D80 */ .word .L801DA704
    /* 9B4 801D89B4 04A71D80 */ .word .L801DA704
    /* 9B8 801D89B8 04A71D80 */ .word .L801DA704
    /* 9BC 801D89BC B8A21D80 */ .word .L801DA2B8
    /* 9C0 801D89C0 04A71D80 */ .word .L801DA704
    /* 9C4 801D89C4 04A71D80 */ .word .L801DA704
    /* 9C8 801D89C8 70A31D80 */ .word .L801DA370
    /* 9CC 801D89CC 04A71D80 */ .word .L801DA704
    /* 9D0 801D89D0 04A71D80 */ .word .L801DA704
    /* 9D4 801D89D4 04A71D80 */ .word .L801DA704
    /* 9D8 801D89D8 04A71D80 */ .word .L801DA704
    /* 9DC 801D89DC 04A71D80 */ .word .L801DA704
    /* 9E0 801D89E0 18A41D80 */ .word .L801DA418
    /* 9E4 801D89E4 04A71D80 */ .word .L801DA704
    /* 9E8 801D89E8 04A71D80 */ .word .L801DA704
    /* 9EC 801D89EC 50A41D80 */ .word .L801DA450
    /* 9F0 801D89F0 04A71D80 */ .word .L801DA704
    /* 9F4 801D89F4 04A71D80 */ .word .L801DA704
    /* 9F8 801D89F8 04A71D80 */ .word .L801DA704
    /* 9FC 801D89FC 04A71D80 */ .word .L801DA704
    /* A00 801D8A00 04A71D80 */ .word .L801DA704
    /* A04 801D8A04 04A71D80 */ .word .L801DA704
    /* A08 801D8A08 04A71D80 */ .word .L801DA704
    /* A0C 801D8A0C 04A71D80 */ .word .L801DA704
    /* A10 801D8A10 04A71D80 */ .word .L801DA704
    /* A14 801D8A14 04A71D80 */ .word .L801DA704
    /* A18 801D8A18 D0A21D80 */ .word .L801DA2D0
    /* A1C 801D8A1C F0A21D80 */ .word .L801DA2F0
    /* A20 801D8A20 04A71D80 */ .word .L801DA704
    /* A24 801D8A24 04A71D80 */ .word .L801DA704
    /* A28 801D8A28 04A71D80 */ .word .L801DA704
    /* A2C 801D8A2C C0A21D80 */ .word .L801DA2C0
    /* A30 801D8A30 F0A21D80 */ .word .L801DA2F0
    /* A34 801D8A34 04A71D80 */ .word .L801DA704
    /* A38 801D8A38 04A71D80 */ .word .L801DA704
    /* A3C 801D8A3C C8A21D80 */ .word .L801DA2C8
    /* A40 801D8A40 04A71D80 */ .word .L801DA704
    /* A44 801D8A44 34A31D80 */ .word .L801DA334
    /* A48 801D8A48 74A31D80 */ .word .L801DA374
    /* A4C 801D8A4C A8A31D80 */ .word .L801DA3A8
    /* A50 801D8A50 04A71D80 */ .word .L801DA704
    /* A54 801D8A54 04A71D80 */ .word .L801DA704
    /* A58 801D8A58 B8A31D80 */ .word .L801DA3B8
    /* A5C 801D8A5C 04A71D80 */ .word .L801DA704
    /* A60 801D8A60 1CA41D80 */ .word .L801DA41C
    /* A64 801D8A64 04A71D80 */ .word .L801DA704
    /* A68 801D8A68 04A71D80 */ .word .L801DA704
    /* A6C 801D8A6C 5CA41D80 */ .word .L801DA45C
enddlabel jtbl_801D888C

.align 2
nonmatching D_801D8A70

dlabel D_801D8A70
    /* A70 801D8A70 */ .asciz "MDEC_rest:bad option(%d)\n"
    /* 4D4445435F726573743A626164206F7074696F6E282564290A000000 */
.align 2
enddlabel D_801D8A70

.align 2
nonmatching D_801D8A8C

dlabel D_801D8A8C
    /* A8C 801D8A8C */ .asciz "MDEC_in_sync"
    /* 4D4445435F696E5F73796E6300000000 */
.align 2
enddlabel D_801D8A8C

.align 2
nonmatching D_801D8A9C

dlabel D_801D8A9C
    /* A9C 801D8A9C */ .asciz "MDEC_out_sync"
    /* 4D4445435F6F75745F73796E63000000 */
.align 2
enddlabel D_801D8A9C

.align 2
nonmatching D_801D8AAC

dlabel D_801D8AAC
    /* AAC 801D8AAC */ .asciz "\t DMA=(%d,%d), ADDR=(0x%08x->0x%08x)\n"
    /* 0920444D413D2825642C2564292C20414444523D283078253038782D3E307825303878290A000000 */
.align 2
enddlabel D_801D8AAC

.align 2
nonmatching D_801D8AD4

dlabel D_801D8AD4
    /* AD4 801D8AD4 */ .asciz "\t FIFO=(%d,%d),BUSY=%d,DREQ=(%d,%d),RGB24=%d,STP=%d\n"
    /* 09204649464F3D2825642C2564292C425553593D25642C445245513D2825642C2564292C52474232343D25642C5354503D25640A00000000 */
.align 2
enddlabel D_801D8AD4

.align 2
nonmatching D_801D8B0C

dlabel D_801D8B0C
    /* B0C 801D8B0C */ .asciz "%s timeout:\n"
    /* 25732074696D656F75743A0A00000000 */
.align 2
enddlabel D_801D8B0C

.align 2
nonmatching D_801D8B1C

dlabel D_801D8B1C
    /* B1C 801D8B1C */ .asciz "tpage: (%d,%d,%d,%d)\n"
    /* 74706167653A202825642C25642C25642C2564290A000000 */
.align 2
enddlabel D_801D8B1C

.align 2
nonmatching D_801D8B34

dlabel D_801D8B34
    /* B34 801D8B34 */ .asciz "clut: (%d,%d)\n"
    /* 636C75743A202825642C2564290A0000 */
.align 2
enddlabel D_801D8B34

.align 2
nonmatching D_801D8B44

dlabel D_801D8B44
    /* B44 801D8B44 */ .asciz "clip (%3d,%3d)-(%d,%d)\n"
    /* 636C697020282533642C253364292D2825642C2564290A00 */
.align 2
enddlabel D_801D8B44

.align 2
nonmatching D_801D8B5C

dlabel D_801D8B5C
    /* B5C 801D8B5C */ .asciz "ofs  (%3d,%3d)\n"
    /* 6F66732020282533642C253364290A00 */
.align 2
enddlabel D_801D8B5C

.align 2
nonmatching D_801D8B6C

dlabel D_801D8B6C
    /* B6C 801D8B6C */ .asciz "tw   (%d,%d)-(%d,%d)\n"
    /* 74772020202825642C2564292D2825642C2564290A000000 */
.align 2
enddlabel D_801D8B6C

.align 2
nonmatching D_801D8B84

dlabel D_801D8B84
    /* B84 801D8B84 */ .asciz "dtd   %d\n"
    /* 64746420202025640A000000 */
.align 2
enddlabel D_801D8B84

.align 2
nonmatching D_801D8B90

dlabel D_801D8B90
    /* B90 801D8B90 */ .asciz "dfe   %d\n"
    /* 64666520202025640A000000 */
.align 2
enddlabel D_801D8B90

.align 2
nonmatching D_801D8B9C

dlabel D_801D8B9C
    /* B9C 801D8B9C */ .asciz "disp   (%3d,%3d)-(%d,%d)\n"
    /* 64697370202020282533642C253364292D2825642C2564290A000000 */
.align 2
enddlabel D_801D8B9C

.align 2
nonmatching D_801D8BB8

dlabel D_801D8BB8
    /* BB8 801D8BB8 */ .asciz "screen (%3d,%3d)-(%d,%d)\n"
    /* 73637265656E20282533642C253364292D2825642C2564290A000000 */
.align 2
enddlabel D_801D8BB8

.align 2
nonmatching D_801D8BD4

dlabel D_801D8BD4
    /* BD4 801D8BD4 */ .asciz "isinter %d\n"
    /* 6973696E7465722025640A00 */
.align 2
enddlabel D_801D8BD4

.align 2
nonmatching D_801D8BE0

dlabel D_801D8BE0
    /* BE0 801D8BE0 */ .asciz "isrgb24 %d\n"
    /* 697372676232342025640A00 */
.align 2
.align 2
    /* BEC 801D8BEC */ .asciz "$Id: sys.c,v 1.129 1996/12/25 03:36:20 noda Exp $"
    /* 2449643A207379732E632C7620312E31323920313939362F31322F32352030333A33363A3230206E6F6461204578702024000000 */
.align 2
enddlabel D_801D8BE0

.align 2
nonmatching D_801D8C20

dlabel D_801D8C20
    /* C20 801D8C20 */ .asciz "ResetGraph:jtb=%08x,env=%08x\n"
    /* 526573657447726170683A6A74623D253038782C656E763D253038780A000000 */
.align 2
enddlabel D_801D8C20

.align 2
nonmatching D_801D8C40

dlabel D_801D8C40
    /* C40 801D8C40 */ .asciz "ResetGraph(%d)...\n"
    /* 52657365744772617068282564292E2E2E0A0000 */
.align 2
enddlabel D_801D8C40

.align 2
nonmatching D_801D8C54

dlabel D_801D8C54
    /* C54 801D8C54 */ .asciz "SetGraphReverse(%d)...\n"
    /* 536574477261706852657665727365282564292E2E2E0A00 */
.align 2
enddlabel D_801D8C54

.align 2
nonmatching D_801D8C6C

dlabel D_801D8C6C
    /* C6C 801D8C6C */ .asciz "SetGraphDebug:level:%d,type:%d reverse:%d\n"
    /* 536574477261706844656275673A6C6576656C3A25642C747970653A256420726576657273653A25640A0000 */
.align 2
enddlabel D_801D8C6C

.align 2
nonmatching D_801D8C98

dlabel D_801D8C98
    /* C98 801D8C98 */ .asciz "SetGrapQue(%d)...\n"
    /* 53657447726170517565282564292E2E2E0A0000 */
.align 2
enddlabel D_801D8C98

.align 2
nonmatching D_801D8CAC

dlabel D_801D8CAC
    /* CAC 801D8CAC */ .asciz "DrawSyncCallback(%08x)...\n"
    /* 4472617753796E6343616C6C6261636B2825303878292E2E2E0A0000 */
.align 2
enddlabel D_801D8CAC

.align 2
nonmatching D_801D8CC8

dlabel D_801D8CC8
    /* CC8 801D8CC8 */ .asciz "SetDispMask(%d)...\n"
    /* 536574446973704D61736B282564292E2E2E0A00 */
.align 2
enddlabel D_801D8CC8

.align 2
nonmatching D_801D8CDC

dlabel D_801D8CDC
    /* CDC 801D8CDC */ .asciz "DrawSync(%d)...\n"
    /* 4472617753796E63282564292E2E2E0A00000000 */
.align 2
enddlabel D_801D8CDC

.align 2
nonmatching D_801D8CF0

dlabel D_801D8CF0
    /* CF0 801D8CF0 */ .asciz "%s:bad RECT"
    /* 25733A626164205245435400 */
.align 2
enddlabel D_801D8CF0

.align 2
nonmatching D_801D8CFC

dlabel D_801D8CFC
    /* CFC 801D8CFC */ .asciz "(%d,%d)-(%d,%d)\n"
    /* 2825642C2564292D2825642C2564290A00000000 */
.align 2
enddlabel D_801D8CFC

.align 2
nonmatching D_801D8D10

dlabel D_801D8D10
    /* D10 801D8D10 */ .asciz "%s:"
    /* 25733A00 */
.align 2
enddlabel D_801D8D10

.align 2
nonmatching D_801D8D14

dlabel D_801D8D14
    /* D14 801D8D14 */ .asciz "ClearImage"
    /* 436C656172496D6167650000 */
.align 2
enddlabel D_801D8D14

.align 2
nonmatching D_801D8D20

dlabel D_801D8D20
    /* D20 801D8D20 */ .asciz "LoadImage"
    /* 4C6F6164496D616765000000 */
.align 2
enddlabel D_801D8D20

.align 2
nonmatching D_801D8D2C

dlabel D_801D8D2C
    /* D2C 801D8D2C */ .asciz "StoreImage"
    /* 53746F7265496D6167650000 */
.align 2
enddlabel D_801D8D2C

.align 2
nonmatching D_801D8D38

dlabel D_801D8D38
    /* D38 801D8D38 */ .asciz "MoveImage"
    /* 4D6F7665496D616765000000 */
.align 2
enddlabel D_801D8D38

.align 2
nonmatching D_801D8D44

dlabel D_801D8D44
    /* D44 801D8D44 */ .asciz "ClearOTag(%08x,%d)...\n"
    /* 436C6561724F54616728253038782C2564292E2E2E0A0000 */
.align 2
enddlabel D_801D8D44

.align 2
nonmatching D_801D8D5C

dlabel D_801D8D5C
    /* D5C 801D8D5C */ .asciz "ClearOTagR(%08x,%d)...\n"
    /* 436C6561724F5461675228253038782C2564292E2E2E0A00 */
.align 2
enddlabel D_801D8D5C

.align 2
nonmatching D_801D8D74

dlabel D_801D8D74
    /* D74 801D8D74 */ .asciz "DrawOTag(%08x)...\n"
    /* 447261774F5461672825303878292E2E2E0A0000 */
.align 2
enddlabel D_801D8D74

.align 2
nonmatching D_801D8D88

dlabel D_801D8D88
    /* D88 801D8D88 */ .asciz "PutDrawEnv(%08x)...\n"
    /* 50757444726177456E762825303878292E2E2E0A00000000 */
.align 2
enddlabel D_801D8D88

.align 2
nonmatching D_801D8DA0

dlabel D_801D8DA0
    /* DA0 801D8DA0 */ .asciz "DrawOTagEnv(%08x,&08x)...\n"
    /* 447261774F546167456E7628253038782C26303878292E2E2E0A0000 */
.align 2
enddlabel D_801D8DA0

.align 2
nonmatching D_801D8DBC

dlabel D_801D8DBC
    /* DBC 801D8DBC */ .asciz "PutDispEnv(%08x)...\n"
    /* 50757444697370456E762825303878292E2E2E0A00000000 */
.align 2
enddlabel D_801D8DBC

.align 2
nonmatching D_801D8DD4

dlabel D_801D8DD4
    /* DD4 801D8DD4 */ .asciz "GPU timeout:que=%d,stat=%08x,chcr=%08x,madr=%08x,"
    /* 4750552074696D656F75743A7175653D25642C737461743D253038782C636863723D253038782C6D6164723D253038782C000000 */
.align 2
enddlabel D_801D8DD4

.align 2
nonmatching D_801D8E08

dlabel D_801D8E08
    /* E08 801D8E08 */ .asciz "func=(%08x)(%08x,%08x)\n"
    /* 66756E633D28253038782928253038782C25303878290A00 */
.align 2
enddlabel D_801D8E08

.align 2
nonmatching D_801D8E20

dlabel D_801D8E20
    /* E20 801D8E20 */ .asciz "CdInit: Init failed\n"
    /* 4364496E69743A20496E6974206661696C65640A00000000 */
.align 2
enddlabel D_801D8E20

.align 2
nonmatching D_801D8E38

dlabel D_801D8E38
    /* E38 801D8E38 */ .asciz "none"
    /* 6E6F6E6500000000 */
.align 2
.align 2
    /* E40 801D8E40 */ .asciz "CdlReadS"
    /* 43646C526561645300000000 */
.align 2
.align 2
    /* E4C 801D8E4C */ .asciz "CdlSeekP"
    /* 43646C5365656B5000000000 */
.align 2
.align 2
    /* E58 801D8E58 */ .asciz "CdlSeekL"
    /* 43646C5365656B4C00000000 */
.align 2
.align 2
    /* E64 801D8E64 */ .asciz "CdlGetTD"
    /* 43646C476574544400000000 */
.align 2
.align 2
    /* E70 801D8E70 */ .asciz "CdlGetTN"
    /* 43646C476574544E00000000 */
.align 2
.align 2
    /* E7C 801D8E7C */ .asciz "CdlGetlocP"
    /* 43646C4765746C6F63500000 */
.align 2
.align 2
    /* E88 801D8E88 */ .asciz "CdlGetlocL"
    /* 43646C4765746C6F634C0000 */
.align 2
.align 2
    /* E94 801D8E94 */ .asciz "?"
    /* 3F000000 */
.align 2
.align 2
    /* E98 801D8E98 */ .asciz "CdlSetmode"
    /* 43646C5365746D6F64650000 */
.align 2
.align 2
    /* EA4 801D8EA4 */ .asciz "CdlSetfilter"
    /* 43646C53657466696C74657200000000 */
.align 2
.align 2
    /* EB4 801D8EB4 */ .asciz "CdlDemute"
    /* 43646C44656D757465000000 */
.align 2
.align 2
    /* EC0 801D8EC0 */ .asciz "CdlMute"
    /* 43646C4D75746500 */
.align 2
.align 2
    /* EC8 801D8EC8 */ .asciz "CdlReset"
    /* 43646C526573657400000000 */
.align 2
.align 2
    /* ED4 801D8ED4 */ .asciz "CdlPause"
    /* 43646C506175736500000000 */
.align 2
.align 2
    /* EE0 801D8EE0 */ .asciz "CdlStop"
    /* 43646C53746F7000 */
.align 2
.align 2
    /* EE8 801D8EE8 */ .asciz "CdlStandby"
    /* 43646C5374616E6462790000 */
.align 2
.align 2
    /* EF4 801D8EF4 */ .asciz "CdlReadN"
    /* 43646C526561644E00000000 */
.align 2
.align 2
    /* F00 801D8F00 */ .asciz "CdlBackward"
    /* 43646C4261636B7761726400 */
.align 2
.align 2
    /* F0C 801D8F0C */ .asciz "CdlForward"
    /* 43646C466F72776172640000 */
.align 2
.align 2
    /* F18 801D8F18 */ .asciz "CdlPlay"
    /* 43646C506C617900 */
.align 2
.align 2
    /* F20 801D8F20 */ .asciz "CdlSetloc"
    /* 43646C5365746C6F63000000 */
.align 2
.align 2
    /* F2C 801D8F2C */ .asciz "CdlNop"
    /* 43646C4E6F700000 */
.align 2
.align 2
    /* F34 801D8F34 */ .asciz "CdlSync"
    /* 43646C53796E6300 */
.align 2
.align 2
    /* F3C 801D8F3C */ .asciz "DiskError"
    /* 4469736B4572726F72000000 */
.align 2
.align 2
    /* F48 801D8F48 */ .asciz "DataEnd"
    /* 44617461456E6400 */
.align 2
.align 2
    /* F50 801D8F50 */ .asciz "Acknowledge"
    /* 41636B6E6F776C6564676500 */
.align 2
.align 2
    /* F5C 801D8F5C */ .asciz "Complete"
    /* 436F6D706C65746500000000 */
.align 2
.align 2
    /* F68 801D8F68 */ .asciz "DataReady"
    /* 446174615265616479000000 */
.align 2
.align 2
    /* F74 801D8F74 */ .asciz "NoIntr"
    /* 4E6F496E74720000 */
.align 2
enddlabel D_801D8E38

.align 2
nonmatching D_801D8F7C

dlabel D_801D8F7C
    /* F7C 801D8F7C */ .asciz "CD timeout: "
    /* 43442074696D656F75743A2000000000 */
.align 2
enddlabel D_801D8F7C

.align 2
nonmatching D_801D8F8C

dlabel D_801D8F8C
    /* F8C 801D8F8C */ .asciz "%s:(%s) Sync=%s, Ready=%s\n"
    /* 25733A282573292053796E633D25732C2052656164793D25730A0000 */
.align 2
enddlabel D_801D8F8C

.align 2
nonmatching D_801D8FA8

dlabel D_801D8FA8
    /* FA8 801D8FA8 */ .asciz "DiskError: "
    /* 4469736B4572726F723A2000 */
.align 2
enddlabel D_801D8FA8

.align 2
nonmatching D_801D8FB4

dlabel D_801D8FB4
    /* FB4 801D8FB4 */ .asciz "com=%s,code=(%02x:%02x)\n"
    /* 636F6D3D25732C636F64653D28253032783A25303278290A00000000 */
.align 2
enddlabel D_801D8FB4

.align 2
nonmatching D_801D8FD0

dlabel D_801D8FD0
    /* FD0 801D8FD0 */ .asciz "CDROM: unknown intr"
    /* 4344524F4D3A20756E6B6E6F776E20696E747200 */
.align 2
enddlabel D_801D8FD0

.align 2
nonmatching D_801D8FE4

dlabel D_801D8FE4
    /* FE4 801D8FE4 */ .asciz "(%d)\n"
    /* 282564290A000000 */
.align 2
.align 2
    /* FEC 801D8FEC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_801D8FE4

.align 3
nonmatching jtbl_801D8FF0

dlabel jtbl_801D8FF0
    /* FF0 801D8FF0 04FB1D80 */ .word .L801DFB04
    /* FF4 801D8FF4 B8FA1D80 */ .word .L801DFAB8
    /* FF8 801D8FF8 B8F91D80 */ .word .L801DF9B8
    /* FFC 801D8FFC 88FB1D80 */ .word .L801DFB88
    /* 1000 801D9000 0CFC1D80 */ .word .L801DFC0C
enddlabel jtbl_801D8FF0

.align 2
nonmatching D_801D9004

dlabel D_801D9004
    /* 1004 801D9004 */ .asciz "CD_sync"
    /* 43445F73796E6300 */
.align 2
enddlabel D_801D9004

.align 2
nonmatching D_801D900C

dlabel D_801D900C
    /* 100C 801D900C */ .asciz "CD_ready"
    /* 43445F726561647900000000 */
.align 2
enddlabel D_801D900C

.align 2
nonmatching D_801D9018

dlabel D_801D9018
    /* 1018 801D9018 */ .asciz "%s...\n"
    /* 25732E2E2E0A0000 */
.align 2
enddlabel D_801D9018

.align 2
nonmatching D_801D9020

dlabel D_801D9020
    /* 1020 801D9020 */ .asciz "%s: no param\n"
    /* 25733A206E6F20706172616D0A000000 */
.align 2
enddlabel D_801D9020

.align 2
nonmatching D_801D9030

dlabel D_801D9030
    /* 1030 801D9030 */ .asciz "CD_cw"
    /* 43445F6377000000 */
.align 2
.align 2
    /* 1038 801D9038 */ .asciz "$Id: bios.c,v 1.86 1997/03/28 07:42:42 makoto Exp $"
    /* 2449643A2062696F732E632C7620312E383620313939372F30332F32382030373A34323A3432206D616B6F746F20457870202400 */
.align 2
enddlabel D_801D9030

.align 2
nonmatching D_801D906C

dlabel D_801D906C
    /* 106C 801D906C */ .asciz "CD_init:"
    /* 43445F696E69743A00000000 */
.align 2
enddlabel D_801D906C

.align 2
nonmatching D_801D9078

dlabel D_801D9078
    /* 1078 801D9078 */ .asciz "addr=%08x\n"
    /* 616464723D253038780A0000 */
.align 2
enddlabel D_801D9078

.align 2
nonmatching D_801D9084

dlabel D_801D9084
    /* 1084 801D9084 */ .asciz "CD_datasync"
    /* 43445F6461746173796E6300 */
.align 2
enddlabel D_801D9084

nonmatching D_801D9090

dlabel D_801D9090
    /* 1090 801D9090 */ .byte 0x3C
    /* 1091 801D9091 */ .byte 0x4E
    /* 1092 801D9092 */ .byte 0x55
    /* 1093 801D9093 */ .byte 0x4C
    /* 1094 801D9094 */ .byte 0x4C
    /* 1095 801D9095 */ .byte 0x3E
    /* 1096 801D9096 */ .byte 0x00
    /* 1097 801D9097 */ .byte 0x00
enddlabel D_801D9090

.align 2
nonmatching D_801D9098

dlabel D_801D9098
    /* 1098 801D9098 */ .asciz "CdRead: sector error\n"
    /* 4364526561643A20736563746F72206572726F720A000000 */
.align 2
enddlabel D_801D9098

.align 2
nonmatching D_801D90B0

dlabel D_801D90B0
    /* 10B0 801D90B0 */ .asciz "CdRead: Shell open...\n"
    /* 4364526561643A205368656C6C206F70656E2E2E2E0A0000 */
.align 2
enddlabel D_801D90B0

.align 2
nonmatching D_801D90C8

dlabel D_801D90C8
    /* 10C8 801D90C8 */ .asciz "CdRead: retry...\n"
    /* 4364526561643A2072657472792E2E2E0A000000 */
.align 2
enddlabel D_801D90C8

.align 2
nonmatching D_801D90DC

dlabel D_801D90DC
    /* 10DC 801D90DC */ .asciz "DMA STATUS ERROR %x\n"
    /* 444D4120535441545553204552524F522025780A00000000 */
.align 2
enddlabel D_801D90DC

.align 2
nonmatching D_801D90F4

dlabel D_801D90F4
    /* 10F4 801D90F4 */ .asciz "VSync: timeout\n"
    /* 5653796E633A2074696D656F75740A00 */
.align 2
.align 2
    /* 1104 801D9104 */ .asciz "$Id: intr.c,v 1.76 1997/02/12 12:45:05 makoto Exp $"
    /* 2449643A20696E74722E632C7620312E373620313939372F30322F31322031323A34353A3035206D616B6F746F20457870202400 */
.align 2
enddlabel D_801D90F4

.align 2
nonmatching D_801D9138

dlabel D_801D9138
    /* 1138 801D9138 */ .asciz "unexpected interrupt(%04x)\n"
    /* 756E657870656374656420696E746572727570742825303478290A00 */
.align 2
enddlabel D_801D9138

.align 2
nonmatching D_801D9154

dlabel D_801D9154
    /* 1154 801D9154 */ .asciz "intr timeout(%04x:%04x)\n"
    /* 696E74722074696D656F757428253034783A25303478290A00000000 */
.align 2
enddlabel D_801D9154

.align 2
nonmatching D_801D9170

dlabel D_801D9170
    /* 1170 801D9170 */ .asciz "DMA bus error: code=%08x\n"
    /* 444D4120627573206572726F723A20636F64653D253038780A000000 */
.align 2
enddlabel D_801D9170

.align 2
nonmatching D_801D918C

dlabel D_801D918C
    /* 118C 801D918C */ .asciz "MADR[%d]=%08x\n"
    /* 4D4144525B25645D3D253038780A0000 */
.align 2
enddlabel D_801D918C
