/* PsyQ 4.0 LIBGTE PATCHGTE: _patch_gte and the words it copies (D_8007FF44 up to the module end).
 * .text 0x8007FEDC..0x8007FF7C, a verbatim LIBSCAN module span (docs/naming/libscan/matches.json),
 * Q106 D3. */
#include "include_asm.h"

__asm__(
    ".section .text\n"
    "    .set\tnoat\n"
    "    .set\tnoreorder\n"
    "    .set noat\n"
    "    .set noreorder\n"
    "glabel _patch_gte\n"
    "    lui $at, %hi(D_800A3658)\n"
    "    sw $ra, %lo(D_800A3658)($at)\n"
    "    jal EnterCriticalSection\n"
    "    nop\n"
    "    addiu $t2, $zero, 0xB0\n"
    "    jalr $t2\n"
    "    addiu $t1, $zero, 0x56\n"
    "    lui $t2, %hi(D_8007FF44)\n"
    "    lui $t1, %hi(CdInit)\n"
    "    lw $v0, 24($v0)\n"
    "    addiu $t2, $t2, %lo(D_8007FF44)\n"
    "    addiu $t1, $t1, %lo(CdInit)\n"
    ".L8007FF0C:\n"
    "    lw $v1, 0($t2)\n"
    "    addiu $t2, $t2, 0x4\n"
    "    addiu $v0, $v0, 0x4\n"
    "    bne $t2, $t1, .L8007FF0C\n"
    "    sw $v1, -4($v0)\n"
    "    jal FlushCache\n"
    "    nop\n"
    "    jal ExitCriticalSection\n"
    "    nop\n"
    "    lui $ra, %hi(D_800A3658)\n"
    "    lw $ra, %lo(D_800A3658)($ra)\n"
    "    nop\n"
    "    jr $ra\n"
    "    nop\n"
    ".globl D_8007FF44\n"
    "D_8007FF44:\n"
    "    nop\n"
    "    nop\n"
    "    addiu $k0, $zero, 0x100\n"
    "    lw $k0, 8($k0)\n"
    "    nop\n"
    "    lw $k0, 0($k0)\n"
    "    nop\n"
    "    addi $k0, $k0, 0x8\n"
    "    sw $at, 4($k0)\n"
    "    sw $v0, 8($k0)\n"
    "    sw $v1, 12($k0)\n"
    "    sw $ra, 124($k0)\n"
    "    .word 0x40026800\n"
    "    nop\n"
    "    .set\treorder\n"
    "    .set\tat\n"
    "    .set reorder\n"
    "    .set at\n"
);
