#!/usr/bin/env python3
"""Root-directory cleanliness audit.

Reports files at the repo root that aren't on the allowlist of expected
build / config / documentation files. Catches accidental tool outputs
(*.log, *.csv, gccdump.*) that should have gone to tmp/ or logs/.

Run manually: `python3 tools/check_root_cleanliness.py`
Or as part of session briefing: integrated into `dc.sh start`.

Exit codes:
  0 — root is clean (only allowlisted files present)
  1 — unexpected files found (printed to stdout)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Documentation files (kept at root for visibility)
# Note: dated handoff/audit docs moved to docs/handoffs/ and docs/naming/
# as part of the 2026-05-18 root-cleanup pass.
ALLOWED_DOCS = {
    "README.md", "CLAUDE.md", "AGENTS.md", "CONTRIBUTING.md", "BUILD.md", "CLAIMS.md",
}

# Build/project configuration files
ALLOWED_BUILD = {
    "Makefile", "splat.yaml", "bb2.ld", "bb2.sha1",
    "diff_settings.py",  # required by asm-differ
    ".gitignore",
    "WORK_QUEUE.md",     # regenerated by dc.sh refresh-queue
    "requirements.txt",  # python deps (used by dc.sh setup-venv + bootstrap)
}

# Build-pipeline .txt files (regfix/asmfix and friends)
ALLOWED_BUILD_TXT = {
    "regfix.txt", "asmfix.txt", "regfix_stage2.txt",
    "named_syms.txt", "symbol_addrs.txt",
    "undefined_syms_auto.txt", "undefined_funcs_auto.txt",
    "inline_asm_canonical.txt", "known_blocked.txt", "known_psyq_stdlib.txt",
    "sdata_exclude.txt", "sdata_funcs.txt", "sdata_syms.txt",
    "expand_lb_funcs.txt", "expand_dest_funcs.txt",
    "multu_funcs.txt", "multu_pad_funcs.txt",
    "reloc_addrs.txt",
    "cheat_retirement_debt.txt",
    "maspsx_label_nop_funcs.txt", "volatile_extern_allowlist.txt",
}

# Tracked CSVs (data files referenced by tools/docs)
ALLOWED_CSV = {
    "kengo_matches.csv",
    "kengo_name_decisions.csv",
}

# Disc image files (source artifact; kept for re-extraction)
ALLOWED_DISC = {
    "Bushido Blade 2 (USA).bin",
    "Bushido Blade 2 (USA).cue",
    # Patched playable build produced by tools/patch_exe_into_bin.py
    # (gitignored via *.bin/*.cue; kept at root next to the source disc).
    "ReBushidoBlade2.bin",
    "ReBushidoBlade2.cue",
}

# User-local artifacts (gitignored but kept at root by user preference).
ALLOWED_USER_LOCAL = {
    "Play ReBushidoBlade2.lnk",  # DuckStation launcher for the patched build
}

# Runtime state files (gitignored, generated)
ALLOWED_STATE_RE = re.compile(r"^\.bb2_.*$|^bb2\.d$|^Makefile\.bak$")

# Dotfiles at root. Most are directories (.venv, .vscode, .claude) and
# don't reach this code path. But .git is a FILE pointer inside a git
# worktree (gitdir: <path>), so is_file() catches it. Treating any
# leading-dot entry as allowed avoids flagging worktree state, editor
# scratch (.vimrc.local, .envrc), etc. — without expanding the named
# allowlist for every possible dotfile.
ALLOWED_DOTFILE_RE = re.compile(r"^\..+")

ALLOWED_FILES = (ALLOWED_DOCS | ALLOWED_BUILD | ALLOWED_BUILD_TXT |
                 ALLOWED_CSV | ALLOWED_DISC | ALLOWED_USER_LOCAL)

# Patterns for files that SHOULD have gone to tmp/ or logs/
SUSPICIOUS_PATTERNS = [
    (re.compile(r"^gccdump\."), "GCC dump file — should be in tmp/ or gitignored"),
    (re.compile(r".*\.log$"), "log file — write to tmp/ (one-off) or logs/ (long-lived)"),
    (re.compile(r".*_results\.csv$"), "tool output CSV — write to tmp/"),
    (re.compile(r".*_run\."), "run output — write to tmp/"),
    (re.compile(r"^triage_.*"), "triage output — write to tmp/"),
    (re.compile(r"^_tmp_.*"), "scratch file — write to tmp/ (not _tmp_* at root)"),
    (re.compile(r".*\.bak$"), "backup file — write to tmp/ or delete"),
    (re.compile(r".*\.orig$"), "merge backup — clean up or delete"),
    (re.compile(r".*\.dump$|.*\.stackdump$"), "crash/debug dump — delete after triage"),
]


def classify(filename: str) -> tuple[str, str]:
    """Return ('allowed'/'state'/'suspicious'/'unknown', reason)."""
    if filename in ALLOWED_FILES:
        return ("allowed", "")
    if ALLOWED_STATE_RE.match(filename):
        return ("state", "runtime state")
    if ALLOWED_DOTFILE_RE.match(filename):
        return ("allowed", "dotfile")
    for pat, reason in SUSPICIOUS_PATTERNS:
        if pat.match(filename):
            return ("suspicious", reason)
    return ("unknown", "not on allowlist")


def main() -> int:
    root = REPO_ROOT
    files = [p for p in root.iterdir() if p.is_file()]
    # In a git worktree, `.git` is a regular file (pointer), not a
    # directory. Skip it explicitly; it's git infrastructure, not a
    # project file requiring allowlist review.
    files = [p for p in files if p.name != ".git"]

    suspicious: list[tuple[str, str]] = []
    unknown: list[str] = []
    allowed_count = 0
    state_count = 0

    for p in sorted(files, key=lambda x: x.name.lower()):
        kind, reason = classify(p.name)
        if kind == "allowed":
            allowed_count += 1
        elif kind == "state":
            state_count += 1
        elif kind == "suspicious":
            suspicious.append((p.name, reason))
        else:
            unknown.append(p.name)

    print(f"Root scan: {len(files)} files ({allowed_count} allowed, {state_count} runtime-state, "
          f"{len(suspicious)} suspicious, {len(unknown)} unknown)")

    if suspicious:
        print()
        print("SUSPICIOUS — should have gone to tmp/ or logs/:")
        for name, reason in suspicious:
            print(f"  {name}  ({reason})")

    if unknown:
        print()
        print("UNKNOWN — not on allowlist (review and either add to allowlist or move):")
        for name in unknown:
            print(f"  {name}")

    if suspicious or unknown:
        print()
        print("If a file is legitimate but new, add it to tools/check_root_cleanliness.py's ALLOWLIST.")
        print("If it's a one-off tool output, move it to tmp/.")
        print("If it's a long-lived log we genuinely need, create logs/ (gitignored).")
        return 1

    print()
    print("OK: root is clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
